### ISSUE TITLE
Idea: User data that can be associated with a duk_context

### ISSUE THREAD

**Issue by beevik** [svaarala/duktape#1065]
Forgive me if this is already possible.

It would be nice if there were some way to store off a pointer to "user data" that was directly accessible from the `duk_context`, without having to store it in the global object or one of the stashes.

In my use case, we frequently want to access a central "manager" associated with the duktape context, but we don't want to have to go through the inefficiency of pulling that manager's pointer out of a context's global stash object.

Perhaps if something like this existed within duk_hthread:

    struct duk_hthread {
        ...
        void *user_data;
    }

    void *duk_get_user_data(duk_context *ctx);
    void duk_set_user_data(duk_context *ctx, void *user_data);

What do you think? Would something like this make sense?

**Comment by mamod** [comment]
what about associating user data when creating a duk context with [duk_create_heap](http://duktape.org/api.html#duk_create_heap)

here's how you can store and retrieve user data, this example was extracted from [dukluv](https://github.com/creationix/dukluv)

````
duk_create_heap(NULL, NULL, NULL, &userdata, NULL);
````

````
duk_memory_functions funcs;
duk_get_memory_functions(ctx, &funcs);
return funcs.udata;
````

**Comment by fatcerberus** [comment]
I think there's a pull open too (or was it already merged?) to add a way to get at the udata pointer directly without going through `duk_get_memory_functions()`.

**Comment by svaarala** [comment]
Answering rather verbosely because there are several issues involved with userdatas :-)

Adding userdata fields is not very difficult, the only real issue is figuring out what set of userdata values makes most sense for the API overall. Right now there's a heap-wide userdata field with no easy way to access it (other than `duk_get_memory_functions()`).

A single heap-wide userdata is not always very convenient, even for heap-wide usage. For example, an external allocator usually needs a state pointer and the heap userdata works well for that (and was actually originally intended only for that purpose). But nowadays the heap userdata is also used for other things, e.g. all the low memory macros and such which makes allocator modularity a bit awkward.

It'd be easy to have a separate allocator user data and "other user data" field. But what about those other uses -- the same argument could be repeated there, i.e. each purpose would most naturally use its own user data. So, for now I haven't split the heap userdata into multiple userdata values because I'm not sure what makes most sense and a single heap userdata is at least conceptually simple.

That API function to access the heap userdata conveniently does make sense regardless of these issues.

In addition to a heap-wide userdata it might sometimes make sense to have a global object wide userdata or a thread wide user data (i.e. mirroring the stashes).

Internally, heap and thread level userdata pointers can simply map to `duk_heap` and `duk_hthread`. Global object userdata is a bit difficult to manage right now (especially if it can be updated on-the-fly, even after multiple threads sharing the same global object exist) so it'd most naturally be implemented by storing a property into the global stash. API-wise it could still appear to be a direct call.

**Comment by svaarala** [comment]
@fatcerberus There's only an issue for it, #817. That one should be trivial to implement and there's not much design thought involved because it's just a convenience helper for what's already possible.

**Comment by svaarala** [comment]
@beevik Just to be clear - would you want to associate the userdata with the entire heap, a global object, or a specific thread (multiple thread objects can live in the same global object space)?

**Comment by beevik** [comment]
In our case, we have one heap, one global object and one thread, so it doesn't really matter which one provides the feature.

If flexibility is your goal, I'd think associating the data with the thread object would provide the most flexibility.

**Comment by svaarala** [comment]
@beevik Ok, so for now you could use the heap userdata and `duk_get_memory_functions()` and fixing #817 would make that more convenient. The remaining work wouldn't affect your use case.

**Comment by beevik** [comment]
Ok thanks. I'll close for now.
