### ISSUE TITLE
Unicode support for fopen() filenames

### ISSUE THREAD

**Issue by hoopoepg** [svaarala/duktape#112]
hi
i'm making library where duktape is integrated (windows platform) & found issue: duktape failed to open files when non ASCII symbols used in path.
investigating issue i found that fopen function used to access to file, and this method invoked using macro
<code>#define DUK_FOPEN fopen</code>
what about bit update macro to make it more intellectual:
<code>#ifndef DUK_FOPEN</code>
<code>#  define DUK_FOPEN fopen</code>
<code>#endif // DUK_FOPEN</code>

this change allows to set own fopen-compatible function for duktape (in my case i implemented unicode version of fopen) without overhead to runtime

thank you for Duktape :)

--Sergey

**Comment by svaarala** [comment]
We could make the change you suggest, i.e. make it easier to change how Duktape opens files. Right now all compile options from applications go through `DUK_OPT_xxx` defines, so perhaps user could provide `DUK_OPT_FOPEN` etc.

But, based on issues it was probably a mistake to include any file I/O in the "Duktape core" to begin with: there are non-ASCII issues, some platforms don't have file I/O at all, on some platforms file I/O or stdout maps in an unexpected way (e.g. drawing to a screen instead of a console), etc.

Duktape 2.0 will probably strip out all I/O functions from Duktape itself. Instead, Duktape distribution would provide optional C files (supported "extras") to provide file I/O functionality. It would then be easier to make them more platform friendly, or replace them altogether with user provided functions.

I'll leave this open for Duktape 1.2 if we come up with a useful interim solution.

**Comment by hoopoepg** [comment]
great!!!
thank you

**Comment by svaarala** [comment]
With the `duk_config.h` changes `DUK_FOPEN()` is now in `duk_config.h` so you can tweak it in 1.3 release. It's not perfect but better than before.

**Comment by svaarala** [comment]
Duktape 2.x no longer provides any file I/O related API calls to avoid portability issues such as this, so this issue is no longer relevant.
