### ISSUE TITLE
Debugger web UI function key support

### ISSUE THREAD

**Issue by denisdemaisbr** [svaarala/duktape#1192]
Hi all!
is easy add tradicional function key's like f7,f8, ... to 'some speed' of debbuging.

duktape is awesome!

**Comment by svaarala** [comment]
The debugger web UI is more a reference/prototype implementation. Developing it forward for better usability, styling, etc, would benefit from a proper web UI structure instead of the ad hoc jquery code that's in place now.

But adding F-key support would probably be relatively easy - though it's a little bit browser specific IIRC and may overlap with keys used by the browser (e.g. F5 is refresh).
