### ISSUE TITLE
Compiler error/warning in duk_debug_macros.c

### ISSUE THREAD

**Issue by nkolban** [svaarala/duktape#1198]
When I compile Duktape from source, my compiler (gcc 5.4.0) throws an error at the following line:

https://github.com/svaarala/duktape/blob/master/src-input/duk_debug_macros.c#L44

The text of the message is:

```
CC src/duktape.o
duk_debug_macros.c: In function 'duk_debug_log':
duk_debug_macros.c:44:31: error: left-hand operand of comma expression has no effect [-Werror=unused-value]
duk_debug_macros.c:44:41: error: left-hand operand of comma expression has no effect [-Werror=unused-value]
duk_debug_macros.c:44:51: error: left-hand operand of comma expression has no effect [-Werror=unused-value]
duk_debug_macros.c:44:61: error: left-hand operand of comma expression has no effect [-Werror=unused-value]
duk_debug_macros.c:44:21: error: statement with no effect [-Werror=unused-value]

```

I have worked around it with the following temporary change:

```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-value"
	DUK_USE_DEBUG_WRITE(arg_level, arg_file, arg_line, arg_func, arg_msg);
#pragma GCC diagnostic pop
```

**Comment by svaarala** [comment]
Thanks @nkolban, these are sometimes a bit painful to eliminate :) There's already a configuration option `DUK_USE_GCC_PRAGMAS` in `duk_config.h` so making those pragmas conditional to GCC (and Clang) would be relatively straightforward.

**Comment by fatcerberus** [comment]
I noticed these a while ago but forgot to report them.

**Comment by svaarala** [comment]
There are a few other warnings that ocme out in specific configurations. I usually fix the known issues right before a release - but I'm also happy to fix them earlier if they annoy someone :-)

**Comment by avih** [comment]
I'm getting a similar warning with duktape 2.0.0 release tag (with gcc 4.9.4, cross compiling to windows using MXE), I hope it's the right place to report it:

```
/path/to/duktape.h:444:23: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  (duk_throw_raw((ctx)), (duk_ret_t) 0)
```

Should this have been fixed?

**Comment by svaarala** [comment]
I'll open a separate issue for these - ultimately getting a 100% warning free compilation with all compilers is very difficult, so it's not a "release blocker" like target.

**Comment by svaarala** [comment]
So the issue here is that `duk_error()` and `duk_throw()` have a technical return / result value so that you can do:

```c
return duk_error(ctx, ...);
```

The `duk_error_raw()` and `duk_throw_raw()` functions are no-return because that allows better code to be generated. But that prevents adding a return value to their prototype because some compilers will warn about that; so they need to return `void`. To allow the return-error idiom to work they are implemented as comma expressions, which then causes an unreachable code warning with some compilers.

One way to eliminate these errors would be to remove the no-return attribute - but this leads to worse generated code and causes awkward issues in call sites where the compiler won't be able to determine that an error stops execution. This in turn may cause (unnecessary) warnings related to uninitialized variables and such.

**Comment by svaarala** [comment]
These warnings are ultimately different from the original reported issue but similar enough to be covered by the same issue I think.

**Comment by fatcerberus** [comment]
Just my two cents: Personally I'm not a big fan of the `return duk_error(...)` idiom: Looking at it from the POV of someone unfamiliar with Duktape, it implies that the error calls actually *do* return without throwing, e.g. by setting an error flag which gets picked up when the Duktape/C call returns.  At least SpiderMonkey actually does work this way for native calls; unsure about V8.

**Comment by svaarala** [comment]
The reason this idiom is used is to signal to the compiler that execution won't continue after the error call. Not all compilers support "no-return" functions which then causes weird issues with incorrect warnings etc.

The idiom actually comes from Lua, where it is very commonly used, e.g. as:

```c
if (something) {
    return luaL_error(L, "failed: %d", rc);
}
```

It's shorter than:

```c
if (something) {
    luaL_error(L, "failed: %d", rc);
    return;  /* Needed to avoid warning with some compilers */
}
```

Skipping the return generates worse code and causes unnecessary warnings. For example:

```
int flag;
if (something) {
    luaL_error(L, "failed: %d", rc);
} else {
    flag = 0;
}
```

A compiler will usually report 'flag' as being used uninitialized which is incorrect because the error throw never returns. But if the compiler doesn't know it, it needs to handle the two control flow paths.

You can often rework the code to avoid the warnings, e.g. initialize the flag to 0 on declaration, but it still ultimately causes unnecessary code to be generated and requires unnecessary warning fixes in the call site.

**Comment by svaarala** [comment]
@nkolban Regarding the original issue reported (issue description), `DUK_USE_DEBUG_WRITE()` is an application supplied macro so I think the problem may be related to how it is defined? The call site in Duktape is simply:

```c
        arg_level = (long) level;
        arg_file = (const char *) file;
        arg_line = (long) line;
        arg_func = (const char *) func;
        arg_msg = (const char *) buf;
        DUK_USE_DEBUG_WRITE(arg_level, arg_file, arg_line, arg_func, arg_msg);
```

and the whole code block is only enabled when DUK_USE_DEBUG and DUK_USE_DEBUG_WRITE are both defined. Could you check your DUK_USE_DEBUG_WRITE definition?

**Comment by svaarala** [comment]
Re: the other issue:

```
/path/to/duktape.h:444:23: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  (duk_throw_raw((ctx)), (duk_ret_t) 0)
```

This is a rather thorny issue. It'd be easy to resolve by removing the noreturn attribute from error throw functions but that's not ideal. I tried resolving the issue with pragmas, but even `_Pragma` cannot portably appear inside an expression. For example, if the application call site is:

```c
return duk_error(ctx, ...);
```

and `duk_error()` expands to a comma expression surrounded by `_Pragma`s, it will be rejected by GCC because the pragmas are inside an expression rather than between statements. So, not yet sure if/how to resolve the warning (beyond removing the noreturn which I find less than ideal).

**Comment by fatcerberus** [comment]
@svaarala Regarding this error:
> `warning: right-hand operand of comma expression has no effect [-Wunused-value]`

It seems that newer versions of gcc now produce this warning by default.  With just a simple "make duk" I get a bunch of them on Ubuntu 17.04.  Needless to say, that's a major platform.  Not sure if anything can be done about it in practice though, as you say all the solutions to fix the warning are suboptimal. :(

IMO this is a lint-level warning and should not be shown by default.  Oh well.

**Comment by svaarala** [comment]
@fatcerberus Yep, I'm aware of that and I get the warnings too when I updated to a newer Ubuntu version.

**Comment by svaarala** [comment]
There are no -Wsign-conversion warnings in Duktape itself at present, the cases where they might occur are places where e.g. `duk_error()` is called without `return duk_error(...);`. These are silenced using:

```c
(void) duk_error(...);
```
