### ISSUE TITLE
i don't understand why use -2 , not -1.

### ISSUE THREAD

**Issue by hsany330** [svaarala/duktape#123]
i don't understand why use -2 , not -1.
the code :
duk_push_global_object（CTX）;
duk_push_c_function（CTX，native_prime_check，    2    / * * NARGS /）;
duk_put_prop_string（CTX，    - 2，    “primeCheckNative”）;/////  why -2 ?  ​ I think it should be -1  .  please tell me why .

**Comment by BrothaOnAcid** [comment]
duk_push_global_object（CTX）;  // global object is now at -1
duk_push_c_function（CTX，native_prime_check， 2 / * * NARGS /）;  // global object is now at -2

so global object is at -2 when you call 'duk_put_prop_string'

**Comment by davidchisnall** [comment]
It helps to look at what's on the stack.  To help debugging, try sticking in calls to `duk_dump_context_stderr(CTX)` in between each call so that you can see what's going on.

For this example:

	duk_push_global_object（CTX）;

Now the top of the stack (-1) contains the global object.

	duk_push_c_function（CTX，native_prime_check， 2 / * * NARGS /）;

Now the top of the stack (-1) contains the C function and the entry below that (-2) contains the global object.

	duk_put_prop_string（CTX， - 2， “primeCheckNative”）;///// why -2 ? ​ I think it should be -1 . please tell me why .

Now you're trying to put the C function (-1) as a property on the global object (-2).  The `duk_put_prop_string()` function always uses the top stack value as the property value and takes an argument to specify which object it should apply to, so you must specify -2.

**Comment by svaarala** [comment]
Hopefully this got resolved :-)
