### ISSUE TITLE
Could use a protected duk_new()

### ISSUE THREAD

**Issue by jimstudt** [svaarala/duktape#124]
I find myself with a need for a protected duk_new() function, say a duk_pnew().

I'm building up a lot of data structures to then hand over to javascript for processing, I can do a better job of error reporting if I can catch an error, say when the javascript has not provided a required constructor or it has the wrong number of parameters.

This might be as easy as making the existing (non-trivial) duk_new() function internal and then exposing it as both duk_new() and duk_pnew() with them passing in a flag to control the DUK_CALL_FLAG_PROTECTED. But… there's a lot going on in the current duk_new that I don't understand. This is probably for someone familiar with the innards.

**Comment by svaarala** [comment]
Should be relatively straightforward to add a duk_pnew() - I'll try to fit it into Duktape 1.2 release.

The biggest differences for ordinary and constructor calls are (1) the creation of a default instance (bound to 'this') and (2) post-processing of the constructor return value.

**Comment by fatcerberus** [comment]
I'm just going to chime in here and second the call for a `duk_pnew`.  I have a use case where it would be really useful, but unfortunately it doesn't yet exist...

**Comment by svaarala** [comment]
Implemented this using an internal duk_safe_call() wrapper which is the safest starting point. The original suggestion of just using DUK_CALL_FLAG_PROTECTED might work, but because duk_new() has some post-processing after duk_handle_call(), that post-processing must first be checked to be error-free. I'm not sure it is right now so this is the safer approach.

**Comment by svaarala** [comment]
Merged to master with testcase, API docs, etc.
