### ISSUE TITLE
set memory limit

### ISSUE THREAD

**Issue by denisdemaisbr** [svaarala/duktape#1280]
Is possible set a memory amount avaliable for Duktape, p. ex., 512kbytes ?

**Comment by fatcerberus** [comment]
You'd have to use a custom allocator which enforced the quota, I think.

**Comment by svaarala** [comment]
That's correct, you can use a custom allocator. There is a pool-based allocator in Duktape extras, but also freelist based allocators are possible.

You can also wrap the system `malloc()` et al and keep track of the allocated memory using counters, though this requires the ability to check the size of a free()'d or realloc()'d chunk which either needs custom allocator or adding an additional header for tracking the current allocation size.

**Comment by svaarala** [comment]
@denisdemaisbr Forgot to mention, there's an example of using an additional header and standard malloc+realloc+free for memory limited sandboxing here: https://github.com/svaarala/duktape/blob/master/examples/sandbox/sandbox.c.

It's not an ideal technique because each allocation will carry additional overhead. But it's something at least to experiment with.

**Comment by denisdemaisbr** [comment]
*thanks!* I will try this approach.
