### ISSUE TITLE
Question: How to properly identify Debug Protocol version?

### ISSUE THREAD

**Issue by harold-b** [svaarala/duktape#1304]
In the debugger.rst it mentions:

> Version identification
>
> When the debug transport is attached, Duktape writes a version identification as an UTF-8 encoded line of the form:
>
> <protocolversion> <SP (0x20)> <additional text, no LF> <LF (0x0a)>
The current protocol version is "1" and the identification line currently has the form:
>
> 1 <DUK_VERSION> <DUK_GIT_DESCRIBE> <target string> <LF>
Everything that follows the protocol version number is informative only. Example:
>
> 1 10099 v1.0.0-254-g2459e88 duk command built from Duktape repo

However, duktape v1.4.0 and v1.5.0 both have protocol version "1", and if I recall the protocol was changed for v1.5.0 with the HeapObject inspection API being the big addition.

Should we always check the DUK_VERSION /DUK_GIT_DESCRIBE for proper identification?

I'm updating the VSCode debug client on the side to support v2.0.0, but some users are still using v1.6.0 so I'ts going to remain backward compatible with the current protocol. However if there are some users of v1.4.0 using the client, just checking <protocolversion> will cause issues. Can you describe how to identify DUK_VERSION's format?

**Comment by fatcerberus** [comment]
The protocol version only gets changed when the debugger is changed in a *backward incompatible* way.  HeapObject inspection was just adding a command, so that didn't bump the protocol version.  Duktape 2.0.0 *did* bump the protocol version (to 2) because the semantics for callstack indices were changed (see #747).

**Comment by fatcerberus** [comment]
For your use case, `DUK_VERSION` is probably your best bet as it will match the Duktape release exactly.  For example, 10601 for Duktape 1.6.1.  Working builds (either from master or a branch) will have 99 for the patch number.

`DUK_GIT_DESCRIBE` will match the version number (with "v" prepended) for official releases.  Working builds will be of the format `vX.X.X-YYYY-gZZZZZZZ`  where X.X.X is the last minor release (e.g. 1.6.0), YYYY is the number of commits made to master since that release, and ZZZZZZZ is the truncated SHA1 hash of the most recent commit.

**Comment by fatcerberus** [comment]
To parse `DUK_VERSION`, convert it to an integer and then do:

```c
major = DUK_VERSION / 10000;
minor = (DUK_VERSION / 100) % 100;
patch = DUK_VERSION % 100;

**Comment by harold-b** [comment]
Excellent, thanks for the info, Bruce.

I suppose once could argue the protocol sort of changed from 1.4.0 to 1.5.0 as `BasicInfo` included a new pointer size field. When I updated it, a user asked about not being able to use it, it was crashing because I had a sanity check on `BasicInfo` providing 7 fields as I did use the sizeof pointer for the 1.5.0 implementation.

**Comment by harold-b** [comment]
Closing because @fatcerberus provided all the info I needed.

**Comment by svaarala** [comment]
Just one additional note - checking the version number is not a reliable indicator that a certain command is supported, because some commands are config option dependent. For example, DumpHeap can be enabled or disabled, and so can object inspection support.

So the intent is to check the major version which defines the potentially available commands and their formats, and then try executing the commands. If the target doesn't support a certain command, degrade gracefully.

One basic improvement would be for the target to list available commands. But even that's not a 100% solution because some commands may still behave differently based on configuration. For example, if refcounts are disabled, refcounts won't be available in inspection.

**Comment by fatcerberus** [comment]
The main problem with testing commands by running them is that many have side effects.  So there's no way to test for something "in advance" (without guessing based on the version number), which is inconvenient.

**Comment by svaarala** [comment]
@harold-b Regarding this:

> I suppose once could argue the protocol sort of changed from 1.4.0 to 1.5.0 as BasicInfo included a new pointer size field. When I updated it, a user asked about not being able to use it, it was crashing because I had a sanity check on BasicInfo providing 7 fields as I did use the sizeof pointer for the 1.5.0 implementation.

That's actually allowed in the protocol - the target and the debug client are intended to ignore any trailing fields which provides a rudimentary way to extend the protocol without breaking backward compatibility, see:

- https://github.com/svaarala/duktape/blob/master/doc/debugger.rst#handling-of-inbound-requests

**Comment by svaarala** [comment]
> The main problem with testing commands by running them is that many have side effects. So there's no way to test for something "in advance" (without guessing based on the version number), which is inconvenient.

Right, I didn't mean to test for functionality in advance. But simply treat the target like any other server: requests may fail because something isn't available or supported, and the requesting party should degrade gracefully.

Trying to provide an accurate feature handshake would be a very complicated thing assuming that command behavior is configuration dependent - which I believe it will ultimately be because the debugger interacts with the internals.

**Comment by harold-b** [comment]
> That's actually allowed in the protocol - the target and the debug client are intended to ignore any trailing fields which provides a rudimentary way to extend the protocol without breaking backward compatibility, see:

Woops! Geez I ought to re-read the whole thing again to make sure I'm fully complying because It's been a while since I referred to it for anything other than specific request/notification dvalue sequences.

**Comment by svaarala** [comment]
@harold-b That section I linked to doesn't actually discuss responses directly, but the intent is spelled a bit more clearly here:

- https://github.com/svaarala/duktape/blob/master/doc/debugger.rst#extending-the-protocol-and-version-compatibility
