### ISSUE TITLE
IIFE Value always returned in comma expression

### ISSUE THREAD

**Issue by josh** [svaarala/duktape#131]
Hey @svaarala 

Found a pretty crazy bug as a result of minifying some JS.

The result of returning a comma separated expression should return the last value in the list.

``` js
(function() { return 0, 1, 2 })()
// expected 2
```

Works fine in Duktape and other JS engines.

However, if an IIFE is in the returned expression, its value is returned no matter what.

``` js
(function() { return 0, (function() { return 1 })(), 2 })()
// expected 2
```

Duktape returns 1 here.

I don't think anyone uses return with comma expressions like this in there own code, but it is pretty common magnification technique used by UglifyJS.

**Comment by svaarala** [comment]
Interesting case, I'll see what's wrong with the bytecode.

It seems that "duk use notail" does not prevent the issue so it's not directly tail call related.  On the other hand assigning to a temporary variable and returning from that does fix the issue:

```
function test2() {
    return 0, (function() { return 1; })(), 2;
}

function test2notail() {
    'use duk notail';
    return 0, (function() { return 1; })(), 2;
}

function test2var() {
    var ret = (0, (function() { return 1; })(), 2);
    return ret;
}
```

Above, test2 and test2notail fail, test2var works.

**Comment by svaarala** [comment]
Ok, it seems the issue *is* tailcall related, I just had the "notail" directive in the wrong function (it needs to be in the callee, i.e. the innermost function).

Here's the bytecode:
```
duk> (function() { return 0, (function() { return 1 })(), 2 })()
[D] duk_js_compiler.c:1807 (duk__getconst): allocating new constant for 1 -> const index 0
[D] duk_js_compiler.c:1807 (duk__getconst): allocating new constant for 1 -> const index 0
[D] duk_js_compiler.c:963 (duk__convert_to_func_template): BC 0000: RETURN 2, 256, 0        ; 0x004000b3 op=51 (RETURN) a=2 b=256 c=0
[D] duk_js_compiler.c:963 (duk__convert_to_func_template): BC 0001: RETURN 1, 0, 0        ; 0x00000073 op=51 (RETURN) a=1 b=0 c=0
[D] duk_js_compiler.c:1807 (duk__getconst): allocating new constant for 2 -> const index 0
[D] duk_js_compiler.c:5539 (duk__parse_return_stmt): return statement detected a tail call opportunity: catch depth is 0, duk__exprtop() emitted >= 1 instructions, and last instruction is a CALL -> set TAILCALL flag
[D] duk_js_compiler.c:1807 (duk__getconst): allocating new constant for 2 -> const index 0
[D] duk_js_compiler.c:5539 (duk__parse_return_stmt): return statement detected a tail call opportunity: catch depth is 0, duk__exprtop() emitted >= 1 instructions, and last instruction is a CALL -> set TAILCALL flag
[D] duk_js_compiler.c:963 (duk__convert_to_func_template): BC 0000: CLOSURE 0, 0, 0        ; 0x00000014 op=20 (CLOSURE) a=0 b=0 c=0
[D] duk_js_compiler.c:963 (duk__convert_to_func_template): BC 0001: LDREG 1, 0, 0        ; 0x00000040 op=0 (LDREG) a=1 b=0 c=0
[D] duk_js_compiler.c:963 (duk__convert_to_func_template): BC 0002: CSREG 1, 1, 0        ; 0x0000404c op=12 (CSREG) a=1 b=1 c=0
[D] duk_js_compiler.c:963 (duk__convert_to_func_template): BC 0003: CALL 1, 1, 0        ; 0x00004074 op=52 (CALL) a=1 b=1 c=0
[D] duk_js_compiler.c:963 (duk__convert_to_func_template): BC 0004: RETURN 2, 256, 0        ; 0x004000b3 op=51 (RETURN) a=2 b=256 c=0
[D] duk_js_compiler.c:963 (duk__convert_to_func_template): BC 0005: RETURN 1, 0, 0        ; 0x00000073 op=51 (RETURN) a=1 b=0 c=0
[D] duk_js_compiler.c:963 (duk__convert_to_func_template): BC 0000: LDUNDEF 0, 0        ; 0x000000be op=62 (DEBUG) a=2 b=0 c=0
[D] duk_js_compiler.c:963 (duk__convert_to_func_template): BC 0001: CLOSURE 1, 0, 0        ; 0x00000054 op=20 (CLOSURE) a=1 b=0 c=0
[D] duk_js_compiler.c:963 (duk__convert_to_func_template): BC 0002: LDREG 2, 1, 0        ; 0x00004080 op=0 (LDREG) a=2 b=1 c=0
[D] duk_js_compiler.c:963 (duk__convert_to_func_template): BC 0003: CSREG 2, 2, 0        ; 0x0000808c op=12 (CSREG) a=2 b=2 c=0
[D] duk_js_compiler.c:963 (duk__convert_to_func_template): BC 0004: CALL 0, 2, 0        ; 0x00008034 op=52 (CALL) a=0 b=2 c=0
[D] duk_js_compiler.c:963 (duk__convert_to_func_template): BC 0005: LDREG 0, 2, 0        ; 0x00008000 op=0 (LDREG) a=0 b=2 c=0
[D] duk_js_compiler.c:963 (duk__convert_to_func_template): BC 0006: RETURN 3, 0, 0        ; 0x000000f3 op=51 (RETURN) a=3 b=0 c=0
```

What goes wrong:

- Duktape compiles the comma expression normally. As part of doing so it tries to avoid emitting unused code, e.g. no bytecode is emitted for loading the constant 0 because it's not returned and it has no side effects.

- The tailcall check in the compiler determines that the last emitted instruction is a CALL so it can be converted to a tailcall.  This goes wrong because the expression `2` has not yet been coerced into an explicit load so that the function call is the last part of emitted bytecode so far.

- When the innermost function has a `use duk notail` directive or tailcalls are disabled entirely, the bytecode works because the tailcall request flag in the CALL opcode is ignored, and the return that follows is correct.

**Comment by svaarala** [comment]
The required fix seems clear but it's a bit non-trivial so I'll need to give it some thought.

The result of compiling the comma expression is a duk_ivalue referencing constant 0 (number 2). No bytecode is emitted for it because the RETURN statement can refer to the constant directly. So when checking for a tailcall, the compiler would need to know that the CALL opcode present in the bytecode "belongs" to the last expression.

Probably the best fix is to track that a certain duk_ivalue is the result of a CALL expression, so that the compiler could check for that when making a tailcall decision.

A smaller fix would be to change the tailcall check so that it checks that the previous opcode must be a CALL(I) and that the result register of that call must match the reg/const of the final expression.  In the above case, the final expression value is "const 0" so it won't match the call result register.

**Comment by svaarala** [comment]
Ok, the simple fix is in the following branch:

- https://github.com/svaarala/duktape/tree/fix-comma-expr-gh131

Not yet merged to master, figured I'd sleep on it :-)

Thanks a lot for reporting, this was not caught by any testcase so far (nor test262).

**Comment by svaarala** [comment]
Fix now in master.

**Comment by josh** [comment]
Wow, thanks @svaarala!

Though, I think still found another one along the same lines. Should I open a new issue?

``` js
(function() { var a = 1; return (function() { a = 2 })(), a })()
```

Should return `2`, but oddly Duktape is returning `undefined` not even `1`.

Just tested on d8158da2bbbc0245d72b6c64aa4a4c8689e9d638.

**Comment by svaarala** [comment]
Confirmed and looks like an issue with the tailcall decision still; the following works:
```
print( (function() { var a = 1; return (function() { 'use duk notail'; a = 2 })(), a })() );
```

The culprit is still the same, the tailcall decision code determines that the previous instruction is a CALL; no instruction is emitted when a register bound variable is returned which I missed in the first fix (which handled constants correctly).

I'll need to make the tailcall decision better, which may need a bit more plumbing.  I'll have a look tonight.

Thanks for reporting! :)

**Comment by svaarala** [comment]
The simple tailcall check was to ensure that:

- The previous instruction is a CALL(I).
- The last evaluation result is a register, not a constant.

The latter condition worked incorrectly when the result is a register bound variable. Changed the check to ensure that the last evaluation result is a temporary register.

**Comment by svaarala** [comment]
Could you check what happens with:

- https://github.com/svaarala/duktape/tree/fix-return-tailcall-reg-gh131

**Comment by svaarala** [comment]
The above fix branch is now merged to master - let me know if you have issues.

**Comment by josh** [comment]
Confirmed!

Thanks so much!!!! :heart:

**Comment by svaarala** [comment]
@josh Good to hear, thanks again for reporting, I'm sure this affected a lot of minified code.
