### ISSUE TITLE
How to deal with UTF-16

### ISSUE THREAD

**Issue by zero-ui** [svaarala/duktape#1404]
my projects is win32 Unicode project,
If you change the code every time, it will affect the efficiency

**Comment by svaarala** [comment]
Duktape doesn't support wide character strings, all strings are in CESU-8 (same as UTF-8 except for allowing surrogate pairs). Unfortunately you'd need to convert between UTF-16 and UTF-8 if the application uses UTF-16 internally.

**Comment by zero-ui** [comment]
I try to CESU-8 right into whar_t in to lexer and compiler,But unsuccessful,May I ask if you can increase this support, Because utf8 is too inconvenient.

**Comment by svaarala** [comment]
While that change is doable, it's unfortunately not a small change; just to give an idea what it would mean:
- String structs would need an #ifdef for their struct layout. Not too difficult.
- All places in Duktape where strings are created using s(n)printf(), strlen(), etc would need to be reworked - there are ~60 such call sites at present.
- The RegExp engine would need to be reworked because the bytecode is represented as an 8-bit string.
- APIs like TextEncoder/TextDecoder would need to be partially rewritten.
- The C API wouldn't be able to support UTF-8 and UTF-16 strings at the same time -- because e.g. `duk_get_string()` returns a "borrowed" pointer to Duktape's internal string data, there's no mechanism to free the result of a possible conversion.
- Testcases assume UTF-8 output now and some tooling would be needed for test coverage (maybe converting UTF-16 for test case result comparison).

None of these steps is a showstopper, but overall there are several weeks of work.

What would be relatively easy is to add an extras/ module providing UTF-16 <-> CESU-8 conversion functions.

**Comment by zero-ui** [comment]
That's the truth.I used to change mujs to full use wchar_t Indeed a lot of work,But the benefits are obvious.
VM will no longer deal with coding problems because the encoding is uniform.Wchar bytes and the same length, more simple process will be to enhance the efficiency of the implementation.
Of course, this is just a suggestion.Of course, this is just a suggestion, whether it depends on you.Personally, I think this is a very good suggestion,After all, in the application development is still more common char and wchar, and compatibility is better or wchar_t.

**Comment by zero-ui** [comment]
That's what I'm doing right now,I am using this method, but I hope to get this support in later versions,Thanks very much.

**Comment by fatcerberus** [comment]
> VM will no longer deal with coding problems because the encoding is uniform.

This is already the case now because UTF-8 is Unicode (don't let the use of `char` fool you).  What you're talking about is the public interface (the C API).

Note that wide characters are inconvenient for most platforms other than Windows.  So if, as you seem to be suggesting, Duktape were to adopt widechar by default, other developers (including me :) would have the same complaint you do now.  So `wchar_t` doesn't magically make everything "uniform". ;)

**Comment by fatcerberus** [comment]
Also it's worth pointing out that widechar strlen is not automatically == character count, so that's not an automatic advantage over UTF-8/CESU-8.  UTF-16 surrogate pairs means a single character may still require 2 code units.

**Comment by zero-ui** [comment]
Yes,i said something wrong before .Forgive me ,please.

**Comment by zero-ui** [comment]
So this will only need to increase the width of the CAPI character support on it.

**Comment by zero-ui** [comment]
If we can get the official support is better than my own module.

**Comment by svaarala** [comment]
@zero-ui Most of the points were discussed above: wchars are quite rare on Unix (I've personally never dealt with them) and so far I've only encountered them on Windows platforms.

But even if that were not the case, UTF-16 would be a bad default because it wastes a lot of memory which matters especially on low memory targets (even more so because they usually deal mostly with ASCII).

**Comment by zero-ui** [comment]
Thanks for your guidance,Probably the reason most of my work is under windows,
Just adding wchar support in CAPI should not take up too much memory.VM continue to use ASCII.

**Comment by svaarala** [comment]
Adding some support functions to do the conversion would be OK I think - but that would mean that pushing/getting strings would still involve a UTF-16 <-> CESU-8 conversion. If that's OK, that wouldn't be difficult to implement.

**Comment by zero-ui** [comment]
Yes, it's more convenient to use

**Comment by zero-ui** [comment]
I use WideCharToMultiByte to convert text , but get this result"TypeError: no sourcecode",
CP_ACP and CP_UTF8 results are the same

**Comment by zero-ui** [comment]
This result was obtained with WideCharToMultiByte conversion "TypeError: no sourcecode",After debugging found that the string head has FF FE two bytes
