### ISSUE TITLE
Duktape chokes on literal braces in RegExp

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#142]
The following code works fine in all other JS engines, but Duktape chokes on it ("invalid quantifer"):

```
function FormatString(s) {
    var a = arguments, i = 1;
    return s.replace(/{\?}/g, function() { return a[i++]; });
}

Abort(FormatString("Hello {?} how are you?", "John"));
```

**Comment by svaarala** [comment]
The E5 specification RegExp productions are rather strict and don't allow unescaped curly braces. There are also a lot of other constructs that are technically syntax errors but are usually accepted by other engines.

Here's an issue tracking various issues:

- https://github.com/svaarala/duktape/issues/74

The best fix is not apparent: since there's no specification for "real world" regexps it's basically case-by-case work. Also some of the fixes require regexp compiler backtracking (to figure out if a curly is part of syntax or to be interpreted literally) which Duktape doesn't do now, so the fix is not trivial.

**Comment by svaarala** [comment]
If you can change the original source, the fix is to escape literal curlies:

```
/\{\?\}/g
```

**Comment by fatcerberus** [comment]
For what it's worth, the regex parser at regex101.com also accepts the literal curly braces.

**Comment by fatcerberus** [comment]
Yeah, I figured out the escaped curlies trick.  The thing is, my game engine is meant to be compatible (as much as possible) with an older engine called Sphere, which used SpiderMonkey for its JS engine.  As a result little things like this tend to pop up from time to time.

**Comment by svaarala** [comment]
Ecmascript E5/E5.1 specifies its Regexp subset explicitly here:

- http://www.ecma-international.org/ecma-262/5.1/#sec-15.10

Unfortunately it doesn't always match what regexp engines offer, so a JS engine which just adopts an external engine will probably use a wider subset.
