### ISSUE TITLE
Duktape cannot run the JSbench benchmarks

### ISSUE THREAD

**Issue by hyanglan** [svaarala/duktape#144]
I try to run jsbench with duktape on ubuntu 12.04, but there are always errors.
You can download jsbench benchmark for offline use from http://jsbench.cs.purdue.edu/.

Here are the error message: 

$ cd jsbench/google/chrome
$ duk urem.js
TypeError: invalid base value
	src-separate/duk_hobject_props.c:2904
	anon urem.js:6758
	global urem.js:48259 preventsyield
error in executing file urem.js

**Comment by svaarala** [comment]
In general, Jsbench probably won't run properly because it's intended for browsers:

> Not all included benchmarks can be run without a browser, and not all non-browser JS environment can run this benchmark suite.

Duktape doesn't provide a browser environment, just the standard Ecmascript environment which is much narrower (no "window" for instance).

The problem on that line (urem.js:6758) is triggered by a register shuffle issue which is fixed in master. On master the test still fails with:

```
Error: register limit (line 5231)
	input:5231
	duk_js_compiler.c:1655
	eval  native strict preventsyield
	anon urem.js:45542
	onload urem.js:235
	finalize urem.js:271
	anon urem.js:48259
	global urem.js:48259 preventsyield
error in executing file urem.js
```

This happens because the testcase exhausts the maximum number of VM registers Duktape currently supports for a single function (which is 262144 for most operations).

**Comment by hyanglan** [comment]
@svaarala 
So is there any plan to fix all those bugs/issues ?

**Comment by svaarala** [comment]
@hyanglan There's probably always going to be some bytecode limitations. I'll look into the TRYCATCH issue (#145) because the bytecode const/register limit for TRYCATCH is smaller than for other operations and is a concrete limiting factor (not only for this test suite).

Duktape won't get browser bindings though, so it won't pass browser test suites.

**Comment by svaarala** [comment]
#145 tracks the concrete change to be done, so closing this
