### ISSUE TITLE
Add equivalent of "instanceof" to the C API (duk_instanceof)

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#148]
Is there currently a way to use `instanceof` from the native side?  I don't see anything to do this in the documentation.  Might be a useful feature to have, particularly for native-side errCreate handlers. ;-)

**Comment by svaarala** [comment]
Right now there isn't, but it would be easy to add.

Just as a little bit of background: the API doesn't mirror all Ecmascript constructs because there are relatively many of them and there's some pressure to keep the API and code footprint small. So, API calls have been added for the obvious cases and based on concrete demand. For example, before Duktape 1.1 `duk_def_prop()` didn't exist and users would call into `Object.defineProperty()` to e.g. set up setters and getters. This turned out to be a common need so a specific API call was added.

Working out the right balance is obviously a bit difficult. For instance, C bindings for array manipulation will probably need to be added but there are quite a few operations that one might potentially need so it's a challenge to keep the API call count low :)

**Comment by svaarala** [comment]
In this specific case, adding `duk_instanceof()` as a public API macro would have minimal footprint impact because the internal instanceof-primitive needs to exist anyway in some form. For the same reason the API call is unlikely to become baggage in the future.

This doesn't work for all primitives because some of them are implemented inline in the bytecode executor, as built-in Duktape/C functions, etc. Also some users dislike macro-based API calls. I like them because they can be used to provide a convenient API with minimal conflict between convenience and low memory environments :-)

**Comment by fatcerberus** [comment]
I don't mind the macros, actually.  A lot of people scoff at their use in Duktape because conversion of an API between function and macro isn't considered a breaking change, but the way the engine is generally used (statically linked), it doesn't matter: updating to a new version requires recompilation anyway.  Binary compatibility isn't even a factor at that point.

**Comment by svaarala** [comment]
Yeah, the function/macro distinction only really comes to play when either using Duktape as a shared library or when one needs to point to Duktape API calls via a function pointer (happens in some wrapping scenarios).

While there are currently no guarantees, in practice function/macro changes are not needed in patch versions.

**Comment by darkuranium** [comment]
I'd just like to toss in my $0.02 and state that I also don't mind the macros, as long as they don't do something unpredictable (like evaluate an argument twice) --- or if they do, at least document and emphasize that.

While I don't remember using them in any shape or form where 2× evaluation would be a problem, I know I might end up with such a call in the future.

**Comment by hftmarkand** [comment]
Macros are evil.

You can't store a macro as a function pointer, you can even less when the macro expands to an expression like : `#define load (load() || exec()).`

It's just a pain to debug your code when it actually contains macros too.

Oh and I remember a while ago, I've added a function named `basename` into a C++ class and because the stupid glibc headers has added something like `#define basename xpg_basename` IIRC, I was debugging why my *own* function was not referenced in the executable.

**Comment by svaarala** [comment]
@hftmarkand We'll just have to agree to disagree then ;)

**Comment by fatcerberus** [comment]
Wow, I derailed the issue thread but good. :-). But getting back on topic, is this a green light for duk_instanceof() then?

**Comment by svaarala** [comment]
Sure, let's add it to the API :)

**Comment by hftmarkand** [comment]
Nice, thanks @svaarala :)

**Comment by svaarala** [comment]
Draft implementation, API doc, and testcase:

- https://github.com/svaarala/duktape/tree/api-instanceof

Behavior for invalid indices in the API call differs intentionally from e.g. `duk_equals()`: a TypeError is thrown if either index is invalid.

This is intentional because unlike comparison operators, `instanceof` is rather picky about its arguments, e.g. throwing a TypeError if the rval is not a *callable* object:

```
duk> 'foo' instanceof {}
TypeError: invalid instanceof rval
	duk_js_ops.c:994
	global input:1 preventsyield
```

So, I made the index checks strict to match this behavior. This behavior is illustrated in the test case:

- https://github.com/svaarala/duktape/blob/api-instanceof/api-testcases/test-instanceof.c

**Comment by fatcerberus** [comment]
Can I have a snapshot from the `api-instanceof` branch?  I'd like to test it out. :)

**Comment by svaarala** [comment]
Regarding the macro guarantees mentioned above - they are explicit (including not evaluated twice) and listed in:

- http://duktape.org/guide.html#duktape-api

**Comment by svaarala** [comment]
Now in master.

@fatcerberus Open an issue if this doesn't work for you :)
