### ISSUE TITLE
how to debug

### ISSUE THREAD

**Issue by MarilynDafa** [svaarala/duktape#1480]
hi,my project is c++ exe, and use duktape to load js script.
1.except logging, is there any other methods to debug javascript.
2.which IDE can debug javascript(like lua), any suggestions?

**Comment by svaarala** [comment]
The main approaches are:
- Debug logging, see http://wiki.duktape.org/HowtoDebugPrints.html
- Debugger protocol, see http://duktape.org/guide.html#debugger for how to get started

To use the debugger your application needs to implement a debug transport provider which is abstracted so that Duktape can be adapted to very different event loops etc; see the guide page and links there for more details.

There's a debugger web UI as part of the Duktape distributable (see debugger/ directory). It's bare bones but functional. Because the debug protocol itself is the same (only the transport may be different) you may be able to use an existing debug client integration. Here's a (somewhat out of date) list: http://wiki.duktape.org/DebugClients.html.

You can implement your own integration either against a binary debug protocol or a JSON protocol via a JSON/binary proxy.

**Comment by denisdemaisbr** [comment]
for vscode:
https://github.com/harold-b/vscode-duktape-debug
https://github.com/vktr/vscode-duk-debug

**Comment by svaarala** [comment]
@MarilynDafa Was this issue resolved from your point of view?
