### ISSUE TITLE
Interrupt with bounded execution time

### ISSUE THREAD

**Issue by debdattabasu** [svaarala/duktape#1520]
Hi. Currently the interrupt system is based on number of instructions. For my use case, I need an interrupt system based on bounded execution time. I have built a small patch for this after the release mode build, ie on the duktape.c file after the configure step.

Is this something that would be broadly useful to duktape? If so, I can contribute a pull request. However, I am not very familiar with the configure system, so will need pointers. 

Regards.

**Comment by svaarala** [comment]
The interrupt mechanism is currently pretty rudimentary. The main problem it solves is allowing a instruction count interrupt to be handled efficiently; this is critical because it affects every opcode dispatched and I think it'd be difficult to involve any more per-opcode checks.

Having a time-based interrupt is probably most straightforward by making the instruction interval shorter (say every 1000 instructions) and then checking a timestamp during the interrupt. This is actually used by the debugger code to decide when to poll for inbound messages: the interrupt counter is used as a means of entering the actual time-based check which tries to poll roughly every 200ms. When debugging is enabled, call handling also forces an interrupt check when we return from a native function call because the call might have taken a long time (and there are also interesting state checks like breakpoints).

There are many ways to improve on this. For example:
- There could be an interval-based check inside the raw instruction count based interrupt. For short intervals to work well, the interrupt counter should be initialized to a smaller value. The interrupt mechanism allows the interrupt instruction interval to adapt to existing state, e.g. the need for a short time-based interrupt.
- The forced interrupt on native function exit could be extended to cover non-debugger situations, so that the time-based check was immediately made when returning from a native call which potentially took a long time.
- There should probably be separate notions of time (Date.now()) and uptime. The latter should be used for debugger poll intervals, execution timeout checks, etc. This is now a potential issue if the time backing Date.now() is adjusted discontinuously.

At present there's no C API for the interrupt/timeout mechanism, but that's more or less a separate issue. 

If you wanted to just have a configuration value providing an interval goal for the interrupt check (say 100ms), I think these changes would be needed at a minimum:
- Ability to specify the interval goal in a config option.
- Ability to specify the raw, instruction-based interrupt interval in a config option.
- Extending the forced interrupt check when returning from a function call so that it gets compiled with debugger support but also with an interval based interrupt.

**Comment by debdattabasu** [comment]
Hi. Thank you, that was really helpful.  I have an aggressive 1ms target, and have followed an approach very similar to what you suggest. I am triggering a timestamp check once every 100 instructions.  I currently run only trusted stuff in my c functions, so have not needed to implement the forced interrupt check, but it may be needed for generality. 

I will take a look at integrating this when I find time. 

Regards.

**Comment by svaarala** [comment]
Closed and merged to #1637.
