### ISSUE TITLE
Propagation of Duktape/C error return values

### ISSUE THREAD

**Issue by beevik** [svaarala/duktape#1534]
When a Duktape/C function returns a negative number (say, -100), it causes an error to be thrown automatically.  Unless it is "caught", this error eventually propagates to the `duk_pcall` or `duk_pcall_method` that triggered it.

For example:
```C
duk_int_t result = duk_pcall_method(context, nargs);
if (result != DUK_EXEC_SUCCESS) {
    if (duk_is_error(context, -1)) {
        HandleError(context);
    }
}
```

Is there any way, within my `HandleError` function, to figure out what the negative return code value was?  If I call `duk_safe_to_string` with the error value on the stack, I get this string: `Error: error (rc -100)`.  But I cannot figure out how to get the actual error code (-100) directly.  Is this possible?

Addendum:  I tried `duk_get_error_code`, but it returned 1.  Not 100.

**Comment by svaarala** [comment]
Short answer: not at present, unfortunately.

The mechanism is mostly a shorthand for known error types, e.g. `return DUK_RET_TYPE_ERROR;` is shorthand for throwing a TypeError. For such an error, `duk_get_error_code()` returns a useful value based on the error instance type, e.g. `DUK_ERR_TYPE_ERROR` here. When using negative codes which don't map to built-in errors (TypeError, RangeError, etc) a plain Error object is created and `duk_get_error_code()` then returns 1, for `DUK_ERR_ERROR` (generic Error); see http://duktape.org/api.html#duk_get_error_code.

The code is not currently preserved as a programmatic value like an Error instance property. Duktape actually did store `.code` explicitly at some point, but because other engines don't, I removed it to make Error objects as similar to other engines as possible. Adding that support back would be easy, but I'm not sure if the behavior should be enabled by default.

**Comment by denisdemaisbr** [comment]
http://duktape.org/api.html#duk_pcall
http://duktape.org/api.html#duk_pcall_method

**Comment by beevik** [comment]
ok thanks, I'll just overload one of the built-in errors for now then.
