### ISSUE TITLE
[FR] Add doc about how to create a proxy object with the C API

### ISSUE THREAD

**Issue by mike-lischke** [svaarala/duktape#1541]
The [duktape API page](http://duktape.org/api.html) as well as [How to use virtual properties](http://wiki.duktape.org/HowtoVirtualProperties.html) often mention proxy objects one could use to virtualize properties. However, it's never explained how to create such a proxy object using the C API. I'd like to virtualize an array and think that a proxy would help here. Thanks.

**Comment by svaarala** [comment]
In master (to become 2.2.0) there's a `duk_push_proxy()` API call: https://github.com/svaarala/duktape/blob/master/website/api/duk_push_proxy.yaml. So you would do something like:

```c
duk_push_array(ctx);  /* target */
duk_push_object(ctx);  /* handlers */
/* Setup handlers, e.g. handlers.get, .set, etc */
duk_push_proxy(ctx);  /* [ target handlers ] -> [ proxy ] */
```

Before 2.2.0 there's no direct API call but you can do something like:

```c
duk_get_global_string(ctx, "Proxy");
/* push Proxy parameters: target, handlers */
duk_new(ctx, 2);  /* new Proxy(target, handlers); */
```

I can add these to the Wiki.

**Comment by mike-lischke** [comment]
Ah, nice addition. Do you have an ETA for 2.2.0?

**Comment by svaarala** [comment]
Release scheduling is not very strictly planned beforehand, as it's more about releasing once there are enough changes to justify a full testing and documentation round. I think there's enough substance between 2.1.0 and master to do the 2.2.0 release in a month or two.

**Comment by mike-lischke** [comment]
Excellent, thanks for all the hard work!

**Comment by mike-lischke** [comment]
When you write the documentation for a proxy, can you please also add example implementations for getters and setters and other traps (like ownKeys)? Thanks.

**Comment by svaarala** [comment]
For ownKeys etc you can also look into MDN, e.g.: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/ownKeys.

For the most part I've tried to avoid writing extensive documentation for generic Ecmascript features because that already exists on the net. So the documentation is focused on:
- Describing Duktape features, e.g. what property virtualization mechanisms are available
- Providing minimal examples to get started (something to test and modify), but not extensive examples of standard Ecmascript features and APIs because that already exists and is not Duktape specific
- Covering the C API which can't be looked up anywhere else
- Describing Duktape limitations and special behaviors

Extensive examples for Proxy traps themselves, as far as Duktape doesn't do anything differently, would IMO be best handled by links to existing resources.

**Comment by mike-lischke** [comment]
All the documentation you mentioned is JS stuff, not duktape. I have a hard time to make this work in my C++ implementation. For instance: when you create a proxy for an array, how do you actually call the methods of the wrapped objects (slice(), toString() etc.) in your getter, for all the things you don't want to customize? Would be so great if there was a code example explaining all these little tricks.

**Comment by svaarala** [comment]
Don't get me wrong, I agree it'd be great to have a lot of documentation - it's just that there isn't much time to write it, so I'm trying to make sure that whatever time is put in makes the most impact.

For that Array case, one useful way to think about it is to first figure out how to do it in pure Ecmascript. Once you have that idea, translating it to C is usually straightforward, because the C API mostly revolves around doing the same operations in a slightly different way. There are some actual differences of course, but this general approach still quite often works.

Re: your specific use case, I'm not sure what you're trying to achieve so it's quite difficult to answer exactly, but typically a `.get` trap would just return `target[key]` if the key isn't virtualized. If the key is, say, `.toString`, the function gets returned and called (the Proxy doesn't do it).

For example:

```js
A = new Proxy([ 'X', 'Y', 'Z' ], {
    get: function (targ, key, recv) {
        print('get', key);
        if (key == 'foo') { return 'FOO'; }
        return targ[key];
    }
});

print(A.foo);
print(A.bar);
print(A.toString());
```

Prints:

```
get foo
FOO
get bar
undefined
get toString
get join
get length
get 0
get 1
get 2
X,Y,Z
```

**Comment by mike-lischke** [comment]
Sorry for asking so many noob questions. I'm not a JS expert and look mostly on the C/C++ side of things here.

You approach works nicely for normal properties., but not for functions. For instance when I call `myArrayProxy.slice()` my getter gets called with `slice` as the property name. Returning `target["slice"]` simply doesn't work. To give you an impression how far I came pls look at this code:

```
/**
 * The getter trap for a string array proxy.
 */
static duk_ret_t arrayHandlerGetter(duk_context *ctx) {
  duk_get_prop_string(ctx, 0, HIDDEN_PREFIX "data");
  StringArrayRef *target = static_cast<StringArrayRef *>(duk_to_pointer(ctx, -1));
  duk_pop(ctx);

  if (duk_is_number(ctx, -2)) {
    duk_idx_t index = duk_get_int(ctx, -2);

    if (index >= 0 && index < (*target)->size()) {
      duk_push_string(ctx, (*target)->at(index).c_str());
      return 1;
    }
  } else if (duk_is_string(ctx, -2)) {
    const char *name = duk_get_string(ctx, -2);
    if (strcmp(name, "length") == 0) {
      duk_push_int(ctx, (duk_int_t)(*target)->size());
      return 1;
    }

    duk_dup(ctx, -2); // Add name to stack again, will be replaced by the following call.
    duk_get_prop(ctx, -4);
    return 1;
  }

  return 0; // For `undefined`.
}
```

**Comment by svaarala** [comment]
Hmm, but in the example I posted above the `.toString()` property is a function and is looked up via the Proxy?

**Comment by svaarala** [comment]
Could you provide the call site where arrayHandlerGetter is pushed (duk_push_c_function())? Just wanted to check that nargs is 3 as expected (most likely it is).

One thing that should be unrelated to looking up `.slice()` is the index handling. Unfortunately standard Ecmascript Proxy traps get their key ToString() coerced, so you would never see integer indices in the Proxy calls. Instead e.g. `arr[123]` would come out with the key `"123"`. (This is something where a custom behavior might make sense: coercing the array index keys is quite counterproductive.)

**Comment by svaarala** [comment]
Here's a `.slice()` example in pure Ecmascript, not sure if it comes close to your use case:

```js
var ARR = 'a b c d e f g h i j'.split(' ');
print(ARR);

var P = new Proxy(ARR, {
    get: function (targ, key, recv) {
        print(typeof key, key);
        if (key === 'length') { return 5; }
        return targ[key];
    }
});

var res = P.slice(2, 8);
print(res);
```

This prints:

```
a,b,c,d,e,f,g,h,i,j
string slice
string length
number 2
number 3
number 4
c,d,e
```

**Comment by svaarala** [comment]
@mike-lischke Re: Proxy index handling, forgot that I left the custom behavior still in master :) I.e. keys appear uncoerced (numbers instead of strings) as shown in the .slice() example above (number 2, number 3, etc).

That behavior is not compliant but it's quite useful. At some point the behavior needs to be made compliant - and when that's done, I'd like there to be an API which allows creation of a Proxy with this non-compliant key coercion behavior (= numbers not coerced to strings) because it's, IMO, much more useful than the standard one. It's probably useful to anticipate that before `duk_push_proxy()` is released, so added #1542.

**Comment by mike-lischke** [comment]
Actually, I like the non-compliant behavior. Why coercing to strings and then parsing them again to get an index? This part works very nicely in my proxy impl. Here's the full setup procedure for my proxy:

```C++
void Utils::pushArrayProxy(duk_context *ctx, std::string const& name, StringArrayRef const& array) {
  // Start with preparation to create a JS Proxy object.
  duk_get_global_string(ctx, "Proxy");

  // Next is the target object for the proxy.
  duk_idx_t objectIndex = duk_push_object(ctx);
  {
    duk_push_pointer(ctx, new StringArrayRef(array));
    duk_put_prop_string(ctx, objectIndex, HIDDEN_PREFIX "data");

    // Store a boolean flag to mark the object as deleted because the destructor may be called several times.
    duk_push_boolean(ctx, false);
    duk_put_prop_string(ctx, objectIndex, HIDDEN_PREFIX "deleted");

    // Store the destructor function as well.
    duk_push_c_function(ctx, arrayObjectFinalizer, 1);
    duk_set_finalizer(ctx, objectIndex);
  }

  // Third is the handler that allows us to virtualize the access to the array.
  duk_idx_t handlerIndex = duk_push_object(ctx);
  {
    duk_push_c_lightfunc(ctx, arrayHandlerGetter, 3, 0, 0);
    duk_put_prop_string(ctx, handlerIndex, "get");
    duk_push_c_lightfunc(ctx, arrayHandlerSetter, 4, 0, 0);
    duk_put_prop_string(ctx, handlerIndex, "set");
    duk_push_c_lightfunc(ctx, arrayHandlerOwnKeys, 1, 0, 0);
    duk_put_prop_string(ctx, handlerIndex, "ownKeys");
  }

  // Instantiate the Proxy object.
  duk_new(ctx, 2);

  duk_put_prop_string(ctx, -2, name.c_str());
  duk_push_string(ctx, name.c_str());
  duk_def_prop(ctx, -2, DUK_DEFPROP_CLEAR_WRITABLE | DUK_DEFPROP_CLEAR_CONFIGURABLE);
}
```

and this all seems to work well (`name` is the property name "execArgv"). The thing is that for e.g. slice() my getter is called with a string argument (in this case "slice") and I have no idea how to forward this as a function to the target.

Here's the JS test code for the proxy (I used `reverse()` however to avoid having to deal with (optional) parameters yet:

```JS
function test() {
  var args = process.execArgv;
  print(Object.getOwnPropertyNames(args));
  print(args.reverse());
}
```

`getOwnPropertyNames` works via the `ownKeys` implementation. for `reverse()` I get the error 

>Could not load main script: main.js
>TypeError: undefined not callable
>    at test (main.js:15)
>    at global (main.js:28)

**Comment by svaarala** [comment]
Regarding forwarding "slice" to the target, what actually happens when you evaluate `proxy.slice(1,2)` is:
- Proxy .get trap gets called with "slice". It is expected to return the function (Array.prototype.slice for example) without calling it.
- The call is then made based on the value returned. This is totally invisible to the Proxy.

So the only thing the Proxy .get trap is expected to do is return `target.slice`.

**Comment by svaarala** [comment]
Hmm:

```
 // Next is the target object for the proxy.
  duk_idx_t objectIndex = duk_push_object(ctx);
```

So here you are pushing a normal object and not an array -- should that be `duk_push_array(ctx)` if you wanted `.slice()` etc to work?

**Comment by svaarala** [comment]
If the Proxy target object needs to be a normal (non-array) object but behave in an array-like fashion, you can use some of the Array.prototype functions with it. For example:

```js
var obj = {
    0: 'foo',
    1: 'bar',
    2: 'quux',
    3: 'baz',
    4: 'quuux',
    length: 5
};

print(obj.slice);  // undefined

print(Array.prototype.slice.call(obj, 1, 3));
```

Array.prototype.slice() is required to work with an "array-like" object having a .length and indexed keys. Note that `arguments` is actually an object like this: it's not an array, but has array-like properties.

If you wanted to use .slice() with a normal (non-array) Proxy target object, you'd need the following in the .get trap:

```js
if (key === 'slice') { return Array.prototype.slice; }
```

because the target object, inheriting from Object.prototype, doesn't have an own or inherited property named `slice`.

**Comment by mike-lischke** [comment]
:-D omg, that's it! I had that thought to try out push_array later once I got the accessors done. By changing the object to an array everything started working as it should. Awesome! Thanks a lot. Feel free to use my code for the proxy doc. It might help others to save a few hours searching. Thanks alot!

**Comment by mike-lischke** [comment]
Hmm, interesting technique. This should definitely be part of the proxy doc (maybe also with some C code to show to actually return a prototype function in the getter).

**Comment by svaarala** [comment]
> This should definitely be part of the proxy doc (maybe also with some C code to show how to actually return a prototype function in the getter).

This is in the difficult grey area: the technique is used generally in pure Ecmascript code, outside of Duktape and even Proxies, so it's definitely "common Javascript stuff" and maybe best linked to. This again just from a pure "best bang for buck" perspective because the time available to write detailed documentation is limited .. :)

**Comment by svaarala** [comment]
> :-D omg, that's it! I had that thought to try out push_array later once I got the accessors done. By changing the object to an array everything started working as it should. Awesome! Thanks a lot. Feel free to use my code for the proxy doc. It might help others to save a few hours searching. Thanks alot!

You're welcome :) In this case starting from a pure Ecmascript example might have saved some of that searching because there would be less moving parts when getting the Proxy pattern first to work, then moving to C etc.
