### ISSUE TITLE
[Q] Proxy enumeration problem

### ISSUE THREAD

**Issue by mike-lischke** [svaarala/duktape#1543]
(let me know if I should rather ask on Stackoverflow)

Almost done with the proxy I have a last thing left: enumeration. For code like:

```JS
for (var arg in arguments)
  print(arg);
```

I get no output, even though my `ownKeys` code is called and returns the array indices. Someone mentioned the returned list is filtered against the list of keys in the target object (like an intersection). What's the correct way to make enumeration working?

**Comment by mike-lischke** [comment]
@svaarala Can you pls help with that?

**Comment by svaarala** [comment]
@mike-lischke I'm a bit busy right now but I'll get back later today.

**Comment by svaarala** [comment]
One perhaps surprising thing about Proxy objects is that the traps are not free to return just any "fake" values they want. The specification involves a variety of trap constraints that should be checked by the engine (Duktape doesn't yet enforce all the constraints and is also missing some Proxy traps). This is one reason why Proxies are not always the most ideal mechanism for object and property virtualization.

For enumeration specifically, the "ownKeys" trap gets invoked, but what comes out `for-in` is further filtered against the enumeration target to ensure that only enumerable keys get enumerated. Because Duktape doesn't yet provide a trap for a property descriptor query that enumerability check happens against the target object. If the target object is missing a property, or the property exists but isn't enumerable, it won't be enumerated.

Here's an example:

```js
var target = [ 'foo', 'bar', 'quux' ];
var proxy = new Proxy(target, {
    ownKeys: function () { return [ '0', '1', '2', '3', '4', 'noSuch', 'length' ] }
});
for (var k in proxy) {
    console.log(k);
}
```

Both Duktape and Firefox will log:

```
0
1
2
```

The '3' and '4' properties are skipped because they don't exist in the target, same for 'noSuch'. The 'length' property exists but isn't enumerable, so it won't come out of the for-in. If one omits 'length' from the ownKeys trap result, Firefox will throw a TypeError from the `for-in` because a trap constraint is violated: ownKeys trap result must include all non-configurable target properties. Duktape doesn't enforce that constraint at present so 'length' can be omitted now.

Duktape doesn't implement the 'getOwnPropertyDescriptor' trap at present. But if it did, one could fake the existence of properties so properties that didn't actually exist in the target object could be reported as enumerable. Here's the above example updated to do that, and tested with Firefox:

```js
var target = [ 'foo', 'bar', 'quux' ];
var proxy = new Proxy(target, {
    ownKeys: function () {
        return [ '0', '1', '2', '3', '4', 'noSuch', 'length' ]
    },
    getOwnPropertyDescriptor: function (target, key) {
        // Cannot report 'length' as enumerable (that would violate
        // getOwnPropertyDescriptor trap constraints).
        if (key === 'length') {
            return Object.getOwnPropertyDescriptor(target, key);
        }
        return {
            value: target[key],
            enumerable: true,
            writable: true,
            configurable: true
        };
    }
});
for (var k in proxy) {
    console.log(k);
}
```

This prints (on Firefox):

```
0 
1 
2 
3 
4 
noSuch
```

The `length` property, which is non-configurable and non-enumerable, cannot be reported as enumerable; there's an ES2015+ trap constraint which prohibits that (Firefox will TypeError from that).

In general the ES Proxy provides least constraints for trap results if the target object is an extensible object without any own properties. For enumeration the "ownKeys" trap can report arbitrary keys, but the "getOwnPropertyDescriptor" trap must back them up by indicating the keys exist and are enumerable. Since Duktape doesn't yet implement the latter trap, at present you can't fake enumerable keys unless they actually exist on the target, and are enumerable own properties of the target.

**Comment by svaarala** [comment]
I'm not sure if `arguments` in your example is an actual arguments object (or a proxified version of one). But if so, `arguments` is a special array-like object (but not actually an array). The number index keys ('0', '1' etc) map to argument values and are enumerable. So a Proxy for an `arguments` target can use `ownKeys` to filter (but not extend) the index set. For example:

```js
var ARGS;
function test() {
    ARGS = arguments;
}
test('foo', 'bar', 'quux');

var proxy = new Proxy(ARGS, {
    ownKeys: function () {
        return [ '0', '2', '4' ]
    }
});
for (var k in proxy) {
    console.log(k, proxy[k]);
}
```

prints:

```
0 foo
2 quux
```

The '4' key is omitted because it doesn't exist in the target.

**Comment by fatcerberus** [comment]
I find these constraints interesting (and maybe a little frustrating), because people--including some involved in TC39--are always harping on how a Proxy object should always have final say wherever one is involved.  Having constraints that are validated directly against the target object seems to contradict that goal.

**Comment by svaarala** [comment]
For the most part using an empty extensible target removes most of the constraints though - but for enumeration specifically this doesn't yet work because one needs both "ownKeys" and "getOwnPropertyDescriptor" traps to fully control enumeration.

But even so for much application work where the Proxy is created from trusted "platform" code I'd prefer a Proxy without any constraints. For Duktape the two main approaches are:
- Extending the Proxy concept with some optional custom behavior, e.g. setting some Duktape specific keys on the handler object (say `__constraints: false` or `__key_coercion: false`).
- Supporting Proxy but providing some more virtualization and native code friendly virtualization mechanism. This may be a good alternative because Proxy is a relatively slow concept because of all the intermediate Array objects, string key coercion, constraint checks, etc.

Not sure yet where to go on this, it probably makes sense to complete the Proxy traps first.

**Comment by mike-lischke** [comment]
@svaarala Thanks a lot for the great explanation. That should go to the proxy documentation as well :-)

However, I'm still not sure what I could do to get proper enumeration with the current duktape code. The underlying target object is an array and I cannot change that or I lose all the array handling functionality. I also agree with @fatcerberus that the control the target objects has over enumeration is rather counter intuitive, since the proxy is there to override that behavior, if wanted.

Do you see any hack or workaround I could apply to make enumeration still work (until duktape supports the `getOwnPropertyDescriptor` trap)?

**Comment by svaarala** [comment]
@mike-lischke If the array elements do exist, you can use `ownKeys` for enumeration, you just cannot return indices that don't actually exist. Is this the case?

**Comment by mike-lischke** [comment]
There are no entries in the target object, if you mean that. The whole point of the proxy is to avoid that and use a different backing store.

**Comment by svaarala** [comment]
If the target is empty (in which it also doesn't matter whether it's an array of a plain object) there's currently no way to get keys to enumerate: the existence check after `ownKeys` will cause the returned properties to be ignored.

**Comment by mike-lischke** [comment]
Well, originally I had a plain object there and had problem with  standard array functions (slice() etc.), and after you mentioned to push an array object instead things started to work pretty well.

You mentioned to forward calls to the array prototype for anything I do not resolve myself. I'll give that a try. Thanks so far!

**Comment by svaarala** [comment]
I could check how difficult `getOwnPropertyDescriptor` support would be. It's not technically difficult except that the operation is currently side effect free and involving a Proxy trap changes that which may or may not be an issue. If not, I might be able to get the trap into master in a relatively short time.

**Comment by fatcerberus** [comment]
In general it seems like full Proxy support will mean that nearly all (if not actually all) object access  can potentially have side effects.  It's something worth keeping in mind going forward, to be sure.  From what i remember there are quite a few places internally where Duktape assumes an operation is side-effect free that will likely need to change.

**Comment by svaarala** [comment]
Sure, dealing with side effects correctly is of course something that needs consideration always. For property code most of the work is done (and accessors already trigger side effects so Proxy wasn't difficult there). Some of the more difficult remaining cases are:
- getPrototypeOf: not difficult for e.g. reading `__proto__` but affects all prototype walks in code
- preventExtension: some call sites may be difficult
- getOwnPropertyDescriptor

`apply` and `construct` are probably not very difficult because call handling involves side effects anyway (and in fact I'll probably implement these next because they should dovetail well with the inline .call(), .apply(), and .construct() handling).

**Comment by mike-lischke** [comment]
Speaking of `__proto__`, in the vscode debugger I never see that like for other objects. Instead I have `__artificial`. Is that from the duktape debugger protocol or the debugger extension?

**Comment by mike-lischke** [comment]
About `getOwnPropertyDescriptor`: since this is a getter it should be pretty riskless to implement.  So it would be very nice if you could add it. However, we still have simple `for (var i = 0; i < obj.length; ++i)` loops, so it's not totally urgent problem. Thanks anyway for all the help!

**Comment by svaarala** [comment]
The `__proto__` property is the "internal" prototype of the object and is an inherited getter. There's also an artificial debugger property which provides the value without a getter call.

**Comment by svaarala** [comment]
> About getOwnPropertyDescriptor: since this is a getter it should be pretty riskless to implement.

There are several places where property attributes of a property are queried internally, so it's not limited to enumeration only. I could add the trap initially for enumeration only, to fix this particular limitation, and then figure out what changes are needed for all the remaining call sites. But we'll see, I'll check what's needed when I get the chance :)
