### ISSUE TITLE
Please help me understand the event loop example...

### ISSUE THREAD

**Issue by mike-lischke** [svaarala/duktape#1566]
... or does duktape support inserting arbitrary code while executing a script?

I'm going to implement an event loop to support timers in my app. For that I studied the event loop example in the repo and found it pretty easy to follow, many thanks for that. However, I have one serious problem with it. Assume the user code is a long running script (maybe with an own loop) and calls `setTimeout` at some places. Since the event loop is blocked by this script how can it actually run the timer callbacks?

I believe this is not an esoteric question. `setTimeout` is described as scheduling a callback which is called somewhere after the given delay, but does not require the script which called `setTimeout` to finish before doing so. That would just be nonsense.

**Comment by mike-lischke** [comment]
With the help of a separate thread it would be possible to measure the passed time so far and then insert the callback in the event loop task list for execution. And if any previous callback is taking too long all others will be delayed. That's ok and documented. However, for the main script that shouldn't be happening. Running callbacks must be possible even if the main script is still running as well.

**Comment by fatcerberus** [comment]
> setTimeout is described as scheduling a callback which is called somewhere after the given delay, but does not require the script which called setTimeout to finish before doing so. That would just be nonsense.

Actually this is exactly how an event loop works, even in browsers.  JS is single-threaded, so blocking code will prevent events (including timeouts) from being processed.  This is the reason most browsers will issue a "this script is taking too long" warning, because as long as a script continues to run nothing else can happen.

**Comment by svaarala** [comment]
@mike-lischke Right, the current callback is not interrupted like @fatcerberus said. Instead, setTimeout() calls schedule callbacks to be executed later. When the current call stack unwinds to the event loop (more on that below), we then check the scheduled times vs. current time to see which timers have fired and call the related callbacks. It's possible for a callback to occur much later than scheduled if previous callbacks take too much time.

The event loop itself may run outside of Duktape, i.e. when we check for fired timers or wait for the next timer to fire nothing is running on the Duktape callstack.

But it's also possible to implement the eventloop as an Ecmascript or Duktape/C function. That function can then just block when there's nothing else to do before running new callbacks.

**Comment by mike-lischke** [comment]
Yes, the principles of the event loop are mostly clear to me. What bothers me is that even for a script currently running (e.g. the initial script that's loaded) you will not get any timer callback. This is something I have understood differently. How can you ever call async code if there's nothing executing it while the initial script is running? That's totally confusing me.

Imagine you have an application implemented in the loaded script which doesn't return because it has an own loop. But that script wants to call `setTimeout` for async work. How's that suppose to work? Since it doesn't return the event loop can never trigger the callback.

**Comment by fatcerberus** [comment]
That's just the nature of the beast.  Essentially what you want to do is get the event loop to do your work for you.  You don't have a "main loop" like you would in, e.g. a C program.  If you did that in a browser you would lock up the page.

Look at some Node.js code to get an idea of how async stuff works.

**Comment by fatcerberus** [comment]
On the other hand, it actually *is* possible to do what you're suggesting.  My game engine miniSphere, for example, has `system.run()`, which performs event loop processing (fulfilling promises, running timers, etc.) and then returns, so that you can make loops like this:

```js
while (!conditionIsSatisfied && system.run()) {
     // perform long operation
}
```

**Comment by mike-lischke** [comment]
I'm studying the node event loop the entire afternoon already and it behaves essentially like the duktape event loop example. So it opens the [same question](https://stackoverflow.com/questions/44571985/how-can-a-script-and-settimeout-setinterval-work-together-in-nodejs/44572872#44572872).

A browser is different, because it has additional threads and a different access to OS messaging (and I don't know if V8 or Webkit allow to run arbitrary code while they execute a script). But what I know is that a timer callback should be triggered even if the script which set it up has not yet finished. Otherwise the timeout concept makes no sense. And when you read the various documentations about `setTimeout` you will never find a sentence that says: the callback is only triggered after the current script has ended. That would just be ridiculos.

**Comment by fatcerberus** [comment]
To put it in perspective, you're basically asking for the ability of a timer to preempt normal execution.  That requires threads (and all that implies--race conditions, synchronization, etc.).  Ecmascript is single-threaded, so the best you can do is cooperative multitasking.  That means you either hang it on the event loop like Node does, or else implement something like my `system.run()` function to trigger the checks manually.  Those are your only real options.

**Comment by mike-lischke** [comment]
Hmm, I don't understand what the timers are good for then. When the script which set up a timer must be finished to make it trigger, what can the callback do actually? The code it was for is already gone.

Probably I'm thinking too much in entire applications. Seems normal JS execution is a stream of short functions interleaved with timer callbacks.

**Comment by fatcerberus** [comment]
> Seems normal JS execution is a stream of short functions interleaved with timer callbacks.

That's how async works, it's not really specific to JS.  You're thinking in terms of synchronous code, which requires you to provide a main loop.  With async, the *platform* provides the main loop and you just hang stuff on it and run off.  Because JS has closures, when your callbacks *do* execute, they still get to access all the variables that were in scope at the time they were set.  Therefore you don't actually lose any information.

**Comment by mike-lischke** [comment]
:-D That's not really async from my perspective. Real async execution means parallel execution and JS is single threaded, so it's just an illusion. I thought there is a trick to inject a callback while the JS engine is interpreting other code. If that were possible it would make things work like people (like me) do expect ;-)

**Comment by fatcerberus** [comment]
They're actually different.  Parallel means threads, async is just doing stuff out-of-band (usually via an event loop, outside normal program flow).  The latter is meant to be have predictable and 100% repeatable behavior; the former often doesn't.

And I don't want to be the one that has to debug the race conditions your proposed system would lead to. 😜 (gentle ribbing there, don't take that as an attack)

**Comment by svaarala** [comment]
@mike-lischke Most of the issue was covered already, but a few comments on interrupting execution and "injecting" a callback.

True parallelism is technically not needed if one interrupts a currently executing function, runs a short timer callback, and then resumes execution of the function. That's how an OS works anyway when you only have one core.

There's no public API mechanism to do that at present and it's not really a use case supported by the Ecmascript specification which is single-threaded throughout. However, Duktape does have an internal "executor interrupt" mechanism which is used for debugger integration and execution timeout. It can periodically interrupt bytecode execution (for every N instructions, where N can be even 1).

That same mechanism could be extended with reasonable effort to allow an interrupt call to be made to a user callback which could then e.g. execute timers and, when finished, resume running the interrupted function, without needing an explicit yield/cooperate call. This has actually been requested a number of times, and if you combine it with duk_suspend() and duk_resume(), you'd then actually have pre-emptive multitasking for Ecmascript code which would be quite useful in a number of use cases.

So longer term there may be some solution that might fit your expectations. Such a solution would necessarily be very engine specific because Ecmascript as a standard is based on a single thread, a single thread running through a "job queue", etc.

**Comment by mike-lischke** [comment]
@svaarala Very interesting idea. However, this may make duktape behave differently than other JS engines, which might have its own problems.

@fatcerberus I'm fully aware of the implications of multithreading. Using that since more than 2 decades ;-)

Thanks again for your help. I'll come back when I have a new question... :-D

**Comment by mamod** [comment]
@mike-lischke adding to what @fatcerberus and @svaarala already said, you're right, it's nonsense in one case which is putting a blocking code inside a timer, this way the main loop will not be able to process other operations so it will be pointless, I tried to explain how timers work simply and posted an answer to your stackoverflow question [here](https://stackoverflow.com/questions/44571985/how-can-a-script-and-settimeout-setinterval-work-together-in-nodejs/44576108#44576108)

In general event loops are great for network operations which do not block, and not so good with cpu bound operations like io, so that's why libuv `(event loop used in nodejs)` use threads to handle io operations

you might also be interested in [dukluv](https://github.com/creationix/dukluv) libuv bindings for duktape

**Comment by svaarala** [comment]
@mike-lischke To be clear, Duktape wouldn't impose that pre-empting on the user - it'd just be an option if you wanted to use it via Duktape specific APIs, similarly to how Duktape coroutines are an option but not in any way mandatory.

**Comment by mike-lischke** [comment]
@mamod Meanwhile I think I good a good idea about how timers work in JS. The only thing I can't yet wrap my mind around is how a main script can do significant work and still use timers. My assumption is currently that it internally sets up a timer after its setup to do the actual work. And dukluv looks very promising too. I'll take a closer look, thank you.

@svaarala Of course, I hadn't meant to use this facility as a general means to do dirty tricks :-) Just wanted to sound out what possibilities I have.

**Comment by fatcerberus** [comment]
How event loop-based systems usually work is that the "significant work" is queued to run on a background thread, immediately returning control to your program.  You don't actually block like you would with sync code, so your script unwinds quickly and you get a call back when the operation has finished, at which point you can fire off more work, and so forth (variables remain in scope thanks to closures--your script doesn't get unloaded just because it stops executing).

Async is quite a different animal from the traditional synchronous blocking style.  It took me a long time to "get it" too--promises confused me for the longest time.  So don't feel too bad about that. :)

**Comment by mike-lischke** [comment]
@fatcerberus Yes, I realized already that JS and all the things that came with it (first ajax, then promises, then async/await) are quite different than what you know from more tranditional languages like C++. Slowly getting my head around it...

@mamod Have you ever finished your NodeJS compatible library based on libuv and duktape? If so can you pls contact me directly?

**Comment by fatcerberus** [comment]
Those are all frameworks/platforms, JS is just a programming language like any other.  It can very much be used in the traditional manner (the Sphere game engine is scripted in C style, for example), it's just that because it got started as the language of the Web and browsers are based around an event loop, people are most familiar with the asynchronous style.  Async-Await and promises are hardly unique to JS--C# has them, for example.

Sorry, just felt that was an important distinction to make to clear up any misconceptions going forward. :)

**Comment by fatcerberus** [comment]
@mike-lischke For what it's worth, I'm personally not a big fan of async style--it can be confusing to read (async/await goes a long way to fixing that though), is difficult to debug, and you tend to lose context when hunting bugs because the callstack is constantly cleared.  It's a necessary evil in a lot of cases, but I try to avoid it whenever possible.

**Comment by fatcerberus** [comment]
The general name for this style of programming is "continuation-passing style":
https://en.wikipedia.org/wiki/Continuation-passing_style

**Comment by svaarala** [comment]
With Ecmascript 2015 the language itself does provide for a "job queue" and in a way brings more of the browser model into the core language. But that's optional to use and Duktape doesn't yet implement such a queue (it is needed for Promises).

**Comment by svaarala** [comment]
@mike-lischke If you don't want actual pre-emption, Duktape coroutines are already enough to implement a scheduler that switches between long running Duktape coroutines which can yield (e.g. to wait for an event) and then be resumed. As long as pre-emption is not needed, pure Ecmascript coroutines can have an appearance of actual multitasking - and this is a model I've used myself a lot and it's really convenient (at least in my view) because there's no unexpected pre-emption and thus no worries about atomicity etc.

In concrete terms you'd implement a scheduler that tracks runnable coroutines. When a coroutine is runnable, you `Duktape.Thread.resume()` it with the value it was waiting for. The coroutine then runs for a while and ultimately finishes or needs to wait for something again. If it needs to wait, it calls `Duktape.Thread.yield()` with a value that indicates what it is waiting for. The scheduler then keeps track of when that condition is set and resumes the coroutine again.

You can either track specific conditions (like timer, data read, etc) or provide some Promise/Future like object that allows any module to create a new waitable object without any specific scheduler support. With a generic Waitable the code that blocks could look something like:

```js
function read(n) {
    var W = new Waitable();
    this.current_pending_read = W;
    scheduler.wait(W);  // this would call Duktape.Thread.yield() internally
    var data = W.get();
}
```

Then, another coroutine may provide the data and allow the previous coroutine to resume, e.g.

```js
function feed(data) {
    this.current_pending_read.set(data);  // marks Waitable as 'set'
}
```

When the current coroutine yields, the scheduler then notices the waitable W is set and the initial coroutine is again runnable, and it can read the value using W.get().

With this model only `scheduler.wait()` indicates you're actually cooperating with other coroutines, and only the scheduler module is aware of Duktape.Thread.yield/resume. The scheduler in turn is only aware of the Waitable type and doesn't need to understand who sets what Waitables.

Typically the scheduler would run all runnable coroutines and then there's either nothing left (and you exit or whatever), or there are one or more timers to wait for. If so, one waits for the timer and then checks runnable coroutines again.

**Comment by mike-lischke** [comment]
That sounds like a very useful extra feature. Are there really threads involved or is Duktape.Thread more like a metapher for a thread? Where can I read more about duktape coroutines? Is there an example implementation somewhere?

**Comment by svaarala** [comment]
There are no native threads involved, Duktape threads (aka coroutines) are pure Ecmascript threads that can be yielded and resumed (they're require close to Lua coroutines). Conceptually it's pretty simple: a coroutine is launched (resumed) with a value, it runs and ultimately finishes or yields a value. From the caller's point of view a resume looks like a function call: value in, value out.

I don't have a worked out example but I could write an example at some point.
