### ISSUE TITLE
Debugging of files loaded dynamically via require()

### ISSUE THREAD

**Issue by mike-lischke** [svaarala/duktape#1578]
Debugging JS code loaded via the `require()` mechanism works nicely, as long as this is called when loading a script. However, I have a situation where `require()` is called during execution of a script (to load files enumerated previously from the file system). Files loaded that way cannot be debugged (I opened an issue for that with the [duktape-debugger](https://github.com/harold-b/vscode-duktape-debug/issues/26) project), but I believe now it's mostly a duktape problem (or rather something I do wrong).

I read code run with `(p)eval` cannot be debugged, but since `require()` works for all files loaded during load of a script I believe it should also work when that's called during execution. Is that possible?

**Comment by svaarala** [comment]
All Ecmascript code can be debugged, but the problem is locating the source for the function being debugged. For modules the source code is dynamically created because the module is wrapped inside a function to provide the necessary scoping rules, and getting that source is currently a bit difficult.

There are ways to work around this limitation, but the best fix would be for Duktape to store the source code for functions (this is not an option for many low memory devices but should be fine for debugging desktop applications) so that it can provide it on request, even for eval code, dynamically created function code, etc.

**Comment by svaarala** [comment]
@mike-lischke So some more detail on the debug client/target contract:
- The debug protocol simply carries a fileName/lineNumber when debugging. The fileName comes from the Function object being debugged. This is the simple, quite minimal underlying contract at present: target code is required to set `.fileName` in a useful manner, and debug client is expected to be able to find source files based on .fileName alone.
- The module-duktape module loader creates a wrapper function for the module. The wrapper doesn't disturb line numbers so that lineNumbers should be compatible with the unwrapped module source. The fileName of the wrapper is set based on `module.filename` (if present) or the absolute resolved ID of the module.
- The module-node module loader uses `module.filename` for the wrapper function (which is built similarly, without disturbing line numbers).

So, you could set `module.filename` in your module loader callbacks to the source file that the debug client is expected to find, i.e. the unwrapped module source file.

For example, with the module-duktape loader you'd do something like:

```js
// test.js
Duktape.modSearch = function (id, require, exports, module) {
    module.filename = 'aiee.js';
    return ...;  // return contents of 'aiee.js'
};

var mod = require('aiee');
console.log(mod);
mod.aiee();
```

When you debug `mod.aiee()` the debug protocol carries 'aiee.js' as the filename and the debug client can then use that to find the module source.

**Comment by mike-lischke** [comment]
I got it the work. Indeed this is again about filenames not matching. The `require()` call for these dynamically loaded files uses absolute paths which the duktape debugger cannot handle. By making them relative to the current workdir in the module resolution step things started to work nicely.

Btw. the module loader from @fatcerberus already sets filename and id properly, hence there's no need to do this in either the module resolution or load callback.

**Comment by svaarala** [comment]
I'm not sure if you mean module-node + some specific resolve/load functions, or an external (Minisphere?) module loader. But either way, good to hear the issue worked itself out :)

**Comment by mike-lischke** [comment]
Well, the duktape node module loader was written by @fatcerberus :-)

**Comment by fatcerberus** [comment]
> Btw. the module loader from @fatcerberus already sets filename and id properly, hence there's no need to do this in either the module resolution or load callback.

I don't understand this statement - the loader sets filename and ID to whatever the resolve callback says it should.  So "no need to do this in module resolution or load callback" does not compute. 🤔

**Comment by mike-lischke** [comment]
I hoped I could get away with a short sentence. It's just my lazyness that keeps me from writing long explanations :-). Sami suggested to set module.filename and module.id to a canonical filename that allows matching the module in the debugger client, which I assumed suggest to do that in the module resolution step (in the function that is registered for `resolve` in the duktape node module code). However, that is not necessary, because this is already done in that said duktape node module code.

**Comment by fatcerberus** [comment]
Yeah, that makes more sense now!

All you have to do in the `resolve` callback is to calculate a canonical module name based on what was passed to `require()`, then the loader wires everything up for you.  It's quite convenient isn't it? :)

In case you're curious, the design of the Node module loader was based on this proposal: #60.

**Comment by mike-lischke** [comment]
Works beautifully! Debugging my Jasmine tests in vscode using duktape in a C++ app has never been nicer :-D

**Comment by fatcerberus** [comment]
I love the debugger, it's my favorite Duktape feature :)
