### ISSUE TITLE
How to debug debug-protocol issues?

### ISSUE THREAD

**Issue by mike-lischke** [svaarala/duktape#1581]
When I enable the log for the duktape-debugger extension I get (among others) this output:

```
OUT -> <REQ: 1> <0x1c: GETCALLSTACK>
IN <- <REP: 2> <str: main.js> <str: global> <int: 10> <int: 26> <str: eval> <str: > <int: 1> <int: 1> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <str: undefined> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 1> <str: TypeError: cannot read property 'constructor' of undefined> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <str: [object global]> <EOM: 0> 
[FE] scopesRequest
OUT -> <REQ: 1> <0x1d: GETLOCALS>
IN <- <REP: 2> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <str: undefined> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <tval: undefined> <EOM: 0> 
[FE] variablesRequest
```
How can I find out what is actually missing (that undefined)? I tried debugging this in duktape/C but couldn't get what that undefined is actually supposed to be.

**Comment by harold-b** [comment]
This is an issue related to the extension, you should open an issue over there. At a glance it looks like these are the evals emitted on a set of variable names in order to get their constructor name and display it as the type's name. The error is harmless, means the specified variable does not have a 'constructor' property.

**Comment by mike-lischke** [comment]
Copied to harold-b/vscode-duktape-debug#28
