### ISSUE TITLE
Enumerating object properties shows self references

### ISSUE THREAD

**Issue by mike-lischke** [svaarala/duktape#1590]
While writing a little object dump utility function (using duk_enum) I saw that many objects point to themselves (e.g. `Error.constructor.constructor.constructor...` or `Error.toString.toString...`). This quickly leads to a stack overflow. What is the rational behind these references and how can I find out if I should stop iterating over them?

**Comment by svaarala** [comment]
The ES specification includes a lot of circular references by design, and these are not unique to Duktape. For example, all constructors have a `.prototype` property, pointing to their (default) prototype object, and that prototype object has a `.constructor` property pointing back to the constructor function. For that particular reference the use case is that when you say `instanceObject.constructor` you can get a reference to the constructor function.

If you want to do a deep object dump, you need to deal with (1) circular references and (2) shared reference targets (if you want to distinguish between identical object instances vs. same object being referenced from more than one place). There's also a third technical problem where enumeration is not read only, e.g. you're enumerating Proxies, and then enumeration itself may cause arbitrary side effects to other objects.

Loops are typically handled using some form of visited/visiting object tracking. One useful technique is a tracking object, whose key is `Duktape.info(val).hptr`, the heap pointer of the object in question. The value could be the object itself, to ensure it doesn't get freed prematurely (and thus allowing the pointer to be potentially reused). This is an actual concern if Proxies are involved in enumeration, because they may have arbitrary side effects.

**Comment by mike-lischke** [comment]
Right, I didn't think of the usual prototype self reference and also sharing of prototypes. With that in mind it's easy to come up with a nice dump routine. Thanks for your quick help.

**Comment by svaarala** [comment]
Safe, side-effect free arbitrary object graph dumping is relatively challenging in standard Ecmascript unfortunately. But you can come up with something that's almost always enough, at least if you're not dealing with actively hostile code like in some sandboxing scenarios.
