### ISSUE TITLE
Enumerator flags problem

### ISSUE THREAD

**Issue by mike-lischke** [svaarala/duktape#1592]
This issue is about 2 things related to enumerations in duktape/C. First the [Duktape API enumeration flags section](http://duktape.org/api.html#defines.9) needs an update. It still lists the 1.x flags.

The real issue is however something else: I'm working on a [util.inspect](https://nodejs.org/api/util.html#util_util_inspect_object_options) implemention with duktape. For that I played with the `DUK_ENUM_NO_PROXY_BEHAVIOR` to see if that would help implementing that special proxy view (with target and handler). It does not, but shows a strange behavior when used with `DUK_ENUM_INCLUDE_HIDDEN`. In that case `duk_enum()` throws the error:

> TypeError: object required, found true (stack index -1)

As soon as I remove the proxy flag everything starts working again. I get this error probably for a proxy property (an array proxy) I created as one of the object members. It shows the virtualized entries when enumeration of hidden member is enabled (and no-proxy-behavior is off), but shows nothing when hidden members are excluded (which seems strange, since these virtualized members are not hidden). Not sure if that's related. I'm just mentioning it for completeness. The main issue is that `duk_enum()` fails when used with the no-proxy-behavior flag together with the show-hidden flag.

**Comment by svaarala** [comment]
Thanks, I'll look into it.

**Comment by svaarala** [comment]
Not sure if related, but the Proxy target/handler values are no longer hidden symbols but are `duk_hproxy` members instead. So at present there's no way to gain access to them from either Ecmascript or C code.

**Comment by svaarala** [comment]
Re: DUK_ENUM_NO_PROXY_BEHAVIOR, it's not a very useful flag at present and should probably be removed for several reasons:
- The _Target and _Handler properties used to be enumerable using the flag. However, they were internal properties and thus not under versioning guarantees. Now the properties are no longer properties but part of duk_hproxy so they can't be enumerated any more.
- A useful flag would be a way to enumerate a target without side effects. That's necessarily going to be a partial result because one can't invoke Proxy traps. But in some contexts one may want to do that.

As a general use case, the ability to inspect internals of values is much wider (and IMO separate) problem from enumeration. Inspection is somewhat tricky to design right because if it comes with versioning guarantees, one can't expose too many internals because they change over time. On the other hand exposing internals without versioning guarantees is easier, but may be frustrating for application writers.

The current solution for inspection is very bare bones and based on two APIs (also the debugger protocol has some access to internals):
- [duk_inspect_value()](http://duktape.org/api.html#duk_inspect_value)
- Duktape.info(), its Ecmascript counterpart

The basic idea is to give an arbitrary value, and the result is an object providing a set of properties describing internal stuff related to the value. This includes things like pointers, type tags, reference count, etc. The keys are not under versioning guarantees and liable to change in any release. However, the set of properties is not very comprehensive; mostly I just transformed the Duktape 1.x array format (which was quite inconvenient) into an object result and left it at that. For example, duk_hproxy internals like target/handler table are not exposed now.

But, because the result is an easily extensible object, and because the keys are not under versioning guarantees, it's relatively straightforward to expose new stuff via the API (and then delete them if the internals change). So exposing the Proxy target/handler would be pretty easy now.

**Comment by fatcerberus** [comment]
Technically if one enumerates a Proxy without invoking any traps, the result is always an empty object--not even a partial one--because all operations are forwarded to the target object.  Not particularly useful :)

**Comment by svaarala** [comment]
@fatcerberus That's not necessarily 100% true if there is later on an API to interact with a duk_hobject directly, without any standard semantics. But right now in master (and 2.2) that's pretty much it.

**Comment by fatcerberus** [comment]
That's a good idea for a future change actually: Make hidden symbol property writes bypass the standard Proxy semantics.  If the eventual plan is for hidden symbols to not be accessible to Ecmascript at all, as is in implied in documentation, then Proxy traps shouldn't be invoked for them either.

**Comment by svaarala** [comment]
That's actually current behavior for hidden Symbols: they don't go through Proxy traps and are invoked on the Proxy itself. That's not necessarily the best behavior if Duktape and application hidden Symbols are separated (which may soon be the case in master).

So yes, you can add a hidden Symbol to the Proxy and then duk_enum() it with DUK_ENUM_NO_PROXY_BEHAVIOR. I stand corrected )

**Comment by svaarala** [comment]
@fatcerberus Re: hidden Symbols and Proxy behavior, I'm not sure what behavior makes sense going forward, so I don't want to change the current behavior unless that idea is clearer.

For application code it might be best if hidden Symbols mostly worked like ordinary Symbols, because it would be awkward if call sites working with a potentially proxied target would need to be aware of the Proxy to set hidden Symbols on the target. At least I would find that a bit surprising.

Skipping the proxy trap is quite important right now so that the trap doesn't get access to a potentially sensitive hidden Symbol. OTOH with the possible change that Ecmascript code can *never* access property values even when holding a hidden Symbol, this would be a non-issue and maybe the trap could be allowed to capture the write.

So, maybe the current behavior is a reasonable compromise between these issues.

For Duktape hidden Symbols the best behavior might be different because they're used for a little bit different purposes. For example, it matters whether a _Finalizer property is set on the target or the Proxy, and the correct behavior may be more a matter of each individual call site rather than there being a single right behavior.

For this the best solution would be C property access APIs allowing control of Proxy behavior, side effects, etc from the call site. But this wouldn't necessarily be tied to Symbols as such; one may want to write a property without a prototype lookup for instance, even for a normal string key, similarly to how duk_def_prop() with DUK_DEFPROP_FORCE bypasses some Ecmascript protections when called by (always trusted) C code.

**Comment by fatcerberus** [comment]
Assuming the behavior is implemented where Ecmascript code can't use the hidden Symbol, then it makes less sense to invoke the trap, since even a simple passthrough trap won't work then:

```js
targ[trappedKey] = value;
```

**Comment by svaarala** [comment]
Hmm, that's true - the trap could just log the access or something like that, but would be unable to forward it. Unless the trap was native, of course.

But in essence this would make it difficult to work with Ecmascript traps and hidden Symbols, which would be a big downside.

**Comment by fatcerberus** [comment]
Anyway I kind of hijacked @mike-lischke's issue, so we should continue this discussion elsewhere. :)

**Comment by svaarala** [comment]
Added a note to #1116 laundry list for Proxy.

**Comment by mike-lischke** [comment]
Looks like it is then not possible to implement proxy details in `util.inspect`. Not a big issue, I guess. No idea how often proxy output is required in `inspect` calls, but I think not very. For the error I have to check my older sources again and come back here once I know more.
