### ISSUE TITLE
GCC warning (-Wformat-truncation) for date formatting

### ISSUE THREAD

**Issue by Legimet** [svaarala/duktape#1602]
I got the following warning with GCC 7.1.0 when compiling Duktape using -O2 optimization:
```
duk_bi_date.c: In function ‘duk_bi_date_prototype_tostring_shared’:
duk_bi_date.c:980:39: warning: ‘%02d’ directive output may be truncated writing 2 bytes into a region of size between 0 and 4 [-Wformat-truncation=]
duk_bi_date.c:980:39: note: directive argument in the range [0, 59]
In file included from duktape.h:173:0,
                 from duk_internal.h:26:
duk_config.h:2152:26: note: ‘snprintf’ output between 7 and 11 bytes into a destination of size 8
 #define DUK_SNPRINTF     snprintf
duk_bi_date.c:980:4: note: in expansion of macro ‘DUK_SNPRINTF’
```

**Comment by svaarala** [comment]
The warning is harmless because the %02d fields will never actually be formatted with parameters outside [0,99] due to timezone offset range limits. Even if they did, `snprintf()` is used so that the result is memory safe. GCC has no reasonable way of knowing about the tzoffset range though.

Is the -Wformat-truncation warning enabled by default or do you enable it explicitly? When using snprintf() truncating the output is sometimes the intended behavior, so if the warning is enabled by default it seems a bit odd to me. Then again, there are several other warnings that are (IMO) too eager.

To avoid the warning `tmp / 60` would need to be changed into e.g. `(tmp / 60) % 24`, or equivalently `(tmp / 60) & 0x3f` or any other operation which doesn't affect the intended range, but guarantees a result in [0,99].

**Comment by Legimet** [comment]
I had enabled it with -Wextra. It seems to be a somewhat frivolous (especially for snprintf!) warning introduced in GCC 7. I will disable that warning, it's not a big deal.

**Comment by fatcerberus** [comment]
The truncation warning is harmless, but this note raises red flags:
> duk_config.h:2152:26: note: ‘snprintf’ output between 7 and 11 bytes into a destination of size 8

It appears to be warning of a potential buffer overrun?

**Comment by svaarala** [comment]
Ok, good to know. I'll try to fix this in any case as the repo Makefile builds with -Wextra.

**Comment by svaarala** [comment]
@fatcerberus I think it is saying that as far as GCC has determined the output size if 7-11 bytes, but the snprintf buffer is 8 bytes. The result would in all cases be truncated by snprintf().

**Comment by svaarala** [comment]
@Legimet If you have time, would be nice to hear if #1646 fixes the warning in your case as well. I was able to reproduce the issue with gcc-7 and the fix seems to work, but just in case.
