### ISSUE TITLE
Is it possible to clone a context at some point?

### ISSUE THREAD

**Issue by rbloch** [svaarala/duktape#1618]
Hello,

I've been browsing the api and guides for days without getting an answer so i'm asking here :smile:  

Is there a way to clone a `duk_context` ?

i've to run js scripts very often but these scripts need some initial libraries to be executed first. Everything works fine but i would like to "save" the sate of my context after executing the libraries so that i don't have to do it all the time. I was thinking about cloning the heap but it seems that there is no helper function to do this. 

Thanks in advance for your answer
Best

Rem

**Comment by svaarala** [comment]
There's no support for cloning a context as a whole - it's a pretty complicated problem because in its general form it involves arbitrary object graphs, native objects, related native allocations, etc. To support it there would probably need to be some support for providing object specific serialization/deserialization functions (to handle e.g. open files and sockets).

If you load framework code from .js files, you can compile each file and then `duk_dump_function()` the result before executing it. After that, you can `duk_load_function()` to run the code without compiling it again. This can be done for individual functions and eval code. For eval code you need to `duk_compile()` it with the `DUK_COMPILE_EVAL` flag, and then call `duk_dump_function()`. This has the effect of compiling but not executing the eval code.

**Comment by rbloch** [comment]
I definetly understand that this is a complex problem :+1: 

Thanks a lot for your answer. I saw the part about compiling in the documentation (great doc btw) but i was wondering if there was a better solution. I'll give it a try and benchmark it.
