### ISSUE TITLE
Make duk_debugger_pause() thread safe

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#1626]
I understand that Duktape isn't thread safe in general, but this is a particular case where it would be useful, when debugging, to be able to safely trigger a debugger pause from a separate monitoring thread. If I have Ecmascript code which enters an infinite loop, my event loop gets starved, so I have no way to break out of it and have to kill the process.

**Comment by svaarala** [comment]
That would either require a mutex-free solution for arbitrary number of threads doing a pause, or abstracting a mutex which is not a trivial portability concern.

I think a much better option is to use the interrupt mechanism and allow user code to react to the interrupts and request a pause on the interrupt call.

**Comment by svaarala** [comment]
Hmm, if you're running a debugger session when the infinite loop happens, couldn't you just send a Pause command? It gets processed automatically when the bytecode executor peeks the incoming debugger message queue.

**Comment by fatcerberus** [comment]
I'm attempting to debug an infinite loop and my engine is set to check for F12 keypresses to break into the debugger.  The event loop is being starved though so it can't respond to the hotkey.

It's possible something else is locking up because in this case the engine won't respond to any debugger commands at all, including Detach.  But when I attempted to debug using a native debugger, the cursor was placed on a `duk_call()` so I wanted to know where I was w.r.t. Ecmascript code being executed.

**Comment by svaarala** [comment]
From Duktape point of view, if the bytecode executor is actually running, it will periodically poll for debugger messages and should process a Pause (with some delay). There would be no difference to a separate thread setting a volatile flag indicating a pause request, and either method would have no good/bad impact on an UI eventloop as far as I can tell.

Maybe you could debug print from the debugger 'peek' callback to see if it gets periodically called or not? This would give a better idea what the actual problem is.

One shortcoming with the executor interrupted based periodic polling is that native calls don't count towards the executor interrupt, so if the infinite loop is native call heavy, the delay for messages to get processed may be longer than expected.

However, using a different signal thread + volatile pause request flag wouldn't perform any better -- unless the flag was checked more often than the executor interrupt, but this would imply a lot of additional overhead. So at least the most obvious implementation (volatile request flag) wouldn't improve the situation one way or another.

There are other useful steps to improve responsiveness, e.g. to do an interrupt check every time one returns from a native call so that native call heavy loops are more responsive. But this is independent of using a Pause request vs. a pause signal flag from a different thread. I'm all for these improvements because they fall into the existing debugger and thread model without introducing new portability issues etc.

**Comment by fatcerberus** [comment]
The only difference right now is that `duk_debugger_pause()` sets the interrupt counter to zero so that it gets processed "immediately" vs. issuing a pause from the client side which must wait until the counter expires + is subject to rate limiting.  It's just not atomic so I can't do it from a different thread.

Anyway, I'll do some further debugging because it might be that the bytecode executor isn't even in play in my particular case--like I said, the debugger won't respond to any commands from the client side, which is why my first thought was to do it from the server side. :)

**Comment by svaarala** [comment]
> The only difference right now is that duk_debugger_pause() sets the interrupt counter to zero so that it gets processed "immediately" vs. issuing a pause from the client side which must wait until the counter expires + is subject to rate limiting. It's just not atomic so I can't do it from a different thread.

That's true - but I don't see an efficient way of reliably setting the counter to zero from another thread. If one uses mutexes, it will impact the executor performance a great deal. If one doesn't use a mutex and writes the counter, it may have been read by the executor just prior and then get overwritten with a much higher value. Changing the counter volatile wouldn't solve that, and would also have a performance impact.

**Comment by fatcerberus** [comment]
Tried breaking into the MSVC debugger during the lockup, it is actively processing bytecode, but I've no idea what Ecmascript code that corresponds to since it still won't respond to debugger commands from the client. :(

**Comment by svaarala** [comment]
Are the transport callbacks being called? Specifically peek and read.

If not, there might be some previously unknown interrupt counter issue.

**Comment by fatcerberus** [comment]
Sure. I'll check into that later tonight.

**Comment by fatcerberus** [comment]
Okay, something really strange is going on.  I've confirmed that at least the peek callback is being called.  I assume read would also be called, if peek returned nonzero.  But as mentioned previously, I can't get it to respond to any debugger commands.  I also tried entering `duk_debugger_pause(ctx)` in the Immediate window, but oddly it had no effect.  So I'm not sure if I triggered a bug in the interrupt counter mechanism, or something else is going wrong somewhere else.  But if Duktape is actively executing bytecode then surely an interrupt should be triggered sooner or later?

**Comment by fatcerberus** [comment]
Well, I'm stupid.  I had forgotten that Dyad (the sockets library used in miniSphere) doesn't run on a separate thread, I have to manually update it in the event loop.  In this case the event loop is completely starved, and peeking on the debug socket always returns 0 because the read buffer never gets filled.  I might need to add a call to `dyad_update()` to the peek callback to work around that.

**Comment by fatcerberus** [comment]
Having just done the above fix of putting an event loop tick into the peek callback, I realize that's actually a useful trick to prevent infinite loops from hanging the engine.  How feasible it would be to implement some generic mechanism to call a callback every so often, even outside of the debugger (obviously this would require interrupt counter support)?  Unless that's already possible and I missed it...

**Comment by svaarala** [comment]
Not very difficult, from the executor's perspective it would appear just like another nested function call (which may already be triggered by many operations, e.g. a property read). Such a mechanism would also allow pre-emptive multitasking for scripts (when combined with duk_suspend() and duk_resume()) without any explicit yielding.

If you wanted to experiment, I think you should be able to just insert something like this into the interrupt callback function in duk_js_executor:

```c
duk_get_global_string(ctx, "hackInterrupt");
duk_pcall(ctx, 0);
duk_pop(ctx);
```

The only difficulty is coming up with a design that won't be baggage from a versioning perspective. Some of the issues involved are:
- Should the callback be able to control the next interrupt time either in opcode counts or time? Conceptually there are multiple consumers to the interrupt mechanism and the next interrupt value would need to be computed based on their needs (e.g. interrupt counter initialized to the smallest "next need").
- Should the callback be able to throw? Should it be able to throw an uncatchable error, as is now used for execution timeout?
- Should the callback be a Duktape/C call or not? There are differences in performance, value stack robustness, etc.
- Should multiple callbacks be supported, from a modularity perspective?
- Should the callback be specific to a global scope or the entire heap? Depending on what it is used for, both answers may be right.
- How does the callback relate to generalizing the execution timeout mechanism? In particular, how does it relate to doing nested timeout checks?

These don't need 100% exact answers, but enough of a solid idea to know what next steps are the best.

**Comment by svaarala** [comment]
Here's that hack test in action :) The diff:

```
diff --git a/src-input/duk_js_executor.c b/src-input/duk_js_executor.c
index 2f881988..851b1400 100644
--- a/src-input/duk_js_executor.c
+++ b/src-input/duk_js_executor.c
@@ -1881,6 +1881,12 @@ DUK_LOCAL DUK__NOINLINE_PERF DUK_COLD duk_small_uint_t duk__executor_interrupt(d
        DUK_ASSERT(thr->heap != NULL);
        DUK_ASSERT(thr->callstack_top > 0);
 
+       thr->interrupt_init = 0x10000000;  /* XXX: would need to prevent nesting */
+       thr->interrupt_counter = 0x10000000 - 1;
+       duk_get_global_string(thr, "hackInterrupt");
+       duk_pcall(thr, 0);
+       duk_pop(thr);
+
 #if defined(DUK_USE_DEBUG)
        thr->heap->inst_count_interrupt += thr->interrupt_init;
        DUK_DD(DUK_DDPRINT("execution interrupt, counter=%ld, init=%ld, "
```

The XXX note is about preventing interrupt counter nesting while the user callback runs. The interrupt counter needs to be set to some (high) value for the duration of the user callback so that it won't get repeatedly called (it's already <= 0). If called, it should be ignored and reset again to a high value, based on some state flag indicating we're in an interrupt.

Example session:

```
((o) Duktape 2.1.99 (v2.1.0-343-g87746c7c-dirty)
duk> for (var i = 0; i < 1e6; i++) {}
= undefined
duk> interruptCount = 0;
= 0
duk> hackInterrupt = function () { print('interrupt', ++interruptCount); };
= {_func:true}
duk> for (var i = 0; i < 1e6; i++) {}
interrupt 1
interrupt 2
interrupt 3
interrupt 4
interrupt 5
interrupt 6
interrupt 7
interrupt 8
interrupt 9
interrupt 10
interrupt 11
interrupt 12
interrupt 13
interrupt 14
interrupt 15
interrupt 16
interrupt 17
interrupt 18
interrupt 19
interrupt 20
interrupt 21
interrupt 22
interrupt 23
= undefined
```

**Comment by svaarala** [comment]
@fatcerberus What about the original issue BTW, was that event loop issue the root cause and Pause commands now work?

As discussed I'm not very eager to implement multi-thread APIs unless they really solve a problem that can't be solved otherwise. And I think a debugger Pause detected via a debug transport peek should work reasonably well for the original issue.

**Comment by fatcerberus** [comment]
Yes, Pause commands now work to break into debugging even if the event pump is starved.  The main thing that bothered me is the rate limiting may delay the actual pause for many thousands of instructions (a lot can happen in 200ms :) but that's mostly theoretical: if you're trying to break out of a long-running loop then chances are the instruction pointer isn't moving very far. ;-)

**Comment by svaarala** [comment]
Right - and adding an API to signal a pause from another thread wouldn't actually improve responsiveness for that scenario because it would only be checked based on the interrupt counter. Forcibly writing the interrupt counter to another value (perhaps a couple of times) and hoping for an earlier interrupt might work often but not always (the outcome would depend on the architecture, compiler, etc).

Making the interrupt interval smaller would of course be possible, it may not be very critical when debugging. Also there's a two level structure now for the transport peek:
- Interrupt counter is used as the low level mechanism to break out and check if we need to peek.
- A time-based mechanism is used to rate limit the peek itself. This is mainly due to peek being expensive in some transports, so 200ms seemed like a good default compromise.

Adding the ability to control both the low level interrupt interval and the debugger transport peek interval wouldn't be difficult, at least if the controls were config options rather than API changes.

As an aside (and an old topic :), what I really don't like about C APIs is that extending them without changing function prototypes etc is painful. It would be nice if one had an easy way to pass e.g. a set of key/value arguments to the debugger attach call, and could then add/remove flags and parameters over time. The only convenient thing at hand would be to use a parameter object (an Ecmascript object) and pass that to the duk_debugger_attach() call for later extensions. That's not currently used in the C APIs (except for return values for e.g. inspection) but I hope to use that in the future to make APIs easier to evolve.

**Comment by fatcerberus** [comment]
> what I really don't like about C APIs is that extending them without changing function prototypes etc is painful.

Agree, I fully sympathize here.  A trick I've picked up over the years miniSphere development is, if I want to provide for future extensibility, design an API to be additive.  Like, my spriteset object has this:
https://github.com/fatcerberus/minisphere/blob/v4.7.1/src/minisphere/spriteset.h#L27-L29

One then does `spriteset_new()` and calls the `spriteset_add_xxx()` functions successively to build up a spriteset.  That particular setup works well for objects that can be constructed piecemeal like that, but the general methodology can be applied to other scenarios if you're clever enough.  In general, the idea is to use a struct with a set of associated methods vs. a loose collection of API calls.

Of course, as you point out, Duktape already has such a mechanism built into the design--Ecmascript objects.  It's just that right, now, it's clunky to populate such objects because of all the value stack balancing involved.  If one could do something like...

```c
duk_push_populated_object(ctx,
    "pig:%s, cow:%s, kittiesEaten:%d",
    "maggie", "Kittycow", 812);
```

...with an equivalent API for getting values out of an object, then I wouldn't mind working with them for Duktape API calls.

**Comment by svaarala** [comment]
Assuming one really wants a single constructor/attach/whatever call, the "new + set_x + set_y + set_z" model works for API stability but the downside is a lot of clutter in the calling code, additional footprint for multiplying function epilogues and prologues for each setter, etc. For me that's a big downside because I work a lot with memory restricted devices and footprint is a difficult battle as is :-)

**Comment by fatcerberus** [comment]
> So if the end result is taking a number of calls to achieve the work of an ideal single call, that is "API baggage" from my point of view.

I definitely agree - if you're footprint-starved, having a bunch of setters adds a lot of extra "weight" to the implementation--and calling code--for the sake of stability (and the importance of API stability is inversely proportional to how often you want to do semver-major releases).  For a project like miniSphere, that kind of thing is pretty much free and avoids the need to refactor constantly, which is a big win (even if I'm a refactoring fiend and do it all the time anyway ;-), but I realize not all projects have the luxury of targeting platforms where multiple gigabytes of RAM is common.

That said, to be fair Duktape already has something similar to the "new + set_x + set_y + set_z" model built into its API design (i.e. duk_push_object + duk_push_xxx + duk_set_prop_string); assuming it was common for Duktape C APIs to accept objects on the value stack, would you then consider that design, without the "ideal single call", to be API baggage?  Legitimately curious, not trying to pick a fight. :)

**Comment by svaarala** [comment]
It would IMO be less of a baggage because from a C point of view the object+property calls are shared and reused across multiple APIs. Something like duk_set_debugger_interval() would be a non-reused call and thus much more baggage.

Also one difference is that when arguments are passed via objects, such objects can be trivially be operated on from both C and Ecmascript code, and that handling is generic.

**Comment by svaarala** [comment]
Similarly, suppose there was a C API concept for C level string-key + string value option maps; if multiple API calls accepted extensible arguments via such a map, it would be an OK API design IMO because the same concept would be reused without duplication of setters. Some libraries use this design, or some variant where you may instead provide some "foo_set_property(string key, string value)" where you'd have a generic setter whose key space can be evolved.

But because there's already a key/value object, which also supports structured values, I think the API should build on that instead and effort should be made to make that as convenient as possible. One hallmark of a good API is that there are relatively few concepts, but they're fully developed and consistently applied.

I'll admit I might be too allergic to API baggage ;) but much of it comes from making mistakes earlier :D

**Comment by fatcerberus** [comment]
> Similarly, suppose there was a C API concept for C level string-key + string value option maps; if multiple API calls accepted extensible arguments via such a map, it would be an OK API design 

I probably didn't make it clear enough in my description above, but this is what I was actually getting at with my ideal design being "additive".  *Not* a bunch of set_this, set_that, etc.  Instead of setters, you have generic "adders".  It's a difficult concept to describe succinctly, but rest assured we are on the same page here. :)

**Comment by svaarala** [comment]
Ah, I see. If the API was something like:

```c
duk_set_property_int(ctx, "debuggerInterval", 123);
`''

that would be OK from a versioning perspective IMO, especially if the call return value indicated whether the property was supported or not. For better footprint, the key could be a define instead, so that the Duktape side could be just be an efficient switch-case.

But, given that there is a key/value representation (object) already in the API, I'd prefer making that more convenient and applying it across the APIs. This has a few upsides (like being atomic if necessary) and some downsides (more difficult to indicate which options were recognized). One upside is that the data type is compatible with script code, so that it's possibly to provide, say, debugger options as an Ecmascript object returned by script code.

**Comment by svaarala** [comment]
Unless there's some concrete change proposal, I think it should be closed.

**Comment by fatcerberus** [comment]
The only thing I can think of is to introduce some sort of "pause now" flag that would override the counter and enter interrupt processing on the next instruction dispatch.  That'd ensure it was atomic, but it would also add an additional check and almost certainly hurt performance.  Not worth it just to make this one call (which isn't even used often) thread safe.

So yeah, I'll close this.
