### ISSUE TITLE
Protected equivalent of `duk_get_prop` and `duk_put_prop` for accessors?

### ISSUE THREAD

**Issue by beevik** [svaarala/duktape#1705]
The duktape API has "protected" variants of `duk_call` and `duk_callmethod`, namely `duk_pcall` and `duk_pcallmethod`.  When an error is thrown within a call to `duk_pcall`, for example, it is "caught" and an error code is returned instead of propagating outside of duktape.

A similar issue can arise when "getting" or "putting" a property that has an accessor.  If an error is generated within the accessor function, it will not be caught and will instead propagate outside of  the call to `duk_put_prop` or `duk_get_prop`.  Is there some way to do something like `duk_pput_prop` or `duk_pget_prop` in cases like this?

Alternatively, is there some way to discover that a property has an accessor and call its accessor function directly with `duk_pcall` or `duk_pcall_method` instead of using `duk_put_prop` or `duk_get_prop`?

**Comment by fatcerberus** [comment]
As a general rule almost any Duktape API you call can throw an error out of your reach.  There's a general mechanism to catch them: `duk_safe_call()`.

The only reason there are dedicated protected variants of call, compile, etc. is because these are almost guaranteed to throw at some point so you always want to guard them.  `duk_safe_call()` is the general-purpose mechanism.

**Comment by beevik** [comment]
@fatcerberus How would you use `duk_safe_call` from C to call a property's set accessor function?

**Comment by svaarala** [comment]
@beevik You'd normally use duk_safe_call() to call a C function which then called duk_get_prop() which would invoke the possibly throwing getter.

**Comment by svaarala** [comment]
@beevik As some background, the reason there isn't a protected variant for property API calls is a conscious API design choice: almost any API call can throw in some situation; be it out of memory, and error thrown by some side effect (getter, setter, Proxy), execution timeout, etc. So adding protected variants for potentially throwing calls would mean almost doubling the API call count.

It's easier to provide a small set of protected calls, and then use unprotected calls within the call targets. The main protected calls either make an actual function/method call (duk_pcall() etc) or make a pure C call (duk_safe_call()) which can be used as a catching wrapper for all other API methods (internally duk_safe_call() is used almost exclusively to implement protected calls).

**Comment by beevik** [comment]
I see.  Thanks for the clarification.  This answers my question.

**Comment by fatcerberus** [comment]
@svaarala On a related note, I've always found the naming of `duk_safe_call()` confusing.  It does something totally different from `duk_call()` despite the similar naming.  Compare `duk_to_string()` vs. `duk_safe_to_string()` which do the same thing except one is guaranteed not to throw.

I remember being confused for a long time why `duk_safe_call()` needed a native callback as an argument, since `duk_call()` doesn't.  I think a better name would have been `duk_try()`, which is exactly the naming I used for this primitive in JSAL.

**Comment by svaarala** [comment]
I agree, and we actually discussed this a while back already: duk_safe_call() is named inconsistently compared to duk_safe_to_string(). duk_protected() would be more consistent and would match the abbreviated "p" in duk_pcall().

**Comment by svaarala** [comment]
Here's that previous discussion:https://github.com/svaarala/duktape/pull/922#issuecomment-241488596.

**Comment by svaarala** [comment]
I actually wrote some naming notes after that previous discussion, it also mentions the inconsistency: https://github.com/svaarala/duktape/blob/master/doc/api-design-guidelines.rst#api-calls.

The inconsistency should be fixed by adding a better named alias for duk_safe_call(), and then removing duk_safe_call() after a long transition period.
