### ISSUE TITLE
Compiling for Windows (x86 and/or x64)

### ISSUE THREAD

**Issue by vpontin** [svaarala/duktape#1716]
Hi!
Is there any tutorial or script to build a Windows shared library (dll) using TDM-GCC or Visual Studio?
I want to make a binding to pascal so i need the dll previously compiled.

All the makefiles are made for unix-like OS and i tried a lot of solutions from internet, but without avail.

Thanks in advance!

**Comment by denisdemaisbr** [comment]
@vpontin to build duktape is need only a pair of files
duktape.c duktape.h
each OS/compiller have a proper way to build static and shared files 
some build systems have some helpers (like cmake, ninja, ...)

some info:
https://msdn.microsoft.com/en-us/library/ms235636(VS.80).aspx
https://msdn.microsoft.com/en-us/library/2kzt1wy3(v=vs.80).aspx
http://www.zealfortechnology.com/2013/08/create-c-program-dynamic-link-library-dll-visual-studio-2012-implicit.html

**Comment by svaarala** [comment]
No tutorial as such - in general Duktape distributable doesn't contain "ready to use" Makefiles, build files, etc, because there are just too many environments and supporting them all would be painful.

But on the upside, there's almost nothing special about it compared to compiling your own code or any other code as a DLL. For Windows getting the declspec() stuff to come out right, you need the --dll option for configure.py:

```
> python2 tools\configure.py --dll --output-directory my-dll-src
```

and then just compile `my-dll-src\duktape.c` into a DLL as one would normally do for any other code.

**Comment by svaarala** [comment]
@vpontin This wiki page covers configuration basics, and includes the --dll option description: http://wiki.duktape.org/Configuring2x.html.
