### ISSUE TITLE
Unicode string problem

### ISSUE THREAD

**Issue by mike-lischke** [svaarala/duktape#1718]
In one of my unit tests I create a folder "Κάποιος κατάλογος" in a workdir. Then `cd` into that and read the current work dir. This suprisingly gives me:

>   x chdir (0 of 1 succeeded)
Failure: Expected 'output/process-specs/currentPath/Κάποιος κατάλογος' to be 'output/process-specs/currentPath/Κάποιος κατάλογος'.

When I print both strings char by char I can see why comparison fails. The string managed in JS is stored in non-combined form (NFD?) while the file system returns a composed string (probably NFC). This is relevant for the 2 `ά` letters. Removing them makes the test succeed.

Obviously I have to normalize the strings, however duktape doesn't seem to support that. When I call normalize() I get an error. What alternatives do I have?

**Comment by svaarala** [comment]
Unicode normalization is a relatively complex process and at present not supported by Duktape.

So at present you'd need to do the normalization in C code, using some Unicode library.

**Comment by mike-lischke** [comment]
Which form does duktape use for strings? Is it NFD?

**Comment by mike-lischke** [comment]
What about using [utf8proc](https://github.com/JuliaLang/utf8proc) in duktape?

**Comment by svaarala** [comment]
Duktape strings are arbitrary 16-bit codepoint sequences encoded in CESU-8 for the C API. Ecmascript doesn't provide or enforce any normalization, it is entirely up to Ecmascript code what kind of strings are created.

**Comment by mike-lischke** [comment]
The String prototype supports [normalization form conversion](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize) (ECMAScript 2015), so regardless of how the string is stored internally, you can at least normalize it to a form that you expect. Would be very helpful if duktape could at least settle on a specific normalization form, if it doesn't support the `normalize()` API.

**Comment by svaarala** [comment]
Re: utf8proc, it's probably a good library for the calling application to use on its own.

Using it as a default dependency for Duktape:
- It would need to be port to all targets Duktape supports, even the more exotic ones. I would need to check if this is the case.
- Duktape's Unicode support is very footprint optimized and currently takes just a few kB. Quickly testing, utf8proc is around 45-50 kB. Compared to the smallest ES5.1 subset builds, which are around 120-130kB, that's quite a lot.

However, it might be a good dependency to provide some Unicode normalization for some platforms before Duktape has its own, more footprint-optimized mechanism.

**Comment by svaarala** [comment]
> The String prototype supports normalization form conversion (ECMAScript 2015), so regardless of how the string is stored internally, you can at least normalize it to a form that you expect. Would be very helpful if duktape could at least settle on a specific normalization form, if it doesn't support the normalize() API.

Right, I was just saying that the internal representation is not consistently in some specific normalization form (you asked: "Which form does duktape use for strings? Is it NFD?").

Duktape doesn't implement the ES2015 normalize() binding yet.

**Comment by svaarala** [comment]
> Would be very helpful if duktape could at least settle on a specific normalization form, if it doesn't support the normalize() API.

But that's not possible without breaking Ecmascript compatibility. Ecmascript strings are literally (heh) arbitrary 16-bit codepoint sequences. Every possible codepoints sequence -- even invalid surrogate pairs -- must be allowed.

**Comment by mike-lischke** [comment]
Hmm, that leaves me in an uncomfortable situation. While I can certainly normalize the return value of my duktape/C implementation for `cwd()`, I have no influence how the string is stored in JS and hence cannot compare them (without another roundtrip to my C++ layer).

But I'll find another solution. Thanks for your excellent support Sami.

**Comment by svaarala** [comment]
> Hmm, that leaves me in an uncomfortable situation. While I can certainly normalize the return value of my duktape/C implementation for cwd(), I have no influence how the string is stored in JS and hence cannot compare them (without another roundtrip to my C++ layer).

I know, working with strings can be a bit painful at times. There are multiple constraints for Duktape and all can't be achieved at the same time:
- Ecmascript strings must be arbitrary 16-bit codepoints, at least Ecmascript code must have that illusion.
- Duktape currently uses CESU-8 (+ UTF-8 with extensions) to deal with Ecmascript strings while simultaneously allowing C code to use UTF-8 strings. This could be replaced e.g. with WTF-8 where surrogates are automatically combined internally (but still allowing invalid surrogates), but Ecmascript code sees the same illusion as before. C code would then mostly see valid UTF-8 strings (not CESU-8).
- Some C code wants ASCII strings and codepages. Some want UTF-8. Some want CESU-8, UTF-16, or `wchar_t` and must specifically be able to represent even invalid surrogate pairs because e.g. an underlying file system or database allows them so they must be representable. *Someone* will need to convert.
- Unicode normalization is one further pain factor: Ecmascript doesn't allow normalization on-the-fly (which might be nice) so an explicit normalization step is needed in any case, via String.prototype.normalize() or some C API `duk_normalize_string(ctx, -1, DUK_UNICODE_NFC);`.
- Unicode tables are large, even compact libraries are often tens of kilobytes which is way too much for low memory targets. The current Unicode, slow as it is, has the merit of being quite small (a few kB). Normalization is not supported and that's actually a bit of a challenge to implement for low memory targets.

So it's a rather complicated design issue. I agree with the sentiment that it should be convenient for the application, so maybe the API eventually needs to support more normalization and conversion functions, maybe limited to various forms of UTF-8 and UTF-16 (and hopefully not arbitrary code pages etc :).

**Comment by mike-lischke** [comment]
I find it a bit amusing to call a 40KB footprint for Unicode tables "big", but I understand the requirements for low mem footprint targets. Though it should be easy to disable `String.prototype.normalize()`/`duk_normalize_string()` with a compile switch and leave out the normalization impl, where mem foot print is important.

I haven't understood the need for support of invalid Unicode codepoints (e.g. half surrogate pairs), however. Even if there can be sources that return invalid Unicode doesn't mean duktape has to accept that. You can't do anything useful with that invalid text anyway.

**Comment by svaarala** [comment]
40kB is big if it represents 25-30% of the footprint :)

**Comment by svaarala** [comment]
> Though it should be easy to disable String.prototype.normalize()/duk_normalize_string() with a compile switch and leave out the normalization impl, where mem foot print is important.

Agree there - Duktape is already in effect supporting two major target configurations:
- Default config with post-ES5.1 features, tracebacks, verbose errors, fast paths enabled, etc.
- Lowmem with ES5.1 subset, tracebacks disabled, minimal errors, favor footprint over speed, etc.

Dropping Unicode normalization from the lowmem target would be relatively straightforward. But that still leaves two issues:
- Portability of any dependent libraries: what if someone wants the Unicode support for a non-lowmem target but the dependent library doesn't port? Awkward answer is to fragment the feature set across targets.
- What to do with lowmem targets that *do* need Unicode normalization?

**Comment by mike-lischke** [comment]
* portability: that remains to be checked. Looks like utf8proc (as example) supports all relevant targets. It's self contained.
* lowmem targets: the same question exists for tracebacks, verbose errors, fast paths etc, no? If low mem footprint is required then you cannot have advanced features. As easy as that :-)

**Comment by svaarala** [comment]
> portability: that remains to be checked. Looks like utf8proc (as example) supports all relevant targets. It's self contained.

Your "relevant" might not match mine. For me e.g. MS-DOS is relevant because Duktape is used in those environments, sometimes with ancient compilers.

> lowmem targets: the same question exists for tracebacks, verbose errors, fast paths etc, no? If low mem footprint is required then you cannot have advanced features. As easy as that :-)

Like I already said: "What to do with lowmem targets that do need Unicode normalization?".

What you can do now is take the lowmem baseline and then enable features you want to pay for in footprint. For example, you *can* enable tracebacks if you really want them and then you pay some footprint cost. Similarly, some environments may specivically need Unicode normalization and should be able to enable it on top of the lowmem baseilne.

So, no, not as easy as disabling it for lowmem. :)

**Comment by mike-lischke** [comment]
MS-DOS: damn, you are kidding me :-)

**Comment by fatcerberus** [comment]
> I haven't understood the need for support of invalid Unicode codepoints (e.g. half surrogate pairs), however. Even if there can be sources that return invalid Unicode doesn't mean duktape has to accept that. You can't do anything useful with that invalid text anyway.

Ecmascript compliance requires this to be supported, a string in JS is not really UTF-16 but just a dumb string of 16-bit chars.  That's why `.length` of a supplemental char is 2 instead of 1 and indexing such a string using array indices will yield the individual surrogate halves.

Also, Windows file system is nominally UTF-16 but in reality treats filenames the same way Ecmascript treats strings, I.e. as a raw array of 16-bit chars.  Unpaired surrogates are allowed, etc.  This is why it's possible to end up with "invalid" Unicode filenames that are then inaccessible to any program that does full normalization of all strings.

Re: footprint, besides MS-DOS, Duktape supports (and is used on in the wild!) platforms with literally only *kilobytes* of ROM and RAM, such as IoT devices.  On such a platform, 50kB is absolutely **ginormous**.

**Comment by mike-lischke** [comment]
Surrogates should be banned anyway.

**Comment by fatcerberus** [comment]
I agree, but JS is stuck with a bunch of legacy baggage to avoid "breaking the web".  It sucks, but it is what it is. :)

That said, JS as a language is slowly getting better support for Unicode proper as time goes on.  Unicode character escapes, `/u` mode for regexps, `String.fromCodePoint()`, etc.

**Comment by svaarala** [comment]
> MS-DOS: damn, you are kidding me :-)

I'm not, it's still used in e.g. some industrial applications :)

**Comment by svaarala** [comment]
@mike-lischke I'd be excited if Ecmascript just moved to "pure" Unicode with the full UTF-8 range and no surrogate pairs anywhere. Duktape internals would be actually read for that change directly, because UTF-8 strings can already be used (but they must be created from C code and cannot be created as Ecmascript literals).

Things would just be much more simpler that way. Even with the ES2015+ non-BMP support things work a bit oddly, assuming that `x = "\u{12345}"`:
- x.length is 2 (not 1).
- x[0] and x[1] are surrogates.
- x.charCodeAt(0) and x.charCodeAt(1) are surrogates.
- x.codePointAt(0) will be 0x12345 -- but x.codePointAt(1) will **still** be a surrogate!

If you create U+12345 as a UTF-8 string from the Duktape C API (or as String.fromCharCode(0x12345)):
- x.length = 1
- x[0] = 0x12345
- x.charCodeAt(0) and x.codePointAt(0) are both 0x12345

This is much cleaner. But, non-compliant.

**Comment by svaarala** [comment]
> Surrogates should be banned anyway. They are just a vehicle to get around 16bit limitations. UTF-8 to the rescue!

Unfortunately if I removed surrogate support from Duktape a bunch of applications would break and there would be a lot of bug reports of non-compliance. It's not only theoretical: some applications use Ecmascript strings as 16-bit integer lookup tables for example!

So, I agree with your sentiment very much and it's precisely I wanted Duktape internals to be UTF-8 ready. It's also supported to work with UTF-8 strings from C code; Ecmascript code mostly works with them as one would expect with a few limitations. (This is actually the way I use Duktape in a few cases.)

But Ecmascript compliance just doesn't allow banning surrogates or using standard UTF-8 in the internal representation; one must use CESU-8, WTF-8 or something that supports arbitrary codepoint sequences (including broken surrogates). I don't defend this position because it's great and desirable, but because it's practical :)

**Comment by mike-lischke** [comment]
Hmm, ok, trying to add a `normalize()` function to the String type now:

```
  duk_get_global_string(ctx, "String");
  duk_get_prop_string(ctx, -1, "prototype");
  JSExport::registerFunction(ctx, Utils::normalize, "normalize", "normalize", 1);
  duk_pop_2(ctx);
```

then later I want to get the string value and replace it:

```
duk_ret_t Utils::normalize(duk_context *ctx) {
  // stack: [ ... format ]
  static std::map<std::string, NormalizationForm> formMap = {
    { "NFC", NormalizationForm::NFC },
    { "NFD", NormalizationForm::NFC },
    { "NFKC", NormalizationForm::NFC },
    { "NFKD", NormalizationForm::NFC },
  };

... get value of the string

  std::string formText = duk_require_string(ctx, -1);
  auto iterator = formMap.find(formText);
  if (iterator == formMap.end())
    throwDukError(ctx, DUK_ERR_RANGE_ERROR, "Invalid normalization form specified");

  std::string result = normalize(text, iterator->second);

... write back the result to the string

  return 1;
}
```

Can you help me with filling the 2 holes please?

**Comment by fatcerberus** [comment]
You already seem to have the "get value" part (`duk_require_string`), the "write back" should just be
```c
duk_push_string(ctx, result.c_str());
```

**Comment by svaarala** [comment]
You would use duk_get_lstring() or duk_require_lstring() to get a byte pointer and length for the string.

It will be represented in https://en.wikipedia.org/wiki/CESU-8.

You would then take the normalized string, encode it back into CESU-8 (if the format was changed for normalization) and then duk_push_lstring() the CESU-8 encoded form.

**Comment by svaarala** [comment]
@fatcerberus I thought formText was actually the format specifier, "NFC", "NFD", etc, and not the actual input string.

@mike-lischke xxx.normalize('NFC') would get the string value as the "this" binding so you'd do something like:

```c
duk_push_this(ctx);
bytes = duk_require_lstring(ctx, -1, &len);
```

and bytes would then contain CESU-8 data, 'len' bytes worth.

**Comment by mike-lischke** [comment]
Yes, just found out of the `duk_push_this()` function. And how can I write back the string (normalize operates in-place)?

**Comment by fatcerberus** [comment]
Strings in JS are immutable, so you wouldn't be able to modify the string pointed to by `this`.  You would have to make a copy (don't mutate the string returned from `duk_require_[l]string()`!) and operate on that, then return it from your `.normalize()` function.

**Comment by mike-lischke** [comment]
Hmm, but the docs say it's in-place, so somehow the string is replaced. How to do that in duktape?

**Comment by fatcerberus** [comment]
MDN says it returns the normalized string, it's not done in-place:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize

Not sure what ECMAScript says, although I highly doubt it specifies mutating the string.

**Comment by fatcerberus** [comment]
http://www.ecma-international.org/ecma-262/6.0/#sec-string.prototype.normalize

So yeah, not in-place.

**Comment by mike-lischke** [comment]
Oh, yes, you are right. I misinterpreted the sample code which never assigned the result of `normalize()` to anything. OK, then only one thing remains, returning a new string. I tried this:

```cpp
  duk_get_global_string(ctx, "String");
  duk_push_string(ctx, result.c_str());
  duk_new(ctx, 1);
```
However, that seems to return a string that is not the same as normal strings. The duktape debug output shows a normal object. What's the correct approach here?

**Comment by mike-lischke** [comment]
OK, thanks, normalization now works in my code. Thank you both for your quick help.

**Comment by svaarala** [comment]
Cool, out of interest, could you share the final normalization function? :)

**Comment by mike-lischke** [comment]
Oh, sure:

```cpp
duk_ret_t Utils::normalize(duk_context *ctx) {
  // stack: [ ... format ]

  static std::map<std::string, NormalizationForm> formMap = {
    { "NFC", NormalizationForm::NFC },
    { "NFD", NormalizationForm::NFD },
    { "NFKC", NormalizationForm::NFKC },
    { "NFKD", NormalizationForm::NFKD },
  };

  std::string form = duk_require_string(ctx, -1);
  auto iterator = formMap.find(form);
  if (iterator == formMap.end())
    throwDukError(ctx, DUK_ERR_RANGE_ERROR, "Invalid normalization form specified");

  duk_push_this(ctx);
  std::string text = duk_get_string(ctx, -1);
  duk_pop(ctx);

  std::string result = normalize(text, iterator->second);
  duk_push_string(ctx, result.c_str());

  return 1;
}
```

as simple as that. And the actual normalization is simply:

```cpp
std::string Utils::normalize(std::string const& text, NormalizationForm form) {
  utf8proc_uint8_t *value;
  switch (form) {
    case NormalizationForm::NFC:
      value = utf8proc_NFC(reinterpret_cast<const uint8_t *>(text.c_str()));
      break;

    case NormalizationForm::NFD:
      value = utf8proc_NFD(reinterpret_cast<const uint8_t *>(text.c_str()));
      break;

    case NormalizationForm::NFKC:
      value = utf8proc_NFKC(reinterpret_cast<const uint8_t *>(text.c_str()));
      break;

    case NormalizationForm::NFKD:
      value = utf8proc_NFKD(reinterpret_cast<const uint8_t *>(text.c_str()));
      break;

    default:
      return text;
  }

  std::string result(reinterpret_cast<std::string::value_type *>(value));
  free(value);

  return result;
}
```

**Comment by svaarala** [comment]
You should remove the pop from this:

```c
  duk_push_this(ctx);
  std::string text = duk_get_string(ctx, -1);
  duk_pop(ctx);
```

While this probably won't cause problems, your code is not holding a reference to the string so `text` is potentially a dangling reference. In practice the `this` binding will hold a reference but just as a general coding guideline holding a string pointer beyond locally guaranteed reachability is a bit dubious.

You don't need to duk_pop() at all: when the function returns, the value stack is automatically cleaned up and the topmost value is used as the return value.

**Comment by fatcerberus** [comment]
> You don't need to duk_pop() at all: when the function returns, the value stack is automatically cleaned up and the topmost value is used as the return value.

As an amusing aside, it took me forever to realize this.  Many of my original miniSphere APIs do tons of unnecessary pops to balance the stack in Duktape/C functions.  I felt very stupid later when I realized Duktape would clean up the mess for me. :)

**Comment by mike-lischke** [comment]
Thanks for the hint. However, I prefer to leave my place as I found it when I entered :-) Call me stupid...

About the string: the assignment to `text` creates a copy from the `char*` returned by `duk_get_string`. So where do you see a danger here?

**Comment by svaarala** [comment]
> About the string: the assignment to text creates a copy from the char* returned by duk_get_string.

Oops, I guess you're right. I'm a bit C++ illiterate ;) Carry on.

**Comment by svaarala** [comment]
> Thanks for the hint. However, I prefer to leave my place as I found it when I entered :-) Call me stupid...

That's fine and very useful for helpers and such. But just in case you get lazy over time, it's quite OK to:

```c
duk_ret_t my_adder(duk_context *ctx) {
    duk_push_number(ctx, duk_to_number(ctx, 0) + duk_to_number(ctx, 1));
    return 1;
}
```

It's also a common idiom for Lua code. Not mandatory in any sense, so it's fine to balance the stack too.

**Comment by svaarala** [comment]
@mike-lischke One more note: when you use duk_get_string() instead of duk_get_lstring() you won't know the length of the string. This won't work correctly with strings containing embedded NULs like `"foo\u0000bar"` which are valid in Ecmascript. So that would most likely normalize() to `"foo"`.

**Comment by mike-lischke** [comment]
Hmm, why is there `duk_get_string()` at all? It shouldn't be used then. But again, thanks for the hint.

**Comment by svaarala** [comment]
Most C programs deal with strings only based on a pointer and don't support strings with internal NULs. It may not always be up to the program either: most C libraries don't deal with strings containing internal NULs.

So, duk_get_string() exists because it's more convenient than duk_get_lstring() and declaring+ignoring the length field.

**Comment by mpietras** [comment]
I'm hopeful after all these years that someone sees this, and hopefully this is simple and I'm missing something basic, but... I have a UTF-8 string "I’m happy to help" where that single-quote is the 3-octet code `e2 80 99`.  From my understanding, CESU-8 only does 4/6-octet conversion and that 3-octet code is encoded the same in UTF-8 and CESU-8, yet duktape throws `cannot string coerce Symbol` when I `duk_push_lstring` that into a context and operate on it.  So, how am I supposed to encode that 3-octet sequence to not look like an internal symbol?
