### ISSUE TITLE
How to make it run faster?

### ISSUE THREAD

**Issue by hsany330** [svaarala/duktape#173]
Can i make it faster for simple js code?
i use duktape for my iOS app。i got a problem ,when i use it for tablew view .  i have to excute js for every cell . The process cost 15 ms  in iPhone 4s.   how to make it in 10ms?

my js code is very simple. i just use it to assign value . without regexp ，without for ,without while.
my js code like this:
  document.onreload = function (data) {
      cellInfoTitle.innerText = data.title;
      cellInfoEvaluateScore.style.width = data.evaluate*6.6 ;
      cellInfoFee.innerText = data.fee;
      cellInfoOther.innerText = data.other;
      cellImage.src = data.image;
      if (!data.corner) {
        cellCornerStamp.style.display = 'none';
      } else {
        cellCornerStamp.style.display = 'block';
      }
  }

**Comment by svaarala** [comment]
Where does the time target come from? If it's from screen redrawing or similar, could you consider refreshing cells so that you refresh a certain number per 10ms interval?

I'm not sure how to speed up the example code you provided, but Duktape call handling performance is being worked on in Duktape 1.3 so that should help your case too.

**Comment by hsany330** [comment]
can i send u my data ? i get it from instruments .  Instruments is a great tool  , it made by Apple

**Comment by svaarala** [comment]
@hsany330 Sure, you can send it to me: sami.vaarala@iki.fi
