### ISSUE TITLE
Add an API to determine if something is an object

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#1731]
Right now we only have `duk_is_object_coercible()`.  If a value is object-coercible but not actually an object, then calling functions such as `duk_get_prop()` will result in a usually pointless coercion that could maybe be avoided if the value is known ahead of time to be primitive.

I propose a new API, `duk_is_object()`, for this purpose.

**Comment by svaarala** [comment]
That actually already exists: http://duktape.org/api.html#duk_is_object.

**Comment by svaarala** [comment]
Also note that if the value is primitive, there won't in most cases be an actual coercion. For example, if the value is a boolean, there are no "own properties" for such a value and the lookup just proceeds directly to Boolean.prototype without creating an object version of the argument.

**Comment by fatcerberus** [comment]
Huh... when was that added?  My entire codebase only ever checks for object coercible, and I remember not finding duk_is_object in intellisense when I looked for it...

**Comment by svaarala** [comment]
It's been in the API since 1.0.0. :)

**Comment by fatcerberus** [comment]
Huh... weird that I never found it then.  Oh well, I’ll close this then :)

**Comment by fatcerberus** [comment]
Wait, no, I remember what it was, there doesn’t seem to be a `duk_require_object()` currently.

**Comment by svaarala** [comment]
That's true, there's no duk_require_object(). That could be added to the API for completeness.

The unnecessary object coercion mentioned in the description is generally not a relevant issue. In concrete terms, a duk_get_prop() for a boolean for example will go to:
- https://github.com/svaarala/duktape/blob/master/src-input/duk_hobject_props.c#L2390-L2394

The lookup will then continue directly from Boolean.prototype without any object being created. Same goes for writing properties: they are handled "as if" an object was created, a property was set, and the object was then discarded. But the object is not actually created because it's not externally visible.

**Comment by fatcerberus** [comment]
I remember there were a few cases where I wanted to reject non-objects early because primitives were nonsensical in a given context.  Array parameters or option tables, for example.

**Comment by svaarala** [comment]
Right, duk_require_object() would be the right API call for that situation. The call is clearly missing from the API from a consistency point of view because e.g. duk_is_undefined() exists.

The API is a bit assymetric for duk_get_xxx(), but that is on purpose: for duk_get_xxx() where the C return code doesn't make sense, the API call would be a no-op because it involves no coercion. So duk_get_undefined() would return void and do nothing useful, and thus doesn't exist.
