### ISSUE TITLE
Debugger StepOver doesn't pause after stepping over a tail call

### ISSUE THREAD

**Issue by beevik** [svaarala/duktape#1786]
In duktape version 2.2.0, the duktape debugger doesn't pause after stepping *over* a call to a function that does a tail call.

See the comment in the code below:
```javascript
var Test = (function () {
    function Test() {
        return this;
    }
    Test.prototype.Foo = function Foo() {
        return 1;
    };
    Test.prototype.TailCall = function ReturnInline() {
        return this.Foo();
    };
    Test.prototype.OnUpdate = function OnUpdate() {
        this.TailCall();    // line A: debugger doesn't pause after stepping over this.
        var extraCode = 1;  // line B:
        ++extraCode;
    };
    return Test;
}());
```

Stepping into the call on line A works fine.  Setting a breakpoint on line B also causes the debugger to pause after stepping over line A.  But if no breakpoint is set on line B, the debugger does not pause on line B when stepping over line A.

Perhaps this issue is related to the following release note:

>Fix incorrect pausing by debugger StepOut, StepOver, and StepInto commands when stepping out/over/into a tail call (https://github.com/svaarala/duktape/issues/1684, https://github.com/svaarala/duktape/issues/1685, https://github.com/svaarala/duktape/issues/1726, https://github.com/svaarala/duktape/issues/1734)

**Comment by svaarala** [comment]
Thanks, I'll see if I can reproduce and ensure it's a tailcall related issue. That's quite likely because tailcalls and pause behavior is surprisingly complicated (not conceptually but in the details it involves).

**Comment by svaarala** [comment]
I have a hunch that the culprit is this:

```c
        thr->heap->dbg_pause_flags &= ~DUK_PAUSE_FLAG_LINE_CHANGE;
```

This is done when the tailcall is executed; line-based pausing is no longer relevant in the current function if a tailcall is executed in the function one is currently running. However, when the tailcall is embedded in a stepped over call, the flag can still be cleared, but should be restored upon return.

**Comment by svaarala** [comment]
Also if pause flag restoring is added into call handling generally, the line change pause trigger can just be cleared for every call (not just tailcalls) instead of relying on the activation pointers being different for nested calls (as is currently done; and this should be valid because the original activation still exists for non-tailcalls).

**Comment by svaarala** [comment]
Hmm. Thinking more about this it might be a bit difficult to just restore flags for the activations: if the pause condition is met (e.g. StepInto) and we resume again with potentially new flags, existing activations will have pause flag snapshots (now out of date) that one would then try to restore and would thus need to edit.

The root cause of the awkwardness is that the "pause if line changed" and some other pause flags are relatively to the activation where resume happens. This is tracked by storing a borrowed reference to the activation in the heap state and then comparing against it. This then becomes a problem for tailcalls where the activation is reused and its pointer remains the same, and the "pause if line changed" clearing is done to avoid this issue.

But maybe it'd be just cleaner to keep a borrowed reference to the activation *and* flag the activation itself explicitly as being the resume starting point. For tailcalls, that flag on the *activation* would be cleared (and the pause flags don't need to be edited, stored, or restored).

This doesn't work fully as such because we still need to detect when we step out of the starting point function; for tailcalls this means we pause when we exit the tailcall target but don't want to pause on line changes any more. So probably two flags are needed on the activation: one flag to indicate it is treated as a starting point for "step out" and another to indicate it is active for "line changed" tracking. On tailcalls the latter is cleared, but the former is not.

I don't have time right to work on this more but I'll try to fix this in the next few days. Thanks for the bug report and the repro!
