### ISSUE TITLE
Make `tools/configure.py` work with Python 3.x

### ISSUE THREAD

**Issue by ghost** [svaarala/duktape#1794]
Currently `tools/configure.py` fails with an error when run with Python 3. It makes things complicated when your build system already uses other scripts done in Python 3. In the perfect scenario both flavors, Py2 and Py3, would be supported.

**Comment by svaarala** [comment]
I tried doing that conversion a while back - it's really painful for the same Python source to work in both environments.

**Comment by svaarala** [comment]
One option I've considered is moving away entirely from Python because of the Python2/Python3 rift (which is awkward for everyone involved). A logical candidate would be Node.js which is also well supported on major platforms. Another approach would be to be self-hosting, i.e. compile a command line tool with the necessary file I/O bindings for doing the configuration step. But no actions on this so far.

**Comment by fatcerberus** [comment]
Node.js is nice but seems like a very heavy dependency, even heavier than Python.  I rather like the idea of self-hosting, personally.  I imagine that would be a very large undertaking, though.

**Comment by fatcerberus** [comment]
Hmm... Is there any benefit nowadays to retaining Python 2 support at all?  I feel like we could upgrade the build tools to Python 3-only and it wouldn't be an issue, as long as there's a way to ensure you run the correct one on systems with both installed.

**Comment by svaarala** [comment]
Other than breaking existing builds I think Python 3 only might be a viable option today. So that change could be made for Duktape 3.x, but I wouldn't want to make it for Duktape 2.x because existing builds would quite likely break.

Self-hosting wouldn't be a large undertaking as far as the build script functionality is concerned. The main concern would be a build dependency to maybe a different Duktape version to run the configuration tooling. It'd be easy if there was a pre-packaged command line binary for major platforms, but lacking that it seems awkward to use (and document in an understandable fashion). So if this approach was taken, it'd be good to release a pre-packaged binary tool for the most common platforms.

**Comment by fatcerberus** [comment]
For what it’s worth I just found out Python 2 won’t be maintained at all after 2020, so that’s probably a good reason to migrate sooner rather than later.

**Comment by svaarala** [comment]
That might pose a risk for availability but for the tooling itself it's not critical that the implementation is maintained (e.g. for security issues), because it's so far removed from actual execution. But certainly availability will eventually become worse closer to 2020. But even so, I don't think it's an immediate concern for at least a few years.

**Comment by svaarala** [comment]
Given a 1-2 year migration window, I think I'll probably start by looking at non-Python alternatives first. After all, maybe there's a hard python3-to-python4 transition down the road and I don't want to go through that again ;)

**Comment by svaarala** [comment]
If the tooling remains Python then one approach is to look at the automatic 2-to-3 conversions. The result may require a small fixup, and it might be feasible to maintain support for both for some time with that approach, then eventually switch to Python 3 only.

**Comment by fatcerberus** [comment]
> After all, maybe there's a hard python3-to-python4 transition down the road and I don't want to go through that again ;)

Yeah...

That’s what’s really nice about the Ecmascript process, backwards compatibility is maintained so a lot of code that was written even 2 decades ago still runs without modification in a modern JS engine.  Sometimes we lose out on new features (like `global`) because of it, but the backward compatibility is really nice.  No Python-like fragmentation. :)

**Comment by TheBrokenRail** [comment]
> Being the last of the 2.x series, 2.7 will have an extended period of maintenance. Specifically, 2.7 will receive bugfix support until January 1, 2020. **After the last release, 2.7 will receive no support.**
> https://www.python.org/dev/peps/pep-0373/#maintenance-releases

Any updates on updating to Python 3 or moving way from Python?

**Comment by svaarala** [comment]
No updates at present. The dependency on python2 is not very problematic in my opinion; python2 is needed to create sources and headers for a custom configuration (not for compilation itself) and as such is easy to e.g. dockerize. But eventually some solution will be needed.

**Comment by svaarala** [comment]
I've been giving this a little thought and if going with a non-Python approach this approach might be nice:

Rewrite the tooling and other utility stuff into Javascript modules. Use pure Javascript YAML and XML libraries (which exist and seem to work well), so that native dependencies are minimized. In effect one would only rely on:
- The ability to parse command line arguments
- Minimal file I/O primitives, e.g. listDir(), readFile(), and writeFile()

This tooling could be run directly with Node.js which is available for major platforms, and is fast which is nice for Unicode processing and such. But because the native binding assumptions are minimal, it would also be easy to run it with Duktape or any other ES5.1 engine (transpiled if necessary) so that the tooling could also be made available on (almost) all targets where Duktape itself runs (which currently isn't possible).

I've experimented a bit with this and it seems straightforward. The pure JS bindings I've used so far are js-yaml and from-xml which seem to fit the purpose well.

**Comment by Ozaq** [comment]
@svaarala I am currently in the situation that I am maintaining a build environment that only depends on python2 for duktape, I very much would like to move away from that. Would you be open for a PR that ports to python3? I do not want to get started on anything if you have set you mind on moving to JS. 

Oh and btw duktape is cool stuff ;)

**Comment by svaarala** [comment]
I think moving to JS makes most sense, and I actually already have most of the tooling already rewritten in JS. It's waiting to be merged when I get a chance to work on it for a few days :)

The JS tooling works on Node.js but also on Duktape itself (not just in theory but in practice too :), making it possible to run the tooling on any target supporting Duktape. To run the tooling on Duktape one needs to bootstrap Duktape with a few additional native bindings (like a wrapper for system(), access to command line arguments, etc).

**Comment by strega-nil** [comment]
I'm also interested in this, since vcpkg only requires python2, I believe, for this exact library 😛

**Comment by Ozaq** [comment]
@svaarala alright, thanks for the update. Much appreciated.

**Comment by ethindp** [comment]
Any update on this? I just tried creating a custom config for Duktape and I can't because I use Python 3.9 only. Tried updating it and ran into a ton of tracebacks.

**Comment by svaarala** [comment]
The JS tooling is in master but it's not yet used by default Makefiles etc. But you can use it as follows:
```
$ make build/duktool.js
[...]
$ nodejs build/duktool.js configure --help
```

Later I'll merge a change that changes configure.py into a compatible wrapper that invokes the JS code (with a deprecation warning).

**Comment by jberryman** [comment]
Oh neat I didn't notice the js implementation until reading through the thread and will try it out, thanks for doing that!

Fwiw debian testing no longer ships anything except the python2 interpreter itself, so it feels truly like the late twilight of that language...

**Comment by saghul** [comment]
Was the script migrated to Python 3 or JS?

**Comment by svaarala** [comment]
It's Node.js based now, in https://github.com/svaarala/duktape/tree/master/src-tools. It will eventually be self-hostable with Duktape too.

**Comment by janisozaur** [comment]
Is node-based tool the preferred way now? On 2.7.0 already? https://wiki.duktape.org/configuring2x still lists python util only.
