### ISSUE TITLE
Catdogs, builtin classes with operator overloading

### ISSUE THREAD

**Issue by kungfooman** [svaarala/duktape#1831]
Hey all,

is it possible to define "native" builtin custom classes like `cat = new Cat();` and `dog = new Dog();` and add custom operators between them? E.g. `cat + dog` will then return an instance of the internal custom type `Catdog`.

I used Duktape quite some time for some game programming, but I always end up giving up on JavaScript for not supporting Operator Overloading. I wonder if builtin classes would allow to circumvent that limitation for special classes.

This would add a lot of value for me, since as a game developer I just don't wanna miss this.

I don't need `Catdogs`, but stuff like `Vector2`, `Vector3`, `Vector4`, `Matrix4x4`, `Quaternion` etc. with all the operators between them.

If this is possible, maybe somebody could make a tutorial like "How to add builtin types with custom operator overloading"? Would be epic. `*g*`

**Comment by kungfooman** [comment]
I have found a JS library now, which makes this obsolete. Library is called JSShaper and this demo basically shows everything off: http://restrictmode.org/try/

It's converting `a + b`, `a += b` etc. on the fly to e.g. `__add(a, b)` and `a = __add(a, b)`

Way better than hacking some custom types directly into the engine.

**Comment by svaarala** [comment]
Sorry for the delay, I've been busy with other pressing stuff. There's been discussion from time to time about overloading because it's useful in some application domains.

The main pro of adding support for overloading would be that normal operations (like 1+2) would suffer no penalty (unlike in rewriting approaches); the overloading check would only affect cases where either argument is an object.

The main con is that it's a non-standard extension. These are not as such forbidden by Ecmascript, however, as additional syntax and behaviors can be added as long as it doesn't interfere with the standard behavior. The ideal case would be that ES would gain some overloading capability and Duktape could then implement all or parts of that. Lacking that, the mechanism would be Duktape specific which people (understandably) have mixed feelings about.

I actually prototyped overloading quickly for arithmetic operations. It's not a difficult change to the engine as such because the code path where arithmetic arguments need object-to-primitive coercion are quite well defined and usually not in the hot path because most code doing arithmetic deals with primitive values.
