### ISSUE TITLE
Best practice for building from source

### ISSUE THREAD

**Issue by wenq1** [svaarala/duktape#1835]
According to the doc, python util/dist.py is used to combine source codes into duktape.c. Is it true that each time source code is changed, dist.py needs to be re-run?

**Comment by svaarala** [comment]
Also responded to this in an unrelated pull request, but for completeness:

The sources in src-input/ are not fully compilable as is: some of the source code is autogenerated based on built-in object and string definitions (strings.yaml, builtins.yaml) and Unicode data files. Autogeneration is necessary for bit-packed Unicode tables, and some use cases call for stripping Unicode data files for smaller footprint. Built-ins also require source generation to support "ROM built-ins" where the built-in objects are compiled into the flash footprint so that they don't consume any RAM at startup.

You don't need to run dist.py for compilation though; it's enough to run tools/configure.py, which can be done both from the repo clone and from an end-user distributable. Configure.py will perform the code generation needed. There's marginal difference between compiling from amalgamated vs. individual source files so that doesn't really matter; the majority of the configure.py time is in processing and bit-packing Unicode data files.

Sometimes an application build expects an end-user distributable as its input. In this case running dist.py is most convenient (if slower) because it will produce the expected input rather than just plain source files.

It would be relatively straightforward to make the amalgamation / configure process support incremental changes (for example, Unicode data files rarely change). But I don't think it's worth the effort personally.
