### ISSUE TITLE
How to implement "alert" properly

### ISSUE THREAD

**Issue by jcmerlin** [svaarala/duktape#1849]
I'm using duktape in a project and I need to implement "alert", a call that will show a native alertBox to the user with some custom buttons ("OK", "Cancel", etc.).

The problem is that this alert returns a value depending on the button that the user selected, and then the script should continue execution with that return value. For example:

var button = alert('Hello'); // Here the application shows an alert box.
if (button == 1) println('Selected OK');
else if (button == 2) println('Selected Cancel');

The logic inside "alert" is thus asynchronous (waiting for the user to select a button), and I assume duktape machine should wait before continuing executing the script.

Is this possible to do with duktape? Is there already a similar example? How could I do this?

Thanks,

**Comment by svaarala** [comment]
There are many variables affecting what's the best solution in your case.

But assuming it is OK that the alert() call blocks, you can simply let the alert() implementation:
- Signal a UI thread to show the alert dialog.
- Block until an UI thread posts the click result (mechanisms for this vary obviously).
- Push the value on the Duktape stack and return from alert().

The downside here is that Duktape will be blocked on alert() and nothing else can execute. Depending on your use case this may or may not be good enough.

If alert() should block but something else should be able to execute in the meanwhile, you can use duk_suspend() and duk_resume() inside the alert() implementation to allow something else to execute. This requires careful locking so that only at most one native thread executes Duktape API calls at any time.

**Comment by svaarala** [comment]
As a small addition: just in general, Duktape doesn't assume calls do not block. That's entirely up to the application, with the caveat that two threads may not enter Duktape at the same time; duk_suspend() + duk_resume() + locking allows one to multitask while waiting (and one can freely use multiple Duktape heaps even at the same time). There's nothing in Duktape itself that fails if the engine is blocked by an application function.

**Comment by svaarala** [comment]
@jcmerlin Did you manage to resolve the original issue?
