### ISSUE TITLE
Incremental mark-and-sweep

### ISSUE THREAD

**Issue by beevik** [svaarala/duktape#1872]
Apologies for asking here if this is not the correct place.

In your memory guidelines, you discuss the possibility of future work on an incremental mark-and-sweep algorithm for garbage collection.  Have you given this any further thought?  We're seeing significant pauses due to garbage collection in our applications and would probably benefit from something other than a stop-the-world GC.

**Comment by svaarala** [comment]
This is a good place to ask re: development directions etc :)

I've done a few incremental mark-and-sweep experiments - it's (naturally) feasible but not a trivial feature because it affects all pointer maintenance code, and adds some cost over refcounting. I'd personally prefer to have both refcounting and incremental mark-and-sweep, because the snappy memory behavior of refcounting is generally quite nice. But, there's no immediate work on implementing incremental mark-and-sweep at present.

At present, you can do the following:
- Ensure objects are refcounting friendly, i.e. don't contain loops. This is obviously not always possible.
- If memory is not a bottleneck resource and objects with loops are not created at a high rate, you can disable voluntary mark-and-sweep (it will still get triggered on allocation failures, as "emergency GC"). This is quite typical for e.g. games.

**Comment by beevik** [comment]
Thanks for the response.  I'm not surprised that adding an incremental or generation garbage collector is a lot of work.

Another question.  How does introducing ref-counting reduce the need to traverse objects during mark-and-sweep.  Does the mark-and-sweep avoid examining objects that can be garbage collected by ref-counting?

**Comment by fatcerberus** [comment]
With refcounting enabled, Duktape frees the object as soon as its refcount hits 0, so the mark-and-sweep algorithm never even sees it.  It goes a long way in reducing GC pauses, as you can imagine.

**Comment by fatcerberus** [comment]
Indeed.  Refcounting doesn’t preclude the need for mark-and-sweep, it just lightens the load by freeing things inline when they can be proven by refcounting alone to be unreachable.

Note that refcount collection can be cascading: if an object is freed by refzero, objects *it* references are decremented and may be freed at the same time.

**Comment by fatcerberus** [comment]
As an addendum to the above, practice the only time refcounting can’t prove an object to be unreachable once it goes out of scope is in the case of cycles (circular references).

**Comment by svaarala** [comment]
@beevik re:
> But any objects that haven't been garbage collected (by refcounting) by the time mark-and-sweep happens will need to be considered by the mark-and-sweep algorithm, correct? In other words, the mark-and-sweep algorithm needs to examine the reachability of all known objects, not merely a subset of them.

That's unfortunately correct: there's no easy to way to foresee which objects will need mark-and-sweep (i.e. will participate in a loop) and an object may enter a loop and exit a loop several times during its lifecycle. The only certain case is where a refcount drops to zero.

So my ideal GC mechanism would:
- Use refcounting for snappy memory behavior in most cases, with predictability as to when that happens (= loop free objects).
- Use incremental GC in the background to recover memory smoothly in the background, with the amount of work done on GC controllable by the application, e.g. more work could be done when lower on memory.
- Use a stop-the-world emergency GC when out of memory and out of other options. Internally this could be just an incremental GC executed for long enough, with no execution activity in-between.

Regarding your use case, is it feasible to disable `DUK_USE_VOLUNTARY_GC` and request manual GC in suitable locations (say when entering menus, etc)? This depends quite heavily on the application at hand: e.g. if a lot of function objects are created all the time it may not be feasible because (Ecmascript) function objects are unfortunately in a reference loop via their automatic `.prototype` object.

**Comment by fatcerberus** [comment]
@svaarala There was talk a while back about doing something to deal with the function prototype cycle issue... are there still plans for such an improvement?

**Comment by svaarala** [comment]
I'll probably try that before rewriting the GC at some point. It would make the function `.prototype` a virtual property that gets only actually created when accessed (often it's never accessed). But it wouldn't change the big picture, one would still have objects in loops for other reasons.

**Comment by svaarala** [comment]
Agreed, it would be nice, and it's a common request in very low memory targets. One reason is that with pool-based allocators one tries to always serve allocations from pools with as closely matching size as possible. The delay introduced by mark-and-sweep may mean that a larger-than-necessary pool size is used (meaning some memory is temporarily wasted) because some garbage has not yet been freed. There's another solution to this problem, though, and that is to allow the allocator to signal back "I can perform this allocation but it will be suboptimal" which would allow a mark-and-sweep to be performed (at least once in a while) before settling on a suboptimal allocation. Currently an allocation either succeeds or fails, which doesn't provide a way for the allocator signal back anything about memory pressure.

**Comment by beevik** [comment]
>Regarding your use case, is it feasible to disable DUK_USE_VOLUNTARY_GC and request manual GC in suitable locations (say when entering menus, etc)? This depends quite heavily on the application at hand: e.g. if a lot of function objects are created all the time it may not be feasible because (Ecmascript) function objects are unfortunately in a reference loop via their automatic .prototype object.

I'm not 100% sure yet, but I suspect our issue may be due at least in part to the sheer number of live objects we have at any one time.   As you state, the more objects there are to mark, the more time it takes to run the algorithm.  We can probably play tricks like hiding a manual GC during other expensive operations, but we're seeing GC hitches of as much as 200ms sometimes, which is really hard to hide in an application that needs to run at 30fps or higher.

We'll probably need to do more tracking to figure out how many function objects we are creating.  Is there any internal profiling data within duktape we can use to monitor the number of objects current in existence?

**Comment by svaarala** [comment]
The easiest way to see the number of objects and strings is to [enable debug prints](http://wiki.duktape.org/HowtoDebugPrints.html) and look for mark-and-sweep summaries at the end of mark-and-sweep, similar to:
```
D0 duk_heap_markandsweep.c:739 (duk__sweep_heap): mark-and-sweep sweep objects (non-string): 0 freed, 376 kept, 0 rescued, 0 queued for finalization
D0 duk_heap_markandsweep.c:576 (duk__sweep_stringtable): mark-and-sweep sweep stringtable: 0 freed, 424 kept
D0 duk_heap_markandsweep.c:1197 (duk_heap_mark_and_sweep): garbage collect (mark-and-sweep) finished: 376 objects kept, 424 strings kept, trigger reset to 39424
```

There's no public API to inspect the heap in more detail, but the debugger protocol provides access to the heap via https://github.com/svaarala/duktape/blob/master/doc/debugger.rst#dumpheap-request-0x20; the DumpHeap command streams out all objects and property tables in the heap which allows one to reconstruct the object graph. The debugger web UI example converts this data into a JSON representation of the object list.

Finally, you can walk the heap manually by peeking into the internals. `heap->heap_allocated` is a list of all non-string objects in existence, and strings are in the string table (whose state is also in `heap`).

**Comment by JoshMarler** [comment]
Apologies for reviving this. Is there any movement on this topic or new/current "best-practice" for avoiding GC/mark-and-sweep CPU spikes? 

I'm working on an application using https://github.com/nick-thompson/blueprint. Blueprint is a framework which implements a React JS renderer that renders down to components in the JUCE C++ framework. It's using Duktape as it's JS engine. 

My app is running on an embedded target and is reaching a reasonable level of complexity. We have React and a React state library in our application along with things like HTML Canvas graphics routines. Needless to say there are a fair number of objects and events flying around. Aiming for a refresh rate of 25hz approx. 

Performance on the whole is great! However I'm seeing the occasional lag in my UI due to CPU spikes from GC. Are there any updates on this topic or pearls of wisdom I might leverage? 

@beevik I appreciate this thread was kicked off a while ago but did you discover any gems you could share? 

Thanks

**Comment by JoshMarler** [comment]
@svaarala sorry for the bump but any chance on a quick confirm as to whether there is new advice for improving mark-and-sweep stalls?

**Comment by svaarala** [comment]
@JoshMarler No worries, sorry for the delay (been quite busy lately with other stuff). At present there's no support for incremental mark-and-sweep and the best low latency solution is to:
- Ensure refcounting is enabled (it's enabled by default), this limits the need for mark-and-sweep unless you generate a lot of circularly referenced garbage.
- Disable voluntary mark-and-sweep - this will avoid mark-and-sweep passes unless out-of-memory is signaled to Duktape i.e. an alloc fails. The option is DUK_USE_VOLUNTARY_GC (which must be disabled).
- Run mark-and-sweep manually when there's an opportunity to do so - e.g. when switching into menus, maybe when a frame completes with plenty of spare time, etc.

**Comment by JoshMarler** [comment]
@svaarala , No problem. Thanks for taking the time. We've got a few alternative to try so thanks for clarifying.
