### ISSUE TITLE
Errors are lost within Promise chains using polyfill (unhandled rejections)

### ISSUE THREAD

**Issue by bwalter** [svaarala/duktape#1934]
Using `polyfills/promise.js`: when an error is thrown inside a promise function, it will be ignored.

Example:
```
Promise.resolve()
            .then(function() {
              console.log("Hello1");
            })
            .then(function() {
              console.log("Hello2");
            })
            .then(function() {
              throw new Error("Supposed to be thrown");
            });
```
I can see the error if I modify the `doReject()` function and add:

```
if (reactions.length === 0) {
        console.error("Within promise, error stack:", val ? val.stack : "unknown");
        throw val;
}
```

Not sure if it is the right way to fix it, though ;)

**Comment by svaarala** [comment]
If no-one has registered a rejection reaction, then it is supposed to be lost.

There are some implementations where one can register an 'unhandled rejection' handler for catching such rejections. See for example: http://2ality.com/2016/04/unhandled-rejections.html.

**Comment by svaarala** [comment]
Incidentally, dealing with unhandled rejections is part of implementing Promises natively. Unfortunately the browser approach doesn't yet work easily because it relies on event propagation (which Duktape doesn't support and which isn't core Ecmascript).

So the most likely mechanism is a callback registered to the global object context (so that each global environment can handle them differently which may be necessary).

**Comment by bwalter** [comment]
Thanks for the clarification! So the only solution for the moment is to always catch errors (which unfortunately makes it very difficult to handle unexpected errors) and check the content of `error.stack`.

For the global callback, do you mean something like `Duktape.onUnhandledRejection()` which would be triggered in the above case (when `reactions.length === 0`)?

**Comment by fatcerberus** [comment]
@svaarala Worth noting here that ECMAScript 2017 has HostPromiseRejectionTracker, a standardized protocol for the engine to communicate unhandled promise rejections to the application.

**Comment by svaarala** [comment]
@fatcerberus Good to know, though it's rather abstract:

> HostPromiseRejectionTracker is an implementation-defined abstract operation that allows host environments to track promise rejections.

But it's good there's some terminology etc for documentation.

For me as a user the best approach would be to:
- Register a finalizer for the Promise when the Promise is created.
- Keep track whether any rejection reactions were ever registered (before or after settling).
- When the Promise is finalized, check if the (1) Promise was rejected, and (2) whether any reject reactions were registered; if not, call some custom unhandled rejection handler.

This would not generate unnecessary "unhandled rejections" from code like:
```
P = Promise.reject(123);  // here rejected, with no reactions

// ... some time later:
P.then(...);  // register reactions, which get queued right away
```

The ES2017 approach seems to generate a "reject" from the Promise.reject() immediately:
> When a promise is rejected without any handlers, it is called with its operation argument set to "reject".

Once `P.then()` is called it would then generate a "handle":
> When a handler is added to a rejected promise for the first time, it is called with its operation argument set to "handle".

This is in fact what happens with Node.js:
```
$ nodejs
> P = Promise.reject(123)
Promise { [...] }
> (node:4452) UnhandledPromiseRejectionWarning: 123
(node:4452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4452) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> P.catch(Math.cos)
Promise { [...] }
> (node:4452) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
```

To me this is pretty annoying because it would make every `Promise.resolve()` (or equivalent) noisy. Then again, if one only checks for unhandled rejections in finalization, it happens much later which may also be confusing.

It would be possible to support both behaviors, and it'd be nice if the application could have a say which behavior is preferred. One simple approach for that would be to support three unhandled rejection events:
- reject: like ES2017
- handle: like ES2017
- unhandledAtFinalization: called if Promise rejection is unhandled at finalization time

User code could then register appropriate callbacks as desired.

**Comment by fatcerberus** [comment]
`Promise.resolve()` won’t generate a notification at all.  You only get a `handle` for a given promise if the same promise was previously rejected without a handler.

How most hosts (including Node and miniSphere) deal with this is to queue up `reject` notifys as they come in, delete any that later get a `handle` and then check at the end of the event loop whether anything is in the queue.

**Comment by svaarala** [comment]
@fatcerberus I meant Promise.reject() as in the Node.js example. Comment fixed now.

**Comment by fatcerberus** [comment]
The de facto standard for this is the WhatWG specification for rejection tracking which essentially boils down to “report an unhandled rejection if no handler is attached before the end of the event loop tick in which it was rejected”

See spec text starting from here: https://html.spec.whatwg.org/multipage/webappapis.html#unhandled-promise-rejections

**Comment by fatcerberus** [comment]
That said, the promise implementation’s responsibility here is just to provide the host with the “handle” and “reject” notifications.  What happens after that is the host’s responsibility—it’s entirely acceptable from a compliance standpoint to just do nothing at all, for example.

**Comment by svaarala** [comment]
Right, that's basically the web browser API linked to above (which uses events).

> What happens after that is the host’s responsibility—it’s entirely acceptable from a compliance standpoint to just do nothing at all, for example.

Agreed, I think the best approach would be to provide the WHATWG / Node.js behavior, but allow one also to catch unhandled rejections (only) at GC time, or at least make it possible to do that with some application glue.

**Comment by svaarala** [comment]
@bwalter I can work up a minimal solution for the polyfill in https://github.com/svaarala/duktape/pull/1935. It's not really critical for the polyfill itself, but similar features will be needed in the native implementation and it's easier to draft the behavior in the polyfill.
