### ISSUE TITLE
Reason for #undefs in duk_config.h?

### ISSUE THREAD

**Issue by MuffinManKen** [svaarala/duktape#1936]
It seems to me that if the default duk_config.h didn't explicitly #undef things like DUK_USE_DEBUG then it would be much easier to have a release vs. debug build without having different duk_config file.  With the #undef there it ignores anything I set at a project level.

I don't see any benefit to having the #undefs there. Am I missing something?

**Comment by fatcerberus** [comment]
`duk_config.h` is autogenerated by genconfig.py.  The default one is really just an example to get you started quickly, it's expected that you'll use genconfig.py in your build chain if you have more "exotic" needs.

**Comment by MuffinManKen** [comment]
How is a separate debug and release version an "exotic" need?

And it doesn't answer the question of what value explicitly #undefing those symbols provides.

**Comment by svaarala** [comment]
@MuffinManKen The idea is that duk_config.h ensures all defines are in correct settings, and no settings come from external sources such as the command line. If you don't want the defaults, the idea is to create a new duk_config.h or edit it manually. The `#undef`s are there to ensure the values are in known state, and also to make it easier to edit manually if desired (you can just search for setting names).

When options were given on the command line (DUK_OPT_xxx in Duktape 1.x) it often led to situations where some options were used to compile Duktape itself, but were then forgotten when compiling application files, leading to odd situations. This was awkward in particular when an installed system library was used because it's difficult to ensure application code gets the same -DXXX options, while it's much easier to ensure that the `duk_config.h` in the include path is correct for the installed library.
