### ISSUE TITLE
Signing bytecode

### ISSUE THREAD

**Issue by livrish** [svaarala/duktape#1943]
"Loading bytecode from an untrusted source is memory unsafe and may load to exploitable vulnerabilities." 

Being able to sign the bytecode would ensure that it comes from a trusted source

**Comment by svaarala** [comment]
Yes, the intent is that if you rely on loading bytecode from remote sources, you would evaluate the security needs and if necessary apply encryption and/or signatures.

Duktape doesn't provide encryption and/or signatures because there are many use cases with a wide variety of security requirements, and one size may not fit all.

**Comment by vshymanskyy** [comment]
Just an idea. How about providing some hooks so the application can decide whether to permit loading the bytecode? Or is it easy to implement already?

**Comment by svaarala** [comment]
The application is already in control of that - no bytecode is ever loaded except without an explicit https://duktape.org/api.html#duk_load_function call.

**Comment by vshymanskyy** [comment]
@svaarala thx for explanation!
