### ISSUE TITLE
Symbol.toPrimitive passed to Proxy as property name even when Symbol builtin is not enabled

### ISSUE THREAD

**Issue by mrmacete** [svaarala/duktape#1968]
In Frida we have a Proxy like this:

```
        const self = new Proxy(this, {
            has(target, property) {
                return hasProperty(property);
            },
            get(target, property, receiver) {
                switch (property) {
                    case "handle":
                        return handle;
                    case "prototype":
                        return target.prototype;
                    case "constructor":
                        return target.constructor;
                    case "hasOwnProperty":
                        return hasProperty;
                    case "toJSON":
                        return toJSON;
                    case "toString":
                    case "valueOf":
                        const descriptionImpl = receiver.description;
                        if (descriptionImpl !== undefined) {
                            const description = descriptionImpl.call(receiver);
                            if (description !== null)
                                return description.UTF8String.bind(description);
                        }
                        return function () {
                            return receiver.$className;
                        };
...
```

Apparently, in the latest version of duktape the `property` argument of `get()` can be a Symbol. In particular when coercing this object to a string, the `"toString"` property turned into a `Symbol.toPrimitive`.

The problem is that if we don't enable the `DUK_USE_SYMBOL_BUILTIN` configuration, there's no way to properly compare the property and get to the right `case`. This is also complicated by the fact we're using `core-js` polyfills which have their `Symbol` implementation which doesn't help in this case.

This can be solved by enabling `DUK_USE_SYMBOL_BUILTIN` and just adding `case Symbol.toPrimitive:` in the switch, but if i understand correctly that's still experimental.

Maybe i'm wrong but i expected that when Symbol builtins are not there, the `property` here should be a string as it was before?

**Comment by svaarala** [comment]
First regarding the trap behavior, Symbols are intended to invoke the `get` trap so that part is correct, e.g. from NodeJS:

```
> var P = new Proxy({}, { get: function (a,b,c) { console.log('trap', a, b); } })
undefined
> P[Symbol.toPrimitive]
trap {} Symbol(Symbol.toPrimitive)
undefined
```

Regarding Symbol support -- Symbol support itself is quite solid, it was marked experimental because @fatcerberus had some concerns about how Symbols appear in the C API. They behave like internal strings in previous Duktape versions so that they test true for `duk_is_string()` but also for `duk_is_symbol()`. C code wanting to exclude them must explicitly check for the Symbol case. This has always been the case since 1.0.0 for internal strings so nothing has really changed in that respect, but IIRC @fatcerberus's concern was that with Symbols in active use one is more likely to encounter Symbols in the C API.

Anyway, it should be fine to enable Symbol support, and since the C API for Symbols has been in active use already for 2.x, it should be enabled by default in master now.

**Comment by mrmacete** [comment]
thanks! let's close this then.

**Comment by fatcerberus** [comment]
I don’t understand the issue here; if there is no built-in Symbol support then the trap can never be called with a symbol?  The core-js polyfill as far as I’m aware transforms Symbol keys into some long string of random characters, so that’s probably what you’d see in the Proxy trap.  But for basic string keys you should still see the string as-is like “valueOf”, “toString”, etc.?  So the switch case should work regardless.

**Comment by mrmacete** [comment]
yes for regular properties it still works with strings, but it doesn't seem the case for implicit string coercion, where instead the `Symbol.toPrimitive` is passed to the trap instead of `"toString"` string property like happened in the past.

**Comment by fatcerberus** [comment]
What I don’t understand is why the trap would be called with `Symbol.toPrimitive` as the key *in lieu of* `toString`.  That seems very bizarre.

**Comment by svaarala** [comment]
ES2015+ consults @@toPrimitive first: https://www.ecma-international.org/ecma-262/6.0/#sec-toprimitive. It then falls back to toString() etc.

**Comment by svaarala** [comment]
@mrmacete One thing you could do if you simply don't want to deal with any Symbols in the "get" trap is:
```
if (typeof key === 'symbol') {
    return target[key];  // pass through; or 'return;' if you want to block pass through
}
```

You could do this e.g. in the default clause or as the first thing in the function.

**Comment by mrmacete** [comment]
thanks! i'll try

**Comment by fatcerberus** [comment]
Then that should be the case even if Symbol support is enabled, correct?  @mrmacete seemed to be suggesting enabling the Symbol built-in made that no longer be the case.  That’s why I’m so confused.

**Comment by svaarala** [comment]
@fatcerberus So this is what happens in ES2015 when you String coerce a Proxy object:
```
> var P = new Proxy({}, { get: function (a,b,c) { console.log(b); return void 0; } });
undefined
> String(P)
Symbol(Symbol.toPrimitive)
toString
valueOf
TypeError: Cannot convert object to primitive value
    at String (<anonymous>)
```

@@toPrimitive is consulted first, then fall back to the pre-ES2015 behavior of .toString() or .valueOf().

**Comment by svaarala** [comment]
@fatcerberus Symbol *support* is always enabled. Symbol built-in can be disabled. This is because Symbols are needed in any case for the internal hidden Symbols, and C code can always use Symbols even when the built-in Symbol object is disabled.

When adding Symbol support there was an implementation option of making it also possible to disable Symbol support internally (except for hidden Symbols), but it affects a lot of places and Symbol support itself does not have a big footprint. But this didn't seem worth the trouble.

**Comment by mrmacete** [comment]
@fatcerberus nope, enabling Symbol built-in just made it possible to handle the case
