### ISSUE TITLE
Duktape chokes on ANSI-encoded script with extended characters

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#197]
I've encountered several legacy scripts which are not UTF8-encoded but contain extended characters (for example, the copyright symbol ©), and Duktape has a heart attack when attempting to parse these, throwing a "char decode failure".  Is there any possibility Duktape could be changed to detect this and switch to ANSI mode in case of a decode failure?

In other words:
* Try to parse the script as UTF8.
* On char decode failure, restart the parse but assume the script is ASCII/ANSI.

Obviously I can resave scripts as UTF8 to get Duktape to read them, but this is not always feasible--for example, there are cases where a script is embedded in a large binary file (e.g. a game map) which can't be easily converted.

**Comment by svaarala** [comment]
Duktape only supports UTF-8 (or rather extended UTF-8) for source code; the error you get is simply to let you know the source has invalid encoding.  Choking and heart attacks have nothing to do with it as far as I know :wink:

I don't think it'd be sensible to support non-UTF-8 encodings. There are quite many of them and there's no way to autodetect them reliably which would be very awkward. Supporting dozens of different encodings would bloat Duktape considerably for very little gain, and there are already good libraries for converting between encodings.

It's best to avoid 8-bit encodings for source files because they're always a portability hassle when editing them across platforms. With legacy code I'd try to transcode them at build time (which is trivial), but if that's not possible, you can always transcode at run time just before you give the string to Duktape. This is quite easy to do with e.g. iconv, and Duktape would need to do something similar if it supported multiple encodings.

**Comment by fatcerberus** [comment]
The main issue is that many old editors don't support UTF8 and will save as raw 8-bit text of whatever code page happens to be in use.  This usually isn't a problem (UTF8 was designed to be back-compatible with ASCII which is awesome), unless the source contains characters outside the 7-bit range, in which case Duktape won't parse it.

Obviously I wouldn't expect Duktape to support every code page in existence, it just surprised me that it completely breaks if a string or comment in the file contains a high-bit-set character.  Such characters are never valid tokens anyway, so I'd only want Duktape to pass them through verbatim if they are encountered in a string and can't be parsed as UTF-8.  The application can handle code page issues, which it would have to in either case since C strings themselves are not UTF8 natively.

**Comment by svaarala** [comment]
What if the copyright sign is in a string literal - wouldn't that be equally possible, as strings in existing code bases may often contain characters with acutes etc; the case where non-ASCII characters are limited to comments is rather narrow? In any case, the decoding process is currently not aware of the context where the codepoints are decoded, so implementing an "allow invalid encoding inside comments" would need some rework.

IMO it's desirable behavior to require the source to be correctly encoded, otherwise it's quite easy to write broken source code that will silently be parsed but may not work as intended. In general I prefer to see errors early rather than late, and UTF-8 handling is generally implemented in a "strict" rather than "loose" fashion (differences exist of course).

**Comment by fatcerberus** [comment]
I do see what you mean--and you're right that extended characters in string literals would cause problems.  Duktape would have to convert them back to UTF-8 internally, which would be impossible without knowing what codepage was used (unless you just assume Windows-1252 and call it a day).  Whoever came up with the idea of codepages needs to be, to quote Garfield, drug out into the street and shot. :)

I admit to not being aware of iconv and the like, although it makes sense there would be a tool for that.  The only issue for me is that GNU iconv is LGPL and I'm trying to keep my engine BSD-licensed.  Presumably it wouldn't be too difficult to do the conversion myself, though.

**Comment by svaarala** [comment]
One reasonable alternative is to replace invalid bytes with the Unicode replacement character (U+FFFD), which is sometimes done when it's more important to get a result string than to be strict. But I'm not sure if this would be more useful than the strict behavior when parsing code, it's probably better to know that e.g. a string literal needs fixing than using the replacement silently.

**Comment by fatcerberus** [comment]
Yeah, like I said, it's easy enough to just resave .js files in UTF-8 to get them to work, the bigger issue for me is that the engine in emulating has a binary map format which embeds entity code directly in the map format.  As the format predates wide use of UTF-8, converting these scripts to UTF-8 breaks the file.

But again, here you're right: as it _is_ a legacy format I'm dealing with, I guess it ultimately falls on me to handle portability issues like this.

**Comment by svaarala** [comment]
Implementing a Windows-1252-to-UTF-8 conversion is not that difficult but you need to map a single input byte to 2-3 output bytes for the non-ASCII characters. I'll push an example shortly :-)

**Comment by svaarala** [comment]
Here's an example:

- https://github.com/svaarala/duktape/compare/add-codepage-conv-example

I'll add it to the dist package because it may be useful to someone else too.

**Comment by fatcerberus** [comment]
Thanks, I'll have to try this out.  Convenient, too, it puts the result right on the valstack so you can immediately call `duk_eval()` afterward.

**Comment by fatcerberus** [comment]
The conversion function worked great, thanks. :smile:

**Comment by svaarala** [comment]
Good to hear, at least it's a starting point if someone faces a similar situation :)
