### ISSUE TITLE
TypeError when accessing arguments.caller or arguments.callee

### ISSUE THREAD

**Issue by morphogo** [svaarala/duktape#2008]
Thank you for all your hard work on Duktape!

Duktape version 2.3

function abc(){
  Object.prototype.toString.call(arguments.caller);
  Object.prototype.toString.call(arguments.callee);
}
abc();

I get the following TypeError in my execution log.

27 Nov 23:23:20.903 [FATAL] a/main.js:53
 > invalid args
   > TypeError: invalid args
   >     at [anon] (src/duktape.c:41640) internal
   >     at ThrowTypeError () native strict preventsyield
   >     at abc (app/main.js:53) strict
   >     at module (app/main.js:56) strict
   >     at load (lib/internal/module.js:87) strict
   >     at _load (lib/internal/module.js:66) strict
   >     at runMain (lib/internal/module.js:72) strict
   >     at run (lib/internal/system.js:14) strict
   >     at bootstrap (env/bootstrap.js:77) strict preventsyield

**Comment by svaarala** [comment]
For ES5.1 and ES2015 which Duktape currently follows w.r.t. arguments object:
- `arguments.caller` is not defined for non-strict argument objects, `arguments.callee` is set to target function.
- For strict arguments objects both are set to a thrower function, see https://www.ecma-international.org/ecma-262/5.1/#sec-10.6, step 14.

Based on the traceback your code is in strict mode, where both `.caller` and `.callee` are required to be throwers up to ES2015, which is why you are seeing a TypeError for the `.caller` access.

However, this seems to have changed in ES2017: https://tc39.github.io/ecma262/#sec-createunmappedargumentsobject, there's a note about this:
> ECMAScript implementations of arguments exotic objects have historically contained an accessor property named "caller". Prior to ECMAScript 2017, this specification included the definition of a throwing "caller" property on ordinary arguments objects. Since implementations do not contain this extension any longer, ECMAScript 2017 dropped the requirement for a throwing "caller" accessor.

The new behavior is the same for non-strict mode, but for strict mode:
- `arguments.caller` is no longer set at all.
- `arguments.callee` is still set to a thrower.

(Note that your code will still throw on the `arguments.callee`, which is still a thrower in strict mode.)

My node.js seems to have the ES2017 behavior:
```
> process.version
'v10.13.0'

// Strict mode arguments.caller is missing.
> function foo() { 'use strict'; console.log(Object.prototype.toString.call(arguments.caller)); }
undefined
> foo();
[object Undefined]
undefined

// Strict mode arguments.callee is still a thrower.
> function foo() { 'use strict'; console.log(Object.prototype.toString.call(arguments.callee)); }
undefined
> foo();
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at foo (repl:1:85)
```

The fix for Duktape would be to remove the `arguments.caller` property in strict mode.

**Comment by morphogo** [comment]
@svaarala,
I would like to thank you for being so prompt in replying and in explaining to me in details what is essentially a non-Duktape related issue.

**Comment by fatcerberus** [comment]
I don’t understand what the spec means when it says “implementations no longer contain this extension” - how is it an extension if the (older) standard already says the property must exist and be a thrower?

**Comment by svaarala** [comment]
I'd have to read the latest draft in more detail to answer that. But the interpretation itself seems correct because Node.js also matches it.
