### ISSUE TITLE
Add CommonJS support for module.exports

### ISSUE THREAD

**Issue by JoshEngebretson** [svaarala/duktape#201]
This would be really handy and make the CommonJS module support significantly more flexible (and work better with various libraries)

I am curious if this is a complicated or relatively simple addition.

**Comment by svaarala** [comment]
It's a relatively simple addition - I've been postponing it because the module model will need some reworking for Duktape 2.x (more flexibility than current modSearch() provides, but perhaps some ES6 alignment too).

But since the change is rather small and backwards compatible, I've implemented it in the work branch here:

- https://github.com/svaarala/duktape/compare/add-module-exports-support

The branch also changes behavior slightly for module caching when module load attempt throws an error (which is underspecified in CommonJS). In Duktape 1.2 and prior the partial module would be cached.  After this change the cache entry is removed so that one can try to re-load the module (this behavior matches Node.js).

**Comment by JoshEngebretson** [comment]
Fantastic!  Thanks! :heart: 

Specifically, I have been doing some work with TypeScript and the Atomic Game Engine,  so module.exports support will really help.  I'll try out the work branch tomorrow (I also like the re-load change!)

**Comment by svaarala** [comment]
The `module.exports` change should be quite clear from semantic versioning perspective: generally adding new functionality is OK as long as existing code wouldn't break.

The module error/reload change is a bit more in the grey area as it changes existing (corner case) behavior. I find it unlikely there would hard dependencies on the previous behavior though (especially since the behavior is underspecified and Duktape 1.2 behavior was different than e.g. Node.js). So, perhaps it would be OK to change with a note in RELEASES.rst and release notes.

Opinions? :-)

**Comment by svaarala** [comment]
@JoshEngebretson Ok, let me know if it works as you'd expect :)

Not all of the behavior is trivial because replacing `module.exports` conflicts with CommonJS circular require support to some extent. As implemented in this branch, if a module replaces `module.exports` that change won't be visible if the module being loaded does a `require()` that leads to a circular require of the module being loaded. Supporting this would be possible if `module.exports` was a setter property with side effects on assignment, though; not sure if e.g. Node.js supports it.

**Comment by fatcerberus** [comment]
For what it's worth I think the change is fine.  Most people would probably consider the old behavior a bug anyway.

**Comment by svaarala** [comment]
Circular requires can lead to quite interesting cases, e.g. supposing loading of module A fails:

- Start loading module A
- Module A requires module B
- Start loading module B
- Module B requires module A, and gets the initial `exports` value from `modLoaded`
- Finish loading module B: module B gets cached
- Module A fails to load: module A is removed from the cache in the new behavior

With the new behavior in this branch, module A is not cached but module B is.  Further, module B has a reference to what it thinks is module A, but actually holds a reference to the partial `exports` value.

With the previous behavior, module B's reference to module A matches what gets cached in `modLoaded`, so it's in some sense more consistent behavior.

Anyway, these really are corner case issues... :)

**Comment by fatcerberus** [comment]
The modules themselves are (or should be) mostly self-contained though, no?  So the caching shouldn't be an issue in that case.

Circular references like this always cause issues anyway.  You can never handle all cases in their presence.  In C for example you use include guards (or `#pragma once`), this protects against infinite recursion but you can end up with mysterious "x not defined" compile errors if you try to use types from one header in another.

So yeah, definitely a corner case issue.  I wouldn't worry too much about it.  Just add a note in the release notes and call it a day. :)

**Comment by svaarala** [comment]
It breaks the logical guarantee that a successful `require("foo")` should always return the same value - either from the initial load or the cached value.

When module loading succeeds normally and `module.exports` is not written to, circular references work perfectly fine and are explicitly supported in CommonJS (unlike many other module systems).

**Comment by fatcerberus** [comment]
Ah, I see.  That complicates matters if the spec explicitly makes provisions for it.  Hm.

**Comment by svaarala** [comment]
The specification is pretty lightweight: http://wiki.commonjs.org/wiki/Modules/1.1.1. The part about cycles is:

> If there is a dependency cycle, the foreign module may not have finished executing at the time it is required by one of its transitive dependencies; in this case, the object returned by "require" must contain at least the exports that the foreign module has prepared before the call to require that led to the current module's execution.

There's no explicit guarantee for `require("foo")` always returning the same value, but as a user I'd expect it to do that.

**Comment by svaarala** [comment]
Another improvement to `module.exports` and circular requires would be to have Duktape.modLoaded[] cache the entire "module" object (which contains "id" and "exports") rather than just the "exports" value. This way changes to "module.exports" would be immediately visible. E.g. in Node.js:

```
// foo.js
module.exports = function adder() { ... }
var bar = require('./bar');

// bar.js
var foo = require('./foo');
print(typeof foo);
// -> function (adder) in Node.js
// i.e. the "module.exports = ..." assignment is already visible here,
// even if foo.js has not finished loading yet
```

With the code currently in this branch, `typeof foo` would be `object`, i.e. the initial `exports` value at start of `foo.js`.

The only real downside of caching the "module" value instead of "exports" directly is that it takes slightly more memory. The module entries should be compacted but still there's a small difference.

**Comment by fatcerberus** [comment]
Doesn't that break the spec?  `exports` is required to be a free variable from what I understand.

**Comment by svaarala** [comment]
It is a free variable - the value for "exports" is set up matching "module.exports" at entry to the module.

If the module changes "module.exports", it won't affect "exports". However, when a sub-module `require()`s the module being loaded we could either return the initial value for "module.exports" (i.e. == exports) or the updated value. Node.js returns the updated value.

**Comment by JoshEngebretson** [comment]
Just reporting that our use case of this is working great, thanks again!

Here's an example:

![scriptwidget](https://cloud.githubusercontent.com/assets/376203/7898391/5c78c952-06b3-11e5-93a8-2a808da984b5.png)

**Comment by svaarala** [comment]
@JoshEngebretson Great to hear! :)

I'll agonize over the module.exports details a little, add some more testcases and then merge this to master in a day or two.

**Comment by JoshEngebretson** [comment]
Circular dependencies do happen, though I wouldn't agonize (too much) over failed imports.  The later could be defined as "user error" in most cases.

**Comment by svaarala** [comment]
Yeah, the `modLoaded[]` change I'm doing will improve circular dependency handling when `module.exports` is assigned to. Basically I'm changing it so that the new `module.exports` value will be visible to any sub-modules required.

**Comment by svaarala** [comment]
Testcase for the case fixed by the change (just pushed):

- https://github.com/svaarala/duktape/blob/add-module-exports-support/ecmascript-testcases/test-commonjs-module-exports-circular.js

**Comment by fatcerberus** [comment]
So I don't understand, why is `module.exports` needed?  It should be sufficient to just reassign the `exports` variable, no?

**Comment by svaarala** [comment]
No, `exports` is just a variable whose initial value is the module export table. If you assign to it, the changed value is not "returned" from the module.

Duktape loads modules by using a temporary function wrapper (which provides the necessary binding semantics). For example:

```js
(function (require, exports, module) {
  exports.add = function (a, b) {
    return a + b;
  };
  // return value is ignored
})
```

The function is called with the module export table in `exports`, but any change to the local variable `exports` is not seen by the caller.

**Comment by fatcerberus** [comment]
Hm, I found what I think is a bug.  If you directly assign a variable in a module, like this:

```javascript
// module: myModule
doStuff = function() { print("Oh no! How did this happen?!"); }
```

And then outside the module:
```
require("myModule");
print(doStuff);
doStuff();  // this shouldn't be possible! but it is...
```

It prints `function anon() {/* ecmascript */}` and successfully calls the function.  The variable assignment is visible from outside.  My understanding of modules was that they were supposed to be completely self-contained so this should not be possible.

**Comment by JoshEngebretson** [comment]
A "module" is a normal closure, where scoping rules don't change.  You would need to use a var declaration to make "doStuff" local.  Otherwise, it is assigned to a global variable.  You can use strict mode to make this into an error.

**Comment by fatcerberus** [comment]
Ah, so it's basically just sugar for an IIFE (self-executing function), that clears things up.  I'll keep that in mind and use strict mode for my modules now.  Thanks for the clarification!

**Comment by svaarala** [comment]
That also happens with Node.js BTW:

https://github.com/svaarala/duktape/blob/master/doc/modules.rst#assignments

**Comment by svaarala** [comment]
Merged to master.

**Comment by JoshEngebretson** [comment]
Level Up!  :star2:
