### ISSUE TITLE
Input file causes segfault

### ISSUE THREAD

**Issue by AndrewFasano** [svaarala/duktape#2015]
Inputs starting with the bytes `\xbf\x0a` cause duktape 2.3.0 to segfault when run from the command line.

I built the program from https://duktape.org/duktape-2.3.0.tar.xz with `make -f Makefile.cmdline`

With [min.js](https://github.com/svaarala/duktape/files/2673973/min.js.txt) as an input file,  running `./duk min.js`  causes a segfault with the following callstack:
```
#0  0x000000000042299e in duk.load_func ()
#1  0x0000000000422d6e in duk_load_function ()
#2  0x000000000042dfac in wrapped_compile_execute ()
#3  0x0000000000412120 in duk_handle_safe_call ()
#4  0x000000000042de73 in handle_fh ()
#5  0x0000000000401eaa in main ()
```

This issue was found by multiple teams during [Rode0day](//rode0day.mit.edu), a continuous bugfinding competition.

**Comment by fatcerberus** [comment]
0xBF is the magic number for compiled Duktape bytecode and only affects the command-line `duk` tool.  Hosts aren’t vulnerable unless they explicitly load bytecode without verification.  Duktape itself doesn’t validate bytecode by design, refer to https://github.com/svaarala/duktape/blob/master/doc/bytecode.rst

See also #1944.

**Comment by AndrewFasano** [comment]
Oh, if its expected behavior then I'll close the issue. Sorry about that. I had assumed that no input files to duk would cause crashes and didn't look it more closely.

**Comment by fatcerberus** [comment]
Yeah, it’s expected behavior, but maybe a bit surprising; you’re certainly not the first person to hit it.  Maybe it would make more sense in the future to have an explicit command-line switch to load bytecode...

**Comment by svaarala** [comment]
@AndrewFasano No input files given to `duk_(p)compile()` and variants should cause a segfault, there is no automatic detection of bytecode there.

Bytecode loading API call `duk_load_function()` may cause a segfault unless the input is compatible as described in bytecode.rst. When application code calls `duk_load_function()` they are required to ensure the bytecode is compatible.

The `duk` command line tool intentionally allows bytecode execution from whatever source because it's convenient in development / testing. But there's no such issue in the Duktape API itself.

**Comment by svaarala** [comment]
That might a good change. Another similar change would be to enable the autodetection explicitly.
