### ISSUE TITLE
How to create "Proper" builtin object?

### ISSUE THREAD

**Issue by TheBrokenRail** [svaarala/duktape#2052]
When creating and object with ```duk_push_object``` and binding it to the global object, unlike Math, Date, JSON, and other built-ins. It will show up when looking at ```this```/```global``` when other built-ins won't, and in the REPL, it will print ```undefined```, where as other built-ins will print ```{}```, also how can you name an object so it prints ```[object NAME]``` instead of ```[object Object]``` without creating a constructor?

```
((o) Duktape 2.3.0 (v2.3.0)
duk> this
= {performance:{now:{_func:true}},console:undefined}
duk> console
= undefined
duk> console.toString() 
= "[object Object]"
duk> JSON
= {}
duk> JSON.toString()
= "[object JSON]"
```

**Comment by svaarala** [comment]
The first issue is about a property's enumerability. Each ECMAScript property has three attributes: writable, configurable, enumerable. When you assign properties they are by default writable, configurable, and enumerable. This means they show up e.g. in the REPL. You can create non-enumerable properties e.g. as follows:

```javascript
Object.defineProperty(this, 'test', {
    writable: true,
    enumerable: false,
    configurable: true,
    value: { /* your object */ }
});
```

Alternatively, you can write the property normally and then just disable its enumerability:

```javascript
this.test = { /* your object */ };
Object.defineProperty(this, 'test', { enumerable: false });
```

This property can be accessed as `this.test` but won't show up in enumeration or the REPL. As a side note, the reason why the built-in `performance` object *is* enumerable is simply because it is specified outside of core ECMAScript and that specification requires that the property be enumerable.

The second question is about `Object.prototype.toString()` output, which is of the form `[object <class>]`. This is a magic function in that it is the only place (as far as I can recall) in ES5.1 where the internal class of an object is directly externally visible. As such you cannot change the internal class of an object, but by enabling Symbol support you can use `Symbol.toStringTag` to change the output.

Example from NodeJS:
```
> X = {}; X[Symbol.toStringTag] = 'MyObject'; Object.prototype.toString.call(X);
'[object MyObject]'
```

The same will work in Duktape, provided that Symbol support is enabled (DUK_USE_SYMBOL_BUILTIN).

**Comment by TheBrokenRail** [comment]
Any way to do this in C instead of JS?

**Comment by TheBrokenRail** [comment]
And what about it evaluating as ```undefined``` in the REPL?

**Comment by svaarala** [comment]
You can do all of the above in C too, using e.g. duk_def_prop(), duk_put_prop() etc.

Re: showing up as undefined, can you show how you initialize `console`?

**Comment by TheBrokenRail** [comment]
https://github.com/svaarala/duktape/tree/master/extras/console

```
duk> console
= undefined
duk> JSON
= {}
```

**Comment by TheBrokenRail** [comment]
```console.log``` still works though.

**Comment by svaarala** [comment]
The REPL serializes values using Duktape JX encoding which is kind of a JSON superset.

The reason why it appears as `undefined` is a bit complicated: an earlier version of the "console" specification required that `console` be a Proxy object and that it should return a NOP function for *any* function name (e.g. `console.noSuchMethod`). This behavior is enabled with the console extra's `DUK_CONSOLE_PROXY_WRAPPER` option, see https://github.com/svaarala/duktape/blob/master/examples/cmdline/duk_cmdline.c#L1160.

Because the `console` object does not have a `.toJSON()` method, the Proxy wrapper returns a nop function instead. This causes JX to encode it as `undefined`.

If this matters, you can either disable `DUK_CONSOLE_PROXY_WRAPPER` or set toJSON explicitly:
```
((o) Duktape [linenoise] 2.3.99 (v2.3.0-52-gb062b50a)
duk> console
= undefined
duk> console.toJSON = function () { return this; };
= {_func:true}
duk> console
= {format:{_func:true},assert:{_func:true},log:{_func:true},debug:{_func:true},trace:{_func:true},info:{_func:true},warn:{_func:true},error:{_func:true},exception:{_func:true},dir:{_func:true},toJSON:{_func:true},toString:{_func:true}}
```

A nicer fix would be for the console extra to skip providing a NOP function for .toJSON(), even if it is missing, and probably remove the Proxy wrapping from `duk` console init because it's no longer the preferred way.

**Comment by TheBrokenRail** [comment]
How do you set the ```Symbol.toStringTag``` in C?

**Comment by svaarala** [comment]
Symbols are treated like strings in the C API, see https://duktape.org/guide.html#symbols. For example, something like:
```
// obj_at_IDX[Symbol.toStringTag] = 'MyObject';
duk_push_string(ctx, "MyObject");
duk_put_prop_string(ctx, IDX, DUK_WELLKNOWN_SYMBOL("Symbol.toStringTag"));
```
