### ISSUE TITLE
64 bits management

### ISSUE THREAD

**Issue by maxime-ohm-georges** [svaarala/duktape#2083]
Hello,
I am porting a C source code that use 64 bits number as function parameter.

I have seen a lot of functions like:
- duk_to_int()
- duk_to_uint()
- duk_to_int32()
- duk_to_uint32()

But, duk_to_int64() and duk_to_uint64() is missing.

Did you plan to add 64 bits support on the next version ?

Thank you in advance,
Max.

**Comment by svaarala** [comment]
Duktape doesn't currently assume 64-bit types to be available (they are not present or not functional on some more exotic targets). But adding these API calls so that they are only available when 64-bit types are found would be possible.

At present you can in most cases simply say:
```
int64_t val = (int64_t) duk_to_number(...);
```

One thing worth noting is that all number types are ultimately IEEE doubles, and as such can only represent integers accurately up to `2^53^, so 64-bit types won't work as expected in some cases.

**Comment by svaarala** [comment]
One future work item is to add support for the (draft) big numbers already supported by e.g. Node.js (#2048). They would allow 64-bit (and larger) values to be handled reliably which would be nice for many applications.

**Comment by maxime-ohm-georges** [comment]
Thank you for your quick reply.
I will use your example and change the code of my application when 64 bits will be available.

Best regards,
Max.
