### ISSUE TITLE
Global object sometimes not being cleaned up

### ISSUE THREAD

**Issue by kinnison** [svaarala/duktape#2084]
Hi,

I have an interesting problem in NetSurf (where we use duktape as our JS engine) -- we maintain browsing contexts by means of a heap which we push threads into.  Those threads then get given quite complex global objects (`Window` in the web JS sense) which has, among other things, a C finaliser which removes callbacks in our browser.

Under *some* circumstances, the specifics of which I have yet to determine, the global object does not get finalised when we pop (and thus destroy) the thread representing the browsing context.

To my knowledge we can't keep references to JS objects outside of duktape, we do not use stashes, and the global object on the heap itself does not appear to have been given additional properties which might represent a way to point back to the `Window` object.

Is there any way we can get the heap to dump a listing of how it's able to reach an object?  What I'd like is to be able to determine how the Window object is being held as "live" still.

The function which we hope causes the cleanup is at <http://git.netsurf-browser.org/netsurf.git/tree/content/handlers/javascript/duktape/dukky.c#n607> and lines 615/616/617 are the popping off of the thread, and then a pair of garbage collect calls to try and force the mark-and-sweep.

This is, understandably, causing us much confusion and upset because if callbacks come along after the context was meant to be cleaned up, "bad things"™ happen :/

If there's anything I can do to assist you in assisting me, please let me know.

D.

**Comment by svaarala** [comment]
Garbage collection should indeed clean up the global object and all other built-ins once the last references to them disappear. Assuming code within each global context stays within the same global context it's not easy to create an outside reference to the global object by accident.

How it could happen is, for example, if you create an object within the global object, and that function is then persistent in some data structure outside of the global context. Something like an unfired timer for example. The function instance inherits from the global object's `Function.prototype`, which inherits from `Object.prototype`, and so on.

There's no API to examine the heap objects as such, but there's a debugger command DumpHeap to list all heap objects which allows one to construct a graph.

**Comment by svaarala** [comment]
One thing to note is that Duktape doesn't have any internal object which represents a "global context" as such. Thread objects (`duk_hthread` / `duk_context` in public API) have internal slots which reference the built-in objects, such as the global object, Function.prototype, etc, which the thread is related to. The built-ins are created when the first thread requiring a fresh global context is created. After this, they're in essence normal objects in the heap, subject to reference counting and reachability-based garbage collection.

It is entirely possible for the `duk_hthread` to be garbage collected, but some or all of the built-in objects themselves to survive because there are references to them elsewhere. Similarly, if multiple threads share the same global objects, this is simply handled by both threads referencing the same objects, with both references being reference counted. The built-in objects may thus outlive the thread for which they were created.

ES2015 has a formal Realm concept which will probably require reworking the modelling of global contexts in Duktape internals. It may change some details, but the same issue will probably remain, i.e. if one creates an object that is reachable while the Realm itself is not, that object may keep whole or parts of the Realm from being garbage collected.

**Comment by kinnison** [comment]
I've certainly not done anything which I'd *expect* to cause `Function.prototype` or similar to have gained objects, but I suppose it's possible that the JS code I'm running might have tried to augment the prototypes of the HTML elements or somesuch and thusly ended up capturing the Window global.  Hmm, I really do need to try and use that DumpHeap debug command.  I'll take a look soon, thanks for your help thus-far.  If it's okay with you, I'll leave this issue open until I can find the root cause.

**Comment by kinnison** [comment]
What I specifically need to be able to do is at the point I believe things to be cleaned up (i.e. after the `duk_gc()` calls in the code I linked, I want to attach and DumpHeap however that works.

Sadly I'm having a bit of a brainfail, since the `duk-trans-dvalue` debugger example isn't making me go "aha, like this..." :(

**Comment by svaarala** [comment]
> I've certainly not done anything which I'd expect to cause Function.prototype or similar to have gained objects [...]

What I was referring to a scenario where e.g. the function argument of setTimeout() is registered outside the global object in question, in some timer state structure. Such a function would reference the `Function.prototype` of the global context where it was created, preventing garbage collection of whatever can be reached via the prototype object. But maybe we're talking about different things.

> Sadly I'm having a bit of a brainfail, since the duk-trans-dvalue debugger example isn't making me go "aha, like this..." :(

With that example you'd need to write the DumpHeap command similar to: https://github.com/svaarala/duktape/blob/master/examples/debug-trans-dvalue/test.c#L68-L90. DumpHeap accepts no arguments so one would just send `REQ 32 EOM` (32 = DumpHeap) and then parse the output.

The command output is written by https://github.com/svaarala/duktape/blob/master/src-input/duk_debugger.c#L1824-L1832 and is otherwise undocumented as the command is a bit experimental.

If you have the ability to use a TCP debugger transport, the web UI example debugger has a DumpHeap button which issues the command and converts the output into a more usable JSON output.

**Comment by fatcerberus** [comment]
Hey look, I’m still around!

My personal suspicion is that you probably shouldn’t be relying on finalizers as your primary mechanism of ensuring cleanup (deregistering callbacks and such).  A finalizer is a great way to prevent leaks, but I wouldn’t generally expect garbage collection to be deterministic enough to prevent “use after free” type scenarios like you describe all on its own.

When I was using Duktape, I basically made it a rule to not assume anything in particular was cleaned up unless I knew the last thing I called was `duk_destroy_heap`. :)

**Comment by kinnison** [comment]
I agree that relying on finalizers as a primary mechanism is risky, so I've added an explicit compartment close step to our bindings in NetSurf.  However I would still like to ensure that we *are* cleaning up as much as we possibly can be, otherwise this is effectively a memory leak until the tab is closed in the browser.

I've not yet managed to wire up the debugger API because I've been super-busy.  @svaarala is there any hope you might be able to knock up a tiny C file which I can include which exposes a single function (`dump_current_heap(duk_context *)`) or somesuch to do the right thing?  I'm fine if it spews to stdout/stderr (though if it can spew to a file, then that's even better)
