### ISSUE TITLE
valuestack corruption

### ISSUE THREAD

**Issue by noomio** [svaarala/duktape#2117]
Hi,

I have implemented c callbacks as described on your guide and it works well. I noticed that when the valuestack isn't popped with duk_pop(ctx); afterwards it will corrupt and then the cpu will hard fault. Is there a way to catch this fault so it doesn't crash the cpu?

```
rc = duk_pcall(ctx, 0);

if (rc != 0) {
  printf("Callback failed: '%s'\r\n", duk_safe_to_string(ctx, -1));
 }
duk_pop(ctx);

```
Here is an image of the value stack corruption:

![stack](https://user-images.githubusercontent.com/51944940/59659196-080d2f00-91e9-11e9-966a-c7d869c26efd.PNG)

**Comment by svaarala** [comment]
This shouldn't happen, can you paste more code?

Can you run your code under valgrind?

**Comment by svaarala** [comment]
One possibility is that when you are not popping the values off as intended, you eventually exhaust the value stack "reserve" (see https://duktape.org/guide.html#programming.5), which can then lead to an API call error *outside* the protection of a `duk_pcall()` or a `duk_safe_call()` (if you do anything outside of protected calls).

Because there is nothing to catch such an error, such an error would be considered fatal, and would trigger the fatal error handler which by default `abort()`s the process.

To eliminate this possibility, you can use a `duk_safe_call()` as the first call in your program, wrapping everything else inside a safe call, so that you never encounter an uncaught error.

**Comment by noomio** [comment]
Hi,

Unfortunately this is an embedded board with limited resources running threadX and I can you valgrind.
Basically im trying to implement the setTimout etc that work well when I pop the value stack otherwise it doesn't. I tried the wrapped call but it has the same effect; no indication of fault/catch. Seems like a hard fault and with the platform I'm using all fault are abstracted and make it very difficult to fault find; cant even jtag. I had to implement malloc etc and not sure if that may cause the issue.

https://wiki.duktape.org/howtonativepersistentreferences

```
for(;;){

	if(tx_queue_receive(timer_queue, &ptr, TX_WAIT_FOREVER) == TX_SUCCESS){
 		timer_store_t *t = (timer_store_t *)ptr;
 		
                if(t == NULL)
 			continue;

		duk_int_t rc;
		duk_context *ctx = t->ctx;

	        /* Get current callback. */
		duk_get_global_string(ctx, t->name);
		
		if (!duk_check_stack(ctx, 1)) {
		    /* return 'undefined' if cannot allocate space */
		    printf("failed to reserve enough stack space\r\n");
		    continue;
		}

		 /* Explicit check for callback existence; log and exit if no callback. */
		if (!duk_is_function(ctx, -1)) {
		    puts("No callback registered\r\n");
		}

		if(t->oneshot){
		    duk_push_null(ctx);
		    duk_put_global_string(ctx, t->name);
		    /* free timer */
		   tx_timer_delete(t->timer);
		   txm_module_object_deallocate(&t->timer);
		   tx_block_release(t);
		}

		rc = duk_pcall(ctx, 0);
		if (rc != 0) {
		    printf("Callback failed: '%s'\r\n", duk_safe_to_string(ctx, -1));
		}

	    	//duk_pop(ctx);

	}
}
```

**Comment by svaarala** [comment]
Ok, I understand re: valgrind, it's often difficult or impossible on limited hardware, and reproducing an error on another target may similarly be difficult.

I guess one important question is why do you want to omit the duk_pop() (which is properly placed) in the first place? Without the pop in place, you are growing the current value stack frame (which exists in the timer loop) without limit.

Some suggestions and questions related to the snippet:

- Could you use a duk_safe_call() to call this timer loop? If that wrapping duk_safe_call() exits, you could then print out an error which may give a hint as to what happens. It seems based on your comments you may have tried this already?
- For debugging you could add a print for `duk_get_top()` at the top of the loop. This would give you an indication whether you are inadvertently growing the value stack. This is a useful technique in general. The expectation is that you'd never be growing the value stack in a loop like this -- otherwise it would potentially grow without bound.
- One useful technique for loops like this is to:
  1. Read the stack top using `duk_get_top()` right before the loop.
  2. Force the value stack top using `duk_set_top()` to that value at the top of the loop. This will handle most value stack push/pop imbalances in a reliable manner, even when some code path inadvertently leaves stuff on the value stack.

You do have a duk_check_stack() in the loop, but it's probably misplaced:
- Suppose duk_check_stack() fails. The code will `continue;` but there is a duk_get_global_string() right before the check (and the following `continue;`), which will remain forever on the value stack. If the situation repeats (which is likely), you will still keep pushing values on the stack, eventually leading to an uncaught error.

It may be better to use a wrapping duk_safe_call() for the entire timer loop, and a `duk_require_stack()` call. If you fail to allocate value stack for callback handling, is there a sane way to continue? If not, `duk_require_stack()` (which throws on failure to allocate) would seem correct, and the code in the duk_safe_call() error path should do something like log an error and reboot.

**Comment by noomio** [comment]
Hi,

Well I don't want to omit it but during development I did by mistake and I couldn't figure out what was going on. The timer has expired at the time of duk_pcall so there isnt really a timer loop and I'm jumping back to javascript code. I want to be able to catch such errors if they happen for whatever reason.

I shall try what you are suggesting.

```
/*
	One shot timer
*/
duk_ret_t native_set_timeout(duk_context *ctx) {
    long timeout;

    duk_require_function(ctx, 0);
    timeout = (long) duk_require_uint(ctx, 1);

	timer_store_t *t = NULL;

	if(tx_block_allocate(timer_pool, (VOID **)&t,TX_NO_WAIT) == TX_SUCCESS){
		if(txm_module_object_allocate(&t->timer, sizeof(TX_TIMER)) == TX_SUCCESS){
			snprintf(t->name,TIMERS_NAME_LEN,"_%08X",(uint32_t)t->timer);
			t->ctx = ctx;
			t->oneshot = true;
		    tx_timer_create(t->timer,t->name,native_invoke_timer_cb, (uint32_t)t, (timeout*TX_TIMER_TICKS_PER_SECOND)/1000, 0,TX_AUTO_ACTIVATE);

		    duk_dup(ctx, 0);
		    duk_put_global_string(ctx, t->name);
		}else{
			tx_block_release((VOID **)&t);
		}
	}

    return 0; /* no return value (= undefined) */
}

void native_invoke_timer_cb(ULONG arg) {
	void *ptr = (void*)arg;
	tx_queue_send(timer_queue, &ptr, TX_NO_WAIT);
}


// Thread loop
for(;;){

	if(tx_queue_receive(timer_queue, &ptr, TX_WAIT_FOREVER) == TX_SUCCESS){
 		timer_store_t *t = (timer_store_t *)ptr;
 		
                if(t == NULL)
 			continue;

		duk_int_t rc;
		duk_context *ctx = t->ctx;

	        /* Get current callback. */
		duk_get_global_string(ctx, t->name);
		
		if (!duk_check_stack(ctx, 1)) {
		    /* return 'undefined' if cannot allocate space */
		    printf("failed to reserve enough stack space\r\n");
		    continue;
		}

		 /* Explicit check for callback existence; log and exit if no callback. */
		if (!duk_is_function(ctx, -1)) {
		    puts("No callback registered\r\n");
		}

		if(t->oneshot){
		    duk_push_null(ctx);
		    duk_put_global_string(ctx, t->name);
		    /* free timer */
		   tx_timer_delete(t->timer);
		   txm_module_object_deallocate(&t->timer);
		   tx_block_release(t);
		}

		rc = duk_pcall(ctx, 0);
		if (rc != 0) {
		    printf("Callback failed: '%s'\r\n", duk_safe_to_string(ctx, -1));
		}

	    	//duk_pop(ctx);

	}
}

```

**Comment by noomio** [comment]
Hi,

I added the stack check and it seems that there is enough stack to allocate and as you can see from the image attached only 6 values are in the stack and then it fails.



```
			duk_idx_t nargs = duk_get_top(ctx);  /* number or arguments */
			printf("stack top is %ld\r\n", (long) nargs);

		    /* Get current callback. */
		    duk_get_global_string(ctx, t->name);

			if (!duk_check_stack(ctx, nargs * 3)) {
			    /* return 'undefined' if cannot allocate space */
			    printf("failed to reserve enough stack space\r\n");		
			    duk_set_top(ctx, -1);     
			    continue;
			}

		    /* Explicit check for callback existence; log and exit if no callback. */
		    if (!duk_is_function(ctx, -1)) {
		        puts("No callback registered\r\n");
		        duk_set_top(ctx, -1); 
			    continue;
		    }
```

![dead](https://user-images.githubusercontent.com/51944940/59758061-68c36700-92d0-11e9-9f68-fa6c1644b8ac.PNG)

**Comment by svaarala** [comment]
Regarding duk_set_top(), I did not mean using duk_set_top(ctx, -1) which is the same as duk_pop(). Rather, a structure like:

```
duk_idx_t top_at_entry = duk_get_top(ctx);
for (;;) {
    /* Dispatch loop. Reset value stack. */
    duk_set_top(ctx, top_at_entry);

    /* Wait and dispatch a message... */
}
```

This loop structure ensures that regardless of what you do with the value stack for a single message, it gets reset to the entry state at the top of the loop.

**Comment by svaarala** [comment]
Can you provide any more information about what it means that the program fails?
- Do you have a Duktape fatal error handler set? If not, set one: https://wiki.duktape.org/howtofatalerrors.
- Can you run with assertions enabled (DUK_USE_ASSERTIONS)?

**Comment by noomio** [comment]
Hi,

Thank you for you time. 

1. Yes I do have a fatal handler
2. I have tried to use assert but nothing can catch it. 

When I mean it fails it looks like a hard fault because of a bad pointer. I cant catch this myself as its abstracted from the application (the fault handler). The app goes to a cyclic reboot,run,hard fault,reboot...

Once the script is executed 2 callbacks are registered and the timers are started (no timer loop). The timers are from the os and when they expire they call the registered callback, I then post a message to my timer task handler to call the script function i.e setTimeout or setInterval accordingly.

I'm just concerned at the stack corruption and why it happens.

See snippet, you can see that when updating the value it corrupts (callback function).
![dead](https://user-images.githubusercontent.com/51944940/59806303-3dc02e00-9337-11e9-9705-f196ffa4fb06.PNG)

**Comment by svaarala** [comment]
Hmm, there's unfortunately not much I can say with certainty, based on the log alone.

Based on the log it's unfortunately probably not just value stack corruption. The lower circled value (thr pointer) is a pointer value formatted using `%p`. Even if the pointer itself was bogus, it should still format as a proper pointer, i.e. a hex value.

**Comment by noomio** [comment]
Ok,

I shall leave it to that. I will just make sure I pop.

Thanks, great work!

**Comment by svaarala** [comment]
Let me know if you figure the root cause out :o

**Comment by noomio** [comment]
Hi,

The culprit was the good old printf...
I used a small lib and forced it use that one. It all works well now even if I leave pop_ctx out.

Nikolas

**Comment by svaarala** [comment]
Ok, not the first candidate, but that's how it often goes :)

By the way, there's a minimal (< 1kB) printf() here too https://github.com/svaarala/duktape/tree/master/extras/minimal-printf.
