### ISSUE TITLE
Does Duktape run on Apple Watch 2.0

### ISSUE THREAD

**Issue by ingo** [svaarala/duktape#216]
There is a limitation on the system frameworks available in WatchOS 2, taken from the "WatchOS 2 Transition Guide". Does Duktape compile in that environment?

**Comment by svaarala** [comment]
I'm not very familiar with iOS / Apple Watch development, but in general Duktape uses very few platform services to remain portable. The most important dependencies are memory allocation primitives, a few string primitives (like `sprintf`), and a provider for date/time. The split nature of the watch applications are also out of Duktape scope.

Do you have specific concerns in mind? Have you tried what happens if you compile?

**Comment by svaarala** [comment]
@ingo Any news on this?

**Comment by svaarala** [comment]
Closing as inactive - @ingo, reopen if this is still relevant.

**Comment by ingo** [comment]
@svaarala yes, it runs. Thanks!

**Comment by svaarala** [comment]
@ingo Any portability notes or suggestions for Apple Watch? :)

**Comment by ingo** [comment]
Just that we got a proof-of-concept to display some data to the screen in the Watch 2 framework. Others may wish to take that further.

**Comment by svaarala** [comment]
Did you need to change anything, use specific options, or something like that?

**Comment by ingo** [comment]
I don't have that information as a co-worker did the test, but it did not take much time (few hours) to tweak whatever was necessary.
