### ISSUE TITLE
Use Strict with Multiple Evaluations

### ISSUE THREAD

**Issue by jessedoyle** [svaarala/duktape#2186]
We recently ran into an issue when using the `use strict` directive with multiple calls to `duk_peval`.

For example consider the code below:

```c
#include "duktape.h"
#include <stdio.h>

int main(int argc, char *argv[]) {
  duk_context *ctx;
  const char *res;
  duk_int_t rc;

  ctx = duk_create_heap_default();
  duk_push_string(ctx, "\"use strict\";\n function test(arg){return arg;}");
  duk_peval(ctx);
  duk_push_string(ctx, "test(1);");
  rc = duk_peval(ctx);
  if (rc != 0) {
    duk_safe_to_stacktrace(ctx, -1);
  } else {
    duk_safe_to_string(ctx, -1);
  }
  res = duk_get_string(ctx, -1);
  printf("%s\n", res ? res : "null");
  duk_pop(ctx);
  duk_destroy_heap(ctx);

  return 0;
}
```

prints the following:

```
ReferenceError: identifier 'test' undefined
    at [anon] (duktape.c:81734) internal
    at eval (eval:1) preventsyield
```

So, it looks like the `use strict` directive prevents access to functions or variables defined for a subsequent `duk_peval` call.

I'm not that familiar with the ECMAScript spec - is this behaviour intentional? 

The issue was first noticed [here](https://github.com/jessedoyle/duktape.cr/issues/53) and we're using Duktape 2.4.0.

Thanks!

**Comment by svaarala** [comment]
Declarations in strict eval code are established in a temporary local scope rather than in the global object. For example, simulating the case on Node.js (Duktape behavior is the same):
```
> eval('"use strict"; function test(arg) { return arg; }')
'use strict'
> typeof test
'undefined'
```

Versus non-strict eval:
```
> eval('function test(arg) { return arg; }')
undefined
> typeof test
'function'
```

Note that ECMAScript differentiates between "program code" and "eval code". Strict program code declarations are established in the global object. So, I think you could use duk_pcompile() (in program mode, the default without any flags) + duk_pcall() instead of duk_peval() to avoid the strict eval semantics.

**Comment by jessedoyle** [comment]
@svaarala - Thanks very much for the clarification - that makes sense!

This issue can be closed - thanks!
