### ISSUE TITLE
Tick/stepping of execution

### ISSUE THREAD

**Issue by dazhbog** [svaarala/duktape#2214]
Hi,

I am running Duk on a microcontroller and I was wondering if there is a way to step the execution of JS from C.

For example lets say the Javascript is busy going around in a loop like while(1), could the C program dictate the speed of execution or do other things in a round-robin loop? Like, instead of

```
  duk_eval_string(ctx, code); //blocking C
```

we could have

```
duk_eval_tick(ctx, code, N) // load code and tick once (run N bytecodes)
while(1){
  duk_next_tick(ctx, code, N); // process next N bytecodes
  // Do other things here, like handle Bluetooth, I/O, sleep, etc.
}
```

I have tried yield and suspend. If I am correct, yield is only for the JS land, to jump between JS threads. 

Suspend works, but it needs the JS to be written in a way where it will call C handlers for suspension. In our case customers write the JS code, so we cannot guarantee they will be placing yields and suspends in the right places.

Similar issue https://github.com/svaarala/duktape/issues/90#issuecomment-70165648

Hope I'm making sense, and looking forward to your ideas. Thanks.

**Comment by noomio** [comment]
Cant you just run this in a thread?
All the other tasks are running in the background handling I/O etc.

**Comment by dazhbog** [comment]
By thread you mean like an RTOS thread/task? 

Yes, but it would be lovely to run this in non-RTOS codebases. But even in RTOS cases you still don't have control of the JS execution. Maybe you want to sleep 250ms and then execute a bit of JS then you go to sleep again. Currently I don't see a way if the JS code has a _while(1)_ loop. 

The only way to make this work is to make sure the JS script behaves like a lamda function. It gets called when something occurs or in an interval dictated by C. If the customer supplies code that has a loop, we kill the execution with the timeout feature (didn't test yet but saw that its possible in duk).

If you are talking about a different type of thread please give me some more context, thanks!

**Comment by noomio** [comment]
The same thing would happen if a C calling function had a while loop or anything else written is C is blocking. In bare metal you write non blocking code and that should be done also for your javascript code. I don't think you have many options without an OS.

**Comment by dazhbog** [comment]
Just found #1637 too.

@svaarala  Is this something that you think we should have more discussion on? Shall we merge this issue and #90 with #1637. For example I found #90 from Google and didn't even see #1637 until now.

You have some questions on the issue #1637, where shall we put our suggestions or thoughts? On that issue or some place else?

**Comment by svaarala** [comment]
Sorry for the delay -- on a concept level letting the user code step bytecode N steps at a time would be quite similar to interrupting every N steps. However, it would be a more difficult API because bytecode execution may involve native recursion so one can't nicely do that from a single call site without managing native stack switching. With interrupts the native stack can grow and shrink between interrupt calls.

So a user-visible interrupt would make most sense to me. Technically it's not difficult and has been proof-of-concept tested already, but there are various design issues listed in #1637. We can try to progress this in master for Duktape 3.0, #1637 is a good place for this discussion, so I'll close this now.
