### ISSUE TITLE
Double debugger Status notification messages sent

### ISSUE THREAD

**Issue by dzzie** [svaarala/duktape#224]
I have noticed that when single stepping I am getting a 2 notification messages
one right after the other.

once with lastline=curline (lastline saved from last notify)

```C
duk_debugger.c
   duk_debug_process_messages
	if (thr->heap->dbg_state_dirty) {
		/* Executed something that may have affected status,
		 * resend.
		 */
[1]		duk_debug_send_status(thr);          
                thr->heap->dbg_state_dirty = 0;
```

and then again with the line number advanced..

```C
duk_js_executor.c
   duk__interrupt_handle_debugger

	if (thr->heap->dbg_state_dirty || thr->heap->dbg_paused) {
		send_status = 1;

	if (thr->heap->dbg_exec_counter - thr->heap->dbg_last_counter >= DUK_HEAP_DBG_RATELIMIT_OPCODES) {
		if (diff_last < 0.0 || diff_last >= (duk_double_t) DUK_HEAP_DBG_RATELIMIT_MILLISECS) {
[2]			send_status = 1;      

	if (send_status) {
		duk_debug_send_status(thr);
		thr->heap->dbg_state_dirty = 0;
	}
```

since the thr->heap->dbg_state_dirty check is the same. 
I tried commenting out the whole if block in [1]

I still ended up getting two notifications with the same attributes now both from 
duk__interrupt_handle_debugger

commenting out line [1] fixes it when single stepping

but now when stepping over a function call you still get two

to remove this second double notification i commented out [2]

that seems to have fixed it in both cases. I have not noticed any side effects 
in testing yet but I dont know all the use scenarios. 

normally these double messages would be beign but there are some cases where 
they would be problematic such as when implementing a run trace. 

This came to light when trying to implement some automated stepping logic.

**Comment by svaarala** [comment]
There's currently no guarantee that extra Status notifications are never sent.

I can try to see if guaranteeing this (with some semantics, not sure which) would be easy to do - and maintain in the future.

**Comment by svaarala** [comment]
As an example of semantics issues: if the semantics chosen were that only one Status notification would be sent for one interrupt (corresponding to 1 bytecode instruction for stepping), when should the Status be sent?

If it's sent right before the debugger message loop, any changes made by debug messages would not show up in a Status until next interrupt. When not single stepping, this can be some time (seconds).

If it's sent right after the debugger message loop, then a debugger UI will see an old Status when it's executing messages. This is especially annoying when in a paused state, so that we won't proceed until the message loop is complete.

There are many other options to choose from but it's somewhat of a compromise. So for now, Status is sent whenever something interesting happens (or may have happened) and there's no 1:1 correspondence with stepping or interrupts.

**Comment by dzzie** [comment]
ok thanks. I will keep experimenting and see what works for my scenario. Wasnt sure if it was a bug or a nuance but figured it was worth logging in case someone else ran into it.

**Comment by svaarala** [comment]
Ok - to be clear, changing the guarantee is also an option, as long as there's a clear guarantee that's also easy to implement and maintain :)

**Comment by dzzie** [comment]
based on this discussion I realized a simple solution. I was paying to close attention to the notification messages and trying to use them for ui updates. 

This behavior has no effect if you just log the last notification and then do UI updates just before you go into your read blocking loop waiting for user input. 

That way you only process the last one received which is the right one to observe. Sorry for the confusion I misread the intent of notify message.
