### ISSUE TITLE
LICENSE text

### ISSUE THREAD

**Issue by SheetJSDev** [svaarala/duktape#2295]
GitHub does some sort of license text matching when determining a project license.  As an example, VueJS is MIT licensed and it is displayed in the project bar:

<img width="993" alt="vuejs_bar" src="https://user-images.githubusercontent.com/6070939/80934433-27c42c00-8d96-11ea-86a6-4b643ce1673f.png">

Duktape is not currently detected as MIT by GitHub:

<img width="993" alt="duktape_bar" src="https://user-images.githubusercontent.com/6070939/80934392-fa777e00-8d95-11ea-8400-6d94098fa42d.png">

This is probably due to the license file containing extra text.  To get GH to recognize the project, it seems that you have to remove the header.  Following VueJS, the license header should just be

```
The MIT License (MIT)

Copyright (c) 2013-present, Duktape authors
```

**Comment by wenq1** [comment]
Duktape uses the "Duktape license", as is in the first (technically second) line in the license file. If GitHub doesn't know how to read and/or write, it should go to school or better get some AI.

**Comment by svaarala** [comment]
The intent is quite plainly to use the MIT license and not a variant of it. The fifth line attempts to make that clear by linking: https://github.com/svaarala/duktape/blob/master/LICENSE.txt#L5. The license file has a heading saying "Duktape license" just to make it clear this file is part of the Duktape repository/distribution (which might not be a good idea because it may confuse more than it clarifies).

I can try what happens if I remove the Duktape license heading - if that fixes the issue, it would be the easiest change because the existing text would not be affected.

**Comment by wenq1** [comment]
I don't think you should change that. It's GH doesn't know how to parse the text of a license file, it's entirely GH's problem.
