### ISSUE TITLE
Duktape event loop and mobile app

### ISSUE THREAD

**Issue by jm4906** [svaarala/duktape#2298]
I'm trying to use the Duktape Event Loop example (https://github.com/svaarala/duktape/tree/master/examples/eventloop) inside a mobile app, so that I can execute things like `setTimeout`, etc. The problem is that, as I understand, JS is single threaded and that's why I run Duktape from the main thread of the mobile app. If I just run Duktape's event loop after a script has finished execution, then the mobile app's main thread gets blocked and there's no possibility of doing scroll, etc. Worse still, if I run `setInterval` then the mobile app deadlocks forever.

So I assume I'd need some way to "handle" the existence of the mobile OS main loop and duktape's event loop, but I'm not sure how to make them cooperate better. I don't know if using Duktape's event loop is a good idea or if the mobile OS event loop should execute the timed JS functions instead (how could I do that?). I'm very new to event loops and JS.

What alternatives do I have to achieve this with Duktape? Thank you.

**Comment by svaarala** [comment]
It's a bit difficult to give concrete advice without knowing the specifics, but I'll try my best :)

From a high level point of view, core Duktape doesn't require or enforce any particular style of event loop. You're free to use any kind of event loop, and call into Duktape from that. There are no assumptions beyond this, except that calls into Duktape don't themselves block, i.e. they are typical event handlers.

This approach has been taken because an embeddable engine should (in my opinion at least) make minimum demands of the application it is being embedded into. Things like event loops, memory allocators, etc, should be provided by the application.

The event loop example is just one concrete example of how you can integrate timers and waiting for file descriptors in a typical select/poll loop. It's intended to illustrate especially how the timer and socket state, including script callbacks, can be managed. It's not part of Duktape itself in any way.

You can use the same approach (and even keep most of the data structures) but swap out the main event loop, i.e. the place where we poll() with a timeout. The mobile OS event loop should probably take that role in your case.

**Comment by jm4906** [comment]
Thanks, I'll see how can I add timers for the mobile OS event loop from C/C++. I have a question about the sample code. In my implementation I do something like this:

```
duk_peval_string(ctx, script);
duk_safe_call(ctx, eventloop_run, NULL, 0 /*nargs*/, 1 /*nrets*/);
```

That is, first I run the script, and then invoke the event loop function, which will terminate immediately if there's no work to do.

But I see in the example

```
duk_eval_string(ctx, "setTimeout(function() { _USERCODE(); }, 0);");
...
duk_safe_call(ctx, eventloop_run, NULL, 0 /*nargs*/, 1 /*nrets*/);
```

That is, the code is invoked inside an immediate `setTimeout` and then the even loop runs. The example solution seems more elegant, but is there any other difference in both approaches? Also, the sample also runs `duk_compile` beforehand. Does `duk_compile` compile the code into bytecode so that it runs faster, right? I assume `duk_peval_string` interprets the code, which will be slower.

**Comment by svaarala** [comment]
Re: running the script with a zero timer, I don't recall the details exactly. Running the main script from inside the event loop minimizes differences between running the script and running event callbacks. For example, the event loop may do some state initialization before it actually runs any callbacks, and some calls (like further setTimeout() calls, socket calls, whatever) might fail before that initialization part is complete. Often that can be avoided by just carefully doing those initializations before running the user script.

Re: duk_compile() and its variants, it compiles a source text into an anonymous function ready to be executed, with the function code itself being in a bytecode representation. The duk_eval() call, and its variants, in essence just combine duk_compile() and duk_call().

**Comment by svaarala** [comment]
Closing now, let me know if this wasn't resolved.
