### ISSUE TITLE
A way to redirect stdout and stderr to a callback

### ISSUE THREAD

**Issue by matwachich** [svaarala/duktape#23]
Hello! Thank you for this great lib!

What do you think of making all data outputed from print, alert and error handlers be redirected to a user-defined callback?

It will be something like: void outputCallback (duk_context* ctx, const char* data, size_t data_size, int data_type, void* user_data)

Thanks

**Comment by svaarala** [comment]
This is addressed for the most part by #64 which provides a supported way to remap all fwrite(), printf(), etc calls.

**Comment by svaarala** [comment]
With #64 you can edit `duk_config.h` and replace `DUK_PRINTF()`, `DUK_FPRINTF()`, etc. Duktape doesn't contain plain calls to `printf()`, `fprintf()`, etc so this should provide you complete control over output to stdout/stderr. But this is not very convenient because some writes to stdout/stderr happen using DUK_PRINTF/DUK_FPRINTF, while others go through DUK_FWRITE.

So this probably needs a better solution still.

**Comment by svaarala** [comment]
With Duktape 2.x this is no longer an issue: core Duktape API doesn't have any file I/O dependencies. Debug prints are handled via a user macro (so that it can be targeted as the application prefers. As a result `duk_config.h` no longer has `DUK_FPRINTF()`, etc.
