### ISSUE TITLE
Callbacks and thread safety

### ISSUE THREAD

**Issue by TomMettam** [svaarala/duktape#2306]
Hi there.

I'm using Duktape in a threaded environment where multiple contexts may be operating at one time. In almost all cases this is no problem, and I can avoid corruption of the stack through multiple calls on the same thread, however I have a problem in one particular case..

When a C function call arrives, I have no way of locking the context so the user can't issue any other commands, without doing this immediately:

```
duk_push_current_function(ctx);
duk_get_prop_string(ctx, -1, "context");
void* ptr = duk_get_pointer(ctx, -1);
duk_pop(ctx);
// Now I have the pointer I need to be thread-safe
```

My concern is that there is a small window here where a user might call eval() or something on the same context and corrupt the stack. Is there another way to associate a pointer with a C callback in a thread safe way?

**Comment by svaarala** [comment]
There are absolutely no guarantees what happens if multiple threads call into Duktape. You would need to surround the code with e.g. a mutex.

**Comment by TomMettam** [comment]
But I can't do that without also mutexing all of the other contexts, because I don't know which context is calling the function.  Is it possible that you might consider allowing association of a "userData" pointer with duk_push_c_function which is then provided in the function call?

**Comment by thradams** [comment]
I am using duktape in a very concurrent environment.
I use something like actor model without visible/managed mutexes. There is
only one actor that can acess duktape.
Everthing else like callbacks are events (messages) to this actor.
This is my suggestion.

**Comment by svaarala** [comment]
@TomMettam I'm not sure I fully understand your scenario, but I'll try to describe it:
- You run multiple Duktape heaps in a concurrent environment.
- Each Duktape heap gets callbacks to the same native Duktape/C function, i.e. it is registered in multiple heaps.
- You can use a mutex to guarantee that a single thread operates a Duktape heap, but you would like to use a per-heap mutex rather than a global one, even for a very short period of time.

Does this sound correct?

If so, a simple but a bit awkward solution would be simply to track the Duktape context pointers created, and associate them with a mutex. A Duktape context pointer is returned from heap creation, and when creating new Duktape threads. That pointer is stable for the lifetime of the context. Note that the `ctx` you get as a Duktape/C argument already identifies the specific Duktape thread (and heap) used for the call but it's an opaque pointer to the calling application.

Another possible solution would be to call `duk_get_memory_function()` which is (in practice, though not explicitly guaranteed) thread safe because it just reads fields from the heap structure. In particular, you could maybe use the heap `userdata` pointer to identify the right mutex to use.

**Comment by TomMettam** [comment]
Thanks, got this solved.

**Comment by svaarala** [comment]
:+1:
