### ISSUE TITLE
Debug protocol: Under what circumstance is a flush triggered?

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#233]
Can I assume that if a flush is triggered, that I have at least one full message available?  The streaming setup is difficult to work with because Duktape is allowed to write partial messages, forcing constant trial parses (as mentioned in the documentation, you can't just blindly scan for an EOM byte), which is inefficient and tedious.

**Comment by svaarala** [comment]
The documented guarantee is weak: a write flush simply suggests that it's a good idea to coalesce current writes and send the data out; the abstraction is intended to model a typical stream (like TCP) which has no message boundary information. The current implementation does this after every EOM (and only after every EOM) though. (It'd be better to call EOM only for the last message if multiple messages are written, but the debugger code doesn't yet do that.)

The only case where a write flush without a full message would be useful is when a debug message needed to be sent in pieces, so that we'd first send some part of it and then needed to wait for something to happen before sending out the rest. In this case we'd want to write flush before waiting so that the pending data was send out as early as possible. However, I don't see a realistic case where this would actually be useful, because it'd be awkward for the outbound debug connection to be "blocked" by an incomplete message: there are no facilities for queueing etc (which is quite intentional).

If write flush semantics were changed to guarantee one or more full messages, I'd rather rename the callback to indicate it's not a standard stream flush but rather related to message boundaries which departs from a typical stream abstraction.

Note that a EOM / full message callback is not helpful to a remote TCP debug client. TCP may get resegmented and there's no guarantee of receiving full messages, so a remote TCP client will need to do ordinary stateful parsing (or trial parsing) anyway.

**Comment by svaarala** [comment]
With respect to parsing, for me the natural implementation would be to trial parse incoming dvalues from the data stream. That's quite a bit easier than trial parsing entire messages, but I can see why parsing full messages might be nicer.

Another option is a standard stateful parser (i.e. a state machine) which can resume parsing on incoming data at arbitary byte boundaries. But because the dvalues are quite simple, trial parsing them individually is the easiest approach IMO.

**Comment by fatcerberus** [comment]
The main reason I ask is because I wanted to implement a proxy on the native side so that my actual debug protocol is text-based (so the client can just scan for LFs) and only the native code sees the binary commands.  It would of course greatly simplify the translation layer if I had some guarantee ahead of time that I was getting a full message, to avoid extra buffering and other complexities.

I try for elegant code when I can. :)  If it's not possible that's fine, but I want to make sure I'm not missing something obvious.

**Comment by fatcerberus** [comment]
By the way, I am aware of the JSON proxy. It's just I wanted to implement something even simpler, a message format that can be parsed just by splitting a message at word boundaries (like a Unix shell).

**Comment by fatcerberus** [comment]
@svaarala 
So just to be clear, at least in current Duktape builds, assuming I'm buffering writes, I can safely assume I have a full message available when the write flush callback is run?  I accept the responsibility if this behavior changes, of course. :)

**Comment by svaarala** [comment]
Yes, right now the only place where a write flush is sent is:

https://github.com/svaarala/duktape/blob/master/src/duk_debugger.c#L774-L783

So it always coincides with an EOM at the moment.

**Comment by fatcerberus** [comment]
You know, I'm probably an idiot for not realizing this before, but I've been going about this all wrong.  NFY, REQ, etc. are themselves valid dvalues.  So how I should have approached this was in terms of an array of dvalues, which as you said are easy to parse individually.  Looking at it that way, a whole message can be picked out by looking at the "dvalue-array" and scanning for an EOM dvalue.  Unlike looking at individual bytes, at this higher level such a scan is unambiguous.

Of course I only realized this when I started implementing a (binary) client in C#.  Programming in C tends to make you look at everything at the byte level.  As they say, "When all you have is a hammer..."

**Comment by svaarala** [comment]
That dvalue-array approach is used by the duk_debug.js example client: https://github.com/svaarala/duktape/blob/master/debugger/duk_debug.js#L601-L774

One change in the binary protocol would be to make each dvalue length-prefixed so that they could be skipped without knowing the dvalue type. The downside of this is that dvalues would be much larger. This wouldn't really matter except for e.g. serial links, and except for very low memory targets, a compressed transport could be used there. This is something to consider when a binary incompatible change is made to the debugger protocol at some point.

Length-prefixing full messages would be difficult because the whole approach is based on streaming out messages without constructing a full message in memory, so I don't really see a way around that.

**Comment by fatcerberus** [comment]
One thing I noticed when reading the documentation is that there are quite a few "reserved" dvalue IBs.  Unfortunately with the current system, adding new dvalue types still breaks compatibility because existing clients won't know how the parse the new values.  So adding a length prefix would definitely be useful in that case.

**Comment by svaarala** [comment]
Yeah, that's exactly why length prefixing would be nice - but the downside is that the length would need to be 4 bytes (or more) so it'd have a relatively large impact (nothing that would matter on desktop hosts etc though).

**Comment by svaarala** [comment]
(Well, the length field could be variable size which wouldn't be that bad.)

**Comment by fatcerberus** [comment]
How would a variable-size length work?  The client would have to have some way of knowing how large the length field is, which requires yet another byte...

**Comment by svaarala** [comment]
I meant a variable-length integer encoding, similar to how UTF-8 codepoints are encoded. In other words, optimize for 1-byte length but provide a way to encode longer lengths.

**Comment by fatcerberus** [comment]
Ah, that makes more sense.  Based on UTF-8 encoding, that would get you a length of 127 before you had to add an additional byte.  And actually, a lot of debug commands would probably probably fit in that space, too.

**Comment by fatcerberus** [comment]
The question here has been adequately answered, so I'm going to close this. :wink:
