### ISSUE TITLE
Programmatically getting stacktrace after error

### ISSUE THREAD

**Issue by len-deuel** [svaarala/duktape#2351]
Trying to get the stacktrace as a sequence of line numbers after a duk_pcall that ends with a duk_error. I found [duk_inspect_callstack_entry](https://duktape.org/api.html#duk_inspect_callstack_entry) but I believe it becomes invalid after the duk_error call, a quick check gets me the line numbers as expected if I do it in a call back to native before the duk_error but not after checking the return value of duk_pcall. I am already using [duk_safe_to_stacktrace](https://duktape.org/api.html#duk_safe_to_stacktrace) to get the stacktrace as a string, is my best option to parse that? Or am I missing a way to programmatically access line numbers / file names after the error is generated?

**Comment by svaarala** [comment]
The way stack traces work by default:
- When an error is thrown, a stack trace is internally captured into an array containing version dependent internal data (concretely it contains function and line references). This data is stored as a hidden Symbol ("internal property") of the Error instance.
- Error.prototype contains a `.stack` accessor which formats this internal data into a string on the fly. The result is a string with no guaranteed format.

Your options are roughly:
- Parse the `.stack` string to extract line numbers. This is a bit version specific but should be otherwise simple.
- Inspect the internal "tracedata" property, and interpret its contents. This is definitely version specific, and accessing internal properties is not ideal.
- Register a `Duktape.errCreate` callback and gather the stack trace yourself. In this callback you would be able to use `duk_inspect_callstack_entry()` to get the file/line information. You'd then store it in the Error for later use.
