### ISSUE TITLE
Get source code from compiled file

### ISSUE THREAD

**Issue by Halteproblem** [svaarala/duktape#2359]
Hello,

I was wondering if it is possible to get the complete javascript source code of a previously compiled javascript file?

Thank you very much for your help.

**Comment by dazhbog** [comment]
Depends how it was compiled. You need to give us more info.

In any case you can type `strings <binary>` to see if u can find it.

**Comment by Halteproblem** [comment]
It was compiled with `./duk -c test.bin test.js`

**Comment by svaarala** [comment]
There's no existing tooling for this purpose.

The decompilation process would be similar to decompiling C but a little bit easier because opcodes are more restricted and higher level, and some metadata like function names are (sometimes) kept. But to be clear, source code is not stored along with the bytecode, so you would need to proceed from the opcodes.
