### ISSUE TITLE
Add pre-configured low memory source

### ISSUE THREAD

**Issue by no1wudi** [svaarala/duktape#2360]
Hi, I'm trying to integrate Duktape to NuttX, see https://github.com/apache/incubator-nuttx-apps/tree/master/interpreters/duktape.

Now it use the default version, but in a embedded system it's better to use low memory optimization,
we should provide an option that allow user choose the suitable optimization.

Now we download the tarball from GItHub directly, it works fine, if we generate low memory optimized source at compiling phase, the host must have python2 & yaml installed. For NuttX, there is a third party toolchain dependency.

So, can we provide a common pre-configured low memory source in source tree, or provide another tarball link?

**Comment by svaarala** [comment]
There are many useful option configurations and it doesn't really make sense (at least for me) to pre-generate sources for a lot of combinations. There are particularly many potentially useful low memory optimizations which depend on the specifics of the target, so there's no single "low memory configuration" that's obviously right.

In your situation you might want to generate the low memory tarball offline and store the resulting tar/zip for the build phase. For example, you could generate the sources and create a repo hosting the configured sources. This may be nice because you can then use tags to reference releases etc.
