### ISSUE TITLE
Get object contents over debug protocol

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#238]
At present, when returning an object over the debug protocol, Duktape gives you (according to the documentation):

`Class number, pointer length, and pointer data (network endian)`

The class number may be useful in some cases, but the pointer is completely worthless to an out-of-process or remote client.  There doesn't seem to be a way to request an object's contents instead.  Perhaps that could be implemented?

**Comment by svaarala** [comment]
The dvalue for objects includes a pointer so that there's at least some way to differentiate between object references. It may become handy when extending the debug protocol later. It's also something people expect, having worked with C debuggers :)

Sending structured values is (as one would imagine) future work. It's unfortunately not very trivial, because values may be arbitrary graphs, there are getter/setter values with side effects, etc. Garbage collection would need to be frozen for the duration of serialization which may be difficult when working with temporary state needed for serialization (difficult to avoid when serializing an arbitrary draft).

There are many ways to deal with these issues. For example, walking the dvalue could be offloaded to the debug client by defining a few debug commands to read object property keys and values individually when given a `duk_hobject` pointer. The debug client could then walk the object graph to the level it wants to, dealing with the necessary book-keeping (perhaps just a single level of properties would be enough in many cases). This is a bit fragile, becaues if the debug client gave a stale pointer, it could lead to a segfault.

Btw, the `DumpHeap` command is a demonstration how the process works when one simply just dumps the entire Duktape heap in sequence to avoid the need for tracking structures. The serial nature of the debug protocol allows this without side effects ruining the operation, even for very large heaps.

**Comment by fatcerberus** [comment]
Regarding side effects, I like the system Visual Studio uses: it will display all values it can get without mutating the object, and any with potential side effects (e.g. enumerating a collection) have to be explicitly expanded by the user.

**Comment by svaarala** [comment]
This is covered by #358 which has more concrete discussion so I'll close this one.
