### ISSUE TITLE
Build failure for CMake dist build - missing constants/macros

### ISSUE THREAD

**Issue by kphillisjr** [svaarala/duktape#241]
I have ran into a build failure when trying to build the separate source release of duktape on windows.  Currently I only have a few Missing Defines/Macros before the library is able to compile completely.
* Missing Constants:
  * DUK_STRIDX_EXPORTS
  * DUK_STRIDX_ARRAY_BUFFER
  * DUK_STRIDX_DATA_VIEW
  * DUK_STRIDX_INT8_ARRAY
  * DUK_STRIDX_UINT8_ARRAY
  * DUK_STRIDX_UINT8_CLAMPED_ARRAY
  * DUK_STRIDX_INT16_ARRAY
  * DUK_STRIDX_UINT16_ARRAY
  * DUK_STRIDX_INT32_ARRAY
  * DUK_STRIDX_UINT32_ARRAY
  * DUK_STRIDX_FLOAT32_ARRAY
  * DUK_STRIDX_FLOAT64_ARRAY
  * DUK_STRIDX_BYTE_LENGTH
  * DUK_STRIDX_BYTE_OFFSET
  * DUK_STRIDX_BYTES_PER_ELEMENT
* Missing Macros/Functions:
  * DUK_HTHREAD_STRING_BYTE_LENGTH
  * DUK_HTHREAD_STRING_BYTE_OFFSET
  * DUK_HTHREAD_STRING_BYTES_PER_ELEMENT

Also for a quick reference, The non-building code can be found on the following branch ( https://github.com/kphillisjr/duktape/tree/cmake-build )

**Comment by svaarala** [comment]
Could you provide a link to the build log?

One thing that has recently changed is that `duk_config.h` must be in the include path but I'm not sure if that's the problem here.

**Comment by svaarala** [comment]
Ah, I see that you're trying to recreate the "make dist" process in CMake (instead of compiling the end result in CMake).

It might be useful to diff the various artifacts created in the build process when compared to the shell script in Duktape repo. For example, is the set of resulting files the same, is there binary/text diff between the files etc.

**Comment by kphillisjr** [comment]
Yea, and based on what I can figure Out I am launching the tools correctly... Here are the two two commands that should generate the correct built-ins...
```
python src/genbuildparams.py --version=10200 --git-describe=v1.2.0-216-ga9423c5-dirty --out-json=buildparams.json --out-header=src/duk_buildparams.h
python src/genbuiltins.py  --buildinfo=buildparams.json  --initjs-data=src/duk_initjs.js --out-header=src/duk_builtins.h --out-source=src/duk_builtins.c --out-metadata-json=duk_build_meta.json
```
note: I am using the following software to try to build the separated source version of duktape... 
* Windows 7
* Python v2.7.3
* CMake 3.1.0 
* MSVC 2013 (Community Edition )

**Comment by svaarala** [comment]
@kphillisjr Just to be sure, do you get the same error if you just build from the separate sources in the`duktape-1.2.2.tar.xz` distributable?

**Comment by kphillisjr** [comment]
I get no build errors with the separate sources in the duktape-1.2.2.tar.xz distributable. However, it should be noted that there is no python scripts in this package, so I did not generate the required data.

**Comment by svaarala** [comment]
@kphillisjr Hmm, just to be sure, the intended use is for an end user application to just use the pre-built sources in a distributable. You're not intended to build the distributable from the Duktape github repo; but if you did, you'd normally use the Duktape repo Makefile to do that. (I know this is not ideal but maintaining build scripts for multiple platforms in the main repo takes a bit of work because there are multiple scripts in the dist etc.)

Anyway, if the distributable compiles then it's just a matter of figuring out what fails when you replicate the Duktape Makefile "make dist" steps in your CMake setup.

**Comment by kphillisjr** [comment]
I know that the intended package for end user applications is to use the pre-configured sources. However, I am mainly working on adding cmake support to help simplify working on the duktape sources from within windows.

**Comment by svaarala** [comment]
Ok - just beware that the dist process has changed in small ways in each release so it's a bit of a moving target. It'll also need a revamp to properly support truly optional built-ins (which is increasingly necessary for low memory targets).

It might be easier to do what you're trying to do if more of the dist process was encapsulated in the Python utility scripts, instead of being shell commands? That change would be relatively straightforward (and probably necessary for improving the optional built-ins support).

**Comment by kphillisjr** [comment]
I agree. Increased use of Python should help, but what is catching me is that the built-in generation script ( src/genbuiltins.py ) is not properly generating all of the strings from the string generation script ( src/genstrings.py )

**Comment by kphillisjr** [comment]
I figured out what happened. The genbuiltins file did not like being ran out of the source folder. Now my git branch successfully compiles the main duktape library code.

**Comment by svaarala** [comment]
Hmm, I'll add a sanity check so this doesn't bite anyone else.

**Comment by kphillisjr** [comment]
I'll make a pull request for the cmake build system in the next couple of days after I add a few of the existing examples and some documentation on how to use the build system. So far the requirements are as follows...

For Source Distribution:
* CMake 2.8 ( I may make this require 3.x for Sanity purposes )
* Working Compiler toolset. ( On Windows, this just means installing the latest MSVC Community Edition )

For Git Source Builds: ( Add the Following )
* git
* Python 2.7
* PyYAML (Possibly optional, I did add a pregenerated config file for cmake. )

**Comment by svaarala** [comment]
Hmm, I'm a bit hesitant to merge in "official" support for CMake (or other build systems), because it'll be more stuff to keep up-to-date when changes to the dist process are made. But perhaps it's OK if it's explicitly noted as being a secondary build system and kept up-to-date with a small delay.

Another option would be to start rewriting the repo Makefile (which is quite messy) and e.g. start using CMake for the dist process (removing the precious dist process in the process).

**Comment by kphillisjr** [comment]
I believe completely replacing the repo Makefile with cmake is a reasonable option. For the most part as long as the the python scripts do not have modifications to the arguments, there should be no reason to update the CMake scripts. My current code already automatically includes any C sources files in the "src" folder ( for work from git repository ) and src-seperate in distribution releases. ( Just set DUKTAPE_BUILD_SEPARABLE to ON for these releases ).

also as a side note, with decent CMake support most of the developers that use windows can rapidly expand/improve duktape without many hassles.

**Comment by svaarala** [comment]
There are >100 Make targets in the repo Makefile:

```
3883a2e9063b0a5f2705bdac3263577a03913c94.zip      emscriptenduktest
ajduk                                             emscripteninceptiontest
ajdukd                                            emscriptenluatest
ajtcl                                             emscriptenmandeltest
all                                               emscriptentest
alljoyn-js                                        es5-tests.zip
apiprep                                           FlameGraph
apitest                                           flow
big-git-files                                     gccpredefs
bluebird.js                                       issuecount
bluebirdtest                                      jquery-1.11.0.js
checkalign                                        JS-Interpreter
checksetup                                        jsinterpretertest
clangpredefs                                      libduktaped.so.1.0.0
clean                                             libduktape.so.1.0.0
cleanall                                          LiveScript
cloc-1.60.pl                                      lodash
closure-compiler                                  lodashtest
closure-compiler/                                 lua-5.2.3
closuretest                                       lua-5.2.3.tar.gz
coco                                              luajs
codepolicycheck                                   luajstest
codepolicycheckvim                                luajs.zip
coffee-script                                     massif-arcfour
compiler.jar                                      massif-deepmerge
compiler-latest.zip                               massif-helloworld
dist                                              matrix10
dist-iso                                          matrix100
dist-site                                         matrix1000
dist-src                                          matrix10000
doc                                               perftest
dtrace4linux                                      perftestduk
duk                                               perftestduk3
dukd                                              qecmatest
dukd-g++                                          qecmatestd
dukd.raw                                          regfuzz-0.1.tar.gz
dukdscanbuild                                     regfuzztest
dukd.vg                                           runtests/
duk-g++                                           runtestsdeps
duk.O2                                            sax-js
duk.O3                                            site
duk.O4                                            test
duk.raw                                           test262-3883a2e9063b0a5f2705bdac3263577a03913c94
dukscanbuild                                      test262cat
duksizes                                          test262-es5-tests
duktape-releases                                  test262test
duk.vg                                            tidy-site
dukweb.js                                         UglifyJS
dukwebtest                                        UglifyJS2
dump-public                                       underscore
ecmatest                                          underscoretest
ecmatestd                                         xmldoc
emscripten                                        xmldoctest
```

Replacing them all will take some time. Some targets can be removed, some targets will need reworking with upcoming changes (like testing framework update), etc.

Replacing the whole Makefile might be quite a bit of work. But perhaps using CMake for the main dist target?

**Comment by svaarala** [comment]
Btw, I think "make dist" works on Cygwin (or very close to it) on Windows.

I guess what CMake would provide is to make "make dist" work without Cygwin?

**Comment by fatcerberus** [comment]
It would also allow the same build scripts to be used on all platforms where CMake is supported.

**Comment by svaarala** [comment]
CMake and all the other prerequisites (Python and a minifier being the most important).

But,how is that concretely different from supporting all platforms where "make dist" currently works? "make dist" should work on OSX and Linux, and on Windows through Cygwin. (If not, the fixes are easy, because it used to work on all three.) Is needing to use Cygwin the issue?

**Comment by svaarala** [comment]
Considering "make dist" only, it's already just a shell script which invokes Python and the usual shell tools, so it's already easy to run without any Make system:

```
dist:   compiler.jar cloc-1.60.pl
        @make codepolicycheck
        sh util/make_dist.sh --minify closure
```

I think @kphillisjr converted make_dist.sh into CMake rules, so the change was really not just a matter of moving from Make to CMake, but rather from "make + bash + python" to "CMake + python".

But since `make_dist.sh` is really where dist happens, and dist already depends on Python, I'd probably prefer converting `make_dist.sh` to Python. Making a dist package would then be essentially be independent of whatever makefile was used in the top level repo.

**Comment by fatcerberus** [comment]
It's my understanding that anything built on Windows using Cygwin will then require Cygwin to be installed to run.  That might not be an issue though, if `make dist` doesn't create any binaries.

**Comment by svaarala** [comment]
That's right, Cygwin is just needed to provide bash and various Unix shell utilities. Nothing is compiled with it.

**Comment by svaarala** [comment]
There are no Duktape changes to track in this issue - the relevant change is to migrate to CMake, #246.
