### ISSUE TITLE
Syntax error in js make duktape craaaaash

### ISSUE THREAD

**Issue by thepyper** [svaarala/duktape#2433]
Testing the following program make duktape crash:
```

#include <duktape.h>
#include <iostream>

int main()
{
    duk_context *ctx = duk_create_heap_default();
    if (!ctx)
        return -1;

    duk_eval_string(ctx, "{ a:0, }");
    // This line without ugly comma let the program survive: duk_eval_string(ctx, "{ a:0 }");

    std::cerr << "I will survive!!!\n";

    duk_destroy_heap(ctx);

    return 0;
}

```
Problem lies in the evaluated string, it's a somehow malformed object because of
the extra comma. On some json evaluation library they let me insert extra comma, it's handy to have last element with same syntax as previous elements.
Anyway I believe duktape should complain in a less extreme way :)

Tested version is duktape 2.6.0

**Comment by svaarala** [comment]
When you encounter an error with no protected call wrapper, Duktape encounters an "uncaught error" situation which by design causes a fatal error. You should use e.g. `duk_peval_string()` to avoid this. Please see https://duktape.org/guide.html#error-handling.

Please reopen if a protected call doesn't solve the issue.
