### ISSUE TITLE
Object.keys() equivalent for C

### ISSUE THREAD

**Issue by ReneHollander** [svaarala/duktape#249]
I am searching for a way to get all the keys in of an object. For one thing I want to know how many keys are currently stored and for antoher thing I want the actual keys. Am I unable to find the function in the API or is there no such function?

Something else I am curious about is if there is a way to search the key of an object by the value that is associated with it. In the worst case I will loop through all keys and check it.

**Comment by svaarala** [comment]
You can enumerate object keys using http://duktape.org/api.html#duk_enum. It doesn't give you the key count though (it does know the count internally but that's an implementation detail which is not exposed at the moment).

There's unfortunately no easy way to search for keys with a certain value. In the general case it's not possible without looking up the value because some values might be accessors (i.e. getters), but even in the case of a static object there's no "reverse index" for key/value pairs.

**Comment by ReneHollander** [comment]
Thanks for your quick reply!

I will then just count the amount by getting the keys and to search by value I will just loop through the keys and check the value.
