### ISSUE TITLE
Handling of fatal errors with duk_json_decode

### ISSUE THREAD

**Issue by rlaveaux** [svaarala/duktape#289]
Currently Duktape calls abort and exit if a fatal error occurs. For example when duk_json_decode is used with invalid JSON data.

This is not ideal for situations where Duktape is used inside a host application. In such a situation the host application just quits without a chance to inform the user.

Please make errors like duk_json_decode with invalid JSON data recoverable. Excuse me, but I don't see a reason why this should trigger a fatal error. So my proposal would be to inform the calling application that duk_json_decode was unsuccessful and let it deal with the situation.

**Comment by svaarala** [comment]
`duk_json_decode()` follows the same behavior as `JSON.parse()`, i.e. it throws a SyntaxError when the input is not valid.

You can use `duk_safe_call()` to get a protected wrapper around `duk_json_decode()` and any other calls you make.

**Comment by fatcerberus** [comment]
Your top-level call should be protected--`duk_pcall()` or `duk_peval()`.  Otherwise any error thrown in JS has no place to go and will crash the process, as you've seen.  I learned this the hard way myself. :)

Duktape definitely works a bit differently than most JS engines in this regard.  I find it's easiest to work with if you view your native stuff as an extension of the JS environment.  So then the abort becomes intuitive--you crashed because you didn't wrap your JSON decode in a try/catch (i.e. protected call), which would be equally fatal in JS as well.

**Comment by svaarala** [comment]
Duktape uses the same basic model as Lua: errors are handled by doing a longjmp, and that longjmp needs to have some place to go. Adding a longjmp catchpoint to every API call (and having return types indicating what happened etc) would be bad for e.g. performance so if fatal errors are an issue (they aren't for all programs) the first call you make should be one of the protected calls:

- http://duktape.org/api.html#taglist-protected

This is analogous to an Ecmascript program wrapping its main function e.g. as:

```
try {
    mainProgram();
} catch (e) {
    print('main program failed: '  + e);
}
```

instead of bubbling out an unhandled exception.

**Comment by fatcerberus** [comment]
On a sidenote, I've never seen any C program abuse longjmp quite so thoroughly as Duktape does. It's glorious. :stuck_out_tongue_winking_eye:  I have to give credit where it's due, the fact you don't leak a single byte of memory with all that jumping around is nothing short of amazing.

**Comment by svaarala** [comment]
I don't agrea at all with saying "abuse longjmp". It's used precisely for its intended purpose, i.e. long control transfers which are otherwise unsupported in C :-)

**Comment by fatcerberus** [comment]
I know, I was mostly using the word "abuse" in an ironic/joking manner, to point out how deftly it's actually employed. :)

**Comment by svaarala** [comment]
There's some classes of programs where long control transfer is quite useful and unfortunately not well supported (other than longjmp) in portable programs. Many interpreters do that, and do some quite unportable stuff like managing multiple C stacks manually.

The upside of long control transfer is that you don't need to pollute *every function everywhere* with return values indicating an error occurred, and then plumb those error codes around very tediously. The downside is that resource tracking needs to be explicit - for Duktape this is relatively easy to handle as long all temporaries are on the value stack which is automatically memory managed. If that wasn't the case it'd be quite difficult to work with.

**Comment by rlaveaux** [comment]
Thank you for your answer. But I need a bit more assistance on how to use duk_safe_call.

Basically I want to set the value of a global variable. The value is a JSON encoded string. But since this is a user provided string, it could have errors which is why I want to add some error handling on the JSON decoding. 

My current code looks like this:

duk_push_global_object( context );
duk_push_string( context, value.c_str() );
duk_json_decode( context, -1 );
duk_put_prop_string( context, -2, variable.c_str() );
duk_pop( context );

How should I use duk_safe_call in this context?

Thank you.

**Comment by svaarala** [comment]
If you just want to wrap this operation inside a protected call (and not a larger program), it'd look something like:

```
duk_ret_t my_json_decode(duk_context *ctx) {
    duk_json_decode(ctx, -1);
    return 1;  /* result on stack top */
}

/* ... */

duk_int_t rc;

duk_push_global_object(ctx);
duk_push_string(ctx, value.c_str());
rc = duk_safe_call(ctx, my_json_decode, 1 /*nargs*/, 1 /*nrets*/);
if (rc != 0) {
    printf("JSON decode failed: %s\n", duk_safe_to_string(ctx, -1));
    duk_pop_2(ctx);  /* pop global and error */
} else {
    /* success */
    duk_put_prop_string(ctx, -2, variable.c_str());
    duk_pop(ctx);
}
```

This will still abort if e.g. `duk_push_string()` runs out of memory. You could fix that but you'd need to postpone the string pushing to happen inside the safe call.

**Comment by rlaveaux** [comment]
Thank you for the example. I have it working now.

**Comment by svaarala** [comment]
Good to hear :)
