### ISSUE TITLE
Assign name to Duktape/C function

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#292]
It doesn't seem to be possible to make a named Duktape/C function, they are created as anonymous functions, and are indistinguishable in a stack trace.  Is it possible to assign a name to these?

**Comment by svaarala** [comment]
Yes, here's an example: https://github.com/svaarala/duktape/blob/master/tests/api/test-bug-set-cfunc-name.c

**Comment by fatcerberus** [comment]
Ah, so you just set the `name` property of the function, that's easy.  I didn't think that would work because, at least according to ES6, the `name` property of a function instance is non-writable (although for some reason *is* configurable...):

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name

**Comment by svaarala** [comment]
If a function doesn't have a `.name` then there'd be nothing to prevent it from being written though? IIRC ES5.1 doesn't even provide a `name` property so the exact behavior may vary a bit between engines.

Earlier Duktape versions had a `Function.prototype.name` which was non-configurable and non-writable which would prevent introducing a new `.name` property on function instances. That was fixed in later versions so that `Function.prototype.name` is now writable so that it's possible to add a `.name` property (an inherited non-writable property prevents property creation).

With `duk_def_prop()` this could be changed back so that `.name` is always protected (even the inherited one), so that Ecmascript code can't change it, but C code could use `duk_def_prop()` to forcibly set or modify an instance `.name` anyway.

This is a small thing to clean up for ES6.

**Comment by svaarala** [comment]
Added #293 to track that ES6 related change - was your original issue resolved? :)

**Comment by fatcerberus** [comment]
Yes, setting name on the Duktape/C function instance worked great, now I can see the MapEngine() (main game loop) call in the debugger callstack. :)
