### ISSUE TITLE
How to get real function body using function.toString()? 

### ISSUE THREAD

**Issue by stoobie** [svaarala/duktape#352]
I'm trying to execute some javascript that was generated using Emscripten and uses tostring on a function. However, when tostring() is called on the function it is returned a string that looks like:

```javascript
function anon() { /* ecmascript */ }
```

I've seen the c function that is called by tostring is `duk_bi_function_prototype_to_string` in `duk_bi_function.c`, and that there's a comment that says there aren't many requirements from Ecmascript 5 to support this, so I'm guessing this might be by design.

But just incase I'm wrong ... Is this by design .. or is there something I can enable that will return the real function body instead? 

If not, any suggestions on how I could go about implementing this functionality?

**Comment by svaarala** [comment]
It is by design. Providing the source code in `.toString()` has a significant memory footprint and has limited use (for other than debugging) because it's not guaranteed to be equivalent to the function being executed. For example:

- The source code doesn't provide any information about the scope where the function was compiled so if you compile the source you'll get back a logically different function.
- If the function is declared in a strict parent function, it will inherit that strictness but that won't be reflected in the original source text of the function. A virtual `"use strict"` directive could be inserted to fix this.

For debugging a `.source` property would be useful so that the debug client didn't need to have a copy of the source being executed. It'd also allow dynamically created function (and maybe even eval code) to be debugged with source.

If you wanted to add support for a source property, you could:

- Modify the compiler to store the source in a `.source` property.
- Also modify `Function` constructor so that it could create a fake source for functions created using e.g. `new Function('x', 'y', 'return x+y'`) which is equivalent to `function (x,y) { return x+y; }`. This might work directly because the current Function constructor implementation is to build that equivalent function for compilation.
- Modify `Function.prototype.toString()` to use `.source` if it exists, and perhaps return the current result if `.source` is missing as a fallback.
- If bytecode dump/load support matters, `.source` should also be dumped and loaded back.

**Comment by stoobie** [comment]
Thanks for the info... 

In the end, I managed to work around the issue by removing the tostring() calls and tackling the problem in a different way entirely. As you suggested, it isn't consistent that this functionality is available or should work, so it's probably best that I don't depend on it.

I'm still getting to know the duktape code base, as I'm pretty new to the project. But once I'm more clued up, I may have a go at implementing it.
