### ISSUE TITLE
#define DUK_USE_TARGET_INFO in duk_custom.h causes macro redefinition error

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#361]
So I recently discovered `duk_custom.h`, which is a lifesaver with me constantly testing out different branches, etc. as my config customizations don't get overwritten.  Everything mostly works okay, except for one issue: defining DUK_USE_TARGET_INFO results in warnings.

Here's my duk_custom.h:
```c
#include "version.h"

#define DUK_OPT_FASTINT

#ifndef MINISPHERE_REDIST
#define DUK_USE_TARGET_INFO ENGINE_NAME
#define DUK_USE_DEBUGGER_SUPPORT
#define DUK_USE_DEBUGGER_FWD_PRINTALERT
#define DUK_USE_DEBUGGER_PAUSE_UNCAUGHT
#define DUK_USE_INTERRUPT_COUNTER
#endif
```

And here's the warning this generates:
```
1>d:\src\minisphere\src\duk_custom.h(6): warning C4005: 'DUK_USE_TARGET_INFO': macro redefinition (compiling source file ..\src\vector.c)
1>  d:\src\minisphere\src\duk_config.h(2256): note: see previous definition of 'DUK_USE_TARGET_INFO' (compiling source file ..\src\vector.c)
```

I can of course #undef the macro first, but that seems a bit awkward, and since the rest of the DUK_USE_ directives don't cause similar warnings, I'm going to assume this is a bug.

**Comment by svaarala** [comment]
It's not actually a bug - you'd have the same issue for any `DUK_USE_xxx` define whose default was not "undefined" so that it'd get defined before `duk_custom.h` was included.

So the best idiom to undefine is (of course):

```
#undef DUK_USE_UNWANTED_FEATURE
```

and the best idiom to re-define is:

```
#undef DUK_USE_FOO_DEPTH
#define DUK_USE_FOO_DEPTH 123
```

For most options there is no value so this just becomes:

```
#undef DUK_USE_WANTED_FEATURE
#define DUK_USE_WANTED_FEATURE
```

which looks odd but if you don't want the header to be dependent on the (current) default, this is needed.

`duk_custom.h` as it is now (included using `DUK_OPT_HAVE_CUSTOM_H`) will be removed along with `DUK_OPT_xxx` options in general. You'll then have two options:

- Move to using YAML files for overrides (I find them much cleaner than C headers). With them that #undef/#define behavior is automatic.
- Keep using a custom header, but instead of it being included at Duktape compilation time, it is given as an argument to `genconfig` which will embed it into `duk_config.h`. The end result is the same, but it's all contained in `duk_config.h`.

I'd personally prefer the YAML route, but I can understand why you might want to work with header overrides too. This Wiki page is intended to provide the concrete best practices so feel free to suggest improvements there too:

- http://wiki.duktape.org/Configuring.html

**Comment by fatcerberus** [comment]
The main thing is that it's a pain to have to invoke genconfig every time I upgrade Duktape (in case some new config option was added, etc.), having a custom header with only Duktape options means I can just drop the files from "make dist" right in without having to change anything, and then I get the same feature options on all supported platforms without having to modify any build scripts.  I guess I could make a shell script to do "make clean dist" -> genconfig for me though...

**Comment by svaarala** [comment]
Hmm - but if you invoke genconfig automatically during build, why is it a pain? Does it take too much time, or is the Python dependency an issue?

Keeping support for an external custom file would be possible of course, but the main point for `duk_config.h` would be to avoid relying on command line options. So it'd be kind of counterproductive if it was driven from the compiler command line?

One option you could use is to use the `--fixup-file` option of genconfig to add a fixup header like this:

```
/* Overrides in external header */
#include "my_custom.h"
```

This snippet would be embedded into `duk_config.h` and would be included at runtime. The nice thing is that the sanity checks for active options are in `duk_config.h` after any fixups and overrides, so option sanity checking will be applied to the final overridden options.

This would save you from running genconfig when you want to tweak the custom header, but you'd still need to run it when you update Duktape though.

**Comment by svaarala** [comment]
Hmm, so to summarize what you'd want is: (1) to use the default autodetect header with whatever option defaults are in place, and (2) have `duk_config.h` include an override header.

I could change the dist process to autogenerate an alternate `duk_config.h` which would otherwise be the same as the default one, but with a hardcoded fixup for:

```
#include "duk_custom.h"
```

You could then use that header as is, and just ensure "duk_custom.h" was in the include path. You wouldn't need to invoke genconfig yourself.

Would this be useful?

**Comment by fatcerberus** [comment]
That's what I mean, it's not automatic--I have to invoke genconfig manually every time I upgrade to a new master, switch branches, etc. in case new defaults were added.  "make dist" by itself only gives me the stock default options without debugger support, etc.

Like I said, I could make a shell script to run genconfig with the proper options (the command line gets quite long!), but it's nice that right now I can just do:
`cp dist/src /d/src/minisphere/src` and be done with it. :)

The other issue, as you can see above, is that I conditionally disable the debugger for redist builds.  That's something genconfig alone won't give me.  So yeah, the fixup header seems the best option for now.

**Comment by fatcerberus** [comment]
Yes, that would be useful.  I think the problem right now is that platform detection is mixed in with (usually platform-agnostic) feature options, which makes things quite messy IMO.

**Comment by fatcerberus** [comment]
Another advantage to the custom fixup is that I can quickly prototype different options without having to run genconfig each time or sift through the quite large duk_config.h.  I like simplicity. :)

**Comment by svaarala** [comment]
You can give all the option overrides from a single YAML input file, or tell genconfig to embed a fixup file (essentially same as a custom header)? The command line would either like:

```
$ python genconfig.py --metadata config --output duk_config.h \
      --fixup-file my_custom.h autodetect-header
```

or with a YAML override file:

```
$ python genconfig.py --metadata config --output duk_config.h \
      --option-file my_custom.yaml autodetect-header
```

There's no need to put the options on the command line?

**Comment by svaarala** [comment]
Actually I tried to separate platform and feature detection/handling. It's not easily workable because sometimes platform features restrict features in an unpredictable manner. Also there are config options which are now platform dependent (like JSON.stringify() fast path which has portability limitations) but then become platform neutral so they'd need to move from file to file.

Having two config headers with options sometimes moving from file to file would be much messier IMO. If I did that, with all the downsides it entails, I think you'd say that it's messy to have two files ;)

**Comment by svaarala** [comment]
Regarding tweaking options quickly, that's what I meant with generating a `duk_config.h` with a fixup file that just included your custom header. You'd do that once per Duktape update, and then you'd just need to edit your override file. The `duk_config.h` would always include it at compile time so it wouldn't be a fixed part of `duk_config.h`.

**Comment by fatcerberus** [comment]
Let me start over, I think may not have communicated the problem well so far. :(

In short, I have two options right now: use duk_custom.h which will probably be removed in 1.4.0, or run genconfig as part of each Duktape build.

The requirement to run genconfig means that I can never use an official distribution as-is (read: downloaded from Duktape.org), and that's my main issue with the current setup.

**Comment by svaarala** [comment]
Why can't you run genconfig as part of your build?

**Comment by fatcerberus** [comment]
Hm, I guess that would be possible, I would have to remember to upgrade it along with the Duktape source when testing out a new build, but then I could take duk_config out of my repo in exchange...

The python dependency might be an issue there though.  Ideally I want minisphere to be buildable from a fresh checkout with only a copy of MSVC installed.  Currently that's the case, but this would add an additional dependency on top of MSVC.

**Comment by svaarala** [comment]
Well, genconfig is part of the dist (along with the config metadata for that dist version) so it's actually assumed you always use a matching genconfig.

**Comment by fatcerberus** [comment]
Yes, but `cp dist/src/*` doesn't pull in genconfig. :)  That's what I meant by having to remember it.

**Comment by svaarala** [comment]
Err, couldn't you just copy `dist/config` too?

**Comment by svaarala** [comment]
Anyway, I think I understand your issue, but  can you suggest a solution if we assume that:

- There are no command line options during compilation (because that's quite awkward when installed as a library)
- Not all users want a `duk_custom.h` to be present (especially if defaults are fine for them)

This would be easily solvable if the C preprocessor had something like:

```
#if exists(duk_custom.h)
#include "duk_custom.h
#endif
```

But since it doesn't, the only solution I can think of is shipping two prebuilt `duk_config.h` headers: one would be as it is now, and the other would always include `duk_custom.h` (and fail to build if it wasn't in the include path).

(I'd actually prefer to not do that: it's quite common for portable libraries to have a configuration step, either automated or manual, and supporting yet another custom header variant seems to complicate things.)

**Comment by fatcerberus** [comment]
Long story short, I'm stubborn and don't like to write shell scripts. ;-). Anyway, this issue can be closed, I'll figure something out.

**Comment by fatcerberus** [comment]
Honestly I think the way duk_custom.h works right now is perfect: You define DUK_HAVE_CUSTOM_H and the config pulls it in, the only change I would suggest is to remove the need to #undef.

**Comment by svaarala** [comment]
The problem with that is that you need a compiler command line option - and because some defines affect both Duktape and the application, you need to remember to use that option for both Duktape and application compilation. If you're using Duktape as a library, so that you compile Duktape first and application(s) separately, this is quite awkward to remember. Even more so, if Duktape is installed as a system library.

**Comment by svaarala** [comment]
Could you provide an example how to avoid the need for `#undef` in practice?

The custom header is applied after defaults have been defined, and some defaults are naturally going to be defining something that you might want to override. The header structure is something like:

```
...
/* Default settings */
#define DUK_USE_XYZ_DEPTH 123
...
#include "duk_custom.h"
...
```

When `duk_custom.h` is included `DUK_USE_XYZ_DEPTH` is already defined, so how could one avoid undefining it? There's no way to "peek" into the custom header to avoid defining the default before including the custom file.

You also can't first include the custom file and then apply defaults, because if the custom file wants to disable something (`#undef DUK_USE_VERBOSE_ERRORS`), there's no way to detect than when applying the defaults to avoid defining the option (in effect overriding the custom file preference).

I guess it'd be possible to move into the model where a "don't use X" would be signaled using:

```
#define DUK_USE_X 0
```

rather than:

```
#undef DUK_USE_X
```

but I find that awkard myself for some reason.

**Comment by fatcerberus** [comment]
That's true.  Hm, I don't really have a good answer to this problem, unfortunately.  For now I will duk_custom; if it is removed in the future I'll cross that bridge when I come to it.

Thanks for being so patient with my stupid issues, it's really appreciated. :)

**Comment by fatcerberus** [comment]
As for the defaults, couldn't they be defined *after* the fixup, and guarded with an #ifdef (don't redefine if already defined)?

**Comment by svaarala** [comment]
It's quite useful to ask stupid questions - choosing a configuration model is not easy because there are a lot of concerns, and people have quite strong preferences in various ways. So it's very useful to know what issues people encounter - the problem for me is that I need to figure out a way which is simple *on the whole* considering a lot of different preferences.

**Comment by svaarala** [comment]
That order of things also doesn't work because suppose the custom header says:

```
#undef DUK_USE_VERBOSE_ERRORS
```

Now, if the defaults are applied afterwards and the default would be to enable verbose errors, what would that look like? There's no way to detect a "not defined at all" from an "#undef'ined".

**Comment by fatcerberus** [comment]
Ah, I see what you mean.  I guess the current solution is the best for now.

**Comment by svaarala** [comment]
So to summarize the 1.4 approach -- there's still time to debate and change it so I really do welcome concrete suggestions:

- Get rid of command line options because they're awkward in many cases. This also removes the confusing two level option model with `DUK_OPT_xxx` "requesting" features and `DUK_USE_xxx` being the final, resolved options.
- Use a single config header which can always be edited manually if necessary, which provides the ultimate backstop for really exotic and proprietary platforms.
- Provide a default autodetect header in the distributable for convenience.
- Provide some platform/architecture/compiler specific files which are much smaller and easier to edit manually.
- Provide a genconfig utility which can be used to create a header with option overrides from files and/or the command line to avoid manual editing of headers in most cases: this will be upgrade compatible because it can be re-executed against a new version with no other changes.
- Make configuration metadata programmatic and modular so that adding new platforms and maintaining the autodetection stuff is more manageable than it was before.

One concern with this is the dependency on Python which is not always welcome. Also genconfig now depends on `python-yaml` which is not installed by default, but I'm planning to eliminate this by packaging the metadata also as JSON in the distributable.

It would of course be possible to add:

- Add a `DUK_HAVE_CONFIG_H` command line option which would cause the default header to include `duk_custom.h` similarly to how `DUK_OPT_HAVE_CUSTOM_H` did before.

This would be useful to make the default header more useful as you point out above. But it would also mean bringing back this single compiler command line option which seems a bit odd :) For example, if I compile an application against a Duktape library built using a custom header, I need to remember to add that same `DUK_HAVE_CONFIG_H` to the command line -- otherwise I'll silently build with incorrect options.

**Comment by fatcerberus** [comment]
The main issue, like I said, is the Python dependency.  On Linux it's easy to install such things on the command line and you can even automate it, but in Windows things generally aren't so easy--you have to download and run the installer yourself, including going to the Python website, etc.  Then you have to install python-yaml, which is another hurdle... This kind of thing doesn't scale well, so I prefer to keep my build as minimal as possible, I.e. Just a compile and link step and copying some files.

I agree with the rationale for doing away with compiler switches though.  For a library the config header is definitely superior.

**Comment by svaarala** [comment]
I see what you mean, but how to achieve that in practice?

The only concrete solution so far would be for Duktape to contain an alternate `duk_config.h-with-custom-h` header that would be hardcoded to include `duk_custom.h`. This would avoid the need to run genconfig and wouldn't require command line options for compilation. (This would work for some users but sometimes you need to adjust headers and/or typedefs and you can't do that with a custom header.)

But supposing a header would need to be generated, what would be convenient on Windows, and would also work on Unix platforms?

**Comment by fatcerberus** [comment]
Hm, one way might be to bootstrap a Duktape build using Duktape itself--make it self-hosting in a sense.  Concretely, this would mean building `duk` using default options, and then using that to do config generation, etc.

**Comment by svaarala** [comment]
That would be possible - it'd need file bindings to be able to work with the metadata files (which would to be JSON) but would otherwise be pretty straightforward.

**Comment by svaarala** [comment]
Anyway, just wanted to clarify that I don't expect application builds to run genconfig as a mandatory, expected step. It's possible to do that but I'd actually expect the opposite.

Basically the model is the same as for any portable library which has a manually editable config file. For such libraries one usually maintains a diff to the upstream config file, or makes the same edits whenever the library is updated. The config file is committed into the repo so that it doesn't need changing unless the library is updated. People modifying the application but not updating the library don't need to worry about it. (I use this process and it's often quite painful when the upstream library update is large.)

Similarly, when Duktape is updated one would need to somehow arrive at a new `duk_config.h`. Using diffs or manual tweaks is possible, but I'd hope people would run genconfig and give overrides at this point (or in Minisphere, you can "bake in" an #include to get your custom header at compile time). Then the header can be committed and the actual application build doesn't need genconfig. The header doesn't need to change until the next Duktape update.

I understand you need to rerun that genconfig step a lot when you track Duktape master though. But as long as you have Python installed, that can be made as simple as running one script file which just reruns genconfig. I understand that this would be inconvenient if you didn't have Python installed -- but if you are tracking Duktape master and doing dists yourself, you'll currently always need Python anyway. Someone else building Minisphere doesn't need Python however, as long as there's a compatible `duk_config.h` available.

**Comment by fatcerberus** [comment]
That's true.  My current process is to manually add options (DUK_OPT_xxx) to the top of duk_config.h and then, when upgrading to a new build:

* `cp dist/src/* /d/src/minisphere/src`
* Take a diff of the minisphere source
* If nothing changed in duk_config.h, discard it (git reset duk_config.h), otherwise copy the options to the top of the new file

Which is of course tedious, and actually difficult to automate because of the diff step.  So I'm glad you have that fixup option in genconfig.py, because there's currently no other way for me to get what I want (conditionally enabling the debugger depending on whether it's a GDK or redist build) outside of manual modification.

Anyway, I'll stop being a pest. :)

**Comment by svaarala** [comment]
In your case I'd maintain two `duk_config.h` files - one for debug and another for release.
