### ISSUE TITLE
Unable to modify fileName and lineNumber in errCreate

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#387]
I'm not sure if this is by design, but I've found that this doesn't work:

```javascript
Duktape.errCreate = function(e) { e.fileName = "the pig"; e.lineNumber = 812; return e; };
```

Similarly, using `duk_put_prop()` to modify those properties (my actual errCreate is implemented in C) doesn't work either.  However, this does work:
```c
	duk_push_string(ctx, "fileName"); duk_push_string(ctx, "the pig");
	duk_def_prop(ctx, 0, DUK_DEFPROP_HAVE_VALUE
		| DUK_DEFPROP_HAVE_WRITABLE | DUK_DEFPROP_WRITABLE
		| DUK_DEFPROP_HAVE_CONFIGURABLE | DUK_DEFPROP_CONFIGURABLE
		| DUK_DEFPROP_HAVE_ENUMERABLE | 0);
	duk_push_string(ctx, "lineNumber"); duk_push_int(ctx, 812);
	duk_def_prop(ctx, 0, DUK_DEFPROP_HAVE_VALUE
		| DUK_DEFPROP_HAVE_WRITABLE | DUK_DEFPROP_WRITABLE
		| DUK_DEFPROP_HAVE_CONFIGURABLE | DUK_DEFPROP_CONFIGURABLE
		| DUK_DEFPROP_HAVE_ENUMERABLE | 0);
```

The fact that the latter snippet works means the properties are configurable, but not writable, by default?  Seems odd, and makes error augmentation more difficult.

**Comment by svaarala** [comment]
Error `.fileName` and `.lineNumber` are not "own properties" of the error but rather automatically created by an inherited getter. The getter return value is based on the internal `_Tracedata` property. This arrangement minimizes "own property" counts for errors:

```
((o) Duktape 1.3.99 (v1.3.0-88-gbdbe2d1-dirty)
duk> err = new Error('aiee');
= Error: aiee
duk> print(Duktape.enc('jx', Object.getOwnPropertyDescriptor(err, 'fileName')));
undefined
= undefined
duk> print(Duktape.enc('jx', Object.getOwnPropertyDescriptor(Error.prototype, 'fileName')));
{get:{_func:true},set:{_func:true},enumerable:false,configurable:true}
= undefined
```

As a side effect, attempt to overwrite either property will be captured by the inherited setter. The current setter is a silent nop.

The inherited setter/getter has been left configurable so that it is possible to create an "own property" of the same name using `Object.defineProperty()`; if the setter/getter were non-configurable, that would also be rejected.

So, the current behavior is by design but it's not necessarily the nicest one.

One improvement might be to make the default setter create the "own property" automatically so that assignment would seem to work normally.

**Comment by svaarala** [comment]
Here's a "polyfill" to emulate the setter change I suggested:

```js
Object.defineProperty(Error.prototype, 'fileName', {
    set: function (v) {
        Object.defineProperty(this, 'fileName', {
            value: v,
            writable: true,
            enumerable: false,
            configurable: true
        });
    }
});
```

With this in place you'll be able to write the `fileName`:

```
duk> err = new Error('aiee'); print(err.fileName);
input
= undefined
duk> err.fileName = 'dummy';
= dummy
duk> err.fileName
= dummy
duk> Duktape.enc('jx', Object.getOwnPropertyDescriptor(err, 'fileName'));
= {value:"dummy",writable:true,enumerable:false,configurable:true}
```

The same approach for `.lineNumber` works of course, perhaps with number coercion in the setter.

**Comment by fatcerberus** [comment]
Thanks.  The current behavior is not a big deal (defineProperty works after all), I just wanted to make sure it was by design and not a bug like with `Function#name` a while back.

**Comment by svaarala** [comment]
Ok, good to hear. That setter change would be quite easy though. It's worth a Wiki howto at least because it's certainly a bit unintuitive.

**Comment by fatcerberus** [comment]
The setter would indeed be convenient, but I didn't know if you actually wanted to add it or not (for footprint reasons).

**Comment by svaarala** [comment]
#390 has the diff needed to make the change -- I'm not sure it's a good idea but it's up for discussion :)
