### ISSUE TITLE
parseInt shouldn't auto-oct when the radix is 16

### ISSUE THREAD

**Issue by HouQiming** [svaarala/duktape#413]
Test case:

    print(parseInt('00e1',16))

It prints 0 in duktape 1.3.0. It should print 225 (0xe1). 

In `duk_bi_global_object_parse_int`, the `radix!=16` hack should unset `DUK_S2N_FLAG_ALLOW_AUTO_OCT_INT` instead of leaving `strip_prefix` as 1 when `radix` is indeed 16.

**Comment by svaarala** [comment]
Thanks. I'll look into it!

**Comment by svaarala** [comment]
Hmm, somewhat unrelated, but there's a different between Node.js v0.12.1 and Rhino in handling automatic octal parsing:

```
parseInt('0123');    // -> 123 in Node.js, 83 in Rhino
parseInt('0123', 8); // -> 83 in Node.js and Rhino
parseInt('0xff');    // -> 255 in Node.js and Rhino
```

So, hex autodetection works without explicit radix but octal is not autodetected. The E5.1 specification is a bit vague for octal because it's an optional feature so I'm not sure which is correct, I'll try to figure it out. As a user I'd prefer V8's behavior though.

**Comment by svaarala** [comment]
Here's a write-up from Mozilla re: octal radix:

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#ECMAScript_5_Removes_Octal_Interpretation

This matches Node.js behavior so I'll change Duktape to do this too - for me it's also the most sensible behavior.

**Comment by HouQiming** [comment]
That would be great, thanks!

**Comment by fatcerberus** [comment]
> Specify 10 for the decimal numeral system commonly used by humans

I find that profoundly amusing. :)
