### ISSUE TITLE
README details for developing on ArchLinux

### ISSUE THREAD

**Issue by WebReflection** [svaarala/duktape#466]
In order to build Duktape there are few missing details from the readme.

  1. the only working Python version as of today is **2**
  2. this means these are needed `sudo pacman -S --needed python2 python2-beautifulsoup4 python2-rdflib python2-yaml`
  3. the builder knows about `nodejs` possibly called as `node` but it hangs in there anyway. To solve this: `sudo ln -s /usr/bin/node /usr/bin/nodejs`
  4. these is pretty much anything else needed to build stuff on Arch: `sudo pacman -S --needed base-devel clang llvm git bc`

After these packages are installed, simply cloning and running `make` should just work.

If there are problems with python, be sure the used version is 2 and not 3.

Not sure you have space in your README for this, or you'd like to add a file a part.

Cheers

**Comment by svaarala** [comment]
It might be best to add these per platform instructions to the Wiki instead (and point to the Wiki from the README).

I'd actually want to remove some detail from the current README and just point to the Wiki, so that the README would best serve end users. Duktape deverlopment details tend to confuse users because they may think they need to be able to `make dist` to use Duktape.

**Comment by svaarala** [comment]
These are now part of http://wiki.duktape.org/DevelopmentSetup.html.
