### ISSUE TITLE
How get function passed as argument in an native function ?

### ISSUE THREAD

**Issue by leonardosnt** [svaarala/duktape#468]
cpp:
```cpp
int bind( duk_context *ctx )
{
	if ( !duk_is_function(ctx, 0) )
	{
		// throw
	}

	// save the function to call later
	return 1;
}
```

js:
```javascript
bind(function () { print ("hello") });
```

**Comment by fatcerberus** [comment]
I'm not at my computer right now so I can't draft up an example, but I can point you in the right direction at least: Look into the "global stash" in the API documentation.

You can call `duk_get_heapptr()` to get the function's heap pointer (and push it back when you need to call it later), but that's not enough to save it from being garbage collected, which is why you need to use the stash to keep it reachable.

**Comment by fatcerberus** [comment]
To elaborate a bit: How I handle this is to keep an array in the global stash, which holds references to all the functions I've been passed in from JS.  The indices into this array are what's passed around in the native code, and when I need to call one I use the value stack API to retrieve it from the array.

It's honestly a bit more complicated than I would prefer, but since `duk_get_heapptr()` alone doesn't shield you from the GC there's no real alternative.

**Comment by svaarala** [comment]
I'll try to write an example to the Wiki about this

But I think the basic approach should be what you'd do if the called function was Ecmascript: you'd write the reference somewhere, e.g. into a global object, and then look it up later:

```js
var func;
function bind(fn) {
    if (typeof fn !== 'function') { throw new TypeError('must be function'); }
    func = fn;
}

function other() {
    // call stored func
    if (!func) { throw new Error('no stored function');
    func();
}
```

For timers and such, the global object tracking the functions is usually an array or an object, etc. The code which calls the function then needs some key (string or number) to look up the function.

There are various other approaches too. Instead of the global object you can use the "stash" objects which are similar but not (easily) accessible from Ecmascript code so they're "hidden" from applications. I'd steer clear of `duk_get_heapptr()` unless you're doing something really performance sensitive: it allows you to push back the stored function using a `void *` from C code but if you do something wrong it's not memory safe. It's safer to use a number/string handle and write the C code similarly to how you'd write the equivalent Ecmascript.

**Comment by leonardosnt** [comment]
@svaarala I'll call from c++, not javascript

**Comment by svaarala** [comment]
Yes, you can then just do the equivalent in C:

```
int bind( duk_context *ctx )
{
    if ( !duk_is_function(ctx, 0) )
    {
        duk_error(ctx, DUK_ERR_TYPE_ERROR, "not a function");
    }

    duk_put_global_string(ctx, "storedFunc");
    return 0;
}

int call( duk_context *ctx )
{
    duk_get_global_string(ctx, "storedFunc");
    duk_call(ctx, 0);  // TypeError if not callable / undefined
    return 0;
}
```

**Comment by fatcerberus** [comment]
@svaarala Re: "Why not script it?"
To be fair, there are legitimate use cases for this.  For example, minisphere's map engine allows a JS function to be provided which will be called when, e.g. the player talks to an NPC.  Because the map engine is coded in C, this type of thing can't be scripted.

**Comment by svaarala** [comment]
Sure, there are cases like that. But I think one should first try to use the simplest and most obvious approaches and only use a more error prone approach when it's justified by performance or other concrete concerns.

**Comment by svaarala** [comment]
@fatcerberus To elaborate a bit, I don't know what the limitations are in your case, but here's an example how to implement callbacks in a memory safe manner, without using `duk_get_heapptr()`, when the only thing one assumes of C code is that it can store a `void *` as a callback identifier/handle:

- Maintain a global object mapping a callback index ("cbindex") to a function, `callbacks[]`.
- Maintain a running callback index counter `next_index`.
- When a new callback is registered, allocate a new cbindex as `cbindex = next_index++`, and set `callbacks[cbindex] = fn`. Give the `cbindex` to C code as the handle for an eventual callback. C code coerces it to `void *`.
- When C code needs to call into a callback, call into a shared script handler, giving the `void *` and possible callback specific parameters as arguments. The shared script handler looks up `callbacks[cbindex]` and calls it with the callback specified arguments. Remove `callbacks[cbindex]` if the callback is one-shot.

This can all be implemented almost purely in Ecmascript: C code is only given a number to use as a handle, and C code only needs to call a shared callback handler which looks up the function and calls it.

This is also fully memory safe: there's no risk of a stale pointer, and the worst that can happen is that indices are mismanaged and either the wrong callback gets called, or `callbacks[cbindex]` is undefined and a clean error happens.

I'm not saying one never needs `duk_get_heapptr()`, but I don't think it should be the first approach to use because it has potential memory safety implications. Avoiding these is (often) a major motivation for using scripting.

**Comment by mamod** [comment]
@svaarala in early implementation I used to store callbacks in objects within Ecmascript and passed index id to C, just like you described, but then I started to use heapptr functions, I noticed the later is faster in performance, not sure about the exact performance gain or if I was comparing these 2 methods correctly, I just felt more comfortable with heapptr and now I'm scared enough to reconsider switching back :P

I recall I was the one who asked for heapptr feature, so I hope it isn't that evil :)

**Comment by svaarala** [comment]
@mamod Hehe :) It's not evil but you just need to be sure you're tracking object reachability status correctly. If performance is a concrete concern it may very well be worth it, at least for multishot callbacks. If performance is not a concern, I personally almost always prefer memory safety.

**Comment by fatcerberus** [comment]
@svaarala Yeah, that's essentially what I do--I keep an array in the stash holding the callback references to keep them reachable, but I do keep their heap pointers around as well for performance reasons (there's a few callbacks that need to be called every frame, for example).  I'm not passing the heap pointers around directly though, they are fully managed by the scripting framework.

**Comment by mamod** [comment]
That's exactly what I was benching, callback inside an event loop where the same function would be called thousands of times, so far millions of timers and tcp tests with no problem at all.

**Comment by svaarala** [comment]
Yeah, just to be clear, `duk_get_heapptr()` + `duk_push_heapptr()` is 100% safe as long as the object doesn't become reachable in between. It's just that it's easy to make mistakes in reachability handling at least if you're not sure what you're doing :)

**Comment by fatcerberus** [comment]
Very easy, in fact.  If you're just calling `duk_get_heapptr()` without pinning the object somehow, and then do this:

```javascript
setCallback(function() { print("yay!") });
```

That function becomes unreachable as soon as setCallback() returns.  This is where object pinning would come in handy (even if it was ultimately just shorthand for "store a reference in the stash").

**Comment by leonardosnt** [comment]
this worked ```duk_get_heapptr()```, thank guys.

**Comment by fatcerberus** [comment]
Just keep in mind what @svaarala said above -- taking the heapptr alone isn't enough, you have ensure the function remains reachable otherwise you'll start to see weird crashes...

**Comment by leonardosnt** [comment]
:+1:
