### ISSUE TITLE
Debugger Eval command does not see correct `this` binding

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#478]
Evaluating `this` with a Debug Eval seems to return the global object instead of the current function's correct `this` binding.  For example, after setting a breakpoint on this line:

```javascript
this.aic.definePhases([ 3000, 2000, 1000, 500 ], 50);
```

Performing an Eval of `this.aic` produces `undefined`, which is obviously incorrect (the code runs fine after resume).  After looking a little deeper into it, this bug is present in 1.3.0 (and prior) as well.

**Comment by fatcerberus** [comment]
Direct Ecmascript `eval()` is unaffected, which is probably why this slipped under the radar.

**Comment by svaarala** [comment]
Here's the bug: https://github.com/svaarala/duktape/blob/master/src/duk_debugger.c#L1380-L1381

**Comment by svaarala** [comment]
The implementations looks about the same in 1.3.0 so I'd be surprised if it worked there. The issue is probably that the debugger code calls `eval()` but because the activation is not tweaked like when eval() is called by the bytecode executor, it gets interpreted as an indirect eval - and an indirect eval will get the global object as its "this" binding.

I'd take this chance to refactor the implementation so that the debugger didn't awkwardly call the `eval()` function like it does now, and would also pass the level as a plain argument to a shared helper rather than in the value stack.

**Comment by fatcerberus** [comment]
Here's the odd thing: The overall effect is like a weird hybrid between a direct and indirect eval.  `this` is the global object like an indirect eval, but I can access local variables like a direct one.

But yeah, refactoring is probably for the best.  I found the current setup pretty awkward myself.

**Comment by fatcerberus** [comment]
I installed an older version of minisphere, which used a prerelease of Duktape 1.3.0 from master and this bug turns out to have been present there too.  So that makes me feel a little better, I didn't introduce this one. ;)

**Comment by svaarala** [comment]
Well it's good you noticed this now so we can fix it :) Like I said above, I'd like to take the chance to split the `eval()` function in `duk_bi_global.c` into a few parts so that we could avoid the awkward call the debugger uses now. Instead, it could just compile the eval code directly in the specified lexical scope, set up this `this` binding directly etc. That second argument could then be removed from the eval() call in `duk_bi_global.c`.

**Comment by svaarala** [comment]
Would you happen to have a small repro case for this?

**Comment by fatcerberus** [comment]
Repro case is posted in #479.

**Comment by svaarala** [comment]
Turned out not to be a bug after all.

**Comment by fatcerberus** [comment]
Might be worth it adding the Eval refactoring as future work, anyway.
