### ISSUE TITLE
Whether you can make duktape only support multi byte character sets

### ISSUE THREAD

**Issue by zero-ui** [svaarala/duktape#505]
My code is not used to UTF8 encoding.Every call CAPI need to do encoding conversion, so that very sacrifice efficiency.

**Comment by svaarala** [comment]
Duktape uses (extended) UTF-8 internally so even if the C API had variants for wide characters (or multibyte strings), Duktape would need to do the conversion into UTF-8 so it wouldn't necessarily perform much better.

Changing Duktape internally to support both UTF-8 and wide characters would be quite a bit of work because all algorithms dealing with bytes/characters would need two variants.

**Comment by zero-ui** [comment]
Can you provide a macro switch in the next version.

**Comment by svaarala** [comment]
Unfortunately the encoding affects a lot of internal operations so it's a pretty major change. I'm closing this; reopen or open a new issue if there's some proposal that would be more practical.
