### ISSUE TITLE
TypeScript compatibility

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#523]
Is Duktape compatible with TypeScript?  The Guide mentions CoffeeScript and few other "transpilers", but no mention of TypeScript.  Is it just that no formal testing been done with this?

**Comment by svaarala** [comment]
There are a couple of people at least running TypeScript with Duktape, so it should be quite functional. It should be added to the website, but it'd be nice someone working with TypeScript + Duktape could comment on if there are any issues.

**Comment by JoshEngebretson** [comment]
TypeScript is used in the AtomicEditor, here's a sample script: 

https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Script/AtomicEditor/ui/frames/inspector/AttributeInfoEdit.ts

There is also support for TypeScript in projects (we're working to streamline this) :

https://github.com/AtomicGameEngine/AtomicExamples/tree/master/Roboman3DTypeScript

We haven't encountered a single Duktape related issue with the transpiled JS to date.

**Comment by fatcerberus** [comment]
How about the TypeScript transpiler itself?  Do you run that with Duktape, or is the TS code transpiled through some other mechanism?

**Comment by JoshEngebretson** [comment]
@fatcerberus We use node + tsc for compiling, I haven't run the TS compiler on Duktape.  This would likely work, though require some shims for a few trivial node API's for IO

**Comment by fatcerberus** [comment]
Thanks guys. :)

**Comment by JoshEngebretson** [comment]
We have now run the TypeScript compiler under Duktape!  

Microsoft has made it easy to plug in IO handling, etc into the compiler.  Straight transpiling is pretty fast, full on compiles (with full validation) are slower.  

We're still working on the integration and can provide better performance metrics.  Though, it works and only required relaxing some regex :+1:

**Comment by svaarala** [comment]
@JoshEngebretson Cool :) If those regexp issues were curly brace related, an incoming pull might make those fixes unnecessary.

**Comment by JoshEngebretson** [comment]
@svaarala I wasn't the one who got it working, though there should be a PR soon with more details on the regex tweak.  I was just really excited that it works :laughing:

**Comment by svaarala** [comment]
I was referring to @crazyjul's pull (https://github.com/svaarala/duktape/pull/513) which would allow unescaped curly braces. That's perhaps the most common issue :)

**Comment by svaarala** [comment]
@JoshEngebretson Anyway it's great that you got it working :)

**Comment by shaddockh** [comment]
I have an update to this.  To get typescript.js to run under duktape, it actually was related to unescaped curly braces.  The only change I needed to make was to escape the curly braces on line 1171:
```
return text.replace(/\{(\d+)\}/g, function (match, index) { return args[+index + baseIndex]; });
```

I've also run into the same issue bringing rot.js ( https://github.com/ondras/rot.js ) into duktape.  All the changes I had to make on that were related to curly brace escaping.

So, if curly brace escaping is no longer necessary, that would be awesome!!

**Comment by fatcerberus** [comment]
Yeah, once #513 is merged such edits won't be needed anymore.  It seems literal braces in regexps is very common despite violating the ES spec (?), if even something as high-profile as the TypeScript compiler expects them to work.

**Comment by svaarala** [comment]
@fatcerberus At least from my reading of the specification literal braces are excluded from pattern characters:

```
PatternCharacter ::
    SourceCharacter but not one of
    ^ $ \ . * + ? ( ) [ ] { } |
```

**Comment by shaddockh** [comment]
fyi, I just confirmed that I was able to load an unmodified copy of typescript.js into the Duktape vm with these changes applied.  Thanks!!

**Comment by svaarala** [comment]
Good to hear, thanks :)

**Comment by svaarala** [comment]
Btw, could I link to something in the Atomic repo to provide an example of how to run the TypeScript compiler with Duktape?

**Comment by fatcerberus** [comment]
Oh goody, now I can go ahead with TypeScript integration for minisphere 3.0.  Thanks, @crazyjul!

**Comment by JoshEngebretson** [comment]
@svaarala We're still working out how compiling TS from the editor is going to work, this isn't a simple example, though if you're curious: 

https://github.com/shaddockh/AtomicGameEngine/blob/TSH-ATOMIC-TYPESCRIPT/Script/AtomicEditor/extensionServices/resourceServices/TypescriptLanguageService.ts

The TypeScript compiler can just work with string buffers, so you could probably add a simple/minimal example pretty easily...

**Comment by JoshEngebretson** [comment]
Speaking of TypeScript, checkout Atomic's new code editor via Ace and the embedded UIWebView, 

Themed syntax highlighting for pretty much every common language, code folding, autocompletion, even linting with info boxes in the gutter!

Going to be fun hooking up Duktape's debugger with it :)

<img width="697" alt="atomicts" src="https://cloud.githubusercontent.com/assets/376203/12431699/c1a52ab8-beab-11e5-9542-90d17616a4f3.png">
)

**Comment by fatcerberus** [comment]
Looks nice.  As for debugger integration, I recommend trying to adapt the JSON proxy if at all possible.  I used the binary protocol directly for minisphere to keep my dependencies to a minimum (JSON proxy requires node.js), but it's pretty tedious to maintain.

**Comment by svaarala** [comment]
Just to provide some background: the debugger protocol and the debugger API are quite low level; they're that way to allow Duktape debugger to work with in very low memory environments (it can work with less than 1kB of static memory overhead and no dynamic allocations in many cases). The downside is that it's binary, etc.

That low memory target is very important because low level environments are one area where Duktape has a lot of (current and potential) users. There are some steps that we can take to make the low level integration (binary protocol) easier to work with, but only up to a certain limit.

So while the low level protocol is binary, I'd like to provide (at least) three additional components (outside of the target) to make integration easier, without compromising the low memory targets:

- A JSON mapping and a JSON proxy which talks binary to the target and JSON to you. There's a Node.js based JSON proxy in the master already, so this is working, but perhaps the Node.js dependency is an overkill. (We could write one using Dukluv... :-)
- A C/C++ library running on the remote peer (debug client) which would allow you to talk to the target without needing to read/write the binary messages directly. Similar to the JSON proxy but working inside the remote peer process. This is currently missing, though https://github.com/svaarala/duktape/tree/master/examples/debug-trans-dvalue should be relatively easy to adapt for that purpose.
- A Node.js library running on the remote peer to talk to the target. There's a Node.js based debug protocol handling class in the debugger example which ships with Duktape. That should be relatively easy to adapt to provide a Node.js API for debugger integration, but at the moment it's tied to the debugger example (not very deeply but still).

@JoshEngebretson When you get around to decide on debugger integration, let me know how you see the various alternatives. I can chip in to make the process easier if you'd prefer a native library or something similar.

**Comment by JoshEngebretson** [comment]
Thanks guys, @svaarala great info dump (as always). I'll be looking at this sooner than later, quite requested feature... I have a good amount of experience with Lua's low level debug interface so hopefully that along with this advice/info will help :)

**Comment by fatcerberus** [comment]
Lua has a debugger?  You learn something new every day. :)

**Comment by belegar** [comment]
It could be easy to write a tiny debugger using a stand-alone GUI app, in Qt for example. Well, this is something I need to code in my growing TODO list :)

**Comment by svaarala** [comment]
Could you print the error `.stack` so there's a better idea of the line number etc?

**Comment by svaarala** [comment]
FWIW in master:
```
