### ISSUE TITLE
Error thrown during CJS module cause debugger pause in wrong location

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#637]
An unhandled Error thrown during processing of `require()` will cause the debugger to halt at the `require()` call, outside the module.  The expected behavior is for a pause to occur at the throw site inside of the module.

**Comment by fatcerberus** [comment]
Nevermind, false alarm - turns out there's no Duktape bug, it was caused by my GUI client automatically sending a Step Out command when it can't find source code.  SSJ downloads source code directly from minisphere so it correctly stopped inside the module.

**Comment by fatcerberus** [comment]
There is an issue though, not a bug but an annoyance: Duktape automatically uses the module ID as the filename, which makes it difficult for the client to find the source code (since it can't differentiate a module ID from a real filename)

**Comment by svaarala** [comment]
The function executing when a module is being loaded is not actually the source provided by modSearch() directly. Instead, a function wrapper is automatically generated around the source code, so all line numbers will reference that function (because the wrapper has now newlines line numbers will match; column numbers wouldn't match for the first line). This is an artifact of the current implementation.

Currently modSearch() will just return a source file with no filename information so the filename is not actually available for compiling the wrapper. One simple compatible workaround would be to allow modSearch() to assign `module.fileName` so that when a source file is returned, that would be set as the fileName of the function wrapper. The property could be initialized with the module ID as it is now.

**Comment by svaarala** [comment]
I'll move the .fileName discussion to #639 (placeholder pull request).
