### ISSUE TITLE
Escaped unicode identifier parts in duktape regexp

### ISSUE THREAD

**Issue by HouQiming** [svaarala/duktape#643]
Found something accepted by browsers but not by duktape:
```javascript
var re=/[\Æ]/;
```
Browser ignores the identity escape, but duktape reports "invalid regexp escape".

A quick search didn't find anything standard-offending in that expression. Since it's rather unlikely for someone to mistakenly write a bogus escape with a unicode character, I think it wouldn't hurt to relax those `duk_unicode_is_identifier_part()` checks.

**Comment by fatcerberus** [comment]
From what I understand Ecmascript doesn't allow escaping any character which is a valid IdentiferPart.  For regexps Duktape follows the spec almost to the letter except for a few hacks to support common real-world regexps.  I don't know that the example above would be particularly common in real-world code?

**Comment by HouQiming** [comment]
I was trying to run a browserified node.js test program in duktape (attached). This detail turned out to be the only incompatibility I encountered. It really shows how impressive duktape is!

The offending code seems to generate a regexp from a JSON map and uses it to convert Unicode strings to/from HTML/XML & thingies. That regexp generation code is a bit conservative and tends to add escapes when it's not needed.

Personally I think the browser behavior makes sense -- given a random non-ASCII character that you want to put in a regexp, blindly escaping it is much easier than going through an identifier check that serves no practical purpose.

[bundle.zip](https://github.com/svaarala/duktape/files/179101/bundle.zip)

**Comment by HouQiming** [comment]
In fact, I think we could just make `DUK_USE_NONSTD_REGEXP_DOLLAR_ESCAPE` skip the entire `duk_unicode_is_identifier_part` check, instead of just adding a special case for `'$'`.

**Comment by svaarala** [comment]
@HouQiming I agree this can be relaxed; it requires some look-ahead to parse control escapes, i.e. `\cD` parses as a control escape while `\c6` parses as `c6`.

The standard offending part of escaping IdentifierPart characters can be found in http://www.ecma-international.org/ecma-262/5.1/#sec-15.10.1:

> IdentityEscape ::
>     SourceCharacter but not IdentifierPart
>     ZWJ
>     ZWNJ

Escaping IdentifierPart characters as identity escape is not allowed in ES5.1.

ES6 has an Annex for additional syntax which is not a mandatory part of an implementation but identifies some common behavior and identity escaping non-IdentifierPart characters is covered there: http://www.ecma-international.org/ecma-262/6.0/#sec-regular-expressions-patterns:

> IdentityEscape[U] ::
>     [+U] SyntaxCharacter
>     [+U] /
>     [~U] SourceCharacter but not c

So this can be considered to be an ES6 issue to some extent. It does handle the "c" character (for control escapes) specially, though.

These relaxations are behind config switches because some people prefer E5.1 compliant behavior, i.e. strict regexp parsing, because that will ensure their code is maximally portable between engines. For some users compliance is a goal in itself, e.g. if they're trying to conform to some specification requiring ES5/ES5.1.

**Comment by HouQiming** [comment]
I see. Then I'd prefer to extend `DUK_USE_NONSTD_REGEXP_DOLLAR_ESCAPE` to
cover this one.

Thanks!

Qiming

**Comment by svaarala** [comment]
@HouQiming I'll try to come up with a pull request for the 1.5.0 release, this should be relatively easy to implement.

Did you get the bundle.js to work otherwise after fixing the regexp, btw? :)

**Comment by HouQiming** [comment]
Yes :)

HTML + CSS + jQuery, in duktape.

**Comment by svaarala** [comment]
With #926 the bundle attached above parses and prints:

```
<body><h2 class="title welcome">Hello <span style="span-style">span text</span>world</h2></body>
0 <h2 class="title welcome">Hello <span style="span-style">span text</span>world</h2> Hello span textworld
1 Hello <span style="span-style">span text</span>world Hello span textworld
2 null Hello 
2 span text span text
3 null span text
2 null world
```
