### ISSUE TITLE
Overriding module.id from modSearch

### ISSUE THREAD

**Issue by saghul** [svaarala/duktape#662]
Hi,

First, let me thank you for Duktape, it's awesome! and the documentation is really outstanding.

On to my little problem: I'm implementing a modSearch function in C, and in there I accomodate for having a module likle this:

foo/
foo/index.js
foo/bar.js

The use would just `require('foo');` and foo/index.js will be loaded. index.js just contains `require('./bar');, so this fails currently, because bar is not attempted to be loaded "inside" foo. Is there something obvious I'm missing here? I tried to look at issues, examples and tests but nothing that explained this...

Thanks!

**Comment by fatcerberus** [comment]
It's important to remember that the module ID is an abstraction - you decide what it actually means in concrete terms.  In your case "./bar" resolves to `foo/bar`.  Since you've already decided that `require('foo`)` means "load foo/index.js", by that definition your layout should be instead:

* foo/
* foo/index.js
* foo/bar/
* foo/bar/index.js

Duktape doesn't know or care what the resolved module name "foo/bar" refers to - that ball is in your court. ;-)

**Comment by saghul** [comment]
I'm not sure I understand. According to the docs (if I understood correctly) Duktape does the resulution of the abstract module ID and then I decide what to load. Given the current layout:

foo/
foo/bar.js
foo/baz.js

If I `require('foo/bar') and bar has `require('./baz.js')` then the ID for baz is foo/baz, Duktape takes care of that. I would like to influence that by making 'foo' and 'foo/index' kinda equivalent, so the layout I mentioned works.

Note that due to Duktape's resolution, I get "bar" when I did a `require('./bar') so I don't really know what to concatenate...

**Comment by fatcerberus** [comment]
Right, Duktape does the path resolution for you as a convenience.  But it's still abstract - you have to decide what it means.

As for `foo/bar` thing, I think I understand the confusion - you're thinking of the final component of a module ID like a directory when it's actually more like a filename.  So if you have a module foo/bar which requires ./baz then you will get foo/baz.  A prefix of "./" therefore refers to a *sibling* module and not a contained one.

**Comment by saghul** [comment]
> A prefix of "./" therefore refers to a sibling module and not a contained one.

Correct. That's why I'm looking into how to make ./baz be a sibling of foo/index, while only needing the user to require foo.

**Comment by fatcerberus** [comment]
Okay, I see what you want now.  Do note that what you're suggesting AFAIK breaks the CommonJS spec, (creating a leaky abstraction) although I may be wrong on that - I'll defer to @svaarala to weigh in on this.

**Comment by saghul** [comment]
FWIW, Node behaves like this. It doesn't mean Duktape should bend over backwards, but that's a datapoint :-)

And, for the sake of completeness, here is the reason why I wanted this: I have a hybrid module foo, which has some native part writen in C, and I wanted to have that in some _foo submodule, as follows:

foo/
foo/index.js: defines dome JS functions + exports stuf from _foo
foo/_foo.so: a low level module written in C

I know I can flatten the tree and just have foo.js and _foo.so, but I wanted me some "namespacing" :-)

**Comment by fatcerberus** [comment]
Huh, I looked up the Node documentation and Node.js `require()` is actually a rather strange beast.  It uses a very convoluted set of rules to find modules that I don't know can be fully accommodated with Duktape's very basic resolver.

If you look around the issues you can find a few mentions of overhauling the module system to be more flexible, which would make use cases like this more feasible in the future. :)

**Comment by svaarala** [comment]
@saghul Hmm, could you paste some code snippets to explain the issue in a bit more detail?

Duktape currently implements modules rather strictly through an abstract CommonJS namespace:
- The global `require()` resolves modules relative to an empty base ID.
- Modules are provided a fresh `require()` function which remembers the module base ID, so that if you require `foo/bar` and then require `./baz` within that module, Duktape can resolve that relative reference to `foo/baz`.
- The resolution process always ends up with an absolute, canonical module ID like `foo/baz` (never `./foo/baz` or `foo/./baz` etc).
- Duktape.modSearch() then maps these absolute, canonical module IDs to whatever source files you want to use. For example, you can implement a search path.
- Modules are also cached using the absolute, canonical module ID.

The downside of this is that users often want to deviate from the CommonJS semantics and because the resolution happens inside Duktape (and is therefore outside of user control) some semantics are not always possible right now.

There's an open issue to perhaps split Duktape.modSearch() into Duktape.modResolve() and Duktape.modLoad() to make this more flexible. Another approach is to just ship an example module loader with Duktape, but make it always external so that it's easy to modify and replace. Duktape would then only depend on the presence of a `require()` function.

Also note that even now you can replace `require()` entirely with your own function; DukLuv actually implements a split modLoad/modResolve model in Duktape 1.x by replacing `require()` entirely.

**Comment by svaarala** [comment]
So based on the description I guess the issue is that your first require is:

```js
var foo = require('foo');
```

Duktape maps that to the canonical ID `foo` (same as the requested ID in this case). You then return a module source from Duktape.modSearch() which:

```js
var bar = require('./bar');
```

Duktape resolves that relative to `foo` via the intermediate `foo/.././bar` and arrives at `bar`. You would prefer this to be resolved to `foo/bar` because `foo` was internally mapped to `foo/index.js`.

To make this work using the built-in require your first require would need to be e.g.:

```js
var foo = require('foo/index');
```

With this `./bar` would resolve via `foo/index/.././bar` to `foo/bar`.

**Comment by saghul** [comment]
@svaarala your reasoning is absolutely correct :-) Now, is it possible to override the require id in order to achieve what I want without overhauling the module loader? I checked dukluv, but it looks like too much work, which hopefully I can avoid :-)

The idea, as you guessed, is to set the require.id to 'foo/index', but that didn't work out since require.id is not writable... are there any options around this?

Thanks!

**Comment by svaarala** [comment]
You can forcibly overwrite even non-configurable and non-writable properties using `duk_def_prop()` if you give it the `DUK_DEFPROP_FORCE` flag. I think you should be able to do that inside `Duktape.modSearch()` because modSearch() is given the `require()` function which the module will ultimately see.

**Comment by svaarala** [comment]
However, you'll need a native helper which Duktape.modSearch() will call to do that forced overwrite - or you need to implement modSearch() as a Duktape/C function. I'd probably opt for the former :)

**Comment by saghul** [comment]
I already implemented my modSearch function in C, so that's fine :-) Thanks, I'll give this a try!

**Comment by saghul** [comment]
Woooho, that works great! Thanks a lot!

**Comment by svaarala** [comment]
@saghul Great :) Maybe this would be a good topic for a small wiki howto? :)

**Comment by saghul** [comment]
Sure, why not! Maybe an extension to the howto modules document?

**Comment by svaarala** [comment]
There's a Wiki issue now pointing back to this issue. I'll try to write it at some point :) Thanks for bringing this use case up, it's a useful use case to consider for Duktape 2.x module loading rework too.

**Comment by svaarala** [comment]
@saghul One note to the approach you're using: Duktape will cache the loaded module using the canonical absolute module ID instead of `require.id`. In your example this means that while `require('foo')` and `require('foo/index.js')` will load the same module, the module would actually be loaded and cached twice using both IDs.

Basically what you're doing is trying to alias `foo` with `foo/index.js`. Conceptually this would be cleanest if it were part of the module ID resolution process (as it is in the proposed Duktape 2.x design) so that any aliasing decisions will then affect both sub-module resolution and module caching. In fact, for the most flexible design, user code should get to decide what ID is used for sub-module resolution and what ID is used for caching. There might be use cases where these are different.

**Comment by fatcerberus** [comment]
@svaarala On a semi-related note, Node.js has `require.cache`.  Would it be possible to refactor Duktape's module caching mechanism to use that rather than the hidden `modLoaded` cache it uses now?

**Comment by svaarala** [comment]
Sure, placement of the cache is trivial to change. I'm not sure why user code would need to access it in practice, though.

There might be some sandboxing scenarios where the cache would need to be hidden (so that neither `require.cache` nor `Duktape.modLoaded` would be appropriate). This is one more more reason I'd prefer the module loading mechanism, including resolution, caching, etc to be outside of main Duktape code so that it'd be easier to adapt and change. It's quite difficult to come up with a design where Duktape handles much of the functionality but simultaneously provides enough flexibility to work with all the sometimes very different module loading tweaks in the wild.

**Comment by fatcerberus** [comment]
The main use case according to the Node docs is forcing a module to be reloaded which otherwise might be cached, by removing it from the cache.

I agree it seems like a weird feature, i just figured since Duktape already does this it would be easy to change it to align with Node.js.  Then again the effort might be wasted if the module system is going to be overhauled in 2.x anyway. :)

**Comment by svaarala** [comment]
I'd prefer to do that change in the 2.x rework; Duktape.modLoaded[] is documented (http://duktape.org/guide.html#builtin-duktape-modsearch-modloaded) so although it's described as private it should probably not be changed just to align with Node.

**Comment by saghul** [comment]
@svaarala thanks for the note!
