### ISSUE TITLE
Add support for using C++ exceptions instead of setjmp/longjmp to support RAII

### ISSUE THREAD

**Issue by ghost** [svaarala/duktape#75]
Hello,

We have a problem with RAII and automatic destruction via stack unwinding because duktape use setjmp/longjmp.

Lua proposes to use real C++ exception instead of setjmp/longjmp if compiled in C++. Can we add this for duktape too?

The following code will never call the Object destructor from test function.

    #include <iostream>
    
    #include "duktape.h"
    
    class Object
    {
    public:
    	Object() = default;
    	~Object()
    	{
    		puts("Destroying object");
    	}
    };
    
    duk_ret_t test(duk_context *ctx)
    {
    	Object o;
    
    	duk_push_string(ctx, "hello");
    	duk_throw(ctx);
    
    	return 0;
    }
    
    int main(void)
    {
    	auto ctx = duk_create_heap_default();
    
    	duk_push_global_object(ctx);
    	duk_push_c_function(ctx, test, 0);
    	duk_put_prop_string(ctx, -2, "test");
    	duk_peval_string(ctx, "try { test(); } catch (ex) { print(ex); }");
    
    	return 0;
    }

**Comment by ddevienne** [comment]
+1. I'm waiting on C++ exception support to be able to use duktape.

**Comment by svaarala** [comment]
I'm reworking call handling in 1.4 release, and this work includes refactoring code so that it'll be easier to replace setjmp/longjmp with C++ exceptions. If all goes as planned adding support for C++ exceptions within 1.4 release might be doable.

**Comment by seanmiddleditch** [comment]
Please make sure exceptions can be turned off in C++ mode. Most games and many other embedded users compile with -fno-exceptions or their compiler's equivalent.

I don't think setjmp/longjmp are better for said cases but rather that throwing Duktape exceptions through C++ code needs to be handled with a more explicitly-controllable API, not implicit magic.

Bound functions should be required to signal that they want to throw and then return explicitly (removing the need for either longjmp or C++ exceptions entirely), and Duktape exceptions should not cross C function boundaries (C functions calling into Duktape can query if an exception was raised and then resignal+return as appropriate).

**Comment by fatcerberus** [comment]
This is basically what a protected call is now: If you do duk_pcall() and the called code throws, the protected call returns with an error code and leaves the thrown object on top of the stack.

**Comment by svaarala** [comment]
@seanmiddleditch Using C++ exceptions (internally) instead of setjmp/longjmp will certainly be a config option and off by default.

With regards to errors not crossing function boundaries, are you suggesting a change to current behavior (with setjmp/longjmp)?

In the current behavior longjmps do cross function boundaries unless the caller uses a protected call. Changing this would be quite awkward, because almost any API call anywhere may throw - property reads can cause getters to throw, coercions may throw, any value push may run out of memory, etc. That's why the API is split into unprotected and protected calls; call sites can use a protected call to ensure they capture control on an error and can then clean up properly. This pattern is used internally.

**Comment by svaarala** [comment]
First version of this provided by #499.

**Comment by kzc** [comment]
Fantastic!
