### ISSUE TITLE
Align with changes in Node Buffer API

### ISSUE THREAD

**Issue by saghul** [svaarala/duktape#763]
I guess this one could go as part of the 2.0 release.

The various constructors have been deprecated, in favor of some `Buffer.from*` functions: https://nodejs.org/api/buffer.html#buffer_buffer_from_buffer_alloc_and_buffer_allocunsafe

I guess we don't need `Buffer.allocUnsafe` because Duktape always zeroed the buffers anyway, AFAIK.

Also, I understand encodings are not currently supported. Should Duktape assert or throw if someone tries to use them? https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings Right now this is silently ignored, which is quite confusing.

**Comment by svaarala** [comment]
Sounds like good change candidates for 2.x.

I agree about the encoding: supporting all the encodings would be a big footprint issue (but maybe they could be handled by an external optional provider), but Duktape could at least throw if the encoding is not UTF-8.

**Comment by svaarala** [comment]
Re: zeroing, by default Duktape always zeroes all allocated buffers, including Node.js Buffers. Typed arrays have that requirement from the specification while Node.js Buffers don't.

However, if you unset `DUK_USE_ZERO_BUFFER_DATA` Node.js Buffers won't be zeroed by default anymore (but typed arrays will because that's required).

**Comment by saghul** [comment]
> However, if you unset DUK_USE_ZERO_BUFFER_DATA Node.js Buffers won't be zeroed by default anymore (but typed arrays will because that's required).

I guess this could also be changed in 2.0? Or we could go the allocUnsafe route.

**Comment by svaarala** [comment]
That config option also affects behavior of `duk_push_buffer()` etc - with the config option unset, the only buffers that will be zeroed are typed arrays (ArrayBuffers) because that's mandated by the specification. There are a few environments where buffer zeroing is a concrete performance issue (or at least perceived as one) which is why the option was added.

**Comment by svaarala** [comment]
Couple of changes noted in plain buffer as ArrayBuffer work:

- Buffer.byteLength() recognizes ArrayBuffers and typed arrays
- new Buffer(arrayBuffer) should create a Buffer sharing the same underlying storage

**Comment by svaarala** [comment]
Buffers.rst now has a future work section which documents the gap to Node.js v6.7.0.

**Comment by svaarala** [comment]
There's a concrete laundry list in #1048 for Node.js v6.9.1 so closing this.
