### ISSUE TITLE
Load module in strict mode

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#772]
I would like a way to force module code to be evaluated in strict mode, similar to the `DUK_COMPILE_STRICT` flag for `duk_compile()`.  Currently this requires explicitly prepending `"use strict";` to the module code returned from `modSearch`, which is awkward and causes unnecessary string churn.

**Comment by saghul** [comment]
Oh, is that so? In sjs I load the user suplied file in strict mode (with that flag), so aren't all the required modules kinda "inheriting" it?

**Comment by fatcerberus** [comment]
I don't think so?  ‘modSearch‘ returns a string of the module code which Duktape then runs using the equivalent of ‘eval()' (after adding a function wrapper).  Since that eval is indirect I doubt if it inherits strictness from the caller.

**Comment by saghul** [comment]
Doh, I guess I have some fixing to do :-S Thanks!

**Comment by svaarala** [comment]
Yeah, strict mode is "inherited" lexically so that nested functions will inherit it. Modules aren't lexically nested so they don't inherit it.

I'm not sure it's necessarily good if modules are automatically strict. The `'use strict'` declaration is the standard way and if I were to look at a source file missing that I'd assume it would work in non-strict mode. But this is of course ultimately up to the application and there are probably cases where automatic strict mode makes more sense.

**Comment by saghul** [comment]
FWIW, I wanted to do this to avoid typing 'use strict' at the top of everything...

**Comment by svaarala** [comment]
I know :) But then any scripts you write will execute differently in other engines. That may be fine in some cases but in others it may also be confusing.

**Comment by svaarala** [comment]
@saghul Not sure if this was already mentioned but you could simply do this in your modSearch:

```js
var src = getSourceFromSomewhere();
return '"use strict";' + src;
```

Since there's no newline, line numbers won't be disturbed.

**Comment by saghul** [comment]
Humm, I'm doing it in C, but that could work!

**Comment by svaarala** [comment]
There's no agreed on concrete change here, and module loading is no longer part of Duktape core functionality (it's always provided by the application, though there are ready-to-use extras) so this is not directly relevant to Duktape core.
