### ISSUE TITLE
Approaches to multi-threading

### ISSUE THREAD

**Issue by saghul** [svaarala/duktape#834]
I'm thinking about how to add multi-threading support to sjs and since everything I have come up with is kinda not ideal, I'm opening this issue so someone can elucidate me :-)

The way I see it there are 2 ways to do this: using "green" threads or coroutines (Duktape.Thread) or using native threads.

Duktape coroutines have severe limitations, the biggest one I see is the inability to yield while in C code. If this was a possibility one could write some network server and handle each request in a Duktape thread, and each blocking call would yield, and resume once the result is available. This would be similar to Python's Stackless sibling. The other problem with this is that we wouldn't be exploiting the multiple cores either, so we need to add some native threads into the mix, which brings us to point 2.

Using native threads looks like has another set of problems: the same heap cannot be used from 2 threads. So I guess I could create a new one for each thread, which basically would make these threads look like child processes, since no data sharing is possible. Some serialization mechanism would be necessary, which means code needs to be written with this in mind. Not necessarily bad, but multi-threading without the possibility of data sharing is... unexpected. The upside is that there are no possible race conditions! :-)

Right now I have the following idea in mind: use native threads and create a new heap for each. When creating the thread, I'd get a callable, which I compile to bytecode, and pass it around so I can execute it on the fresh heap. Then use a couple of pipes for communication. One important unsolved problem is that while this allows for threads A and B (assuming A spawned B) to communicate, it doesn't allow for threads B and C (assuming A spawned C) to do so, because they don't know about each other. I could use a global list to store thread identifiers and some associated data, but it sounds quite hackish.

Did I miss anything painfully obvious? Thoughts?

**Comment by svaarala** [comment]
I don't think you missed anything obvious, that's pretty much the big picture.

Regarding coroutines, you can use coroutines for networking if the yielding code is Ecmascript. For example, for a socket read a native call can return "no data right now" and an Ecmascript read implementation can yield until more data is available. This same approach works whenever native code would block.

It'll be possible to relax the C yield/resume limitations a little bit, but it'll require native code to explicitly support a resume for a function. Having the resume work with no awareness of C code means, essentially, switching C stacks which is quite unportable (but would otherwise be nice).

That IPC issues sounds like a classic discovery problem, which often involves some kind of client registry, discovery broadcasts, or similar.

**Comment by fatcerberus** [comment]
It should be noted that Node.js is single-threaded, and they actually tout that as an advantage!  I think the thinking there is that you don't pay for context switches that way; to take advantage of multiple cores, you're supposed to fork the process.  I don't necessarily agree with it being a boon, but yeah.

At the end of the day it's just the nature of the beast - JavaScript itself is traditionally single threaded, having been designed for the web in a time before multi-core processors were even a thought and Moore's Law was still very much in effect.

**Comment by svaarala** [comment]
That's true, even web workers are essentially IPC.

There are a few things that could be improved to make life easier:

- Relaxing the coroutine limitations; this needs some awareness from C code most likely, in effect having the ability to resume a previous call. This should be a flag in a function's internal flags so that specific functions would have that ability where it matters.
- Relaxing the threading limitations so that when a certain Duktape thread (coroutine) suspends, one can resume another. This is currently not possible due to some internal limitations but @andoma has requested this a long time ago (and unfortunately it's still not implemented).
- Make it easier to shuffle values between Duktape heaps for IPC. This won't work for generic values but maybe some useful subset (which would be larger than JSON) would be possible. For example, loop-free objects with function values dropped but types like `ArrayBuffer` etc preserved (copied).

**Comment by saghul** [comment]
@fatcerberus I don't disagree :-) But with sjs I'm experimenting with using JavaScript just as a language, not the whole eventing thing around it. You can build it on top of select / poll / and friends. For a low number of connections, threads are still better than a single threaded event loop.

I'll sleep over this for a while and start prototyping some approach. If I'm not back, send help! :-P

**Comment by svaarala** [comment]
@saghul Using several native threads and multiple VM instances is also quite common with e.g. Lua. It often comes up when a platform mostly provides blocking API calls, so that it's necessary to isolate those calls in separate (permanent or temporary) VM instances and use some form of IPC between the instances.

In these situations it'd be awesome if there was some basic IPC support code included in the distributable (not part of the core but something you could take into use with relative ease). One natural thing might be to include some deluxe value serialization/deserialization code with Duktape so that it'd be easier to build the IPC stuff without actually providing an eventloop (which is very environment sensitive).

**Comment by fatcerberus** [comment]
Value-sharing between heaps would be great - I've sometimes wanted this, e.g. as a way to run a transpiler script in a separate heap but rethrow any errors within the main context.

**Comment by svaarala** [comment]
There are maybe two separate issues there: an IPC mechanism which maps functions, arguments, success results, and error results somehow to serializable values; and a serialization mechanism for values which would preserve values to some extent, e.g. supporting Error instances.

Serializing primitive values and objects without caring about inheritance etc (like JSON does) is relatively clean, and can be improved on by supporting more types (like JX does). Having an efficient format (binary) for sharing values with at least the typing support of JX would be one obvious solution and a lot faster than using JX.

From that point on it's a bit less clear. The "full problem" involves serializing object graphs, inheritance chains, function objects, native resources, etc. This is an important problem and certainly worth working on, but it's not a very easy problem (bytecode dump/load handles one difficult subset of it to a large, but not 100%, extent).

Choosing something between these two extremes is also not easy; it can easily lead to versioning issues because the set of values that are faithfully serialized needs to change over time. For example, it'd be quite useful to serialized Errors so that they come out as Error instances (preserving at least a part of their inheritance chain) but what to do about user errors? Or error objects that depend on added methods in `Error.prototype`, etc. Similar issues apply to buffer objects, and many other things, whose importance varies depending on the application.

**Comment by andoma** [comment]
> Relaxing the threading limitations so that when a certain Duktape thread (coroutine) suspends, one can resume another. This is currently not possible due to some internal limitations but @andoma has requested this a long time ago (and unfortunately it's still not implemented).

Yeah, it would still be awesome to have that :-)

**Comment by oleavr** [comment]
> Relaxing the threading limitations so that when a certain Duktape thread (coroutine) suspends,
> one can resume another. This is currently not possible due to some internal limitations but
> @andoma has requested this a long time ago (and unfortunately it's still not implemented).

Also very interested in this for [Frida](http://www.frida.re) :-) Our current challenge is that we allow the user to call any native function from JS, so without a way to let go of our lock to allow other native threads to execute JS while we're calling out to an unknown function, it's very easy to end up in dead-lock situations.

Was wondering though, if we create separate Duktape Threads for each native thread, is there anything else than `duk_ljstate` that needs to be maintained per thread? Just wondering if this is worth trying to implement, or we'd be better off making our `NativeFunction` primitive provide a way to perform an asynchronous call, and allow `NativeCallback` (callbacks from C to JS) to return a `Promise` to make the C code yield until the promise is fulfilled.

**Comment by oleavr** [comment]
Took a stab at it here:
https://github.com/frida/frida-gum/commit/79cd01d694eda61a156fe914c151b23a948622d3

(I patched the generated source for now as the patch is so small and I have no idea if this is going to work well. All of Frida's tests are passing, but I still haven't tried this on real-world code yet; going to do that next.)

**Comment by svaarala** [comment]
@oleavr The alternatives I've looked into were basically: (1) something transparent that doesn't require application cooperation and (2) something like you proposed, an explicit thread suspend/resume. The former seems difficult; for example, if you resume a different thread without Duktape being really aware of the switch, any uncaught errors from the new thread are caught by the previous thread which is highly confusing. So, at least as a first API iteration, an explicit suspend/resume would probably be the better choice.

Your quick stab is pretty close to what I've been thinking. There are a few alternatives how/where the suspend state could be saved (for example, it could be on the value stack somewhere or in calling C state). Encapsulating it in a struct like you do seems like a good idea; I've been trying to reduce the state that needs to be suspended but there are still a few awkward fields left and the set of fields is quite likely to change over time.

**Comment by svaarala** [comment]
One of the things that doesn't really work well with the thread suspend/resume are any native stack recursion depth limits. Depending on whether the new calls (after suspend) are made using the same or a different native thread the limits may or may not be useful. There are various other concrete issues with trying to establish safe limits, so my plan has been to remove the limits and replace them with something like #231 for environments where accurate stack limit checks matter - as a result, it doesn't matter much whether the limits work perfectly with an initial suspend/resume implementation.

**Comment by oleavr** [comment]
@svaarala Cool! Thanks for reviewing – glad to hear I'm not entirely on crack here. :-) I also think that (1) sounds like a tricky one, and (2) clearly has the advantage of being explicit, so it avoids surprises, and also means there's no added performance overhead for the simpler use-cases.

I see your point on the stack limits, so replacing those sounds great. For my current use-case the Duktape-threads are always used to completion on any given native thread, so that should be alright for now. The current implementation just uses a flag to know if the heap thread is currently in use, so if native thread A is already using it and native thread B wants to execute JS it will see that the flag is set and create a new Duktape thread that it keeps alive in the global stash, and lets go of once it finishes the JS call. (The assumption is that most of the time there will only be a single native thread executing JS.)

**Comment by oleavr** [comment]
Just submitted a PR with my slightly evolved version in #893. Been stress-testing it a lot lately and no problems so far.

**Comment by svaarala** [comment]
The tasks for 2.0 are now tracked by #391 and there's an initial implementation by @oleavr in #893, so closing this.
