### ISSUE TITLE
require.id on global object not anymore?

### ISSUE THREAD

**Issue by mxmauro** [svaarala/duktape#849]
Hi Svaarala, (created different issues to separate them)

In the past, by your recommendation, I set require.id to the filename of the global object so DukTape's `require` with a relative path can be resolved successfully.

Now seems require object on global no longer exists. What can I do to mimic the old behavior?

BTW, Please re-add the allocation failed to DUK_ERR_xxx list. In my opinion is a fatal error different from other fatal errors.

Regards,
Mauro.

**Comment by fatcerberus** [comment]
The CommonJS system has been removed from the core and now requires integrating one of the module loader extras:
* Duktape 1.x compatible: https://github.com/svaarala/duktape/tree/master/extras/module-duktape
* Node.js like (this might be better if you want Node-style relative path resolution): https://github.com/svaarala/duktape/tree/master/extras/module-node

**Comment by svaarala** [comment]
@mxmauro Re: the alloc error code, just to be clear allocation errors are not fatal errors (i.e. fatal error handler is not called) and they can occur in harmless situations without needing special treatment, e.g. `new ArrayBuffer(1e9)` on a low memory device. (Interestingly e.g. Node.js seems to treat an alloc error as a fatal error which seems risky for sandboxing/containment - granted, they're not easy to handle correctly.)

I could add back the alloc error code, but to be consistent with how error codes and error objects relate to each other I'd also need to add an Ecmascript `AllocError` so that the error code would have an Ecmascript counterpart. Without this in place, when an alloc error is thrown, there's no way to detect that the error object is an `AllocError` (this check is based on the error object inheritance chain).

But more importantly, how would one actually use that specific error type in practice? Would a C call site have some special handling for an alloc error, different from other errors?

**Comment by mxmauro** [comment]
@fatcerberus Thanks for the info.

@svaarala: I'll answer the alloc issue in the exception handling issue because they share some points.

**Comment by fatcerberus** [comment]
@svaarala: Regarding fatal errors for "harmless" alloc failures: Node.js is designed for desktop platforms (specifically servers) with large amounts of RAM.  Generally on these platforms if an allocation fails, assuming the application requested a reasonable size allocation, there's not a lot of room left to recover.  Crashing was probably seen as the most useful default.

If I remember correctly with V8 though, it's up to the application to provide an allocation helper for buffer objects as the engine itself doesn't provide one.  So if Node.js raises a fatal error for insane ArrayBuffer allocations too, that makes less sense.

**Comment by mxmauro** [comment]
Yes, one of the reasons I like DukTape is because you can have control of the whole engine.

V8 calls abort on fatal errors without giving you chance to ignore it, I.e. you have a webserver I would like to keep it running and return error 500 when possible instead of shutting down the app until memory condition is normalized.

**Comment by svaarala** [comment]
@fatcerberus Node.js behavior is a bit off topic but for me it's pretty weird that a server process (which Node.js is also used for) would abort when an alloc fails. This is what happens now with Node.js:

```
sva-p@keppihevonen:~$ node
> b = new ArrayBuffer(1e9);
{}
> try { v = new Uint8Array(b); } catch (e) { print('aiee'); }
FATAL ERROR: invalid array length Allocation failed - process out of memory
Aborted
sva-p@keppihevonen:~$
```

**Comment by fatcerberus** [comment]
Hm, I wonder if it's actually Node that's aborting though or just hardcoded V8 behavior.  Maybe someone should file a bug against the Node.js repo. :)

**Comment by mxmauro** [comment]
It is hardcoded in V8

**Comment by fatcerberus** [comment]
Anyway, I guess this issue should be closed since there's no bug.

**Comment by mxmauro** [comment]
Yes I'll close it... thank you both for the info.
