### ISSUE TITLE
Version 1.5.0 use-strict issue

### ISSUE THREAD

**Issue by amerkoleci** [svaarala/duktape#873]
I have script compiled with typescript and when I load it in duktape with latest 1.5.0 it evals with success but when i execute a function it does not finds the function, to workaround this issue i'm ommiting typescript use-strict declaration with noImplicitUseStrict param

**Comment by svaarala** [comment]
Use strict should be working - can you narrow the problem down in any way?

**Comment by amerkoleci** [comment]
Take this code:
`use-strict;
function initialize() {
}
;
function update(time) {
}
;
function draw() {
}
;
function shutdown() {
}
;
//# sourceMappingURL=main.js.map`

Load it this way:
`
String source = "......."; // loaded from file
duk_push_string(ctx, fileName.c_str());
if (duk_peval_string(ctx, source.c_str()))
{
  // Do error logging
}
duk_pop(ctx);
`

Then when you call it in this way:
`
duk_get_global_string(ctx, "initialize");
if (duk_is_function(_ctx, -1))
{
  // Never enters here
}
`

**Comment by svaarala** [comment]
Right, that's actually correct eval behavior: strict eval code has a local scope for variable declarations so that they don't pollute the calling scope (here the global object). For example, if you eval the following:

```js
eval('"use strict"; function myfunc(){}');
print(typeof myfunc);
```

It will print `undefined`. Without the "use strict" it will print `function`.

If you want global bindings to be created from strict code function declarations, you should compile the script using `duk_compile(ctx, 0)` which compiles the source (by default) as "program code" instead "eval code". There are subtle differences between the two, especially w.r.t. scopes and bindings. Then execute the result using `duk_call()`. Use protected calls if there's no existing protected call catcher like `duk_safe_call()`.

**Comment by svaarala** [comment]
This comes up relatively often so added Wiki issue for explaining the differences and providing code samples for each context: https://github.com/svaarala/duktape-wiki/issues/130.
