### ISSUE TITLE
Add a bytecode executor timeout mechanism

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#90]
Add a basic mechanism for interrupting execution when a user-provided callback function indicates the script has been executing for too long:

- [x] Add a macro-based callback and prototype the mechanism

**Comment by sogard** [comment]
Please, also consider implementing a suspend/resume mechanism. 
I have integrated duktape in a tiny webserver (without threads) and want to multiplex javascript execution with the network events. 

Something like: 
```C
     /* SMALL_SLICE - some parameter how much time/ instructions to execute */
      duk_pcall_sliced(ctx, 0, SMALL_SLICE ); 
     while(1) 
     {   
           handle_network_events();
           result = duk_continue_pcall_sliced(ctx); /* Continue execution of the call ... */
           if(result == DUK_DONE_EXECUTION) 
           {
                // Handle returns ... 
                // eventually start another call 
           } else if(/* If we timeout, or the connection was closed ... */)
           {
                duk_abort_pcall_sliced(ctx);
           }; 
           handle_network_events();
           ... 
      }
```

I think this is a extremely important feature for embedded devices where multiplexing is necessary but also is very useful for server environments that target to resolve the C10K problem. 

Some more ideas:
* support switching between corutines to make it more "threadish" (non cooperating)
* single step support/breakpoints

If you think this will not be implemented to soon, pleas give me some hints how do you think it should be implemented and maybe I will give it a try to make a quick and dirty hack. 

For now I cheated by spiting javascript code small chunks that I make sure that will return in time to handle network events, but this is not really a solution.

**Comment by svaarala** [comment]
@sogard If I understand correctly you can implement what you want with coroutine yield/resume. You'd need to implement a scheduler that keeps track of executing coroutines and what they're waiting for (timer, data read, etc), and then resume them as appropriate.

Anyway, coroutine changes should be unrelated to an execution timeout mechanism (which involves no "resume" component) so perhaps a separate issue should be opened.

**Comment by sogard** [comment]
Nop. I mentioned corutines as a crazzy idea I  had but the real topic is suspending duktape execution after a certain amount of time and do some other stuff before resuming the javascript execution.

The idea is that I handle multiple network connections in the same thread and I also execute js for processing some of the data from/to connections is a script is taking to long to execute the rest of the connections are stalled because the code is executing a duk_pcall() and can not handle the rest of the connection until duk_pcall is returned. 

The reason why is working right now for me is because I have write the javascript function to return after some amount of processing is done, and execute the function and continue processing  and I have to keep track of them  "outside" in C code. But I expect that some other people write some javascript that will not return from time to time and will hang everything until return.

**Comment by svaarala** [comment]
Basically what you'd be looking for is an automatic "yield" after a certain amount of time.

**Comment by sogard** [comment]
Yes, you are right this can be implemented this way. But that means wrapping all calls in a "Duktape.Thread.resume" which is inconvenient. 

And also means that the "bytecode executor timeout" can be implemented with an automatic "yield" that never return or a automatic "throw".

What I really want is just a callback that gives me control of execution back to C code from time to time without cooperation of javascript in anyway and and where I can decide if the script should continue executing or not.  
Even if just a callback without possibility to abort the script will be sufficient.

**Comment by svaarala** [comment]
Merged a primitive macro-based mechanism:

https://github.com/svaarala/duktape/commit/9fd7e71493d56deb55898e5408e1cee6a9420d86

See "ajduk" target for a concrete example (the example has a 5 second timeout):

```
$ make clean ajduk
$ ./ajduk
[...]
duk> for (;;) {}
RangeError: execution timeout
	duk_js_executor.c:1373
	global input:1 preventsyield
```

**Comment by svaarala** [comment]
Improvements moved to #160.
