### ISSUE TITLE
Optional separate duk_internal.h  from duktape.c

### ISSUE THREAD

**Issue by harold-b** [svaarala/duktape#904]
Hi Sami,

Been having the pleasure over the past few weeks to finally integrate duktape into my framework. I was updating my debugger to v1.5.0 and now I wanted to bring in the patch I had written a while back to allow me to grab closure-scoped keys from a stackframe.

I was hoping to move it into an `AppRequest`, instead of a custom one, in order to be able to use vanilla 1.5. However, I needed access to duk_internal.h for this. So I'd had to copy over the separate headers from the dist into the my project instead of just the duktape.h & duktape.c. In order to keep it like so, I figured I'd just patch the source in a separate branch again and use the single file dist like I did before.

So I was wondering if you would consider adding an option to generate a separate duk_internal.h for the single file solution? This way, making the distributables with said option would yield:
- **duk_config.h**
- **duk_internal.h**
- **duktape.c**        *<-- would include duk_internal.h in this case, instead of embedding it*
- **duktape.h**

This would allow for anyone wanting to add routines or mess with internals --without actually having to modify the source-- to have access to it and still having the simple single-file duktape.c object.

Eager to hear your thoughts are on this. Or if you have a better solution.

Thanks

**Comment by fatcerberus** [comment]
Good to see someone else find a use case for my AppRequest feature. :)

**Comment by svaarala** [comment]
@harold-b I'm doing a related change later on in master, where `duktape.h` contains all the internal structure definitions. This allows the public API to directly access internals, e.g. value pushers can directly interact with the value stack. This would also allow access to internal functions (with the caveat that every commit may break the calling code and there's no warranty ;). However, this may not always work when linking against a prebuilt library because those symbols might not be present in the symbol table.

In any case, this would be equivalent to having a separate `duk_internal.h` but it'd be rolled into `duktape.h`.

**Comment by fatcerberus** [comment]
@svaarala Would it be possible to gate the internal stuff behind a compiler option so that application code can't see it by default and must opt-in?  I often use Intellisense to explore unfamiliar APIs (since this gets me up to speed faster than poring over formal documentation), and that's how I ended up using the undocumented `duk_error_raw()` function in minisphere. ;)

**Comment by svaarala** [comment]
That's a little bit tricky: if a public API macro accesses a function which is not part of the public API, it must be visible for compilation.

**Comment by harold-b** [comment]
>In any case, this would be equivalent to having a separate duk_internal.h but it'd be rolled into duktape.h.
@svaarala Awesome, well that should do it.

For the time being I just patched it as I did before :).
