### ISSUE TITLE
Finalized Object being used after finalization

### ISSUE THREAD

**Issue by harold-b** [svaarala/duktape#914]
I added an anonymous function that does nothing to my test code when making sure my debug client was still working well with local-only scope (As I had been testing with the custom command for the better part of the week) and I started getting crashes right after.

I don't know what exactly introducing this function caused (said function does nothing at all but assign some local number variables to value passed in), but it started causing an finalizable object that I have be used even after it has been finalized.

The object in question is a wrapper to a native object, which allows me to draw debug text and line in my framework, so I use it every frame. For this particular object I don't keep any references to it stashed anywhere so it's eligible for garbage collection as per normal requirements in the scripting side.

The finalizer gets called just fine, and I then recycle the 'glue' object tat binds the native object to the scripting object. Right after, however, that very same object is used to draw some text!

If  I remove that dummy anonymous function (see `_game.update()` below), then it works normally as it did before. However, when I place it back in there, even when it's commented out, as shown below, it causes that error.

It's going to be a bit hard to show what is going on given that is deeply bound to my framework but I'll do my best to help.

This is the basic flow of the program *(typescript)*:
``` typescript

/// Called from the native side with the correct 'this' binding:
App.ts.update()

// Inside update, i do some debug drawing and updating a native renderable object.
// I call also call some dummy javascript functions that
// are simply there to help me test debugging:

public update( dt:number ):void
{
    this._time += dt;
    
    let time  = this._time;
    let math  = Math;

    let pt    = 24;
    let y     = 10-pt;
    let fps   = 1.0 / dt;
    let dd    = musa.DebugDraw.default;  // This is the object being collected then used
    let mouse = this._mouse;

    // This does nothing
    let func = ( aLocal:boolean ) => {

        let mouse = this._mouse;
        let keys = this._keys;
    }

    // Here, normally, I have no errors.
    // However, after adding that dummy function within _game.update(),
    // when it gets to this next call, the finalizer has already been called.
    dd.drawText( "FPS       " + math.round(fps), 10, y+=pt, pt );
    dd.drawText( "Time      " + time, 10, y+=pt, pt );
    dd.drawText( "DeltaTime " + dt,   10, y+=pt, pt );
    dd.drawText( `Mouse     ${mouse.x} ${mouse.y}`, 10, y+=pt, pt  );

    func(true); // Call dummy function

    // _game.update is another dummy function,
    // inside of which is the culprit, the anonymous function
    // which is causing all the trouble.
    // Please see the next code block to see it's internals.
    this._game.update( dt );

    this.updatePlayer( dt );
}
```

``` typescript
// this is _game.update()

update( dt:number ):void
{
    let x = 0;
    let y = 2;
    let z = y + x + 2;

    // This is the culprit!
    let f = (xx) => {
        let x = xx;
        let y = x;
    }
    //f(x);
}
```

I've no idea why this happens! Any ideas what could it be?
I'll try to provide with as much context as I can given it's a foreign codebase.

**Comment by svaarala** [comment]
What version of Duktape are you using and what patches do you apply to it?

Re: commented out `f(x)`, declaring an inner function actually has some reference counting implications because that function will reference its outer scope (and vice versa). So it's not abnormal for garbage collection for such a function instance to be affected.

It'd be maybe useful to see what the typescript-compiled files look like, as that's what Duktape is ultimately running.

**Comment by fatcerberus** [comment]
Related to #108, I wonder?

**Comment by harold-b** [comment]
Here's the transpiled script that I load on duktape: [pastebin](http://pastebin.com/kLAJhi4b)

I'm running off of the v1.5.0 tag. The branch I'm using only applies modifications to **debugger.h/c** you
can see it here: https://github.com/harold-b/duktape/commit/5edc585e0c8452d20af74280fff52d6ad77259e8

I'll try with vanilla 1.5.0 to make sure all is well.

**Comment by svaarala** [comment]
@fatcerberus Maybe - though there are no confirmed open issues for finalizers at present. There was an issue with try/catch which you encountered, and another which affected refcount-finalized objects which were rescued by their finalizer. Both are fixed in 1.5.0 (and 1.4.1 for 1.4.x).

**Comment by harold-b** [comment]
Just tested with vanilla v1.5.0. Same issue :(

My log on creation/finalization, and the drawText function which notices the finalized object:
```
+ Created Default DebugDraw: 0x07F03408
- Destroyed Default DebugDraw: 0x07F03408
Error, Drawing with finalized object!
```

**Comment by svaarala** [comment]
@harold-b Just to clarify a few issues in your description:

- When you say "wrapper for a native object", do you mean that there's an Ecmascript object which somehow references a native object which is outside the Duktape heap? Is there, for instance, a plain pointer in the wrapper object to the native resource, or how does this work?
- You said you don't keep any references to the wrapper object so that it's eligible for garbage collection - what does this mean in practice? There must obviously be a reference to the object somewhere if it is used? Is the object live, for example, for a single frame and then a new one is created?
- Are you using `duk_get_heapptr()` for managing references to this or other objects? If so, is their reachability guaranteed at all times before the corresponding `duk_push_heapptr()`?
- When you say you "recycle the glue object", could you be more specific what that means?

It would be useful if you could identify the problematic object and write out what happens in the life cycle of that object. In other words how is it allocated, what properties does it have, what does the finalizer do, what does "recycling" mean in this context, etc.

**Comment by harold-b** [comment]
Ok, in regards to your queries:

> When you say "wrapper for a native object", do you mean that there's an Ecmascript object which somehow references a native object which is outside the Duktape heap? Is there, for instance, a plain pointer in the wrapper object to the native resource, or how does this work?

Yes, it's an Ecmascript object that contains an internal property which is a pointer to a 'glue' object which contains information about the native object and the Ecmascript object.

The 'native object' being a game-engine object, in this case the "DebugDraw" object.

The 'glue' object contains a pointer or handle to the native object, and a heapptr/weak reference to the Ecmascript object. It also contains a type identifier that allows me to identify what kind of native object it represents, and optionally a 'strong reference' to the Ecmascript object. Which is really an index into a stash array which stores the Ecmascript object. This particular native oject (DebugDraw) does not use strong references.

The native object itself is given a script reference that points to the 'glue' object.

> You said you don't keep any references to the wrapper object so that it's eligible for garbage collection - what does this mean in practice? There must obviously be a reference to the object somewhere if it is used? Is the object live, for example, for a single frame and then a new one is created?

I meant I don't keep any references to the Ecmascript object in terms of retaining a strong-reference. The 'glue' object does contain a heapptr, but in the case of this native object, it's not even used because the native DebugDraw object doesn't need to know about the Ecmascript object.

When we obtain it via `musa.DebugDraw.default` in line 80 of the pastebin, we check our native DebugDraw instance for a script reference, if it does not have one, then we create a new Ecmascript object, and bind it together with the 'glue' object. But because we don't care about retaining this particular object indefinitely, we don't create a strong reference, we just grab the heapptr. When `musa.DebugDraw.default` is called again, because a script reference has been given to it, we just return the Ecmascript object from the heapptr.

When the finalizer is called, the 'glue' object is recycled (they are pooled) and the script reference on the native object is nullified. So subsequent calls to `musa.DebugDraw.default` will create a new glue and Ecmascript object.
(Yes, I know this is not efficient to let it be GCed all the time, but it's like that right now for testing purposes only.)

> Are you using duk_get_heapptr() for managing references to this or other objects? If so, is their reachability guaranteed at all times before the corresponding duk_push_heapptr()?

I'm using `duk_get_heapptr()` when I create the 'glue' object to store the weak ref. Reachability is not guaranteed because we get rid of it once it's finalized.

> When you say you "recycle the glue object", could you be more specific what that means?

The 'glue' objects are preallocated in a big pool, so when an object is finalized they are released back into the pool and part of the memory they occupy is used as a linked list to the next free pooled object. This is how I noticed what exactly was causing the crash, because the native pointer in the glue object was '0x07', I put a data breakpoint on it triggered when the object was released and the native pointer address in the glue object was replaced by an index of the next free object.

**Comment by svaarala** [comment]
Hmm, lot of information here :) But did I understand correctly that you call `duk_get_heapptr()` and keep that pointer value around for an object that is not strongly referenced?

So the important guarantee I'm trying to verify is that: between a `duk_get_heapptr()` and `duk_push_heapptr()` the object in question must never be unreachable, not even temporarily, or all bets are off. Is this guaranteed in the wrapper approach?

**Comment by harold-b** [comment]
@svaarala Yes, because we only use `duk_push_heapptr()` in `musa.DebugDraw.default`, which if a finalizer was called before it, will release the 'script reference' in the native object, causing it to create a new one. So I'm actually depending on duktape's gc semantics here to manage the lifetime for me.

**Comment by svaarala** [comment]
So just so I understand the setup:

- A glue object is a native object, whose allocation is outside the scope of Duktape. It's referenced by an opaque pointer as far as Duktape is concerned.
- A wrapper object has some internal property (say `_gluePointer`) which points to the native glue object.
- A glue object weakly references the wrapper object, via a `duk_get_heapptr()` obtained pointer.
- A wrapper object has a finalizer which will look up the glue object, and ensure the `duk_get_heapptr()`-obtained pointer is never used once the wrapper is finalized.

To clarify the symptom: do you get an unexpected call to the wrapper (how do you identify that if so?) or an unexpected call using the freed glue object (how do you identify that if so)?

Just to make sure, could you add some running identifier to the wrapper object and log that, to make sure that it is indeed the *wrapper* which gets called after finalization, instead of a new wrapper referencing a freed glued object.

Another thing, could you make sure your finalizer doesn't throw an error? Finalizer errors are ignored silently, which can sometimes lead to odd issues. It's best to `duk_safe_call()` the entire finalizer body if in doubt.

**Comment by harold-b** [comment]
Here are some snippets from my binding code, in case it helps:

*Note: The aforementioned 'glue' object is named here "ScriptedObject"

``` C++
// This corresponds to 'musa.DebugDraw.default'
static duk_ret_t get_default( duk_context* cx )
{
    /// Stack Args: [0]

    JS_ASSERT( !duk_is_constructor_call( cx ) );
    
    // Return default engine debug draw.
    ScriptContext* sc     = GetStashedSystem( cx );
    Engine*        engine = sc->_engine;

    DebugDraw*  dd    = engine->dbgDraw;
    MusaObject* muObj = dd->GetMusaObject();

    if( muObj->script != MUSX_NULL_SCRIPT_REF )
    {
        // Safe to return a heapptr here because
        // the finalizer should never have been called,
        // otherwise muObj->script == MUSX_NULL_SCRIPT_REF
        ScriptedObject* so;
        so = OpenScriptReferenceObject( sc, muObj->script );

        duk_push_heapptr( cx, so->sptr );   // [dd]
    }
    else
    {
        // No script reference, so we create a new one here.
        // We only store a weak reference here,
        // 'CreateScriptedObject' will use 'duk_get_heapptr()'
        ScriptedObject* so;
        Scripting::AllocJSObjectByType( sc, TYPE_DEBUG_DRAW );  // [dd]
        so = sc->CreateScriptedObject( 0, dd, TYPE_DEBUG_DRAW );

        Log::WriteLine( "+ Created Default DebugDraw: 0x%08X", so->sptr );
        muObj->script = Scripting::MakeScriptReference( sc, so );
    }
    
    // [dd]
    return 1;
}

// This is the finalizer code:
static duk_ret_t fin( duk_context* cx )
{
    /// Args: [ target:Object, heapDestructing:bool ]

    ScriptedObject* so;
    so = GetScriptedObjTypeNoThrow( cx, 0, TYPE_DEBUG_DRAW );
    if( so != nullptr )
    {
        Log::WriteLine( "- Destroyed Default DebugDraw: 0x%08X", so->sptr );
        ScriptContext* sc = GetStashedSystem( cx );
        DebugDraw*     dd = so->CastNativePtr<DebugDraw>();
        
        // Release ScriptedObject, we will create one again 
        // if the user requrests another DebugDraw.
        MusaObject* muObj = dd->GetMusaObject();
        muObj->script = MUSX_NULL_SCRIPT_REF;   // Here we nullify the reference of the (glue) ScriptedObject
                                                // so when 'musa.DebugDraw.default' is called again, we must create a new one.
        sc->DestroyScriptedObject( so );
    }

    return 0;
}
```

**Comment by harold-b** [comment]
> A glue object is a native object, whose allocation is outside the scope of Duktape. It's referenced by an opaque pointer as far as Duktape is concerned.

Correct

>A wrapper object has some internal property (say _gluePointer) which points to the native glue object.

Correct

> A glue object weakly references the wrapper object, via a duk_get_heapptr() obtained pointer.

Correct (at least as this object is concerned)

> A wrapper object has a finalizer which will look up the glue object, and ensure the duk_get_heapptr()-obtained pointer is never used once the wrapper is finalized.

Sort of, we don't delete the internal property or anything, we're counting on duktape to never call a native function with that object as the 'this' binding again, once the finalizer has been called.

We do nullify the script reference from the native object when the finalizer is called as you can see above:

``` c++
MusaObject* muObj = dd->GetMusaObject();
muObj->script = MUSX_NULL_SCRIPT_REF;
```

> To clarify the symptom: do you get an unexpected call to the wrapper (how do you identify that if so?) or an unexpected call using the freed glue object (how do you identify that if so)?

> Just to make sure, could you add some running identifier to the wrapper object and log that, to make sure that it is indeed the wrapper which gets called after finalization, instead of a new wrapper referencing a freed glued object.

In the log I showed before you could see the heapptr associated with the Ecmascript object that was being created/called with this binding.
I also added now the heapprt from `duk_push_this` and the first parameter of the finalizer for clarity. You can see here the first address is the address I initialliy got from `duk_get_heapptr()` and stored in the ScriptedObject, the second address I obtained from `duk_push_this()` or the first parameter of the finalizer:

```
+ Created Default DebugDraw: 0x08890590
- Destroyed Default DebugDraw: 0x08890590 | 0x08890590
Error, Drawing with finalized object: 0x08890590 | 0x08890590
```

As you can see it matches.

> Another thing, could you make sure your finalizer doesn't throw an error? Finalizer errors are ignored silently, which can sometimes lead to odd issues. It's best to duk_safe_call() the entire finalizer body if in doubt.

I'm not seeing any errors thrown at all in regard to the finalizer. In fact, I don't think I'm calling any duktape methods there. I also didn't make any explicit calls to the finalizer, the only call into duktape I make is the 'update' method.

**Comment by harold-b** [comment]
I hope that made sense...

**Comment by svaarala** [comment]
I think so - it's quite hard to help with something like this because I don't have the ability to reproduce the issue. So that's why I'm trying to make sure what facts are knowns and make sure the facts are certain to be correct :)

Note that a certain heap pointer value may very well be reused by Duktape: when an object has been freed a new object can be allocated, ending up with the same pointer value. This is even quite frequent, considering that an allocator will have an unused slot of exactly same size as requested.

So what I'd first like to verify with as much certainty as possible, is that it's indeed a finalized Ecmascript object which gets called after being finalized.

To that end a very reliable check would be to add some property like `creationCount` to each allocated wrapper object, and dumping the value of that property in the finalizer and in any method (draw) being called. This would make it unambiguously certain that an object gets finalized too early -- it must be too early because someone is able to reference it after finalization to make that function call (draw).

There are only two logical reasons why that would happen: (1) some mismatch in Duktape reference counting or mark-and-sweep, or (2) some application code mismanaging a pointer obtained via `duk_get_heapptr()` which can seemingly "resurrect" an object (and usually leads to a crash).

**Comment by svaarala** [comment]
By the way, refcount bugs in the engine are quite difficult to spot. There's obviously an attempt in the test coverage to cover as many refcount related code lines as possible but it's never perfect. In particular coming up with finalizer tests that match all the possible scenarios (rescuing, weak pointers, etc) is challenging.

One useful assertion for Duktape reference counting code would be to check that an object added to the "refzero queue" (= ready to be finalized/freed) is indeed not reachable. There's no convenient way to do that at present however, because that assert would essentially mean running mark-and-sweep to figure out the object's reachability status.

In any case an assert like that would detect cases where there are too many refcount decrements or some missing refcount increments.

**Comment by harold-b** [comment]
@svaarala  OK, well, I'll see what I can do to track it, I had to step away from the PC for a little while but I'll be back to debug it more. I'm sorry I can't provide a good test case/context to easily debug this :disappointed:

**Comment by svaarala** [comment]
@harold-b No worries, that's quite common with finalizer issues because they're invariably tied into the native code in a way that makes it difficult to create a reproducible standalone test. I'll try my best to help but at this stage there's unfortunately not enough information to narrow it down so I could figure out a potential cause and maybe come up with a test.

**Comment by svaarala** [comment]
I'm off to bed for a while - I'll check back later on.

**Comment by harold-b** [comment]
@svaarala  No problem, I'm back, so I'll see what more info I can dig up to provide you.

**Comment by harold-b** [comment]
> To that end a very reliable check would be to add some property like creationCount to each allocated wrapper object, and dumping the value of that property in the finalizer and in any method (draw) being called. This would make it unambiguously certain that an object gets finalized too early -- it must be too early because someone is able to reference it after finalization to make that function call (draw).

I tried the approach which you mentioned, I added the internal property 'ccount' to the Ecmascript wrapper object, and I logged the count on creation. Then, each time it called `drawText` I increased and logged the count as well. On the finalizer, I again logged the count. This matched what was reported on the last `drawText` call. Finally, it subsequently called `drawText` (without any new wrapper Ecmascript object ever being created again. The native function for creating one, `get_default`, was never called.) and it indeed reported the same ccount reported on the finalizer:


```
+ Created Default DebugDraw: 0x08F03110
DebugDraw.drawText: (0x08F03110) ccount: 0
DebugDraw.drawText: (0x08F03110) ccount: 1
DebugDraw.drawText: (0x08F03110) ccount: 2
DebugDraw.drawText: (0x08F03110) ccount: 3
DebugDraw.drawText: (0x08F03110) ccount: 4
DebugDraw.drawText: (0x08F03110) ccount: 5
DebugDraw.drawText: (0x08F03110) ccount: 6
DebugDraw.drawText: (0x08F03110) ccount: 7
...
DebugDraw.drawText: (0x08F03110) ccount: 17921
DebugDraw.drawText: (0x08F03110) ccount: 17922
DebugDraw.drawText: (0x08F03110) ccount: 17923
DebugDraw.drawText: (0x08F03110) ccount: 17924
DebugDraw.drawText: (0x08F03110) ccount: 17925
DebugDraw.drawText: (0x08F03110) ccount: 17926
DebugDraw.drawText: (0x08F03110) ccount: 17927
- Destroyed Default DebugDraw: 0x08F03110 | 0x08F03110 ccount: 17928
DebugDraw.drawText: (0x08F03110) ccount: 17928
```

What's bothering me, is that when I was the log string, it would end up creating a and destroying a few DebugDraw Ecmascript objects normally (without calling drawText after finalization, but instead creating a new one), until it finally did the same thing of calling drawText on a finalized one. Whereas usually it was doing it on the first one created.

...Weird...

**Comment by harold-b** [comment]
Hopefully I haven't corrupted more duktape data like I did in the whole realloc fiasco.

**Comment by harold-b** [comment]
I enabled `DUK_USE_DEBUG` and spewed out a 100m log.
[Here's a truncated version](https://drive.google.com/open?id=0B-5FVS50scEReGl4OEVjZ3hXVms), (I cut out large portion of the middle). Hopefully I left enough info in there to help.

Please let me know if it's useful at all. If you see anything unusual that might indicated I've messed something up, please let me know.

I think this is the best I can do for the time being.

Note that the last entry that says:
`[DD] duk_hobject_props.c:3781 (duk_hobject_putprop): put to an existing entry at index 1 -> new value 6946`

And then it says:
`DebugDraw.drawText: (0x087860A0) ccount: 6945`

They have the same value, I just log the current value vs what we just stored (ccount+1).

**Comment by harold-b** [comment]
If you \*happen\* to need the huge original, let me know. I kept it.

**Comment by svaarala** [comment]
Alright, I'll look at this more closely over the weekend (or Monday at the latest). One thing that does pop up is that the finalized object in question has been queued by a previous mark-and-sweep round for finalization, but the finalizer wasn't run then because a mark-and-sweep flag prevented it (some situations require avoiding side effects). Maybe that handling has some sort of a bug.

If so, it would only affect objects in circular references (otherwise refcounting would deal with them), e.g. typical functions.

**Comment by svaarala** [comment]
Hmm, also one thing that might be an issue here: once the mark-and-sweep round has detected than an object is unreachable and has a finalizer, it will get queued for a finalizer run but it takes some time for the object to be finalized and collected:

- In the normal case the finalizer runs on the same mark-and-sweep round as where the object was deemed unreachable. The object is then collected on the next mark-and-sweep round.
- In rare cases the mark-and-sweep is running in a context which prevents finalizer execution to avoid their side effects. In this case an object may be unreachable, queued for finalization, but the finalizer only runs later in the next mark-and-sweep round.

In the rare case, the object has been queued for finalization so it's no longer safe to reference it. Duktape won't do that (assuming it is working correctly) simply because there's no reference to the object anywhere to do that.

However, if an application has a stashed `duk_get_heapptr()`-obtained pointer, *that* pointer value is now unsafe to use -- even if the finalizer hasn't yet been executed. Maybe this is happening here?

**Comment by fatcerberus** [comment]
Either that or the object in question was rescued at some point between being queued for finalization and actually being finalized - but Duktape doesn't acknowledge the rescue.  Don't know if that can actually happen in practice though...

**Comment by svaarala** [comment]
It shouldn't happen here because the finalizer doesn't rescue the object.

**Comment by svaarala** [comment]
Or, well, pushing the object on the value stack (for example) using `duk_push_heapptr()` while the object is waiting for finalization is "sort of" rescuing it. But it's a violation of the `duk_push_heapptr()` API contract because only pointers guaranteed to be reachable at all times can be operated on safely.

**Comment by svaarala** [comment]
Hmm, so to rephrase a bit: an application doesn't currently have any way of detecting the exact moment an object becomes unreachable. It sort of does that for refcounting (but not always, e.g. when debugger is paused), but not for mark-and-sweep. There may be considerable time between an object becoming unreachable and the finalizer running, and then more time before the object is collected. That's kind of hard to avoid in allocation contexts where finalizers can't be executed due to potential side effects.

Providing a *native* callback to indicate "object became unreachable" without actually allowing rescuing or any other side effects would be possible in mark-and-sweep too. It could be called right away when the object is queued for finalizer execution. But I'm not sure if that would make things easier or harder to understand.

If I understood correctly @harold-b is using the finalizer as the endpoint of the pointer lifecycle, in effect emulating weak references. Unfortunately the finalizer semantics don't really allow you to do that, at least without taking the potential delays into account somehow.

**Comment by harold-b** [comment]
I'm here, reading up on the new posts.

**Comment by svaarala** [comment]
The concrete potential issue is that this assignment is not guaranteed for an unreachable object:

    muObj->script = MUSX_NULL_SCRIPT_REF

It may take multiple mark-and-sweep rounds before the finalizer executes so that the script reference will point to an unreachable object. I'm not sure this is the actual issue here, but it's at least a potential one :)

**Comment by harold-b** [comment]
>The concrete potential issue is that this assignment is not guaranteed for an unreachable object:

>muObj->script = MUSX_NULL_SCRIPT_REF

>It may take multiple mark-and-sweep rounds before the finalizer executes so that the script reference will point to an unreachable object. I'm not sure this is the actual issue here, but it's at least a potential one :)


That call is only called from the finalizer itself though. What it does is tell the actual native object that it does not have an Ecmascript representation anymore.

In the issue I'm having, it never gets to the point where it checks again if it has an Ecmascript representation because the next native call immediately after the finalizer is call is the `drawText` call, which it calls for the already-finalized object. 

Inside of `drawText` I get the pointer for the (glue) ScriptedObject* by accessing an internal property, so in this case we never check for the native object's script reference.

**Comment by svaarala** [comment]
@harold-b But is it certain that some other code is not using the script reference between it becomes unreachable and before the finalizer runs? Based on the log the issue is quite possibly related to delayed finalizer execution.

Btw, do you have an idea what code is doing that call by the way? Because mark-and-sweep has deemed the object unreachable, there should be no Ecmascript side references around any longer to make the call, unless native code resurrects a reference using the heap pointer. If this is indeed certain, then mark-and-sweep must be missing some reference root and in essence considers some reachable objects to be unreachable.

One instrumentation which might shed light on that is if you debug log every `duk_get_heapptr()` and `duk_push_heapptr()` in your application. That would make it certain the object reference is not used by the application, and would then have to be a mark-and-sweep reachability graph issue.

**Comment by harold-b** [comment]
* Note: I was writing this when your new reply popped up so I'm addressing it in the next post*

I was just triple checking the call chain as well to make absolutely sure I didn't have anything stashed anywhere for that object. I didn't find anything, all was as expected.

I'll try to summarize here all that takes place in the 3 calls to the native functions from ecmascript.

First some definitions to try to clarify some stuff:
- **Native Object**: Any object supplied by my framework, unrelated to duktape, but may have a 'Script Reference' which we can query to get a 'ScriptedObject'

- **ScriptedObject**: Servers as a glue between Native Objects and Ecmascript objects. It keeps a pointer to the Native Object and a (weak) heapptr to the Ecmascript object (obtained via `duk_get_heapptr`). The heapptr is never stashed.

- **Script Reference**: An opaque handle which a Native Object has that points to a ScriptedObject.

`get_default`:
Checks in my engine's default DebugDraw native object to see if the native object has an ecmascript representation ( `if( muObj->script != MUSX_NULL_SCRIPT_REF )` ). If not, it creates a new ecmascript object and assigns it the appropriate prototype. Then the (glue) ScriptedObject is created and given the heapptr via `duk_get_heapptr()` we never stash it though. Finally, we give the native object a 'script reference' ( simply a compressed handle to the ScriptedObject and a context ).

`drawText`:
Get's some numerical and string arguments, Then uses `duk_push_this()` to get the ScriptedObject pointer from the 'this' binding ecmascript object, which is stored in an internal property. If the object is not the correct type, of if that internal property is not present, we throw an error (Which isn't occurring here). The 'this' object is popped from the stack right after we get the internal property, so it's never left on the stack, if it matters. Finally it calls the draw function unrelated to duktape.

`fin`:
As with drawText, it queries the object for the internal property which has the ScriptedObject pointer, but from the first argument on the stack instead of 'this'. Then, simply releases the ScriptedObject back to the pool without making any calls to duktape (It just puts it back on a free list).

**Comment by harold-b** [comment]
I'm checking and checking again but everything seems in order. I'm afraid to say with 100% certainty that I'm not doing anything wrong, but as we both know, I'm often the culpable party of the issue... But everything seems in order. This object is only ever being accessed by those 3 functions I specified.

> Btw, do you have an idea what code is doing that call by the way?

Which call? The finalizer? If so I don't know... But I'm never calling any finalizers manually. (None of my code either here or elsewhere does that) Before I added that dummy function which caused this behavior it was always finalized and recreated without issues before doing any calls to `drawText`. Once I introduced that dummy function, it started calling the finalizer before the first `drawText` call that's in the `update` function, without recreating a new one...

> One instrumentation which might shed light on that is if you debug log every duk_get_heapptr() and duk_push_heapptr() in your application.

I will try this and report back.

**Comment by svaarala** [comment]
I'll be back in a few hours and I'll see if mark-and-sweep code is missing something. For that it'd be useful to list the places where the wrapper object reference is stored in the Ecmascript code, it might give some clues to what storage location wasn't handled correctly.

Since the dummy function triggers the issue, it might be that something scope object related is not marked correctly.

**Comment by harold-b** [comment]
I'd give you private access to my repo, but it's in a... ugly transition state right now and not in position which you can get a 'one button build' of sorts...

Talk to you soon and let me know if there's anything else I can do. I'll try the suggestion you mentioned earlier in a bit.

**Comment by fatcerberus** [comment]
You say the heapptr is kept as a weak reference, without stashing it.  At what point is `duk_push_heapptr()` called?

**Comment by harold-b** [comment]
@fatcerberus The only time it's used is in 'get_default' to see if an Ecmascript representation of the Native Object has been created already. Before it does that however, it needs to check if the Script Reference is valid, which it isn't once the finalizer is called as it is nullified.

**Comment by svaarala** [comment]
@harold-b The main step I'm worried about:

> Checks in my engine's default DebugDraw native object to see if the native object has an ecmascript representation ( if( muObj->script != MUSX_NULL_SCRIPT_REF ) ).

That reference may be != MUSX_NULL_SCRIPT_REF, even if the target object has become unreachable and is waiting for finalization. But this is not an issue if `muObj->script` is never referenced in this state - but since you have no visibility in the application to see that an object is pending finalization, I don't understand how that would be possible - unless `muObj->script` is *never* used with `duk_push_heapptr()`. But if so, why is it stored in the first place? :)

> Before it does that however, it needs to check if the Script Reference is valid, which it isn't once the finalizer is called as it is nullified.

But because an object may be unreachable and pending finalization for a long time, is there a guarantee that the script reference is not used in this state? The finalizer hasn't yet executed so you'll have no way of knowing that the object is already unreachable and pending finalization.

**Comment by fatcerberus** [comment]
> Before it does that however, it needs to check if the Script Reference is valid, which it isn't once the finalizer is called as it is nullified.

This is (probably) the bug - You are assuming "finalizer called" correlates exactly with "the object is no longer reachable", which as @svaarala pointed out above, isn't necessarily the case.

**Comment by harold-b** [comment]
Ah I think I follow what you're saying.

**Comment by harold-b** [comment]
I think I misunderstood something before. That must be the case then. The object becomes unreachable but the finalizer has not yet been called, yet I assume the object is still reachable when we get to `get_default`.

**Comment by harold-b** [comment]
Saami must love me, I take him into deep rabbit trails which always end up pointing back to me :rabbit: ...

Is there any way to query duktape to know if an object has been marked for finalization? i.e. has become unreachable?

**Comment by svaarala** [comment]
So I think what you'd want is effectively weak references, and are essentially emulating that by keeping a weak `heapptr` reference and relying on finalization to tell you when to let go of the reference. The current finalizer semantics don't allow that to work reliably unfortunately and there may not be an easy fix for that: finalizers have side effects which can't be allowed for some GC scenarios. (Never say never, but those assumptions may be difficult to remove :-)

Providing weak reference support would probably serve your purpose directly :) Alternatively, if there was some *side effect free* callback which allowed an application to know when an object is no longer safe to reference, that might be enough.

> Is there any way to query duktape to know if an object has been marked for finalization? i.e. has become unreachable?

Not at present, and it's potentially a somewhat dangerous API feature to provide because an object may also be unreachable before it is queued for finalization so it's already technically unsafe to reference from an API guarantee viewpoint (it won't have practical effects though, I think, if one does that).

**Comment by svaarala** [comment]
> Sami must love me, I take him into deep rabbit trails which always end up pointing back to me :rabbit: ...

No worries @harold-b, I'm happy to help whenever I can :) And it's still possible this is a Duktape issue, it's just very hard to figure out without pinning the problem down first. (There was a finalizer related issue with Frida, for example, which was a Duktape issue and the Frida developers were able to very generously provide a test case for the issue.)

**Comment by harold-b** [comment]
> Not at present, and it's potentially a somewhat dangerous API feature to provide because an object may also be unreachable before it is queued for finalization so it's already technically unsafe to reference from an API guarantee viewpoint (it won't have practical effects though, I think, if one does that).

Got it. Well, this particular object was supposed to be strongly-reffed anyway, it's weak at the moment because there's some refactoring I need to do before that. So no harm, I just wasn't sure if it was a gc issue and I wanted to make sure I reported it since everything *seemed* to be in-order on my part. But I falsely assumed fin === immediately after unreachable.

> No worries @harold-b, I'm happy to help whenever I can :) And it's still possible this is a Duktape issue, it's just very hard to figure out without pinning the problem down first. (There was a finalizer related issue with Frida, for example, which was a Duktape issue and the Frida developers were able to very generously provide a test case for the issue.)

Thanks for your graciousness as always Saami :)

And thanks to @fatcerberus as well.

**Comment by svaarala** [comment]
This is actually a useful Wiki Howto note for dealing with `duk_get_heapptr()` pointers. I'll add it somewhere for future reference :)

**Comment by fatcerberus** [comment]
@harold-b No problem.  And don't feel too bad about going down the rabbit hole - I've had my share of those too.  Witness #175, which turned out to be caused by me passing a `ctx` pointer to something totally unrelated to Duktape.  It ultimately led to a useful change. :)

**Comment by harold-b** [comment]
Cheers fellas :)

**Comment by svaarala** [comment]
Hmm, for this issue one possible change would be to add an assert to `duk_push_heapptr()`: check that the object is not in the mark-and-sweep finalizer queue.
