### ISSUE TITLE
`obj.isPrototypeOf()` is broken

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#918]
At the very least, it's broken for Error objects (haven't tested other types),   Specifically: `Error.isPrototypeOf()` returns `false` when given a constructor of a subclass, such as `TypeError`.  V8 returns `true` in this case.

Duktape:
```
fatcerberus@pigcult-vm:~/src/duktape$ ./duk
((o) Duktape [linenoise] 1.99.99 (v1.5.0-458-g8397dd2)
duk> Error.isPrototypeOf(TypeError)
= false
duk> 
Cleaning up...
```

V8 (Node.js):
```
fatcerberus@pigcult-vm:~/src/duktape$ nodejs
> Error.isPrototypeOf(TypeError)
true
> .exit
```

This prevents my implementation of Node.js's "assert" module, specifically `assert.throws()` from working correctly.  It's based on the Node.js code, which uses `Error.isPrototypeOf()` to differentiate between an Error constructor (in which case it asserts for instanceof) vs. a validation function.

**Comment by fatcerberus** [comment]
I just took a look at the MDN page for `Object.prototype.isPrototypeOf()`:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/isPrototypeOf

It actually seems like Duktape's behavior is correct and V8 is the odd one out.  V8 is apparently treating `.isPrototypeOf()` as an inverted instanceof which is specifically noted at the top of the MDN page to not be the case.

So Duktape seems be in the clear here.  Still might be worth looking at the E5/6 specifications for what they say about this call's behavior.  MDN is usually trustworthy in this regard, though.

**Comment by svaarala** [comment]
I think the require behavior is pretty clear: http://www.ecma-international.org/ecma-262/6.0/#sec-object.prototype.isprototypeof. For Object.prototype.isPrototypeOf(V):

- False if V is not an object
- Let O = ToObject(this)
- Walk the prototype chain of V:
  + Let V = internal prototype of V (note that V itself is never compared, comparison begins at V's first prototype)
  + If V = null => false
  + If SameValue(O,V) => true

So, for `Error.isPrototypeOf(TypeError)`:

- F = TypeError (the constructor)
- O = Error (the constructor)
- First prototype walk step:
  + V = internal prototype of V; since TypeError is a Function instance, its internal prototype is Function.prototype
  + SameValue(O, V) => not true, continue
- Second prototype walk step:
  + V = internal prototype of Function.prototype; since the Function.prototype inherits from Object, it is (usually) Object.prototype
  + SameValue(O, V) => not true, continue
- Third prototype walk step:
  + V = internal prototype of Object.prototype => null
  + V is null => return false

**Comment by svaarala** [comment]
The original expression is a bit odd: with `Error.isPrototypeOf(TypeError)` you're checking whether the Error constructor appears in the internal prototype chain of the TypeError constructor which is a bit odd. You probably need something like:

```
> Error.prototype.isPrototypeOf(new TypeError())
true
```

In other words, checking that Error.prototype appears in the prototype chain of an Error instance.

**Comment by svaarala** [comment]
> It's based on the Node.js code, which uses Error.isPrototypeOf() to differentiate between an Error constructor (in which case it asserts for instanceof) vs. a validation function.

Just re-read this part; not sure how to do that cleanly.

So, if I understood correctly, you're looking for a way to check whether a constructor function would create objects that would inherit from `Error.prototype`? That would be:

```js
Error.prototype.isPrototypeOf(val.prototype);
```

IOW, you're checking the `.prototype` external property, which is typically the *internal* prototype for any instances created, against the Error.prototype which is almost always in Error inheritance chains.

This is by no means 100%, because it's quite possible to write an Error constructor, which creates instances inheriting from Error.prototype, but whose `.prototype` is not set.

**Comment by svaarala** [comment]
Btw, that check I proposed above:

```js
Error.prototype.isPrototypeOf(val.prototype);
```

Should work for e.g. TypeError and anything derived from Error:

```
> duktape@keppihevonen:~/duktape$ ./duk.O2
((o) Duktape [linenoise] 1.99.99 (v1.5.0-460-g350e92d)
duk> function check(V) { return Error.prototype.isPrototypeOf(V.prototype); }
= undefined
duk> check(TypeError)
= true
duk> function MyError() {}; Object.setPrototypeOf(MyError.prototype, RangeError.prototype);
= RangeError
duk> check(MyError)
= true
```

However, it won't accept Error itself, because the isPrototypeOf() lookup *doesn't* compare the argument itself; the walk begins from the argument's internal prototype. So:

```
duk> check(Error)
= false
```

This check would work as expected if the argument was an Error instance, because skipping the value itself then makes sense (we'd look up Error.prototype and find an immediate match). So you can tweak this e.g. as:

```
val === Error || Error.prototype.isPrototypeOf(val.prototype);
```

or you can create a dummy instance which would then work as expected:

```
Error.prototype.isPrototypeOf(new val());
```

But, since you probably don't want to invoke the constructor, you could also create a "simulated" instance:

```
var testValue = {};
Object.setPrototypeOf(testValue, val.prototype);
return Error.prototype.isPrototypeOf(testValue);
```

Again, the lookup would begin from the internal prototype of the dummy instance (skipping the dummy instance), i.e. from `val.prototype`.

**Comment by fatcerberus** [comment]
Or I could just do `value instanceof Error` and skip all the headaches. ;-)

I don't know the reason for V8's strange behavior here - I do find it interesting though that something as high profile as Node.js relies on the nonconforming behavior.  That's why I thought it was a Duktape bug - until I read the MDN page.

**Comment by svaarala** [comment]
Well if `value` is a construct function and not an *error instance* that check would be incorrect. The error constructor does not inherit from Error.prototype because it is a Function instance.

**Comment by svaarala** [comment]
The inheritance chains would be:

- Error constructor: Error -> Function.prototype -> Object.prototype
- Error instance: instance -> Error.prototype -> Object.prototype
- MyError instance which is a "subclass" of RangeError: instance -> MyError.prototype -> RangeError.prototype -> Error.prototype -> Object.prototype

All assuming that the `.prototype` properties have their initial values.

**Comment by svaarala** [comment]
Hehe, I'm quite used to people relying on non-conforming behavior. Witness the regexp issues for example ;) People are often very much unwilling to fix their code to be compliant, so there's a lot of grey area unfortunately.

**Comment by fatcerberus** [comment]
V8 also displays this behavior in Chrome, so it's not a Node.js-specific extension.  Firefox/Spidermonkey at least is conformant: `Error.isPrototypeOf(TypeError)` returns `false`.

**Comment by svaarala** [comment]
Hmm... Maybe it's version dependent?

```
$ node
> Error.isPrototypeOf(TypeError)
false
> process.version
'v0.12.1'
```

**Comment by fatcerberus** [comment]
Interesting.  Here's the relevant line in the `assert` module I was trying to replicate:
https://github.com/nodejs/node/blob/master/lib/assert.js#L302-L304

I wonder what that module looks like in 0.12.1, since the compliant behavior isn't desirable in this case.

**Comment by fatcerberus** [comment]
So it turns out V8 may not be out of spec after all--I found out that in ES6, class constructors directly inherit from the constructor of their superclass.  `Error.isPrototypeOf(TypeError) === true` is consistent with that.

**Comment by fatcerberus** [comment]
In any case, I settled on this for the check.  It seems relatively clean:
```javascript
if (expected === Error || expected.prototype instanceof Error) { ... }
```

Note that by the time this check is done, `expected` is already known to be a function, so the instanceof check is unambiguous.

**Comment by svaarala** [comment]
That inheritance could also be changed for Duktape, should be a simple change.

**Comment by fatcerberus** [comment]
Yeah, see this SO question (specifically the answer on the bottom, along with the comments):
http://stackoverflow.com/questions/30993434/check-if-a-constructor-inherits-another-in-es6

**Comment by svaarala** [comment]
One concrete problem with changing the inheritance is that the change will conform to ES6, but if you want an ES5.1 build it will be non-compliant. In general keeping the ES5.1 build clean while adopting ES6 parts needs some attention.

My current plan for solving this is related to merging the genbuiltins+genconfig+make_dist tooling; to prepare an ES6 build one would first read in `builtins_es5_base.yaml` metadata (with ES5.1 semantics) and then load `builtins_es6_additions.yaml` on top of that. That ES6 file can then add the new Math functions, change Error inheritance chains, etc.

I'm not sure if it's worthwhile to keep a pure ES5.1 build intact (though I do think ES5.1 is a good feature set), but there should at least be the tooling to do that.

**Comment by fatcerberus** [comment]
@svaarala I found out that the change to constructor prototype chains in ES6 wasn't just done on a whim (it seemed arbitrary to me that the *constructor*, a function, would have its prototype monkeyed with); the reason is because, when using classes:

```js
class B {
  static x = 42;
}

class D extends B { 
}

D.x; // = 42
```

Static class members are subject to inheritance.  The simplest way to do that is through the prototype chain.
