### ISSUE TITLE
Make Duktape more Unix distribution friendly

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#94]
Some possible improvements:

- [x] More source/binary compatibility guarantees. Perhaps guarantee binary compatibility for patch releases.
- [x] Avoid the need to duplicate feature options when compiling an application (#64). Not a blocker if defaults are good enough.
- [x] Document how Duktape is intended to be used in a distribution.

Avoiding macros in API calls would be good for distributions and writing language bindings, but it also has downsides, see #87.

Any other suggestions?

**Comment by cb88** [comment]
@avih I know the netsurf developers were looking at using ducktape... I imagine it would be a good fit for text based browers as well. In those cases the lighter the better! Netsurf runs on 68k Amiga and ... I persontally run it on retro sparc hardware also it would be cool to write some js apps there... very niche sure but I'm just throwing it out there since you were wondering ;-).... that said even the oldest sparc workstation or 68k amiga is pretty beefy compared to any 8 or 16bit microcontroller some of which ought to have enough flash/sram (256k/8k)to run duktape like an atmega 2560 assuming it were possible to adapt to using smaller datatypes. Althought something like a PSoC5 might be a better target were you wanting to embed js.

**Comment by avih** [comment]
Well, When I suggested to start with one group, I was thinking more of current *nix systems like Linux and OS X.

FWIW, there's a patch to add js scripting support to the mpv video player, which currently waits for some weeks already since the maintainers don't want to use code which doesn't have standard system install.

It seems that the patch will either wait forever or will land as soon as Duktape could be installed like other "normal" libraries - which now it can't due the lack of makefiles (as simple as they might be - still not provided by DUktape) and the fact that the API changes between functions/macro rather randomly.

**Comment by darkuranium** [comment]
@avih: I do think Duktape would benefit from the *option* of having a macroless compile, but I personally don't think points 1 and 3 are that much of a problem; especially since the "usual" way to do it is to just compile that 1 file.

On a closely related note (and also to @svaarala) I've been pondering of adding Duktape to FreeBSD ports, but then I figured there wasn't much point.
Practically anyone who wants to use it will compile statically anyways (from that 1 file, so no point for a lib), and the API's a bit too much in flux for that (not that I mind --- I like the fact that Duktape is constantly being improved --- it's just that it's not very appropriate for ports, that's all).

**Comment by avih** [comment]
> Practically anyone who wants to use it will compile statically anyways

As I mentioned, that's not true. Some projects, especially projects which use several 3rd party packages, will just not include or compile a 3rd party package together withe the main project. It's simply considered bad practice.

**Comment by svaarala** [comment]
Already covered by previous messages but:

Given that the default feature options should be OK for Unix distributions, what's the problem with compiling a library? I don't see the situation as much different from Lua. If you tweak the `lua_Number` type you'll have a Lua that's binary incompatible. Same thing with Duktape feature option tweaking (and actually only very few options will concretely impact binary compatibility right now).

There's a problem if you need custom feature options but that shouldn't be the case for an ordinary distribution. Going forward that's going to be addressed by #64 so that there can be a system header that contain any custom options (and application builds don't need to define them).

**Comment by avih** [comment]
> Given that the default feature options should be OK for Unix distributions, what's the concrete problem with compiling a library?

Due to warnings and notes like this:
> Note: If you use Duktape feature options, you must define the feature options both when compiling Duktape and when compiling any application code using the duktape.h header. This is necessary because some feature options affect the binary compatibility of the Duktape API.

or this:

> You can compile Duktape and the application with a C or a C++ compiler in any combination. Even so, it is recommended to compile both Duktape and the application with the same compiler (i.e. both with a C compiler or both with a C++ compiler) and with the same compiler options.

Or

> Use the same feature options and the same compiler when compiling Duktape and your application. This is especially important when Duktape is compiled as a library in a separate step.

And there could be others.

As a developer who wants to use this as a library and doesn't follow every commit or small change within Duktape development, all these notes put a big question mark over whether this could be safely installed once and then used by many.

I _think_ functions-only or mostly API should cover it and I know you have this as a plan, but I was answering darkuranium.

**Comment by svaarala** [comment]
But as it says, these only apply *if* you use feature options?

Using the same compiler (and compiler options) for a library and the application is also a common requirement for any library. There's no guarantee that typing would match if you mix compilers or compiler options (something that affects the ABI for instance) as far as I can tell - although it would probably be rare to encounter concrete problems.

**Comment by avih** [comment]
There's clang and gcc for instance, which generally can be used interchangeably since clang is presumably ABI compatible to gcc, but these warnings make me think it might not work.

And especially the c/c++ mix warning/recommendation will not let me trust the lib to "just work". Sure, I can try, and it might even work as far as my own cases go, but these warnings and the lack of an official Makefile don't make me feel safe to install it globally.

**Comment by svaarala** [comment]
I understand that the wording may seem overcautious, but do you have a suggestion for improving it?

Sure, you can mix clang and gcc but since this isn't the case for all compilers, what should the requirements say? Also note that with certain options you'll break compatibility between the application and the library even with, say, gcc. For instance, if you change default struct packing, an application and a library might no longer be compatible. This is the case for all libraries.

Perhaps the documentation should just be silent about these issues, as they're common to all libraries?

**Comment by avih** [comment]
Silencing warnings about issues which are not unique to Duktape is a good step IMO.

But seeing that Duktape uses so many macros and #ifdef's for APIs, platforms, compile flags, compilers, etc, means that a developer (or a distribution Duktape maintainer for that matter) would not know what to trust when there's no official Makefile. Maybe the default options _are_ great and will end up with zero or close to zero issues, but only you can know that for sure, again, due to the many conditional compilation blocks and the warnings at the docs.

As for packing, well, this depends on the API. If the API itself is packing agnostic, then the app and the lib can be built with different packing flags, for instance.

**Comment by avih** [comment]
Is this still a goal? IIRC this was targeted for milestone 1.2, though I can't find reference for it now...

**Comment by svaarala** [comment]
I guess at this point I'm not 100% clear what the actual concrete changes would need to be.

Regarding a "function only" API I'm still not quite sure what the best goal there is. A 100% function only API would be possible but many other libraries are considered "UNIX friendly" even though they use API macros. For example Lua uses API macros: http://www.lua.org/source/5.1/lua.h.html.

Documentation changes would be easy to make - the more concrete suggestions the better.

Regarding the feature options, there's oncoming work probably within a month to move into a model where the user provides a `duk_config.h` in the include path and no feature options are used for compilation. This should fix the feature option issues raised above.

**Comment by avih** [comment]
I think a reasonable goal to make it *nix friendly is to be able to install duktape as a static/dynamic system wide library (either by building and installing locally using a provided build system - as simple as it might be, or downloading a binary from a repository which a maintainer can maintain).

Being a system library, it will need some defined naming convention and/or other enforcements such that an application which links dynamically with it will know that it's safe to use it at runtime without fear of incompatibility due to its own compilation flags or due to duktape library updates - it should know at runtime if it can trust the lib or not.

I'm not sure what the exact mechanisms to put in place to get there, but does that sound like a reasonable goal?

**Comment by svaarala** [comment]
I agree with the general goals but I'm not clear on the best concrete steps forward. I think we might come pretty close with the following changes:

- The feature option rework which uses `duk_config.h` and requires no command line feature options when compiling the application.  Application would just `#include "duktape.h"` and ensure it has the system-wide `duk_config.h` in its include path.  Any system specific hacks etc can be applied to the `duk_config.h`, including everything that's currently controlled through feature options.

- Providing an additional versioning guarantee that patch-only changes (e.g. 1.1.1 -> 1.1.2) would not change API function/macro status (minor version changes could). This would mean that a patch update would be binary compatible. Other guarantees would also be possible but this would probably be quite workable and seems to be the case (in practice) for several other libraries too.

I'm a bit hesitant to add an official UNIX build/install Makefile to Duktape main repository. It would need to support a bunch of different conventions, packaging systems, etc, and since Duktape targets such a wide range of targets I'm actively trying to avoid maintaining official build files.

One option for this would be to create a separate repo which would provide all the build files needed for a Duktape UNIX build - including building and installing locally, creating a .deb or other package, etc. What build results should be supported in your opinion? Local install only? Packaging? What systems?

**Comment by avih** [comment]
I'm far from a *nix specialist (in fact, I'm pretty much the opposite of that), but I'd think that clear instructions might be enough (e.g. create duktape_config.h and put it at your system include directory, then do that or that... etc). Maybe even create a sample makefile which would work for cases of your choice and which people could use as a base or maybe even as is.

As long as there's a known way to install it safely globally which people can follow or maintainers could maintain (and on both cases the result would probably be interchangeable - up to issues mentioned at the instructions), I believe it could be enough.

But maybe someone who's more familiar with this subject than myself could also comment?

**Comment by hftmarkand** [comment]
I don't think Duktape should be installed wide into the system.

As Sami already pointed out, it contains no filesystem operation so to make it useful on such situations you will require to enable your own Duktape.modSearch function which is pointless as there are no standard way to load external modules.

Also, later, when Duktape will have alternative setjmp/longjmp using C++ exceptions it will be nonsense to install it as compiled in C for C++ apllications.

Duktape is like Lua, it is designed to be embedded directly into your application. Duktape has an advantage over Lua in that way because it does amalgamation just like SQLite.

**Comment by avih** [comment]
> I don't think Duktape should be installed wide into the system.
> ...
> Duktape is like Lua, it is designed to be embedded directly into your application. Duktape has an advantage over Lua in that way because it does amalgamation just like SQLite.

And yet both Lua and SQLite can be installed system wide as libs.

**Comment by svaarala** [comment]
To elaborate my earlier point a little bit, distributions try to discourage libraries bundled in packages for several reasons. For example, see Fedora's policy:

- http://fedoraproject.org/wiki/Packaging:No_Bundled_Libraries

As you can see, for Lua there's an exception for Spring RTS: it has specific patches and redefines `lua_Number` so it can't use the system-wide library.

I think Duktape would right now install as a system library the same way as Lua does: the system-wide library would be a C library with default feature options (= nothing specific on the command line). If an application needs specific feature options, it will need to use a bundled library and may need to justify that to get packaged into a certain distribution (like Spring RTS does for Lua in the example above).

So mostly I think the situation is quite similar between Lua and Duktape. One clear issue that I can see is that *if* the system-wide library needs some feature options (say, forcing alignment), that option would also be used when compiling the application which is not very convenient. But this is being fixed in #64 by using a `duk_config.h` header that would then be part of the system-wide library installation.

Like I said above I'm not sure what concrete steps are needed (other than #64).

**Comment by avih** [comment]
Sounds good.

> Like I said above I'm not sure what concrete steps are needed (other than #64).

Possibly what you just wrote, but as part of the official docs. Maybe with a sample makefile which builds Dukpate with the default options, then copies the lib and h files to their system locations (assume for instance `/usr/local/lib` and `/usr/local/include`, with instructions how to setup and use the global config file.

**Comment by svaarala** [comment]
All the changes mentioned in the description are now in master. There's no sample Makefile though.

**Comment by svaarala** [comment]
Split the sample Makefile into #300. If anyone can suggest concrete, specific changes to the portability/compatibility wording on the website, I'll be happy to make those changes. I'm closing this one because it's quite overdue, please open separate issues for specific improvements.
