### ISSUE TITLE
Increase max number of arguments in DUK_OP_NEW

### ISSUE THREAD

**Issue by fmazan** [svaarala/duktape#955]
I managed to hit the limit of maximum arguments passed to a new constructor in version 1.5.1 which is limited by 9 bit C opcode slot = 511 arguments (and as I see in the latest branch, the B and C register shrank to 8 bits). Although I have no in-depth knowledge of inner workings of the compiler and executor, but let me ask: wouldn't it be possible to switch the layout of DUK_OP_NEW from current a_b_c to a_bc or ab_c where the nargs parameter would be sufficiently large? In the current implementation of a_b_c the register a is unused.

Also, similar problem might emerge in the future with DUK_OP_CALL, but the proposed solution wouldn't work there, as all of the a, b and c registers are used.

For reference on how many arguments are supported in other engines:
[http://stackoverflow.com/questions/22747068/is-there-a-max-number-of-arguments-javascript-functions-can-accept](url)

**Comment by svaarala** [comment]
I'll be doing at least one more rework step on the call setup and call opcodes and I can look into raising the limit at the same time.

There's no other reason for the limit other than practical opcode issues. In master the arguments to a DUK_OP_NEW are:
- Argument count in slot A (8 bits)
- Base register in combined slot B+C (16 bits)

Because the base register is 16 bits, there's no need for an "indirect" opcode variant at the moment (in general register limit is now 2^16). Reducing the size of the base register field would make it necessary to add an indirect variant which is of course an additional complication. Making the base register always indirect (loaded from a register) increases bytecode size and affects call performance a little bit.

Even so, current limits are relatively low so it'd be nice to extend them.

**Comment by fmazan** [comment]
I managed to solve this issue now in my local project by adding a new flag to OP_CALL[I] and OP_NEW[I]
`#define DUK_BC_CALL_FLAG_EXTENDED_NARGS     (1 << 2)`
The flag is set in compiler when nargs > DUK_BC_C_MAX and the nargs itself is emited as a next uint32 in the bytecode. The executor similarly checks for this flag and reads next uint32 and iterprets it as the correct nargs. This approach avoids increase of bytecode and the performance hit is minimal - it is triggered only on nargs > 511 which is quite rare in my opinion.

The question now is, what do you think about this? Is this approach in line with this project's philosophy?

**Comment by svaarala** [comment]
In master NEW/CALL opcodes don't have a flags field anymore, but the (now 8-bit) opcode field can be used for small flags field (for example, two flags would reserve four consecutive opcode slots).

At the moment opcode slots always contain opcodes, not opcode parameter values. But I can't think of a reason why that would be a problem.

It does, however, increase bytecode size as two opcode slots are used to encode a NEW/CALL instruction. An indirect NEW/CALL has the same bytecode impact: a NEW/CALL is preceded by e.g. a LDINT opcode serving a similar purpose.

**Comment by svaarala** [comment]
This is now implemented in master, to be part of 2.2.0.
